# SPDX-License-Identifier: GPL-2.0-only
"""Build reviewed help text from immutable source/logical-line identities.

No runtime English-string lookup: the C projection selects file ordinal and the
same logical line counted by show_file().  Japanese wording is authored here,
not generated by replacing fragments of a rendered English buffer.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
COMMIT = 'f3082213b73f3e463e3d0d60bff4b00462beae6e'
FILES = ('index.txt', 'commands.txt', 'r_comm.txt', 'r_index.txt', 'symbols.txt')
PINNED_HASHES = {
    'index.txt': '360a58a4e19205e39d7ef6e09568f59ecaa680758a399bdbb048bf1f2865fdb3',
    'commands.txt': '45ac65143d1fa5d560bb322b68571d4b3d0cc8738a36ee986a603c787b34b0af',
    'r_comm.txt': 'f59f406cad4b1e4da0be501f9f4f74220154e3c7f7d17fe7ebe46e363cfb217b',
    'r_index.txt': '81255d61a8e3725b5976ec416e131b5a355ae44171e4405960e4b1d8fc41a18c',
    'symbols.txt': 'ddbd790b723908158bc980426a081dd91e010c640b8a6fe5f9fb6a8a1dc4f076',
}

# Reviewed producer identities. Logical/physical line numbers are provenance,
# never the semantic identity of a textual row. The action pairs below describe
# the two original columns, including deliberately unbound source keys.
INDEX_ROLES = [
    'reference.summary', 'reference.details', 'layout.reference_gap', 'reference.manual_link',
    'layout.manual_gap', 'layout.choices_lead_gap', 'menu.choose_file', 'layout.choice_gap',
    'menu.commands', 'menu.symbols', 'layout.menu_tail_gap_1', 'layout.menu_tail_gap_2',
    'layout.menu_tail_gap_3', 'layout.menu_tail_gap_4', 'navigation.heading',
    'navigation.file_and_line', 'navigation.page_and_search', 'navigation.line_and_highlight',
    'navigation.half_page_and_case', 'layout.navigation_tail_gap',
]
EXPLANATION_ROLES = [
    'control_notation_prefix', 'control_modifier_and_alternative', 'sequential_prefix_command',
    'system_interception', 'system_interception_and_autoexplore_option',
    'autoexplore_commands_and_off_state', 'autoexplore_default_and_on_state',
    'autoexplore_current_stair', 'autoexplore_nearest_known_stair', 'autoexplore_stair_kind',
    'autoexplore_unexplored_location', 'autoexplore_enabled',
]
ORIGINAL_COMMAND_ROLES = [
    'aim_wand_and_activate', 'browse_book_and_unbound_b', 'close_door_and_character_info',
    'drop_item_and_disarm_or_lock', 'equipment_and_eat', 'fire_ammunition_and_refuel',
    'pickup_and_learn_spells', 'default_ammunition_and_unbound_h', 'inventory_and_inspect',
    'unbound_j_keys', 'ignore_and_toggle_ignore', 'look_and_locate', 'cast_spell_and_level_map',
    'repeat_command_and_unbound_n', 'open_door_or_chest_and_unbound_o', 'autoexplore_and_unbound_p',
    'quaff_and_retire', 'read_scroll_and_rest', 'steal_and_abilities', 'take_off_and_tunnel',
    'use_staff_and_item', 'throw_and_version', 'equip_and_walk_into_trap', 'unbound_x_keys',
    'unbound_y_keys', 'zap_rod_and_unbound_z', 'unbound_bang_and_debug', 'unbound_at_and_control_b',
    'unbound_hash_and_break', 'unbound_dollar_and_control_d', 'unbound_percent_and_window_toggle',
    'control_prefix_and_level_feeling', 'unbound_ampersand_and_autopickup', 'target_and_unbound_control_h',
    'unbound_parenthesis_and_tab', 'screen_dump_and_linefeed', 'inscribe_and_unbound_control_k',
    'uninscribe_and_center_map', 'monster_list_and_return', 'object_list_and_unbound_control_n',
    'unbound_hyphen_and_previous_message', 'unbound_underscore_and_message_history',
    'alter_grid_and_unbound_control_q', 'options_and_redraw', 'walk_pickup_and_save_continue',
    'note_and_unbound_control_t', 'closest_target_and_unbound_control_u',
    'preference_command_and_unbound_control_v', 'wait_pickup_and_wizard_mode', 'ascend_and_save_quit',
    'run_and_unbound_control_y', 'descend_and_borg_command', 'bypass_keymap_and_knowledge',
    'escape_and_help', 'identify_symbol', 'quiver_contents',
]
ROGUELIKE_COMMAND_ROLES = [
    'zap_rod_and_activate', 'walk_and_run_southwest', 'close_door_and_character_info',
    'drop_item_and_disarm_or_lock', 'equipment_and_eat', 'unbound_f_and_refuel',
    'pickup_and_learn_spells', 'walk_and_run_west', 'inventory_and_inspect', 'walk_and_run_south',
    'walk_and_run_north', 'walk_and_run_east', 'cast_spell_and_level_map', 'walk_and_run_southeast',
    'open_door_or_chest_and_toggle_ignore', 'autoexplore_and_browse_book', 'quaff_and_retire',
    'read_scroll_and_rest', 'steal_and_abilities', 'fire_ammunition_and_take_off',
    'walk_and_run_northeast', 'throw_and_version', 'equip_and_locate', 'look_and_use_item',
    'walk_and_run_northwest', 'aim_wand_and_use_staff', 'unbound_bang_and_debug',
    'center_map_and_alter_southwest', 'unbound_hash_and_break', 'unbound_dollar_and_ignore',
    'unbound_percent_and_window_toggle', 'control_prefix_and_level_feeling',
    'unbound_ampersand_and_autopickup', 'target_and_alter_west', 'unbound_parenthesis_and_tab',
    'screen_dump_and_alter_south', 'inscribe_and_alter_north', 'uninscribe_and_alter_east',
    'monster_list_and_return', 'object_list_and_alter_southeast', 'walk_into_trap_and_previous_message',
    'unbound_underscore_and_message_history', 'alter_grid_or_steal_and_unbound_control_q',
    'options_and_redraw', 'walk_pickup_and_save_continue', 'note_and_tunnel',
    'closest_target_and_alter_northeast', 'preference_command_and_repeat', 'run_and_wizard_mode',
    'ascend_and_save_quit', 'wait_pickup_and_alter_northwest', 'descend_and_borg_command',
    'bypass_keymap_and_knowledge', 'escape_and_help', 'identify_symbol', 'default_ammunition',
    'quiver_contents',
]
SYMBOL_TEXT_ROLES = {
    0: 'heading', 3: 'overview.categories', 4: 'overview.features_and_items',
    5: 'overview.items_and_creatures', 6: 'overview.creature_mobility', 7: 'overview.creature_danger',
    9: 'overview.shared_entity_symbols', 10: 'overview.shared_categories_and_player_symbol',
    11: 'overview.default_player_symbol', 13: 'identification.no_memorization_needed',
    14: 'identification.slash_command', 15: 'identification.command_reference',
    17: 'preferences.custom_symbols', 18: 'preferences.familiar_symbols',
    22: 'terrain.transparent_heading', 25: 'terrain.floor_and_general_store',
    26: 'terrain.hidden_trap_and_armoury', 27: 'terrain.known_trap_and_weapon_smith',
    28: 'terrain.warding_glyph_and_bookseller', 29: 'terrain.open_door_and_alchemy_shop',
    30: 'terrain.broken_door_and_magic_shop', 31: 'terrain.up_stair_and_black_market',
    32: 'terrain.down_stair_and_home', 33: 'terrain.lava_pool', 36: 'terrain.opaque_heading',
    39: 'terrain.secret_door_and_wall', 40: 'terrain.closed_door_and_mineral_vein',
    41: 'terrain.locked_door_and_treasure_vein', 42: 'terrain.blocking_and_passable_rubble',
    45: 'objects.heading', 48: 'objects.potion_or_flask_and_polearm',
    49: 'objects.scroll_or_book_and_edged_weapon', 50: 'objects.mushroom_or_food_and_hafted_weapon',
    51: 'objects.wand_or_rod_and_launcher', 52: 'objects.staff_and_ammunition',
    53: 'objects.ring_and_soft_armour', 54: 'objects.amulet_and_hard_armour',
    55: 'objects.money_and_miscellaneous_armour', 56: 'objects.tools_or_chests_and_shield',
    57: 'objects.multiple_items', 60: 'monsters.heading', 63: 'monsters.coins_and_mushrooms',
    64: 'monsters.ant_and_ainu', 65: 'monsters.bat_and_bird', 66: 'monsters.centipede_and_canine',
    67: 'monsters.dragon_and_ancient_dragon', 68: 'monsters.floating_eye_and_elemental',
    69: 'monsters.feline_and_dragon_fly', 70: 'monsters.golem_and_ghost', 71: 'monsters.humanoid_and_hybrid',
    72: 'monsters.icky_thing_and_insect', 73: 'monsters.jelly_and_snake', 74: 'monsters.kobold_and_killer_beetle',
    75: 'monsters.tree_or_ent_and_lich', 76: 'monsters.mold_and_hydra', 77: 'monsters.naga_and_unbound_n',
    78: 'monsters.orc_and_ogre', 79: 'monsters.human_and_giant', 80: 'monsters.quadruped_and_quylthulg',
    81: 'monsters.rodent_and_reptile_or_amphibian', 82: 'monsters.skeleton_and_arachnid',
    83: 'monsters.townsperson_and_troll', 84: 'monsters.minor_and_major_demon',
    85: 'monsters.vortex_and_vampire', 86: 'monsters.worms_and_wight_or_wraith',
    87: 'monsters.unbound_x_and_xorn_or_xaren', 88: 'monsters.yeek_and_yeti', 89: 'monsters.zombie_or_mummy_and_hound',
}


def semantic_id(filename, logical, english):
    if filename in ('index.txt', 'r_index.txt'):
        prefix = 'help.index' if filename == 'index.txt' else 'help.roguelike_index'
        return prefix + '.' + INDEX_ROLES[logical]
    if filename in ('commands.txt', 'r_comm.txt'):
        prefix = 'help.original' if filename == 'commands.txt' else 'help.roguelike'
        if logical == 1:
            role = 'heading'
        elif 4 <= logical <= 15:
            role = 'explanation.' + EXPLANATION_ROLES[logical - 4]
        elif logical >= 17:
            roles = ORIGINAL_COMMAND_ROLES if filename == 'commands.txt' else ROGUELIKE_COMMAND_ROLES
            role = 'command.' + roles[logical - 17]
        else:
            role = f'layout.row_{logical:04d}'
        return prefix + '.' + role
    assert filename == 'symbols.txt'
    if english.strip() and not re.fullmatch(r'[=-]+', english):
        return 'help.symbols.' + SYMBOL_TEXT_ROLES[logical]
    return f'help.symbols.layout.row_{logical:04d}'

INDEX = [
    'これは、ゲーム中のコマンドと地図の記号を確認するための',
    '簡単な手引きです。詳しい説明は、次のサイトをご覧ください。',
    '', '   https://angband.readthedocs.io/en/latest/', '', '',
    '次のヘルプファイルから選んでください。', '',
    '    (a) コマンド一覧', '    (b) 地図の記号一覧', '', '', '', '',
    'ヘルプ閲覧の操作：',
    '  # 指定行へ ／ % 指定ファイルへ ／ ? 前のファイル・メインメニューへ',
    '  SPACE 1ページ進む ／ - 1ページ戻る ／ / 文字列を検索',
    '  RET 1行進む ／ = 1行戻る ／ & 文字列を強調表示',
    '  + 半ページ進む ／ _ 半ページ戻る ／ ! 大文字・小文字の区別を切り替える',
    '',
]
KEY_EXPLANATION = [
    '^ に続く文字は、その文字キーを Control キーと同時に押して',
    '離す操作を表します。^ を押して離した後、その文字キーを',
    '押して離すことでも、同じコマンドを実行できます。',
    'システムが Control と文字キーの組み合わせを捕捉し、',
    'ゲームに渡さない場合は、こちらの方法を使えます。autoexplore_commands',
    '設定は、<、>、p の動作を変更します。この設定がオフのときは',
    '（初期設定はオフ）、下の説明どおりに動作します。設定がオンなら、',
    '< と > は、現在地に対応する向きの階段があれば、それを使います。',
    '対応する階段の上にいなければ、既知の階段のうち、',
    '対応する向きで最も近いものへ移動します。',
    'autoexplore_commands がオンのとき、p は最も近い',
    '未探索の場所へ移動します。',
]
# Each tuple is one source row: exact source keys are retained by extraction.
ORIGINAL_ROWS = [
    ('魔法の杖を狙って使う', 'アイテムを発動する'),
    ('本を閲覧する', '—'), ('扉を閉じる', 'キャラクター情報'),
    ('アイテムを落とす', '罠を解除する・扉に鍵をかける'),
    ('装備一覧', '食べ物を食べる'), ('弾を発射する', 'ランタン・松明に燃料を補給する'),
    ('床のアイテムを拾う', '新しい呪文・祈りを習得する'),
    ('標準の弾を標的へ発射する', '—'), ('所持品一覧', 'アイテムを調べる'),
    ('—', '—'), ('アイテムを無視する', '無視設定を切り替える'),
    ('周囲を見る', '地図上で自分の位置を探す'), ('呪文を唱える', '階層全体の地図'),
    ('前のコマンドを繰り返す', '—'), ('扉・箱を開ける', '—'), ('—（上の説明を参照）', '—'),
    ('薬を飲む', '引退して終了する'), ('巻物を読む', '一定時間休む'),
    ('モンスターから盗む（盗賊）', '能力を見る'), ('装備を外す', 'トンネルを掘る'),
    ('魔法のスタッフを使う', 'アイテムを使う'), ('アイテムを投げる', 'バージョン情報'),
    ('装備を身につける・武器を持つ', '罠へ踏み込む'), ('—', '—'), ('—', '—'),
    ('魔法のロッドを使う', '—'), ('—', '（特殊：デバッグコマンド）'), ('—', '—'),
    ('—', '（特殊：中断）'), ('—', '—'), ('—', '所持品・装備ウィンドウを切り替える'),
    ('（特殊：Control キー）', '階層の感触をもう一度表示する'), ('—', '自動拾得する'),
    ('モンスター・場所を標的にする', '—'), ('—', '（特殊：タブ）'),
    ('画面をファイルに保存する', '（特殊：改行）'), ('アイテムに銘を刻む', '—'),
    ('アイテムの銘を消す', '地図を中央に表示する'), ('見えているモンスターの一覧', '（特殊：リターン）'),
    ('見えているアイテムの一覧', '—'), ('—', '直前のメッセージを表示する'),
    ('—', '過去のメッセージを表示する'), ('隣接マスに働きかける', '—'),
    ('設定を変更する', '画面を再描画する'), ('歩く（拾得あり）', '保存して続ける'),
    ('メモを取る', '—'), ('最も近いモンスターを標的にする', '—'),
    ('ユーザー設定コマンドを入力する', '—'), ('その場に留まる（拾得あり）', '（特殊：ウィザードモード）'),
    ('上り階段を使う（上の説明を参照）', '保存して終了する'), ('走る', '—'),
    ('下り階段を使う（上の説明を参照）', '（特殊：borg コマンド）'),
    ('（特殊：キーマップを迂回する）', '知識を確認する'), ('（特殊：エスケープ）', 'ヘルプを表示する'),
    ('記号を調べる',), ('矢筒の中身の一覧',),
]
ROGUELIKE_ROWS = [
    ('魔法のロッドを使う（発動）', 'アイテムを発動する'), ('（南西へ歩く）', '（南西へ走る）'),
    ('扉を閉じる', 'キャラクター情報'), ('アイテムを落とす', '罠を解除する・扉に鍵をかける'),
    ('装備一覧', '食べ物を食べる'), ('—', 'ランタン・松明に燃料を補給する'),
    ('床のアイテムを拾う', '新しい呪文・祈りを習得する'), ('（西へ歩く）', '（西へ走る）'),
    ('所持品一覧', 'アイテムを調べる'), ('（南へ歩く）', '（南へ走る）'), ('（北へ歩く）', '（北へ走る）'),
    ('（東へ歩く）', '（東へ走る）'), ('呪文を唱える', '階層全体の地図'), ('（南東へ歩く）', '（南東へ走る）'),
    ('扉・箱を開ける', '無視設定を切り替える'), ('—（上の説明を参照）', '本を閲覧する'),
    ('薬を飲む', '引退して終了する'), ('巻物を読む', '一定時間休む'),
    ('モンスターから盗む（盗賊）', '能力を見る'), ('弾を発射する', '装備を外す'),
    ('（北東へ歩く）', '（北東へ走る）'), ('アイテムを投げる', 'バージョン情報'),
    ('装備を身につける・武器を持つ', '地図上で自分の位置を探す'), ('周囲を見る', 'アイテムを使う'),
    ('（北西へ歩く）', '（北西へ走る）'), ('魔法の杖を狙って使う', '魔法のスタッフを使う'),
    ('—', '（特殊：デバッグコマンド）'), ('地図を中央に表示する', '（南西のマスに働きかける）'),
    ('—', '（特殊：中断）'), ('—', 'アイテムを無視する'), ('—', '所持品・装備ウィンドウを切り替える'),
    ('（特殊：Control キー）', '階層の感触をもう一度表示する'), ('—', '自動拾得する'),
    ('モンスター・場所を標的にする', '（西のマスに働きかける）'), ('—', '（特殊：タブ）'),
    ('画面をファイルに保存する', '（南のマスに働きかける）'),
    ('アイテムに銘を刻む', '（北のマスに働きかける）'), ('アイテムの銘を消す', '（東のマスに働きかける）'),
    ('見えているモンスターの一覧', '（特殊：リターン）'),
    ('見えているアイテムの一覧', '（南東のマスに働きかける）'), ('罠へ踏み込む', '直前のメッセージを表示する'),
    ('—', '過去のメッセージを表示する'), ('隣接マスに働きかける（盗賊は盗む）', '—'),
    ('設定を変更する', '画面を再描画する'), ('歩く（拾得あり）', '保存して続ける'),
    ('メモを取る', 'トンネルを掘る'), ('最も近いモンスターを標的にする', '（北東のマスに働きかける）'),
    ('ユーザー設定コマンドを入力する', '前のコマンドを繰り返す'), ('走る', '（特殊：ウィザードモード）'),
    ('上り階段を使う（上の説明を参照）', '保存して終了する'), ('その場に留まる（拾得あり）', '（北西のマスに働きかける）'),
    ('下り階段を使う（上の説明を参照）', '（特殊：borg コマンド）'),
    ('（特殊：キーマップを迂回する）', '知識を確認する'), ('（特殊：エスケープ）', 'ヘルプを表示する'),
    ('記号を調べる',), ('標準の弾を標的へ発射する',), ('矢筒の中身の一覧',),
]
SYMBOLS = [
    '地図の記号', '===================', '',
    '地図の記号は、三つの種類に分けられます。壁、床、扉、罠などの',
    'ダンジョンの地形、宝物、武器、魔法の道具などの拾える',
    'アイテム、そして生き物です。生き物にはダンジョン内を',
    '動き回るものも動かないものもいますが、大半はあなたに',
    '危害を加えます。', '',
    '一つの記号が複数の種類を表すことや、異なる分類のものを',
    '表すこともあります。初期設定では、@ は自分の',
    'キャラクターを表します。', '',
    'すべての記号と意味を覚える必要はありません。',
    'スラッシュのコマンド（/）で、地図上の任意の記号を',
    '調べられます（commands.txt を参照）。', '',
    'ユーザー設定ファイルを使うと、記号を好みのものに',
    '変更できます。', '', '', '',
    '視線を遮らない地形', '----------------------------------------', '',
    '. 床 ／ 1 雑貨店の入口', '. 隠れた罠 ／ 2 防具店の入口', '^ 既知の罠 ／ 3 武器店の入口',
    '; 守りの刻印 ／ 4 書店の入口', "' 開いた扉 ／ 5 錬金術店の入口", "' 壊れた扉 ／ 6 魔法店の入口",
    '< 上り階段 ／ 7 闇市場の入口', '> 下り階段 ／ 8 自宅の入口', '# 溶岩の池', '', '',
    '視線を遮る地形', '---------------------------------', '',
    '# 隠し扉 ／ # 壁', '+ 閉じた扉 ／ % 鉱脈', '+ 鍵のかかった扉 ／ * 宝の埋まった鉱脈',
    ': 瓦礫 ／ : 通行できる瓦礫', '', '', 'アイテム', '-------', '',
    '! 薬（または瓶） ／ / 長柄武器', '? 巻物（または本） ／ | 刃のある武器',
    ', キノコ（または食べ物） ／ \\ 柄のある武器', '- 魔法の杖・ロッド ／ } スリング・弓・クロスボウ',
    '_ 魔法のスタッフ ／ { 弾・矢・ボルト', '= 指輪 ／ ( 軟らかい鎧',
    '" アミュレット ／ [ 硬い鎧', '$ 金・宝石 ／ ] その他の防具',
    '~ 光源・道具・箱など ／ ) 盾', '& 複数のアイテム', '', '', 'モンスター', '--------', '',
    '$ 這い回る硬貨 ／ , キノコの群生', 'a 巨大アリ ／ A アイヌ', 'b 巨大コウモリ ／ B 鳥',
    'c 巨大ムカデ ／ C イヌ科', 'd ドラゴン ／ D 古代ドラゴン', 'e 浮遊する目 ／ E 精霊',
    'f ネコ科 ／ F トンボ', 'g ゴーレム ／ G 幽霊', 'h 人型生物 ／ H 混成獣',
    'i ベトベト ／ I 昆虫', 'j ゼリー ／ J ヘビ', 'k コボルド ／ K 殺人甲虫',
    'l 木・エント ／ L リッチ', 'm カビ ／ M 多頭ヒドラ', 'n ナーガ ／ N —',
    'o オーク ／ O オーガ', 'p 人間 ／ P 巨人', 'q 四足獣 ／ Q クイルスルグ（脈打つ肉塊）',
    'r 齧歯類 ／ R 爬虫類・両生類', 's 骸骨 ／ S クモ・サソリ・ダニ',
    't 町の住人 ／ T トロル', 'u 下位デーモン ／ U 上位デーモン', 'v 渦 ／ V ヴァンパイア',
    'w ミミズ・ミミズの群れ ／ W ワイト・レイス', 'x — ／ X ゾーン・ザレン',
    'y イーク ／ Y イエティ', 'z ゾンビ・ミイラ ／ Z ゼファーハウンド', '',
]


def visible_lines(text):
    """Exactly show_file's directive skip (including the terminating blank)."""
    skipped = False
    visible = []
    directives = []
    for physical, line in enumerate(text.splitlines(), 1):
        if skipped:
            if all(c in ' \t' for c in line):
                skipped = False
            directives.append((physical, line))
            continue
        if line.startswith('.. '):
            skipped = True
            directives.append((physical, line))
            continue
        visible.append((physical, line))
    return visible, directives


def command_ja(lines, rogue):
    rows = ROGUELIKE_ROWS if rogue else ORIGINAL_ROWS
    assert len(rows) == len(lines) - 17
    out = ['', 'ローグ風キー配置のコマンド一覧' if rogue else '標準キー配置のコマンド一覧', lines[2][1], '']
    out += KEY_EXPLANATION + ['']
    for (_, english), ja in zip(lines[17:], rows):
        # This is source extraction, not a runtime translation heuristic.
        cells = re.split(r'\s{2,}', english.strip())
        assert len(cells) == 2 * len(ja), (english, cells)
        keys = cells[::2]
        out.append('  ' + ' ／ '.join(f'{key} {value}' for key, value in zip(keys, ja)))
    return out


def entry(id, source, english, japanese, original_call, parameters=None, **extra):
    return dict(id=id, source=source, english=english, japanese=japanese,
        original_english=english, original_call=original_call,
        parameters=parameters or [], notes=[], **extra)


def build():
    en, ja, entries, file_records = {}, {}, [], []
    binding = hashlib.sha256()
    c_files = []
    for ordinal, filename in enumerate(FILES):
        path = ROOT / 'data/help' / filename
        raw = path.read_bytes()
        assert hashlib.sha256(raw).hexdigest() == PINNED_HASHES[filename], f'upstream help asset changed: {filename}'
        binding.update(filename.encode('ascii') + b'\0' + raw)
        lines, directives = visible_lines(raw.decode('utf-8'))
        japanese = INDEX if filename in ('index.txt', 'r_index.txt') else (
            SYMBOLS if filename == 'symbols.txt' else command_ja(lines, filename == 'r_comm.txt'))
        assert len(lines) == len(japanese), (filename, len(lines), len(japanese))
        key = filename.removesuffix('.txt')
        ids = []
        for logical, ((physical, english), japanese_line) in enumerate(zip(lines, japanese)):
            id = semantic_id(filename, logical, english)
            assert id not in en
            # Curly braces are real key/symbol glyphs in these static source rows.
            # Escape for the reviewed template grammar; rendering restores the
            # exact glyph. Do not invent a parameter for a literal key.
            en[id] = english.replace('{', '{{').replace('}', '}}')
            ja[id] = japanese_line.replace('{', '{{').replace('}', '}}')
            ids.append(id)
            item = entry(id, {'file': f'data/help/{filename}', 'line': physical,
                'logical_line': logical}, en[id], ja[id], english,
                source_kind='help_logical_line', role='layout' if not english.strip() or re.fullmatch(r'[=-]+', english) else 'text')
            item['original_english'] = english
            item['notes'] = [
                'Reviewed semantic topic/action/symbol role; canonical filename plus zero-based logical line is a separate producer binding, never a runtime English lookup.',
                'Blank/underline rows are layout identities. Japanese rows reflow in a separate browser panel; no C byte-column substitution.',
            ]
            if filename in ('index.txt', 'r_index.txt') and logical in (17, 18):
                item['notes'].append('Upstream documentation lists =,+,_ navigation, but ui-help.c has no matching switch cases; preserved as source text, not claimed implemented.')
            entries.append(item)
        file_records.append(dict(filename=filename, ordinal=ordinal, sha256=hashlib.sha256(raw).hexdigest(),
            physical_lines=len(raw.decode('utf-8').splitlines()), logical_lines=len(lines),
            skipped_lines=[dict(line=n, original=line) for n, line in directives],
            native_menu_hooks={'a': 'r_comm.txt' if filename == 'r_index.txt' else 'commands.txt', 'b': 'symbols.txt'}
                if filename in ('index.txt', 'r_index.txt') else {}, ids=ids))
        c_files.append((filename, ids))
    # Exact accepted-source call locations, separate from normalized templates.
    native = (ROOT / 'tests/accepted-source-snapshot/ui-help.c').read_text(encoding='utf-8')
    source_lines = native.splitlines()
    ui = [
        ('help.caption.file', 141, "Help file '{filename}'", 'ヘルプ「{filename}」', "Help file '%s'", [('filename', 'opaque_file_path')]),
        ('help.error.cannot_open', 150, "Cannot open '{filename}'.", '「{filename}」を開けません。', "Cannot open '%s'.", [('filename', 'opaque_file_path')]),
        ('help.title', 332, '[{build}, {caption}, Line {first}-{last}/{total}]', '[{build}、{caption}、行 {first}–{last}/{total}]', '[%s, %s, Line %d-%d/%d]',
            [('build', 'opaque_build_identity'), ('caption', 'localized_text'), ('first', 'integer'), ('last', 'integer'), ('total', 'integer')]),
        ('help.prompt.menu', 339, '[Press a Letter, or ESC to exit.]', '[文字キーで選択、ESC で終了]', '[Press a Letter, or ESC to exit.]', []),
        ('help.prompt.short_file', 342, '[Press ESC to exit.]', '[ESC で終了]', '[Press ESC to exit.]', []),
        ('help.prompt.next_page', 345, '[Press Space to advance, or ESC to exit.]', '[Space で次のページ、ESC で終了]', '[Press Space to advance, or ESC to exit.]', []),
        ('help.prompt.highlight', 361, 'Show: ', '強調表示する文字列：', 'Show: ', []),
        ('help.prompt.find', 371, 'Find: ', '検索する文字列：', 'Find: ', []),
        ('help.prompt.goto_line', 390, 'Goto Line: ', '移動先の行：', 'Goto Line: ', []),
        ('help.prompt.goto_file', 405, 'Goto File: ', '移動先のファイル：', 'Goto File: ', []),
    ]
    for id, line, english, japanese, original, params in ui:
        local = source_lines[line-1]
        original_call = local.strip()
        if id == 'help.title':
            original_call += '\n' + source_lines[line]
        assert json.dumps(original, ensure_ascii=False)[1:-1] in original_call
        en[id], ja[id] = english, japanese
        item = entry(id, {'file': 'logic/ui-help.c', 'line': line}, english, japanese, original_call,
            [dict(name=name, type=type) for name, type in params], source_kind='ui_call')
        item['original_english'] = original
        item['notes'] = ['Original native call/keys retained. Browser semantic callback precedes blocking input.']
        if params:
            item['notes'].append('Opaque filename/build identity is copied verbatim; caption uses a reviewed nested semantic reference, never completed English.')
        entries.append(item)
    # New reviewed browser action labels derive from the exact original native
    # branches. They are separate from original visible prose coverage.
    event_lines = (ROOT / 'logic/ui-event.h').read_text(encoding='utf-8-sig').splitlines()
    escape_definitions = [(line + 1, text, re.fullmatch(r'#define\s+ESCAPE\s+(0x[0-9A-Fa-f]+|[0-9]+)\s*', text))
        for line, text in enumerate(event_lines)]
    escape_definitions = [(line, text, match) for line, text, match in escape_definitions if match]
    assert len(escape_definitions) == 1
    escape_line, escape_call, escape_match = escape_definitions[0]
    escape_code = int(escape_match.group(1), 0)
    actions = [
        ('previous_line', 'Previous line', '前の行', 415, ord('k')),
        ('next_line', 'Next line', '次の行', 430, ord('j')),
        ('previous_page', 'Previous page', '前のページ', 421, ord('-')),
        ('next_page', 'Next page', '次のページ', 436, ord(' ')),
        ('first_line', 'First line', '先頭へ', 425, ord('7')),
        ('last_page', 'Last page', '末尾へ', 440, ord('1')),
        ('find', 'Find text', '文字列を検索', 369, ord('/')),
        ('highlight', 'Highlight text', '文字列を強調表示', 359, ord('&')),
        ('goto_line', 'Go to line', '指定行へ', 387, ord('#')),
        ('goto_file', 'Go to file', '指定ファイルへ', 396, ord('%')),
        ('toggle_case', 'Toggle case sensitivity', '大文字・小文字の区別を切り替える', 355, ord('!')),
        ('back_or_exit', 'Back / exit', '戻る／終了', 456, escape_code),
        ('exit_all', 'Close help', 'ヘルプを閉じる', 352, ord('?')),
    ]
    for role, english, japanese, line, key in actions:
        id = f'help.navigation.{role}'
        en[id], ja[id] = english, japanese
        item = entry(id, {'file': 'logic/ui-help.c', 'line': line}, english, japanese,
            source_lines[line-1].strip(), source_kind='reviewed_application_action', native_activation_key=key)
        item['original_english'] = None
        if role == 'back_or_exit':
            assert 'ch.code == ESCAPE' in source_lines[line-1]
            item['key_source'] = {'file': 'logic/ui-event.h', 'line': escape_line,
                'expression': 'ESCAPE', 'value': key, 'original_call': escape_call}
        else:
            native_literal = re.search(r"(?:case\s+|ch\.code\s*==\s*)'([^']*)'", source_lines[line-1])
            assert native_literal and len(native_literal.group(1)) == 1 and ord(native_literal.group(1)) == key, role
            item['key_source'] = {'file': 'logic/ui-help.c', 'line': line,
                'expression': repr(native_literal.group(1)), 'value': key,
                'original_call': source_lines[line-1].strip()}
        item['notes'] = [
            'Authored browser action label derived from the exact original C branch/key; not an original terminal string.',
            'Adapter sends the captured original native key; no translated-text key inference, new parser identity or gameplay change.',
        ]
        entries.append(item)
    digest = binding.hexdigest()
    manifest = dict(schema_version=1, upstream_commit=COMMIT,
        status='source_connected_not_runtime_verified', corpus_sha256=digest,
        license='GPL-2.0-only',
        coverage=dict(files=len(FILES), logical_rows=sum(f['logical_lines'] for f in file_records),
            text_rows=sum(e.get('role') == 'text' for e in entries), layout_rows=sum(e.get('role') == 'layout' for e in entries),
            ui_templates=len(ui), catalog_ids=len(entries)),
        application_actions=len(actions),
        exclusions=['External/arbitrary help files', 'Detailed external ReadTheDocs content',
            'Compiled/browser acceptance of Japanese matching, highlighting and committed IME input is pending root validation',
            'No Unicode normalization, transliteration or full Unicode case-fold equivalence beyond scalar lowercase'],
        native_rst_skip_rule='Skip any line starting .. ; then skip through and including the next spaces/tabs-only or empty line. Logical indices count remaining lines from zero.',
        files=file_records, entries=entries)
    output = {
        HERE / 'en.json': json.dumps(en, ensure_ascii=False, indent=2) + '\n',
        HERE / 'ja.json': json.dumps(ja, ensure_ascii=False, indent=2) + '\n',
        HERE / 'source-manifest.json': json.dumps(manifest, ensure_ascii=False, indent=2) + '\n',
    }
    output[HERE / 'row-bindings.tsv'] = ''.join(
        f'{file["filename"]}\t{logical}\t{id}\n'
        for file in file_records for logical, id in enumerate(file['ids']))
    header = ['/* SPDX-License-Identifier: GPL-2.0-only */', '/* Generated by migration/help-data/build_catalog.py; source identities only. */',
        '#ifndef ANGBAND_WEB_HELP_DATA_H', '#define ANGBAND_WEB_HELP_DATA_H',
        f'#define AB_HELP_CORPUS_SHA256 "{digest}"',
        'struct ab_help_file_data { const char *filename; const char *const *ids; size_t count; const uint32_t *activation_keys; };']
    for ordinal, (filename, ids) in enumerate(c_files):
        header.append(f'static const char *const ab_help_rows_{ordinal}[] = {{')
        header += [' ' + json.dumps(id) + ',' for id in ids]
        header.append('};')
        header.append(f'static const uint32_t ab_help_keys_{ordinal}[] = {{')
        header += [' ' + str(97 if logical == 8 else 98 if logical == 9 else 0) + ','
            if filename in ('index.txt', 'r_index.txt') else ' 0,' for logical in range(len(ids))]
        header.append('};')
    header += ['static const struct ab_help_file_data ab_help_files[] = {']
    header += [f' {{"{filename}", ab_help_rows_{ordinal}, {len(ids)}, ab_help_keys_{ordinal}}},' for ordinal, (filename, ids) in enumerate(c_files)]
    header += ['};', 'struct ab_help_action_data { const char *id; uint32_t activation_key; };',
        'static const struct ab_help_action_data ab_help_actions[] = {']
    header += [f' {{"help.navigation.{role}", {key}U}},' for role, _, _, _, key in actions]
    header += ['};', '#endif', '']
    output[ROOT / 'logic/web-help-data.h'] = '\n'.join(header)
    return output, manifest


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output, manifest = build()
    for path, content in output.items():
        if args.check:
            assert path.read_text(encoding='utf-8') == content, f'stale generated file: {path}'
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    print(json.dumps(dict(**manifest['coverage'], corpus_sha256=manifest['corpus_sha256'], check=args.check)))


if __name__ == '__main__':
    main()
