"""Prepare isolated resource-origin evidence and observers; never build/apply.

The checked generated data is an existing read-only snapshot, not an output
created by this script. A future bootstrap must hash the actually loaded bundle
before enabling the native observers. Source/order comparisons occur offline.
"""
from __future__ import annotations
import argparse
import collections
import difflib
import hashlib
import importlib.util
import json
import ast
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
SOURCE = ROOT.parent / 'official-source-audit/NetHack-5.0.0'
LOCALES = ROOT / 'locales/phase6'
OUT = HERE / 'generated'
COMMIT = '16ff59115315917b93185d026aeefea06db9b0f4'
NOTICE = b"#\tThis data file is generated by 'makedefs'.  Do not edit. \n"


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def load(path):
    return json.loads(path.read_text(encoding='utf-8'))


def module(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    import sys
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def write(name, value):
    raw = (json.dumps(value, ensure_ascii=False, indent=2) + '\n').encode('utf-8')
    (OUT / name).write_bytes(raw)
    return sha(raw)


def xcrypt(raw):
    result = bytearray()
    mask = 1
    for byte in raw:
        result.append(byte ^ mask if byte & (32 | 64) else byte)
        mask <<= 1
        if mask >= 32:
            mask = 1
    return bytes(result)


def padded(raw, amount):
    assert raw.endswith(b'\n')
    return raw[:-1] + b'_' * max(0, amount - len(raw)) + b'\n'


def lines_with_offsets(raw):
    offset = 0
    for number, line in enumerate(raw.splitlines(keepends=True), 1):
        yield number, offset, offset + len(line), line
        offset += len(line)


def rendered(raw, newline):
    assert raw.endswith(b'\n')
    return raw[:-1] + newline


def rnd_source_lines(path, mail):
    enabled = True
    stack = []
    for number, line in enumerate(path.read_bytes().splitlines(), 1):
        if line == b'^?MAIL':
            stack.append(enabled)
            enabled = enabled and mail
        elif line == b'^.':
            assert stack
            enabled = stack.pop()
        elif line.startswith(b'^'):
            raise ValueError(f'Unsupported makedefs directive {path}:{number}')
        elif enabled and line and not line.startswith(b'#'):
            yield number, line + b'\n'
    assert not stack


def certify_random(data, by_line, cat, inv, records, certificates, blocked):
    specs = [('epitaph', 'dat/epitaph.txt', 60, 'No matter where I went, here I am.'),
             ('engrave', 'dat/engrave.txt', 60, 'No matter where you go, there you are.'),
             ('bogusmon', 'dat/bogusmon.txt', 20, 'grue')]
    for member, relative, pad, default in specs:
        actual = (data / member).read_bytes()
        variants = []
        for newline in (b'\n', b'\r\n'):
            for mail in ([False, True] if member == 'engrave' else [False]):
                source_rows = list(rnd_source_lines(SOURCE / relative, mail))
                all_rows = [(None, default.encode() + b'\n')] + source_rows
                chunks = [rendered(NOTICE, newline)]
                for _, line in all_rows:
                    chunks.append(rendered(xcrypt(padded(line, pad)), newline))
                if b''.join(chunks) == actual:
                    variants.append((newline, mail, all_rows, chunks))
        if len(variants) != 1:
            blocked.append({'member': member, 'reason': 'No unique exact source-order makedefs reconstruction', 'matching_variants': len(variants)})
            continue
        newline, mail, all_rows, chunks = variants[0]
        offset = len(chunks[0])
        certificates[member] = {'sha256': sha(actual), 'bytes': len(actual),
            'certification': 'byte-exact entire file from pinned source order/padline/xcrypt/default',
            'line_ending': repr(newline), 'makedefs_mail_variant': mail,
            'configuration_status': 'whole artifact reconstruction certified; native compiler macro trace not independently captured',
            'source': relative, 'source_sha256': sha((SOURCE / relative).read_bytes())}
        for (number, original), chunk in zip(all_rows, chunks[1:]):
            entry = by_line.get((relative, number)) if number is not None else None
            ident = entry['id'] if entry else inv.semantic_candidate('nethack.resource.native_default', default)
            prefix = entry.get('original_bogusmon_prefix_code') if entry else None
            records.append({'member': member, 'start': offset, 'end': offset + len(chunk),
                'id': ident, 'control_prefix_removal_required': bool(prefix),
                'source': relative if entry else 'util/makedefs.c', 'line': number,
                'recipe': 'xcrypt/padline; original get_rnd_line newline/decryption/unpadline',
                'private_control_code': prefix, 'kind': 'selected-line'})
            if entry is None:
                cat['en'][ident] = default
                cat['argument_schemas'][ident] = []
            offset += len(chunk)
        assert offset == len(actual)


def certify_rumors(data, by_line, overlay, records, certificates):
    actual = (data / 'rumors').read_bytes()
    header, stats, *_ = actual.splitlines(keepends=True)
    assert header.rstrip(b'\r\n') == NOTICE.rstrip(b'\n')
    import re
    values = re.fullmatch(rb'(\d+),(\d+),([0-9a-f]+);(\d+),(\d+),([0-9a-f]+);0,0,([0-9a-f]+)\r?\n', stats)
    assert values, 'Original rumors header contract'
    count_t, size_t, start_t, count_f, size_f, start_f, end = [int(x, 16 if i in (2,5,6) else 10) for i,x in enumerate(values.groups())]
    newline = b'\r\n' if header.endswith(b'\r\n') else b'\n'
    chunks = [header, stats]
    offset = len(header) + len(stats)
    private = {e['private_original_source_unit_id']: e for e in overlay['entries']}
    for relative, count, size, start in [('dat/rumors.tru', count_t, size_t, start_t), ('dat/rumors.fal', count_f, size_f, start_f)]:
        assert start == offset
        rows = list(lines_with_offsets((SOURCE / relative).read_bytes()))
        assert len(rows) == count
        beginning = offset
        for number, _, _, line in rows:
            if not line.endswith(b'\n'):
                line += b'\n'
            chunk = rendered(xcrypt(padded(line, 60)), newline)
            entry = by_line[(relative, number)]
            correction = private.get(entry['id'])
            public = correction['public_event_after_original_removal']['id'] if correction else entry['id']
            records.append({'member': 'rumors', 'start': offset, 'end': offset + len(chunk),
                'id': public, 'control_prefix_removal_required': bool(correction),
                'source': relative, 'line': number, 'kind': 'selected-line',
                'recipe': 'original selected offset/newline/xcrypt/unpadline; cookie branch observed separately',
                'private_authoring_id': entry['id'] if correction else None,
                'truth_class_must_not_enter_public_event': True})
            chunks.append(chunk)
            offset += len(chunk)
        assert size == offset - beginning
    assert end == offset == len(actual)
    assert b''.join(chunks) == actual
    certificates['rumors'] = {'sha256': sha(actual), 'bytes': len(actual),
        'certification': 'byte-exact whole file from original header/source order/padline/xcrypt',
        'source_sha256': {f: sha((SOURCE / f).read_bytes()) for f in ['dat/rumors.tru', 'dat/rumors.fal']},
        'private_buckets_offline_only': True}


def certify_oracles(data, entries, inv, records, groups, certificates):
    actual = (data / 'oracles').read_bytes()
    rows = list(lines_with_offsets(actual))
    count = int(rows[1][3].strip())
    assert count == len(entries) + 1
    positions = [int(rows[i + 2][3].strip(), 16) for i in range(count + 1)]
    assert positions[-1] == len(actual)
    # Special quoted oracle is not translated without excerpt-specific rights.
    special = actual[positions[0]:positions[1] - len(b'---\r\n' if actual.endswith(b'---\r\n') else b'---\n')]
    c = (SOURCE / 'util/makedefs.c').read_text(encoding='utf-8')
    a = c.index('static const char *special_oracle[] = {')
    b = c.index('\n};', a)
    tokens = inv.c_tokens(c[a:b])
    expected_special = []
    strings = []
    for token in tokens:
        if token.kind == 'string':
            strings.append(inv.decode_c_string(token.text))
        elif token.text == ',' and strings:
            expected_special.append(''.join(strings)); strings = []
    if strings:
        expected_special.append(''.join(strings))
    newline = b'\r\n' if rows[0][3].endswith(b'\r\n') else b'\n'
    assert special == b''.join(rendered(xcrypt(s.encode() + b'\n'), newline) for s in expected_special)
    for index, entry in enumerate(entries, 1):
        start, end = positions[index], positions[index + 1]
        chunk = actual[start:end]
        expected = b''.join(rendered(xcrypt(line.encode() + b'\n'), newline)
                            for line in entry['english_source_literal'].split('\n')) + b'---' + newline
        assert chunk == expected, (entry['id'], 'original paragraph/offset mismatch')
        group = {'member': 'oracles', 'start': start, 'end': end, 'id': entry['id'],
                 'row_count': len(entry['english_source_literal'].split('\n')),
                 'source': entry['source'], 'source_start_line': entry['source_start_line'],
                 'owner': 'outoracle original tmpwin', 'completion': 'original delimiter read after exact full row sequence'}
        groups.append(group)
        for ordinal, (_, rstart, rend, line) in enumerate(lines_with_offsets(chunk)):
            records.append({'member': 'oracles', 'start': start+rstart, 'end': start+rend,
                'id': entry['id'], 'group_start': start, 'ordinal': ordinal,
                'kind': 'group-delimiter' if line == b'---' + newline else 'group-row',
                'control_prefix_removal_required': False})
    certificates['oracles'] = {'sha256': sha(actual), 'bytes': len(actual),
        'certification': 'original numeric offsets + exact source-order paragraphs + makedefs special C literals',
        'source_sha256': sha((SOURCE / 'dat/oracles.txt').read_bytes()),
        'special_quoted_oracle': {'runtime_binding_approved': False, 'rights_status': 'third-party Garey/Johnson excerpt translation permission unestablished',
            'source': 'util/makedefs.c:1400-1411', 'original_notice': '[Garey and Johnson, p. 185.]'}}


def certify_plain(data, entries, records, certificates, blocked):
    for relative in sorted({e['source'] for e in entries}):
        member = Path(relative).name
        actual = (data / member).read_bytes()
        original = (SOURCE / relative).read_bytes()
        if actual != original:
            blocked.append({'member': member, 'reason': 'plain source/generated bytes differ; needs exact makedefs preprocessing owner trace'})
            continue
        offsets = {n: (a,b) for n,a,b,_ in lines_with_offsets(original)}
        for entry in entries:
            if entry['source'] == relative:
                a,b = offsets[entry['source_start_line']]
                records.append({'member': member, 'start': a, 'end': b, 'id': entry['id'],
                    'source': relative, 'line': entry['source_start_line'], 'kind': 'display-line',
                    'control_prefix_removal_required': False,
                    'source_contains_tab': '\t' in entry['english_source_literal'],
                    'consumer_contract': 'consumer must preserve its original trim/tab/directive behavior; complete exact read only'})
        certificates[member] = {'sha256': sha(actual), 'bytes': len(actual), 'source_sha256': sha(original),
                                'certification': 'byte-exact pinned source copy'}


def collect_catalog(units, labels, overlay):
    cat = {'en': {}, 'ja': {}, 'argument_schemas': {}}
    authors = {}
    inputs = []
    for p in sorted(LOCALES.glob('*.authored.json')):
        source = p.with_name(p.name.replace('.authored.json', '.json'))
        if not source.exists() or not any(p.name.startswith(s) for s in ['help-history-', 'random-selected-text-', 'oracle-', 'lua-direct-message-', 'lua-public-field-', 'public-label-']):
            continue
        inp, authored = load(source), load(p)
        assert authored['input_sha256'] == sha(source.read_bytes())
        assert [e['id'] for e in inp['entries']] == [e['id'] for e in authored['entries']]
        for e,a in zip(inp['entries'], authored['entries']):
            assert e['source_records'] == a['source_records'] and e['argument_schemas'] == a['argument_schemas']
            assert a['runtime_binding_approved'] is False
            assert a['source_review_status'] == 'faithful-official-source-equivalent'
            if a.get('source_translation_approved', True):
                authors[e['id']] = a
        inputs.append({'input': str(source.relative_to(ROOT)), 'input_sha256': sha(source.read_bytes()),
                       'authored': str(p.relative_to(ROOT)), 'authored_sha256': sha(p.read_bytes()),
                       'runtime_binding_approved': False})
    correction = {e['private_original_source_unit_id']: e for e in overlay['entries']}
    for entry in units + labels:
        if entry.get('kind') in ['encyclopedia-body', 'tribute-selected-passage']:
            continue
        old_id = entry['id']
        change = correction.get(old_id)
        ident = change['public_event_after_original_removal']['id'] if change else old_id
        english = change['public_event_after_original_removal']['en'] if change else entry['english_named_template']
        cat['en'][ident] = english
        cat['argument_schemas'][ident] = entry['argument_schemas']
        author = authors.get(old_id)
        if author:
            japanese = author['whole_message_ja']
            if change:
                assert japanese.startswith('[cookie] '), (old_id, 'authored private-prefix reconciliation required')
                japanese = japanese[len('[cookie] '):]
            cat['ja'][ident] = japanese
        if entry.get('kind') == 'help-or-history-line':
            # whatdoes_help emits p after its original leading whitespace scan,
            # while keeping the line terminator in the original putstr argument.
            trimmed='variant.trimmed.'+ident
            cat['en'][trimmed]=english.lstrip(' \t')+'\n'
            cat['argument_schemas'][trimmed]=[]
            if ident in cat['ja']:cat['ja'][trimmed]=cat['ja'][ident].lstrip(' \t')+'\n'
            # tty_display_file strips LF and performs native tabexpand. Tabbed
            # rows await an explicit Unicode layout contract instead of treating
            # Japanese byte positions as original native column positions.
            if '\t' not in entry['english_source_literal']:
                tty='variant.tty.'+ident
                cat['en'][tty]=english
                cat['argument_schemas'][tty]=[]
                if ident in cat['ja']:cat['ja'][tty]=cat['ja'][ident]
        if entry.get('kind') == 'original-random-selected-line':
            quoted = 'variant.quoted.' + ident
            cat['en'][quoted] = '"' + english + '"'
            cat['argument_schemas'][quoted] = entry['argument_schemas']
            if ident in cat['ja']:
                cat['ja'][quoted] = '「' + cat['ja'][ident] + '」'
    return cat, inputs


def certify_archive(path, data, certificates):
    raw=path.read_bytes();lines=raw.split(b'\n')
    rev,count,strings,start,total=map(int,lines[0].split())
    assert rev==1 and total==len(raw)
    directory=[]
    for line in lines[1:count+1]:
        handling_name,offset=line.split()
        assert handling_name[:1]==b'n'
        directory.append((handling_name[1:].decode('ascii'),int(offset)))
    assert directory[0]==('Directory',0)
    assert directory[1][1]==start
    by_name={}
    for index,(name,offset) in enumerate(directory[1:],1):
        end=directory[index+1][1] if index+1<len(directory) else total
        by_name[name]={'start':offset,'end':end,'sha256':sha(raw[offset:end])}
    for name,cert in certificates.items():
        assert by_name[name]['sha256']==cert['sha256'], (name,'actual archive differs from mapped data snapshot')
        assert raw[by_name[name]['start']:by_name[name]['end']]==(data/name).read_bytes()
        cert['archive_range']=by_name[name]
    return {'path':str(path),'sha256':sha(raw),'bytes':len(raw),'directory_entries':count,
            'certification':'original DLB rev1 directory and exact byte/hash equality of every mapped member',
            'source_reader_evidence':'src/dlb.c:133-146; original member offsets, no text lookup',
            'runtime_verified':False}


def generated_c(records, groups, certificates, archive):
    members=sorted(name for name in certificates if isinstance(certificates[name],dict))
    member_index={name:i for i,name in enumerate(members)}
    def c(s):return json.dumps(s,ensure_ascii=True) if s is not None else '0'
    out=['/* Generated private native origins; never export offsets or predicates. */',
         '#define NH_RESOURCE_EXPECTED_ARCHIVE_SHA '+c(archive['sha256']),
         'static const struct nh_member nh_members[] = {']
    out += ['    {'+c(name)+','+c(certificates[name]['sha256'])+','+str(certificates[name]['archive_range']['start'])+'L,'+str(certificates[name]['archive_range']['end']-certificates[name]['archive_range']['start'])+'L},' for name in members]
    out += ['};','static const struct nh_origin nh_origins[] = {']
    kind={'selected-line':0,'display-line':1,'group-row':2,'group-delimiter':3}
    for r in sorted(records,key=lambda x:(member_index[x['member']],x['start'])):
        ident=r['id'];display=r['kind']=='display-line'
        out.append('    {'+','.join([str(member_index[r['member']]),str(r['start'])+'L',str(r['end'])+'L',
            c(ident),c('variant.quoted.'+ident) if r['kind']=='selected-line' else '0',
            c('variant.trimmed.'+ident) if display else '0',
            c('variant.tty.'+ident) if display and not r.get('source_contains_tab') else '0',
            str(int(r['control_prefix_removal_required'])),str(kind[r['kind']]),
            str(r.get('group_start',0))+'L',str(r.get('ordinal',0))])+'},')
    out += ['};','static const struct nh_group_origin nh_group_origins[] = {']
    for g in groups:out.append('    {'+','.join([str(member_index[g['member']]),str(g['start'])+'L',str(g['end'])+'L',c(g['id']),str(g['row_count'])])+'},')
    out+=['};','']
    (OUT/'nh_resource_origin_data.inc').write_bytes('\n'.join(out).encode())


def source_owner_plans(units, labels):
    """Source-selected keys; VM execution and mutable ownership remain unbound."""
    import re
    # Reuse only the already reviewed lexer function, without executing the
    # frozen audit generator's top-level file writes or regenerating its queues.
    lexer_source=(LOCALES/'build-resource-audit.py').read_text(encoding='utf-8')
    function=next(n for n in ast.parse(lexer_source).body if isinstance(n,ast.FunctionDef) and n.name=='lua_tokens')
    namespace={'re':re}
    exec(compile(ast.Module(body=[function],type_ignores=[]),'<reviewed-lua-lexer-function>','exec'),namespace)
    tokenise=namespace['lua_tokens']
    origins=[]
    for entry in [e for e in units if e['source'].endswith('.lua')]:
        text=(SOURCE/entry['source']).read_text(encoding='utf-8')
        tokens=tokenise(text)
        chosen=[i for i,t in enumerate(tokens) if t[2]==entry['lua_literal_start'] and t[3]==entry['lua_literal_end']]
        assert len(chosen)==1
        literal=chosen[0]
        calls=[]
        for i in range(len(tokens)-3):
            if tokens[i][0]!='identifier' or tokens[i+1][1]!='.' or tokens[i+2][0]!='identifier' or tokens[i+3][1]!='(':
                continue
            api=tokens[i][1]+'.'+tokens[i+2][1]
            if api!=entry['lua_consumer_call']:continue
            depth=0
            for until in range(i+3,len(tokens)):
                if tokens[until][0]=='punct' and tokens[until][1]=='(':depth+=1
                elif tokens[until][0]=='punct' and tokens[until][1]==')':
                    depth-=1
                    if not depth:
                        if i<literal<until:calls.append((i,until))
                        break
        assert len(calls)==1,(entry['id'],calls)
        i,until=calls[0]
        call=text[tokens[i][2]:tokens[until][3]]
        origins.append({'id':entry['id'],'source':entry['source'],'source_sha256':entry['source_sha256'],
            'native_api':entry['lua_consumer_call'],'field':entry.get('lua_field'),
            'call_start':tokens[i][2],'call_end':tokens[until][3],
            'call_start_line':text.count('\n',0,tokens[i][2])+1,
            'call_end_line':text.count('\n',0,tokens[until][3])+1,
            'original_call_expression':call,'original_call_sha256':sha(call.encode()),
            'literal_token_start':entry['lua_literal_start'],'literal_token_end':entry['lua_literal_end'],
            'argument_schemas':entry['argument_schemas'],
            'producer_contract':'Bind exact certified loaded chunk + executed native call owner + original consumed field; no completed-English lookup. Multi-line Lua debug line/column is not yet an execution proof.',
            'accumulation_contract':'des.message original append/newline order and entire owner sequence; capture original convert_line/convert_arg snapshots once for quest tokens, never evaluate them again',
            'persistent_contract':'Mutable object/monster/engraving/grave retains original spelling; source-origin sidecar must survive creation, knowledge, damage, rename, save/load/bones before localized rendering',
            'debug_call_owner_proven':False,'runtime_binding_approved':False})
    counts=collections.Counter(e['native_api'] for e in origins)
    write('lua-source-producer.plan.json',{'source_commit':COMMIT,'entries':origins,'counts':dict(counts),
         'lexer_source_sha256':sha((LOCALES/'build-resource-audit.py').read_bytes()),
         'source_api_or_data_modified':False,'runtime_binding_approved':False,
         'unbound_cases':['current Lua source/PC/field owner at native call not compiled or captured',
             'table fields created or moved dynamically require exact owner lineage; debug line alone insufficient',
             'accumulated level-message original quest argument snapshots and whole callback group',
             'persistent producer lineage/mutations and versioned safe save/load/bones sidecar',
             'Elbereth native gameplay comparison must remain original spelling']})
    groups=collections.defaultdict(list)
    for e in labels:groups[(e['source'],e.get('source_array'),e.get('row'),e.get('field'))].append(e)
    plan=[]
    for key,entries in groups.items():
        for ordinal,e in enumerate(sorted(entries,key=lambda x:x['source_literal_start'])):
            plan.append({'id':e['id'],'source':e['source'],'source_sha256':e['source_sha256'],
                'source_array':e.get('source_array'),'original_row':e.get('row'),'original_field':e.get('field'),
                'literal_ordinal_inside_field':ordinal,'original_token_start':e['source_literal_start'],
                'source_tokens':e['source_literal_tokens'],'consumer_evidence':e['consumer_evidence'],
                'binding_contract':'Observe already selected original row/subfield/index and consumed native string once; carry a copied typed leaf descriptor directly through that public producer. Never map a pooled char pointer or English bytes to identity.',
                'knowledge_guard':e['knowledge_guard'],'native_input_values_unchanged':True,
                'runtime_binding_approved':False})
    write('public-label-producer.plan.json',{'source_commit':COMMIT,'entries':plan,
        'source_sites':len(plan),'runtime_binding_approved':False,
        'pending':['roles rank gender subfields need original selected branch/ordinal, not another rank_of call',
            'role copy gu.urole requires certified original role ownership; custom defaults literal fallback',
            'deity native underscore/gender branch already computed; expose displayed label only',
            'option/command descriptions have native parser tokens/defaults separate from translated prose',
            'status hunger/encumbrance original selected index once; Unicode display cells and UTF-8 byte precision must be explicit',
            'whole menus/status formatter owner recipes need every consumed member or whole original English']})


def source_patch():
    changes = collections.defaultdict(list)
    def add(relative, needle, insertion, mode='after'):
        text = (SOURCE / relative).read_text(encoding='utf-8')
        assert text.count(needle) == 1, (relative, needle, text.count(needle))
        changes[relative].append({'needle': needle, 'insertion': insertion, 'mode': mode})
    for relative in ['src/dlb.c','src/rumors.c','src/do_name.c','src/pager.c','win/tty/wintty.c']:
        text=(SOURCE/relative).read_text(encoding='utf-8')
        add(relative,text.splitlines()[0],'/* Modified 2026-10-02: additive source-origin presentation observers; original gameplay/source below preserved. Source-only proposal, not active build. */\n','before')
        anchor='#include "dlb.h"' if '#include "dlb.h"' in text else '#include "hack.h"'
        add(relative, anchor, '\n#include "nh_resource_origin.h"')
    add('src/dlb.c', '    dp->mark = 0;', '\n    nh_resource_opened(dp, name, start, size);')
    add('src/dlb.c', '    dp->mark = curpos;', '\n    nh_resource_seeked(dp, curpos);')
    add('src/dlb.c', '    char *bp, c = 0;', '\n    long nh_origin_start = dp->mark;')
    # Record only lib_dlb_fgets; no extra ftell/read/selection query.
    add('src/dlb.c', '\n    return buf;\n}\n\nstaticfn int\nlib_dlb_fgetc', '\n    nh_resource_read(dp, nh_origin_start, dp->mark, c == \'\\n\');', 'before-return')
    add('src/dlb.c', '        free((genericptr_t) dp);\n    }\n    return ret;', '        nh_resource_closed(dp);\n', 'before')
    add('src/rumors.c', '    rumor_buf[0] = \'\\0\';\n    if (gt.true_rumor_size < 0L)', '    nh_resource_reset_value();\n', 'before')
    add('src/rumors.c', '        *dst = \'\\0\'; /* terminator wasn\'t copied */', '\n        nh_resource_control_removed();')
    add('src/rumors.c', '    if (padlength)\n        unpadline(buf);', '\n    nh_resource_selected(fh);')
    add('src/rumors.c', '    buf[0] = \'\\0\';\n    if (fh) {', '    nh_resource_reset_value();\n', 'before')
    add('src/do_name.c', '        ++mnam;', '\n        nh_resource_control_removed();')
    add('src/rumors.c', '    boolean reading = (mechanism == BY_COOKIE || mechanism == BY_PAPER);', '\n    struct nh_resource_value nh_rumor_value;')
    add('src/rumors.c', '    line = getrumor(truth, buf, reading ? FALSE : TRUE);', '\n    nh_rumor_value = nh_resource_value_snapshot();')
    add('src/rumors.c', '        verbalize1(line);', '        nh_resource_value_emit_begin(&nh_rumor_value, 1);\n', 'before')
    add('src/rumors.c', '        verbalize1(line);', '\n        nh_resource_display_end();')
    add('src/rumors.c', '    pline1(line);\n}\n\nstaticfn void\ninit_oracles', '    nh_resource_value_emit_begin(&nh_rumor_value, 0);\n', 'before')
    add('src/rumors.c', '    pline1(line);\n}\n\nstaticfn void\ninit_oracles', '\n    nh_resource_display_end();', 'after-pline')
    # Original oracle callbacks are retained; group commit is a separate proposal.
    add('src/rumors.c', '        putstr(tmpwin, 0, "");\n\n        while (dlb_fgets', '\n        nh_resource_group_begin(tmpwin, oracles);', 'before-while')
    add('src/rumors.c', '            putstr(tmpwin, 0, xcrypt(line, xbuf));\n        }\n        display_nhwindow(tmpwin, TRUE);\n        destroy_nhwindow(tmpwin);\n close_oracles:', '\n            nh_resource_group_row(tmpwin, oracles);', 'inside-before-close')
    add('src/rumors.c', '        display_nhwindow(tmpwin, TRUE);\n        destroy_nhwindow(tmpwin);\n close_oracles:', '        nh_resource_group_finish(tmpwin, oracles);\n', 'before')
    add('src/pager.c', '        putstr(tmpwin, 0, p);', '        nh_resource_display_begin(fp, 1);\n', 'before')
    add('src/pager.c', '        putstr(tmpwin, 0, p);', '\n        nh_resource_display_end();')
    add('win/tty/wintty.c', '                tty_putstr(datawin, 0, buf);', '                nh_resource_display_begin(f, 2);\n', 'before')
    add('win/tty/wintty.c', '                tty_putstr(datawin, 0, buf);', '\n                nh_resource_display_end();')
    patches=[]
    for relative, edits in changes.items():
        original=(SOURCE/relative).read_text(encoding='utf-8')
        modified=original
        for e in edits:
            needle=e['needle'];insertion=e['insertion']
            if e['mode']=='before-return': replacement=needle.replace('\n    return buf;',insertion+'\n    return buf;')
            elif e['mode']=='before-while': replacement=needle.replace('\n\n        while',insertion+'\n\n        while')
            elif e['mode']=='inside-before-close':replacement=needle.replace('\n        }',insertion+'\n        }',1)
            elif e['mode']=='after-pline':replacement=needle.replace('    pline1(line);','    pline1(line);'+insertion,1)
            elif e['mode']=='before': replacement=insertion+needle
            else: replacement=needle+insertion
            assert modified.count(needle)==1,(relative,needle)
            modified=modified.replace(needle,replacement)
            e['replacement']=replacement
        restored=modified
        for e in reversed(edits):
            assert restored.count(e['replacement'])==1
            restored=restored.replace(e['replacement'],e['needle'])
        assert restored==original
        target=OUT/'source'/relative;target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(modified.encode())
        diff=''.join(difflib.unified_diff(original.splitlines(True),modified.splitlines(True),fromfile='a/'+relative,tofile='b/'+relative))
        patches.append(diff)
    (OUT/'source-observers.patch').write_bytes(''.join(patches).encode())
    return [{'source':p,'source_sha256':sha((SOURCE/p).read_bytes()),'observer_count':len(e),
             'original_source_restored_byte_exact_after_unwrap':True,'edits':e} for p,e in changes.items()]


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--generated-data',type=Path,default=ROOT/'work/phase4/NetHack-5.0.0/dat')
    parser.add_argument('--refresh-author-provenance',action='store_true',help='Explicitly accept revised source-authored fragment hashes; never imply old Japanese bytes were unchanged.')
    args=parser.parse_args()
    OUT.mkdir(parents=True,exist_ok=True)
    inv=module(ROOT/'tools/inventory_source.py','resource_origin_inventory')
    units=load(LOCALES/'resource-units.json')['entries']
    labels=load(LOCALES/'public-label-queues.json')['entries']
    overlay=load(LOCALES/'resource-transformations.overlay.json')
    cat,author_inputs=collect_catalog(units,labels,overlay)
    previous=load(OUT/'manifest.json') if (OUT/'manifest.json').exists() else None
    if previous:
        old={e['authored']:e['authored_sha256'] for e in previous['author_inputs']}
        new={e['authored']:e['authored_sha256'] for e in author_inputs}
        changes=[{'authored':name,'prior_sha256':old.get(name),'current_sha256':new.get(name)}
                 for name in sorted(set(old)|set(new)) if old.get(name)!=new.get(name)]
        if changes and not args.refresh_author_provenance:
            raise ValueError('Source-authored fragments changed after checkpoint; review exact paths/hashes and explicitly use --refresh-author-provenance: '+json.dumps(changes))
        if changes:
            snapshot=OUT/'snapshots';snapshot.mkdir(exist_ok=True)
            old_manifest=(OUT/'manifest.json').read_bytes()
            (snapshot/(sha(old_manifest)+'.manifest.json')).write_bytes(old_manifest)
            if (OUT/'catalog.source-reviewed.json').exists():
                old_catalog=(OUT/'catalog.source-reviewed.json').read_bytes()
                (snapshot/(sha(old_catalog)+'.catalog.json')).write_bytes(old_catalog)
            write('author-provenance-refresh.json',{'changes':changes,'prior_manifest_sha256':sha(old_manifest),
                 'prior_full_manifest_and_catalog_preserved':True,'runtime_approved':0,
                 'claim':'source-only author revisions explicitly accepted; original source/queue binding must still pass; Japanese content change is not dismissed as a hash-only change'})
    records=[];groups=[];certificates={};blocked=[]
    by_line={(e['source'],e['source_start_line']):e for e in units if e['source_start_line']==e['source_end_line']}
    certify_plain(args.generated_data,[e for e in units if e['kind']=='help-or-history-line'],records,certificates,blocked)
    certify_random(args.generated_data,by_line,cat,inv,records,certificates,blocked)
    certify_rumors(args.generated_data,by_line,overlay,records,certificates)
    certify_oracles(args.generated_data,[e for e in units if e['source']=='dat/oracles.txt'],inv,records,groups,certificates)
    archive=certify_archive(args.generated_data.parents[1]/'wasm-data/nhdat',args.generated_data,certificates)
    certificates['bootstrap_requirement']='Every mapping remains disabled until the actually loaded immutable bundle and each member SHA match this manifest; external changed data never trusted by filename.'
    observations=source_patch()
    source_owner_plans(units,labels)
    generated_c(records,groups,certificates,archive)
    hashes={}
    for name,value in [('catalog.source-reviewed.json',cat),('offsets.private.json',{'records':records,'groups':groups,'private_metadata_never_in_player_events':True}),
                       ('certificates.json',{'source_commit':COMMIT,'members':certificates,'generated_data_snapshot':str(args.generated_data),
                            'archive':archive,
                            'build_script_sha256':sha((ROOT/'tools/build-upstream.py').read_bytes()),
                            'snapshot_is_not_a_new_build':True,'native_macro_proof_status':'not captured; only exact artifact/source-order reconstruction is certified'}),
                       ('source-observers.json',{'entries':observations,'runtime_binding_approved':False}),
                       ('label-source-keys.private.json',{'entries':labels,'selection_contract':'original consumed table row/field/token ordinal; never text-pointer pooling or completed-English matching','runtime_binding_approved':False}),
                       ('lua-source-origins.private.json',{'entries':[e for e in units if e['source'].endswith('.lua')],
                            'accumulation_contract':'Every source-selected des.message owner and original sequence must be certified; capture original quest resolver snapshots once; any missing member means whole original English group.',
                            'persistent_contract':'No identities inferred from stored English. Need original creation-owner sidecar, mutation/rename/wipeout lineage, safe save/load/bones serialization before runtime binding.',
                            'runtime_binding_approved':False})]:hashes[name]=write(name,value)
    for name in ['lua-source-producer.plan.json','public-label-producer.plan.json','nh_resource_origin_data.inc','source-observers.patch']:
        hashes[name]=sha((OUT/name).read_bytes())
    for name in ['nh_resource_origin.h','nh_resource_origin.c']:
        hashes['../'+name]=sha((HERE/name).read_bytes())
    summary={'schema_version':1,'source_commit':COMMIT,'phase':'source-only-resource-origin-preparation',
             'counts':{'offset_records':len(records),'oracle_groups':len(groups),'certified_data_members':len(certificates)-1,
                'catalog_en':len(cat['en']),'catalog_ja_source_authored':len(cat['ja']),'label_source_sites':len(labels),
                'lua_source_sites':sum(e['source'].endswith('.lua') for e in units),'cookie_source_corrections':len(overlay['entries']),
                'source_observer_files':len(observations),'runtime_approved':0},
             'author_inputs':author_inputs,'artifacts':hashes,'blocked':blocked,
             'integration_applied':False,'compiler_run':False,'browser_run':False,
             'remaining_blockers':['actual bootstrap member/archive SHA verification and package provenance wiring',
                'shim display_file byte-offset adapter (native shim callback delegates reading to browser)',
                'scoped selected-line descriptor ownership into actual emission/name/engraving producers',
                'complete oracle callback group ownership/commit adapter; special third-party excerpt rights',
                'Lua VM/source owner identity and original quest token snapshots before message accumulation',
                'persistent name/engraving/grave sidecar mutation/save/load/bones lifecycle',
                'original selected public label subfield/index bindings, Unicode status cell/precision contracts',
                '1076 encyclopedia/tribute source-unit translation permissions unresolved; native English retained',
                'external stdio, resource backends and unverified data files fail closed'],
             'frozen_catalogs_queues_untouched':True}
    write('manifest.json',summary)
    print(json.dumps(summary['counts']))


if __name__=='__main__':main()
