import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { WASI } from 'node:wasi';
import { fileURLToPath } from 'node:url';
const root = path.dirname(fileURLToPath(import.meta.url));
const filename = process.argv[2] ?? 'hello.wasm';
const bytes = fs.readFileSync(path.join(root, filename));
const module = await WebAssembly.compile(bytes);
const imports = WebAssembly.Module.imports(module);
const exports = WebAssembly.Module.exports(module);
const wasi = new WASI({ version: 'preview1', args: [], env: {}, preopens: {}, returnOnExit: true });
const instance = await WebAssembly.instantiate(module, { wasi_snapshot_preview1: wasi.wasiImport });
const exit = wasi.start(instance);
const result = { compiler: 'official FPC pinned source 843eb4a6ac1e7c995c0af626c88639e4b1aeaf0d', filename, bytes: bytes.length, sha256: crypto.createHash('sha256').update(bytes).digest('hex'), imports, exports, exit, fullGame: false };
fs.writeFileSync(path.join(root, `${filename}.execution.json`), JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify(result, null, 2));
if (exit !== 0) process.exitCode = 1;
