const fs = require('node:fs');
const path = require('node:path');
const out = __dirname;
const common = 'Rubik dialogue uses lightly colloquial Japanese (おいら／お前さん). Official adjacent ja.po and translate-dialogue entries establish エクゾディ, ルビク, グレートグレイ, ベンゼテ, 掩体壕, 別時空／異界, and CBM names. Source translator comments guide the dialect paraphrases.';
const rows = [
  ['exodii.sign.traders_welcome', '商いの方、ようこそおいでなされ', ['The contradictory archaic phrase “Come Well Avaunt” is treated as a welcoming trader sign, consistent with the trader entrance and adjacent directional sign.']],
  ['exodii.sign.traders_direction', '<- 商いの方はこちら'],
  ['exodii.rubik.missions.anesthetic_request', 'お前さんに金属とプラスチックを仕込むんなら、あの麻酔薬が1000単位要るのさ。半分はお前さんの考える肉のため、残り半分はおいらたちの蓄えってわけだ。'],
  ['exodii.rubik.missions.good_luck', '王様のご加護あれ！'],
  ['exodii.rubik.missions.decline_accepted', '決めるのはお前さんだ、好きにしな。気が向いたらまたおいらのところへおいで。'],
  ['exodii.rubik.missions.anesthetic_hint', '外科の手術場やら、その辺を探してみるといいんじゃないかね。'],
  ['exodii.rubik.missions.anesthetic_pending', 'おいらたちは、その麻酔薬を気長に待ってるよ。'],
  ['exodii.rubik.missions.completion_ready', 'よしよし。お前さんの都合がいい時に、次へ進めるよ。'],
  ['exodii.rubik.missions.try_again_later', 'よしよし。またやる気になったら、おいらのところへおいで。'],
  ['exodii.rubik.missions.bunker_report_prompt', 'さて、あのガラクタ壕を偵察して、何が分かったかね？'],
  ['exodii.rubik.missions.bunker_report_success', 'おお、上出来だ！記録に書き留めとこうじゃないか。どうも、あいつらは厄介の種になりそうだね。老いぼれルビクのためにも、お前さんの別時空からおいらたちを追い出す気じゃないといいんだが。'],
  ['exodii.rubik.missions.bunker_report_less', 'ふむ。おいらたちの偵察じゃ、そこまでは分からなかったね。スキシアンに話しておくとしようか。', ['Scythy is the nickname for the Scythean; no filled official Japanese name was found, so スキシアン is a provisional transliteration.']],
  ['exodii.rubik.missions.warehouse_description', '探すのは、隠れ家みたいな建物さ。砂や石や金属でできたやつだ。'],
  ['exodii.rubik.missions.warehouse_pending', 'おいらたちは、気長に待ってるよ。'],
  ['exodii.rubik.missions.job_offer', '頼まれりゃ、できる範囲で何とかしようじゃないか。ああ、スキシアンのやつがおいらをせっついてる件があってね。おいらみたいなガチャガチャ者にゃ向かない仕事だが、お前さんみたいな雇われ働きなら、うってつけかもしれないよ。'],
  ['exodii.rubik.missions.subtlety_limit', 'おいらたちのでっかいガチャガチャやドシドシ四つ脚は見ただろう？得意なことは山ほどあるが、そっと静かにってのは苦手なのさ。いい出会いを望むなら、まずは麻の敷物でも敷いて、下ごしらえしなきゃならん。', ['The “hempen mats” idiom is preserved as an unusual image for preparing a meeting; translator notes do not define a more specific action.']],
  ['exodii.rubik.missions.bunker_explanation', '話すのはちょいと骨が折れるが、老いぼれルビクもできるだけやってみよう。遠くへ送り出す連中、おいらは「エスコルト」と呼ぶが…探検隊、かね？そいつらが、少し見込みのありそうな場所を偵察したんだ。コンクリの石壁に囲まれた、ガラガラした…「掩体壕」だ。死んだ土地じゃ、あいにく珍しくもないが、ここは人の出入りがある。まだ何かが中にいるんだが、誰なのか、ルビクも気になってね。味方か、それとも敵か？お前さんも、ちょいと偵察を手伝ってくれないかい？'],
  ['exodii.rubik.missions.bunker_no_contact', '違うぞ、おいらの友よ、違う！接触しちゃならん、いいね？こいつはこっそりやる仕事だ。安全だと思ったら近づいて見て回ってもいいが、くれぐれも誰とも話さず、長居もしないことだ。'],
  ['exodii.rubik.missions.bunker_plain_explanation', '*一瞬黙り込み、ゆっくりとため息をつきます。自分の言い回しにつまずきながら、ためらいがちに話します。「接触はするな。おいらたちは察する…思うに、掩体壕の外方…外側は安全で…安全に調べられる。お前さんみたいな、この土地から来た者ならね。中に入って偵察…見て回るのも、察するに、危…危険はない。見つかったと思ったら、手でも振って通り過ぎな。老いぼれルビクとエクゾディのことは、口にしちゃならん。あのガラガラ…あの掩体壕について、もう少し分かるまではね。'],
  ['exodii.rubik.missions.bunker_safe_for_locals', '偵察した限りじゃ、お前さんと同じような連中に見える。物拾いが一人二人、あそこを無事にうろついてるのも見たんだ。荒れ地の物拾いが出入りできるんなら、お前さんだって大丈夫なはずさ。'],
  ['exodii.rubik.missions.understood', 'ああ、よく分かってるじゃないか。'],
  ['exodii.rubik.missions.payment_haggle', 'こりゃまた、なかなか手強い商談だね。老いぼれルビクが約束しよう。お前さんがご立派に仕事を終えて帰ってきたら、この店のピカピカした金物から、好きなものを選ばせてやるよ。どうだい？'],
  ['exodii.rubik.missions.payment_offer', 'ああ、いい心意気だ。お返しに、老いぼれルビクの店にあるピカピカした金物をやろうじゃないか。お前さんの好きなものをね。どうだい？'],
  ['exodii.rubik.missions.payment_choice', 'そりゃ結構！さて、老いぼれルビクから、何を受け取りたいかね？'],
  ['exodii.rubik.missions.warehouse_brief', 'もちろんさ、友よ！よく分かってるじゃないか。倉庫だよ、お前さんも見たことがあるようなやつだろう。大抵のより古くて、鉄とコンクリの石をまとってる。屋根のてっぺんからは、細い鉄の突起が空へ伸びてる。普段なら、グレートグレイが呼びかけて、その突起の信号を読んで、調べに探検隊を送り出せるのさ。だがジャンプの時に突起がぐらついて、ただのガラクタになることがよくある。もう一度動かすための道具なら、おいらが渡してやれる。そいつは間違いない。'],
  ['exodii.rubik.missions.warehouse_offer', 'もちろんさ、友よ！お前さんの腕の見せどころかもしれないね。ルビクから、また頼みがあるんだ。エクゾディの旅は揺れたり跳ねたりするものでね、この前のジャンプでも、いくつかの物が迷子になったのさ。あいにく、よくあることだ。その一つが、探検隊でも信号でも見つからない。お前さんはこの土地に詳しいだろう、探してみてくれないかね？そうそう、分かってるじゃないか。倉庫だよ、お前さんも見たことがあるようなやつだろう。大抵のより古くて、鉄とコンクリの石をまとってる。屋根のてっぺんからは、細い鉄の突起が空へ伸びてる。普段なら、グレートグレイが呼びかけて、その突起の信号を読んで、調べに探検隊を送り出せるのさ。だがジャンプの時に突起がぐらついて、ただのガラクタになることがよくある。もう一度動かすための道具なら、おいらが渡してやれる。そいつは間違いない。'],
  ['exodii.rubik.missions.warehouse_offer_returning', 'もちろんさ、友よ！これまでにも、お前さんには世話になったからね。よく分かってるじゃないか。倉庫だよ、お前さんも見たことがあるようなやつだろう。大抵のより古くて、鉄とコンクリの石をまとってる。屋根のてっぺんからは、細い鉄の突起が空へ伸びてる。普段なら、グレートグレイが呼びかけて、その突起の信号を読んで、調べに探検隊を送り出せるのさ。だがジャンプの時に突起がぐらついて、ただのガラクタになることがよくある。もう一度動かすための道具なら、おいらが渡してやれる。そいつは間違いない。'],
  ['exodii.rubik.missions.antenna_plain_explanation', '突起ってのは、長くて細い棒だ、いいね。倉庫はコンクリートと錆びた鉄でできていて、上に光る棒がある。その棒が壊れてるんだと思う。止まってるのさ。もう一度動かすための道具は、ルビクが持ってるよ。'],
  ['exodii.rubik.missions.grandmother_joke', 'その通りさ。おいらの大事なジャリイに話すみたいだね、実によく分かってくれる。さて、どうする？'],
  ['exodii.rubik.missions.jaryi_definition', 'はは、お前さんをおいらのジャリイと呼んでるんじゃないよ。ジャリイは、母の母のことさ。キングズランディングで祖母をそう呼ぶんだ。ちょいとお前さんをからかったのさ。'],
  ['exodii.rubik.missions.grandparents_memory', 'そうさ、よく気がついたね。ルビクの母の母は、昔ながらの人だった。その連れ合いも、ルビクの父の父もね。父の母は「グラン」で、古いロンドンの面影みたいな人だったが、おいらにはジャリイも、タイタも、タモイもいたんだ。」ルビクの声が、一瞬遠くなります。「みんな、最後の最後までそこにいた。誰も彼も、一緒に踏みとどまったのさ。」しばらく黙ってから、我に返ったように話を続けます。「昔話をしてる暇はないね。今ここに、話を戻そうじゃないか。'],
  ['exodii.rubik.missions.warehouse_search_area', '手掛かりもないんじゃ、探すあてもない。おいらたちのドシドシ四つ脚で、隅から隅まで回るわけにもいかないし、他にも迷子の品がたくさんある。目ざとい者なら見つけやすい建物だから、この世界のお仲間が力を貸してくれるかもしれないね。'],
  ['exodii.rubik.missions.warehouse_local_guide', 'そこはお前さん次第だろうね。老いぼれルビクが見つけられるんなら、ドシドシ四つ脚を送り出すさ。でも、ちょいとこの世界のお仲間に聞いて回るのはどうだい？商人や旅人なんかにね。土地を知ってる案内人向けの仕事だと思うよ。'],
  ['exodii.rubik.missions.warehouse_cbm_reward', '老いぼれルビクの、尽きぬ喜びが報酬かね？」ルビクの顔の装甲の奥から、金属めいた笑い声が聞こえます。「もちろん、ちゃんとしたものもやるよ。CBMの保管庫から、ちょいと特別なものを見つくろってやろう。選べるようにするかね？三つばかりあるんだ。」ルビクは目の前の机から、小さな緑色に光るCRTを取り出します。奇妙な異世界の技術に囲まれた中で、それは1970年代のSF映画に出てきそうな、妙に見慣れた姿をしています。リストを素早く送って三つの項目を探し、指で叩いて示します。「CBM: 空気清浄システム」「CBM: 血液分析センサー」「CBM: 放射能洗浄システム」です。\n\n「よく考えて、仕事が済んだら決めておくれ。'],
  ['exodii.rubik.missions.warehouse_complete', '見事にやってくれたね。ありがとさん。もう、あそこへ向かう手配は進んでるよ。', ['The opaque “crib on the walkway” occurs after a successful locator reboot. Japanese uses neutral arrangements to head there, without asserting a particular camp, structure, or route.']],
  ['exodii.rubik.missions.warehouse_forgot_reboot', '*じっとこちらを見つめます。金属の殻の中でゆっくりまばたきしているのが、どういうわけか分かります。「何か忘れちゃいないかい？再起動は？おいらの心臓と外殻にかけて、そんな難しい仕事じゃなかったろうに。仕方ないね、じゃあ道順を教えておくれ。」メモ帳を取り出し、こちらへ鉛筆を差し出します。'],
  ['exodii.rubik.missions.warehouse_reward_ready', '老いぼれルビクが倉庫へ降りて、いい品をいくつか見つくろってきたよ。」カウンターの下から、透明なビニール袋を三つ取り出します。それぞれに別のサイバネティック・モジュールが入っています。「だが、渡せるのは一つだけだ。どれにする？望むなら、おいらたちが仕込んでやるよ。」'],
  ['exodii.rubik.greeting.quick_return', 'まばたき一つ、息一つでもう戻ったのかい？'],
  ['exodii.rubik.greeting.return', 'ああ、戻ってきたようだね。'],
  ['exodii.rubik.greeting.welcome_back', 'よく戻ってきたね、相棒。」ルビクは片手をカウンターに置き、もう片方の手でこちらを手招きします。'],
  ['exodii.rubik.greeting.still_alive', '結構結構、まだ死んでないね。」ざらついた声は陽気です。「ルビクの縄張りに、何の用で来たんだい？'],
  ['exodii.rubik.greeting.trade_return', 'こりゃ明るい日だ、戻ってきたね！」ルビクのざらついた声に、親しげな笑いが混じります。「ルビクに渡す品があるんなら、お前さんに渡す品もあるよ。'],
  ['exodii.rubik.greeting.first_encounter', '&目の前には、高さ7フィート以上もある金属の塊がそびえています。胴体の中央には、光を反射する大きなガラス板があります。あなたが部屋に入ると振り向き、驚くほど自然なしぐさで手を上げて挨拶します。鋼鉄の骨組みのどこかにある、見えないスピーカーからざらついた声が響きます。周囲のすべてとは裏腹に、その口調は奇妙なほど普通です。「おう、お前さんは死んでないね。取引するかい？」どこかイギリス風の訛りですが、聞き慣れたものではありません。コックニーをひどく下手にまねしたような響きです。'],
  ['exodii.rubik.introduction', 'おいらたちはエクゾディっていうんだ。他にも呼び名はあるが、それでいいさ。ここはおいらたちの住まい、まあ、こんなものだ。おいらはルビクと呼ばれてて、商いを任されてる。取引したいのかい？おいらたちはいつでも、くず金属やら何やらを探してるよ。'],
  ['exodii.rubik.agree', 'なら、結構なことだ。'],
  ['exodii.rubik.decline', 'お前さんの好きにしな。'],
  ['exodii.rubik.goods.bronze_origin', 'ちょいと意外だろう？この土地に来る前、おいらたちは、ここの時代より千年ほど前にあたる場所にいたんだ。戦の真っ最中に降り立ってね、死んだ者までまた加わり始めて、戦はとんでもないことになってた。正直、そう珍しい話じゃない。「敵」はおいらたちを戦わせるのさ。やがておいらたちが入った頃には、殺し合いの野には青銅の収穫がたっぷり残ってた。湖の鋼じゃないが、かじりつく口を食い止めるには、なかなか頑丈な金属だ。だから鎧や刺す物をいくつか、商い用に取っておいたんだよ。', ['The English dialect says “a half-score century” (ten centuries), while its translator note says about 600 years. Japanese follows the literal English source with 千年ほど; the conflicting note remains documented.']],
  ['exodii.rubik.goods.armor_origin', 'ああ、商いの目が利くね。そいつらは長年の試行錯誤の成果さ。おいらたちはずっと「敵」とやり合っててね、年月をかけて、それ向けの装いを考え出したんだ。歩く者を、もう少し長く歩かせてくれるのさ。部品はいくつかここに置いてあるが、装いを組み上げるのは、お前さんが自分で汗をかいてやるんだよ。'],
  ['exodii.rubik.goods.scavenger_suit', 'あれこれさ、分かるだろう。狩りの獲物をたっぷり背負って歩き回るためのものなんだ。つまり、死んだ土地の冷たい腕からもぎ取ったものを、歩きにくくもならず、這い寄る冷たい手につかまれやすくもならずに、運べるってわけだ。それに、釘みたいに頑丈なのさ。'],
  ['exodii.rubik.goods.fabricator_limit', '単純に、ジャンプの仕組みのせいさ。おいらたちの装いは、訪れた土地の布や皮でできてることが多いんだが、転送装置は旅の途中で、生き物からできた品をあちこち引き裂いちまう。気をつけりゃ残せるものもあるが、予備を十分にしまっておく場所がない。それに、製造機は太陽石みたいに熱くなるほど働きづめでね、おいらたち自身が使わないものに手間をかける余裕はないのさ。'],
  ['exodii.rubik.goods.restock_interval', 'へへ、老いぼれルビクの品が、そんなに恋しいのかい？もちろんさ、<interval>したらまたおいで。'],
  ['exodii.rubik.talk.cost', '試すぶんにはいいさ。おいらは話の上手な方じゃないし、いつまでもただで喋ってるわけにもいかないんでね。'],
  ['exodii.rubik.service.prompt', 'もちろんさ。」ざらついた声が、いかにも「お客様対応」という調子になります。「おいらに、何をしてほしいんだい？'],
  ['exodii.rubik.service.business_first', 'ああ、商売が先っていうからね。老いぼれルビクに何の用だい？'],
  ['exodii.rubik.service.operating', 'いや、相棒、まだ手術中だよ。'],
  ['exodii.rubik.service.fetch_patient', 'ちょいと待ちな、ここへ連れてくるよ。'],
  ['exodii.rubik.service.assess_patient', 'ちょいと見せておくれ。ぴかぴかの硬貨で、できるだけのことはしよう。'],
  ['exodii.rubik.service.cyborg_options', 'この者なら、仕込まれた物を取り出して、使えるやつをお前さんに渡せる。壊れた部分だけ取り除いて、残りはこの者がまだ使えるようにもできる。それとも、おいらに引き渡すのはどうだい？なかなか役に立つ働き手になれると思うよ。'],
  ['exodii.rubik.service.dead_cyborg_options', 'この者はもう動かせないね。死に食われた脳が多すぎる。だが部品を回収するか、ウォーカーに作り替えるか、それとも腐った部分と神経の接続だけ取り除いて、きちんと弔えるようにすることはできるよ。'],
  ['exodii.rubik.world.arrival_date', 'ありがとさん。お前さんとルビクが初めて会った時、あの騒ぎが始まってから、どれくらいたってたかね？'],
  ['exodii.rubik.world.benzete_lucky_jump', 'こりゃ結構！ベンゼテは自分が二人になるほど喜ぶだろう、間違いない！つまり、大喜びするってことさ。あれにとっちゃ初めてのジャンプで、それが大当たりなんだからね。'],
  ['exodii.rubik.world.benzete_resume', '確か、ベンゼテの話をしてたね。初めてにしちゃ、実にいいジャンプだったって話をさ。'],
  ['exodii.rubik.world.fresh_deadland', '古い世界が歯茎まで擦り切れる前に出て、向こう側にまだ元気な世界を見つけなきゃならん。お前さんの死んだ土地は、ぴかぴかの新品さ。'],
  ['exodii.rubik.world.time_before_next_jump', '気にしなさんな。つまり、この土地の「敵」はまだ新しくて、次のジャンプまで、おいらたちにも少しは日の当たる安全な時間があるってことさ。'],
  ['exodii.rubik.world.technology_advantage', 'それもあるさ。だが、ここは誰にとってもいいことがあって、前のジャンプ先より頭いくつ分も上だ。フューシリーやモビングのある別時空なら、おいらたちは大助かりなのさ。'],
  ['exodii.rubik.world.technology_advantage_agree', 'その通りさ！それに、ここは誰にとってもいいことがあって、前のジャンプ先より頭いくつ分も上だ。フューシリーやモビングのある別時空なら、おいらたちは大助かりなのさ。'],
  ['exodii.rubik.world.fusilly_mobbing_definition', 'おっと、そうだった。土地ごとに呼び方が違うからね。フューシリーは武器だよ。火薬のバンってやつで、弾をものすごい速さで飛ばすんだ。モビングはでっかい金属の箱で、中で燃やしたり爆発させたりして動かすのさ。分かるかい？'],
  ['exodii.rubik.world.dictionary_update', 'よしよし、辞書に書いておこう。ほら、言葉の国境を越えて教えてくれたお礼に、ぴかぴかの真鍮貨を一枚だ。'],
  ['exodii.rubik.world.benzete_origin', 'あれは、三回ばかり前のジャンプ先から来た別時空の者さ。空みたいに広々とした、明るい新入りでね。おいらたちがどうやって行き先を探るか、その仕組みに夢中なのさ。'],
  ['exodii.rubik.world.benzete_tracker', 'ふむ。あれが…前のジャンプの計画を立てたのかな？年寄りの追跡役の、弟子みたいなものさ。']
];
if (rows.length !== 70) throw new Error('Expected 70 authored rows');
const records = rows.map(([semanticId, translation, ambiguities], auditIndex) => ({ auditIndex, semanticId, translation, explanation: common, ...(ambiguities ? { ambiguities } : {}) }));
fs.writeFileSync(path.join(out, 'missing-a.json'), JSON.stringify({ schemaVersion: 1, records }, null, 2) + '\n');
console.log('Authored ' + records.length + ' missing translations');
