{ Generated source-guarded original item-name transition rules. GPL-2.0. }
unit drlsemanticitemcatalog;
{$mode objfpc}{$H+}
interface
implementation
uses drlsemanticitemnames, drlsemanticregistry, drlsemantictext;
const BaseNames: array[0..171] of record ID, English: AnsiString; end = (
 (ID:'chainsaw';English:'chainsaw'),
 (ID:'bfg9000';English:'BFG 9000'),
 (ID:'ublaster';English:'blaster'),
 (ID:'ucpistol';English:'combat pistol'),
 (ID:'uashotgun';English:'assault shotgun'),
 (ID:'upshotgun';English:'plasma shotgun'),
 (ID:'udshotgun';English:'super shotgun'),
 (ID:'ulaser';English:'laser rifle'),
 (ID:'utristar';English:'tristar blaster'),
 (ID:'uminigun';English:'minigun'),
 (ID:'umbazooka';English:'missile launcher'),
 (ID:'unplasma';English:'nuclear plasma rifle'),
 (ID:'unbfg9000';English:'nuclear BFG 9000'),
 (ID:'utrans';English:'combat translocator'),
 (ID:'unapalm';English:'napalm launcher'),
 (ID:'uoarmor';English:'onyx armor'),
 (ID:'uparmor';English:'phaseshift armor'),
 (ID:'upboots';English:'phaseshift boots'),
 (ID:'ugarmor';English:'gothic armor'),
 (ID:'ugboots';English:'gothic boots'),
 (ID:'umedarmor';English:'medical armor'),
 (ID:'uduelarmor';English:'duelist armor'),
 (ID:'ubulletarmor';English:'bullet-proof vest'),
 (ID:'uballisticarmor';English:'ballistic vest'),
 (ID:'ueshieldarmor';English:'energy-shielded vest'),
 (ID:'uplasmashield';English:'plasma shield'),
 (ID:'uenergyshield';English:'energy shield'),
 (ID:'ubalshield';English:'ballistic shield'),
 (ID:'uacidboots';English:'acid-proof boots'),
 (ID:'ubloodboots';English:'blood boots'),
 (ID:'umod_firestorm';English:'firestorm weapon pack'),
 (ID:'umod_sniper';English:'sniper weapon pack'),
 (ID:'umod_nano';English:'nano pack'),
 (ID:'umod_onyx';English:'onyx armor pack'),
 (ID:'uswpack';English:'shockwave pack'),
 (ID:'ubskull';English:'blood skull'),
 (ID:'ufskull';English:'fire skull'),
 (ID:'uhskull';English:'hatred skull'),
 (ID:'knife';English:'combat knife'),
 (ID:'garmor';English:'green armor'),
 (ID:'barmor';English:'blue armor'),
 (ID:'rarmor';English:'red armor'),
 (ID:'sboots';English:'steel boots'),
 (ID:'pboots';English:'protective boots'),
 (ID:'psboots';English:'plasteel boots'),
 (ID:'shglobe';English:'Small Health Globe'),
 (ID:'bpack';English:'Berserk Pack'),
 (ID:'iglobe';English:'Invulnerability Globe'),
 (ID:'scglobe';English:'Supercharge Globe'),
 (ID:'lhglobe';English:'Large Health Globe'),
 (ID:'msglobe';English:'Megasphere'),
 (ID:'map';English:'Computer Map'),
 (ID:'pmap';English:'Tracking Map'),
 (ID:'gpack';English:'Light-Amp Goggles'),
 (ID:'backpack';English:'Backpack'),
 (ID:'ashard';English:'armor shard'),
 (ID:'ammo';English:'10mm ammo'),
 (ID:'shell';English:'shotgun shell'),
 (ID:'rocket';English:'rocket'),
 (ID:'cell';English:'power cell'),
 (ID:'pammo';English:'10mm ammo chain'),
 (ID:'pshell';English:'shell box'),
 (ID:'procket';English:'rocket box'),
 (ID:'pcell';English:'power battery'),
 (ID:'pistol';English:'pistol'),
 (ID:'shotgun';English:'shotgun'),
 (ID:'dshotgun';English:'double shotgun'),
 (ID:'ashotgun';English:'combat shotgun'),
 (ID:'bazooka';English:'rocket launcher'),
 (ID:'chaingun';English:'chaingun'),
 (ID:'plasma';English:'plasma rifle'),
 (ID:'smed';English:'small med-pack'),
 (ID:'lmed';English:'large med-pack'),
 (ID:'phase';English:'phase device'),
 (ID:'hphase';English:'homing phase device'),
 (ID:'epack';English:'envirosuit pack'),
 (ID:'nuke';English:'thermonuclear bomb'),
 (ID:'mod_power';English:'power mod pack'),
 (ID:'mod_tech';English:'technical mod pack'),
 (ID:'mod_agility';English:'agility mod pack'),
 (ID:'mod_bulk';English:'bulk mod pack'),
 (ID:'barrel';English:'barrel of fuel'),
 (ID:'barrela';English:'barrel of acid'),
 (ID:'barreln';English:'barrel of napalm'),
 (ID:'tree';English:'Phobos tree'),
 (ID:'lever_flood_water';English:'lever'),
 (ID:'lever_flood_acid';English:'lever'),
 (ID:'lever_flood_lava';English:'lever'),
 (ID:'lever_kill';English:'lever'),
 (ID:'lever_explode';English:'lever'),
 (ID:'lever_walls';English:'lever'),
 (ID:'lever_summon';English:'lever'),
 (ID:'lever_repair';English:'lever'),
 (ID:'lever_medical';English:'lever'),
 (ID:'lever_ammo';English:'lever'),
 (ID:'schematic_0';English:'schematics'),
 (ID:'schematic_1';English:'schematics'),
 (ID:'schematic_2';English:'schematics'),
 (ID:'lava_element';English:'lava element'),
 (ID:'unullpointer';English:'Charch''s Null Pointer'),
 (ID:'umodstaff';English:'Hell Staff'),
 (ID:'ubutcher';English:'Butcher''s Cleaver'),
 (ID:'umjoll';English:'Mjollnir'),
 (ID:'usubtle';English:'Subtle Knife'),
 (ID:'utrigun';English:'Trigun'),
 (ID:'ujackal';English:'Anti-Freak Jackal'),
 (ID:'umega';English:'Mega Buster'),
 (ID:'uberetta';English:'Grammaton Cleric Beretta'),
 (ID:'usjack';English:'Jackhammer'),
 (ID:'ufshotgun';English:'Frag Shotgun'),
 (ID:'urbazooka';English:'Revenant''s Launcher'),
 (ID:'uacid';English:'Acid Spitter'),
 (ID:'ubfg10k';English:'BFG 10K'),
 (ID:'urailgun';English:'Railgun'),
 (ID:'umarmor';English:'Malek''s Armor'),
 (ID:'ucarmor';English:'Cybernetic Armor'),
 (ID:'unarmor';English:'Necroarmor'),
 (ID:'umedparmor';English:'Medical Powerarmor'),
 (ID:'ulavaarmor';English:'Lava Armor'),
 (ID:'uenviroboots';English:'Enviroboots'),
 (ID:'unboots';English:'Nyarlaptotep''s Boots'),
 (ID:'ushieldarmor';English:'Shielded Armor'),
 (ID:'uhwpack';English:'Hellwave Pack'),
 (ID:'aarmor';English:'Angelic Armor'),
 (ID:'uberarmor';English:'Berserker Armor'),
 (ID:'udragon';English:'Dragonslayer'),
 (ID:'lever_spec3';English:'lever'),
 (ID:'hellportal';English:'Hellgate'),
 (ID:'dis_switch';English:'lever'),
 (ID:'lever_centralprocessing1';English:'lever'),
 (ID:'lever_centralprocessing2';English:'lever'),
 (ID:'lever_centralprocessing3';English:'lever'),
 (ID:'lever_centralprocessing4';English:'lever'),
 (ID:'lever_centralprocessing5';English:'lever'),
 (ID:'uarenastaff';English:'Arena Master''s Staff'),
 (ID:'lever_chain1';English:'lever'),
 (ID:'lever_chain2';English:'lever'),
 (ID:'lever_chain3';English:'lever'),
 (ID:'lever_deimoslab';English:'lever'),
 (ID:'spear';English:'Longinus Spear'),
 (ID:'uscythe';English:'Azrael''s Scythe'),
 (ID:'lever_limbow';English:'lever'),
 (ID:'lever_limboe';English:'lever'),
 (ID:'lever_erebus';English:'lever'),
 (ID:'lever_phoboslab1';English:'lever'),
 (ID:'lever_phoboslab2';English:'lever'),
 (ID:'lever_toxinrefinery1';English:'lever'),
 (ID:'lever_toxinrefinery2';English:'lever'),
 (ID:'lever_toxinrefinery3';English:'lever'),
 (ID:'stubitem';English:'stubitem'),
 (ID:'teleport';English:'teleport'),
 (ID:'nat_imp';English:'ranged attack'),
 (ID:'nat_cacodemon';English:'ranged attack'),
 (ID:'nat_knight';English:'ranged attack'),
 (ID:'nat_baron';English:'ranged attack'),
 (ID:'nat_arachno';English:'ranged attack'),
 (ID:'nat_revenant';English:'ranged attack'),
 (ID:'nat_mancubus';English:'ranged attack'),
 (ID:'nat_arch';English:'ranged attack'),
 (ID:'nat_nimp';English:'ranged attack'),
 (ID:'nat_ncacodemon';English:'ranged attack'),
 (ID:'nat_nknight';English:'ranged attack'),
 (ID:'nat_narachno';English:'ranged attack'),
 (ID:'nat_nrevenant';English:'ranged attack'),
 (ID:'nat_nmancubus';English:'ranged attack'),
 (ID:'nat_narch';English:'ranged attack'),
 (ID:'nat_bruiser';English:'ranged attack'),
 (ID:'nat_shambler';English:'ranged attack'),
 (ID:'nat_lava_elemental';English:'ranged attack'),
 (ID:'nat_mastermind';English:'ranged attack'),
 (ID:'nat_apostle';English:'ranged attack'),
 (ID:'nat_arenamaster';English:'ranged attack')
);
const Rules: array[0..296] of record
 EventID, SemanticID, EnglishTemplate, ExpectedPrefix, ExpectedFixed,
 RequiredPrototype, AssemblyID, AssemblyEnglish: AnsiString;
 Kind: Byte;
end = (
 (EventID:'item.name.aspect.assembly.chainsword';SemanticID:'item.name.assembly.chainsword';EnglishTemplate:'chainsword';ExpectedPrefix:'';ExpectedFixed:'chainsword';RequiredPrototype:'';AssemblyID:'chainsword';AssemblyEnglish:'chainsword';Kind:0),
 (EventID:'item.name.aspect.assembly.pblade';SemanticID:'item.name.assembly.pblade';EnglishTemplate:'piercing {{name}}';ExpectedPrefix:'piercing ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'pblade';AssemblyEnglish:'piercing blade';Kind:1),
 (EventID:'item.name.aspect.assembly.speedloader';SemanticID:'item.name.assembly.speedloader';EnglishTemplate:'speedloader pistol';ExpectedPrefix:'';ExpectedFixed:'speedloader pistol';RequiredPrototype:'';AssemblyID:'speedloader';AssemblyEnglish:'speedloader pistol';Kind:0),
 (EventID:'item.name.aspect.assembly.elephant';SemanticID:'item.name.assembly.elephant';EnglishTemplate:'elephant gun';ExpectedPrefix:'';ExpectedFixed:'elephant gun';RequiredPrototype:'';AssemblyID:'elephant';AssemblyEnglish:'elephant gun';Kind:0),
 (EventID:'item.name.aspect.assembly.gatling';SemanticID:'item.name.assembly.gatling';EnglishTemplate:'gatling gun';ExpectedPrefix:'';ExpectedFixed:'gatling gun';RequiredPrototype:'';AssemblyID:'gatling';AssemblyEnglish:'gatling gun';Kind:0),
 (EventID:'item.name.aspect.assembly.micro';SemanticID:'item.name.assembly.micro';EnglishTemplate:'micro launcher';ExpectedPrefix:'';ExpectedFixed:'micro launcher';RequiredPrototype:'';AssemblyID:'micro';AssemblyEnglish:'micro launcher';Kind:0),
 (EventID:'item.name.aspect.assembly.tarmor';SemanticID:'item.name.assembly.tarmor';EnglishTemplate:'tactical armor';ExpectedPrefix:'';ExpectedFixed:'tactical armor';RequiredPrototype:'';AssemblyID:'tarmor';AssemblyEnglish:'tactical armor';Kind:0),
 (EventID:'item.name.aspect.assembly.tboots';SemanticID:'item.name.assembly.tboots';EnglishTemplate:'tactical boots';ExpectedPrefix:'';ExpectedFixed:'tactical boots';RequiredPrototype:'';AssemblyID:'tboots';AssemblyEnglish:'tactical boots';Kind:0),
 (EventID:'item.name.aspect.assembly.nanofiber';SemanticID:'item.name.assembly.nanofiber';EnglishTemplate:'nanofiber {{name}}';ExpectedPrefix:'nanofiber ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'nanofiber';AssemblyEnglish:'nanofiber armor';Kind:1),
 (EventID:'item.name.aspect.assembly.high';SemanticID:'item.name.assembly.high';EnglishTemplate:'high power {{name}}';ExpectedPrefix:'high power ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'high';AssemblyEnglish:'high power weapon';Kind:1),
 (EventID:'item.name.aspect.assembly.power';SemanticID:'item.name.assembly.power';EnglishTemplate:'powered {{name}}';ExpectedPrefix:'powered ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'power';AssemblyEnglish:'power armor';Kind:1),
 (EventID:'item.name.aspect.assembly.tshotgun';SemanticID:'item.name.assembly.tshotgun';EnglishTemplate:'tactical shotgun';ExpectedPrefix:'';ExpectedFixed:'tactical shotgun';RequiredPrototype:'';AssemblyID:'tshotgun';AssemblyEnglish:'tactical shotgun';Kind:0),
 (EventID:'item.name.aspect.assembly.plate';SemanticID:'item.name.assembly.plate';EnglishTemplate:'tower shield';ExpectedPrefix:'';ExpectedFixed:'tower shield';RequiredPrototype:'';AssemblyID:'plate';AssemblyEnglish:'tower shield';Kind:0),
 (EventID:'item.name.aspect.assembly.fparmor';SemanticID:'item.name.assembly.fparmor';EnglishTemplate:'fireproof {{name}}';ExpectedPrefix:'fireproof ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'fparmor';AssemblyEnglish:'fireproof armor';Kind:1),
 (EventID:'item.name.aspect.assembly.fpboots';SemanticID:'item.name.assembly.fpboots';EnglishTemplate:'fireproof {{name}}';ExpectedPrefix:'fireproof ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'fpboots';AssemblyEnglish:'fireproof boots';Kind:1),
 (EventID:'item.name.aspect.assembly.balarmor';SemanticID:'item.name.assembly.balarmor';EnglishTemplate:'ballistic {{name}}';ExpectedPrefix:'ballistic ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'balarmor';AssemblyEnglish:'ballistic armor';Kind:1),
 (EventID:'item.name.aspect.assembly.plasmatic';SemanticID:'item.name.assembly.plasmatic';EnglishTemplate:'plasmatic {{name}}';ExpectedPrefix:'plasmatic ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'plasmatic';AssemblyEnglish:'plasmatic shrapnel';Kind:1),
 (EventID:'item.name.aspect.assembly.gboots';SemanticID:'item.name.assembly.gboots';EnglishTemplate:'grappling {{name}}';ExpectedPrefix:'grappling ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'gboots';AssemblyEnglish:'grappling boots';Kind:1),
 (EventID:'item.name.aspect.assembly.grarmor';SemanticID:'item.name.assembly.grarmor';EnglishTemplate:'grappling {{name}}';ExpectedPrefix:'grappling ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'grarmor';AssemblyEnglish:'grappling armor';Kind:1),
 (EventID:'item.name.aspect.assembly.lavboots';SemanticID:'item.name.assembly.lavboots';EnglishTemplate:'lava {{name}}';ExpectedPrefix:'lava ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'lavboots';AssemblyEnglish:'lava boots';Kind:1),
 (EventID:'item.name.aspect.assembly.double';SemanticID:'item.name.assembly.double';EnglishTemplate:'double chainsaw';ExpectedPrefix:'';ExpectedFixed:'double chainsaw';RequiredPrototype:'';AssemblyID:'double';AssemblyEnglish:'double chainsaw';Kind:0),
 (EventID:'item.name.aspect.assembly.tacticalrl';SemanticID:'item.name.assembly.tacticalrl';EnglishTemplate:'tactical rocket launcher';ExpectedPrefix:'';ExpectedFixed:'tactical rocket launcher';RequiredPrototype:'';AssemblyID:'tacticalrl';AssemblyEnglish:'tactical rocket launcher';Kind:0),
 (EventID:'item.name.aspect.assembly.storm';SemanticID:'item.name.assembly.storm';EnglishTemplate:'storm {{name}}';ExpectedPrefix:'storm ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'storm';AssemblyEnglish:'storm bolter pistol';Kind:1),
 (EventID:'item.name.aspect.assembly.rifle';SemanticID:'item.name.assembly.rifle';EnglishTemplate:'assault {{name}}';ExpectedPrefix:'assault ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'rifle';AssemblyEnglish:'assault rifle';Kind:1),
 (EventID:'item.name.aspect.assembly.energy';SemanticID:'item.name.assembly.energy';EnglishTemplate:'energy {{name}}';ExpectedPrefix:'energy ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'energy';AssemblyEnglish:'energy pistol';Kind:1),
 (EventID:'item.name.aspect.assembly.assault';SemanticID:'item.name.assembly.assault';EnglishTemplate:'burst {{name}}';ExpectedPrefix:'burst ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'assault';AssemblyEnglish:'burst cannon';Kind:1),
 (EventID:'item.name.aspect.assembly.vbfg9000.nuclear';SemanticID:'item.name.assembly.vbfg9000.nuclear';EnglishTemplate:'nuclear VBFG9000';ExpectedPrefix:'';ExpectedFixed:'nuclear VBFG9000';RequiredPrototype:'';AssemblyID:'vbfg9000';AssemblyEnglish:'VBFG9000';Kind:0),
 (EventID:'item.name.aspect.assembly.vbfg9000.regular';SemanticID:'item.name.assembly.vbfg9000.regular';EnglishTemplate:'VBFG9000';ExpectedPrefix:'';ExpectedFixed:'VBFG9000';RequiredPrototype:'';AssemblyID:'vbfg9000';AssemblyEnglish:'VBFG9000';Kind:0),
 (EventID:'item.name.aspect.assembly.envboots';SemanticID:'item.name.assembly.envboots';EnglishTemplate:'environmental {{name}}';ExpectedPrefix:'environmental ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'envboots';AssemblyEnglish:'environmental boots';Kind:1),
 (EventID:'item.name.aspect.assembly.fireshield';SemanticID:'item.name.assembly.fireshield';EnglishTemplate:'fire shield';ExpectedPrefix:'';ExpectedFixed:'fire shield';RequiredPrototype:'';AssemblyID:'fireshield';AssemblyEnglish:'fire shield';Kind:0),
 (EventID:'item.name.aspect.assembly.nanoskin';SemanticID:'item.name.assembly.nanoskin';EnglishTemplate:'nanoskin {{name}}';ExpectedPrefix:'nanoskin ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'nanoskin';AssemblyEnglish:'nanofiber skin armor';Kind:1),
 (EventID:'item.name.aspect.assembly.gravity';SemanticID:'item.name.assembly.gravity';EnglishTemplate:'antigrav {{name}}';ExpectedPrefix:'antigrav ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'gravity';AssemblyEnglish:'antigrav boots';Kind:1),
 (EventID:'item.name.aspect.assembly.hyperblaster';SemanticID:'item.name.assembly.hyperblaster';EnglishTemplate:'hyperblaster';ExpectedPrefix:'';ExpectedFixed:'hyperblaster';RequiredPrototype:'';AssemblyID:'hyperblaster';AssemblyEnglish:'hyperblaster';Kind:0),
 (EventID:'item.name.aspect.assembly.fdshotgun';SemanticID:'item.name.assembly.fdshotgun';EnglishTemplate:'focused double shotgun';ExpectedPrefix:'';ExpectedFixed:'focused double shotgun';RequiredPrototype:'';AssemblyID:'fdshotgun';AssemblyEnglish:'focused double shotgun';Kind:0),
 (EventID:'item.name.aspect.assembly.nanomanufacture';SemanticID:'item.name.assembly.nanomanufacture';EnglishTemplate:'nanomachic {{name}}';ExpectedPrefix:'nanomachic ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'nanomanufacture';AssemblyEnglish:'nanomanufacture ammo';Kind:1),
 (EventID:'item.name.aspect.assembly.nsharpnel';SemanticID:'item.name.assembly.nsharpnel';EnglishTemplate:'nano {{name}}';ExpectedPrefix:'nano ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'nsharpnel';AssemblyEnglish:'nano-shrapnel';Kind:1),
 (EventID:'item.name.aspect.assembly.demolition';SemanticID:'item.name.assembly.demolition';EnglishTemplate:'demolition {{name}}';ExpectedPrefix:'demolition ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'demolition';AssemblyEnglish:'demolition ammo';Kind:1),
 (EventID:'item.name.aspect.assembly.cybernano';SemanticID:'item.name.assembly.cybernano';EnglishTemplate:'cybernano {{name}}';ExpectedPrefix:'cybernano ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'cybernano';AssemblyEnglish:'cybernano armor';Kind:1),
 (EventID:'item.name.aspect.assembly.biggest.nuclear';SemanticID:'item.name.assembly.biggest.nuclear';EnglishTemplate:'biggest fucking nuclear gun';ExpectedPrefix:'';ExpectedFixed:'biggest fucking nuclear gun';RequiredPrototype:'';AssemblyID:'biggest';AssemblyEnglish:'biggest fucking gun';Kind:0),
 (EventID:'item.name.aspect.assembly.biggest.regular';SemanticID:'item.name.assembly.biggest.regular';EnglishTemplate:'biggest fucking gun';ExpectedPrefix:'';ExpectedFixed:'biggest fucking gun';RequiredPrototype:'';AssemblyID:'biggest';AssemblyEnglish:'biggest fucking gun';Kind:0),
 (EventID:'item.name.aspect.assembly.ripper';SemanticID:'item.name.assembly.ripper';EnglishTemplate:'ripper';ExpectedPrefix:'';ExpectedFixed:'ripper';RequiredPrototype:'';AssemblyID:'ripper';AssemblyEnglish:'ripper';Kind:0),
 (EventID:'item.name.aspect.assembly.cerboots';SemanticID:'item.name.assembly.cerboots';EnglishTemplate:'cerberus {{name}}';ExpectedPrefix:'cerberus ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'cerboots';AssemblyEnglish:'cerberus boots';Kind:1),
 (EventID:'item.name.aspect.assembly.cerarmor';SemanticID:'item.name.assembly.cerarmor';EnglishTemplate:'cerberus {{name}}';ExpectedPrefix:'cerberus ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'cerarmor';AssemblyEnglish:'cerberus armor';Kind:1),
 (EventID:'item.name.aspect.assembly.mother';SemanticID:'item.name.assembly.mother';EnglishTemplate:'Mother-In-Law';ExpectedPrefix:'';ExpectedFixed:'Mother-In-Law';RequiredPrototype:'';AssemblyID:'mother';AssemblyEnglish:'Mother-In-Law';Kind:0),
 (EventID:'item.name.aspect.overcharge';SemanticID:'item.name.overcharged';EnglishTemplate:'overcharged {{name}}';ExpectedPrefix:'overcharged ';ExpectedFixed:'';RequiredPrototype:'';AssemblyID:'';AssemblyEnglish:'';Kind:1),
 (EventID:'item.name.aspect.schematic.armory.chainsword';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'chainsword schematics';RequiredPrototype:'schematic_1';AssemblyID:'chainsword';AssemblyEnglish:'chainsword';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.pblade';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'piercing blade schematics';RequiredPrototype:'schematic_1';AssemblyID:'pblade';AssemblyEnglish:'piercing blade';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.speedloader';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'speedloader pistol schematics';RequiredPrototype:'schematic_1';AssemblyID:'speedloader';AssemblyEnglish:'speedloader pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.elephant';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'elephant gun schematics';RequiredPrototype:'schematic_1';AssemblyID:'elephant';AssemblyEnglish:'elephant gun';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.gatling';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'gatling gun schematics';RequiredPrototype:'schematic_1';AssemblyID:'gatling';AssemblyEnglish:'gatling gun';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.micro';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'micro launcher schematics';RequiredPrototype:'schematic_1';AssemblyID:'micro';AssemblyEnglish:'micro launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.tarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'tarmor';AssemblyEnglish:'tactical armor';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.tboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'tboots';AssemblyEnglish:'tactical boots';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.nanofiber';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'nanofiber';AssemblyEnglish:'nanofiber armor';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.high';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'high power weapon schematics';RequiredPrototype:'schematic_1';AssemblyID:'high';AssemblyEnglish:'high power weapon';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.power';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'power armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'power';AssemblyEnglish:'power armor';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.tshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical shotgun schematics';RequiredPrototype:'schematic_1';AssemblyID:'tshotgun';AssemblyEnglish:'tactical shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.plate';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tower shield schematics';RequiredPrototype:'schematic_1';AssemblyID:'plate';AssemblyEnglish:'tower shield';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.fparmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'fparmor';AssemblyEnglish:'fireproof armor';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.fpboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'fpboots';AssemblyEnglish:'fireproof boots';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.balarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ballistic armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'balarmor';AssemblyEnglish:'ballistic armor';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.plasmatic';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'plasmatic shrapnel schematics';RequiredPrototype:'schematic_1';AssemblyID:'plasmatic';AssemblyEnglish:'plasmatic shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.gboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'gboots';AssemblyEnglish:'grappling boots';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.grarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'grarmor';AssemblyEnglish:'grappling armor';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.lavboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'lava boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'lavboots';AssemblyEnglish:'lava boots';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.double';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'double chainsaw schematics';RequiredPrototype:'schematic_1';AssemblyID:'double';AssemblyEnglish:'double chainsaw';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.tacticalrl';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical rocket launcher schematics';RequiredPrototype:'schematic_1';AssemblyID:'tacticalrl';AssemblyEnglish:'tactical rocket launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.storm';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'storm bolter pistol schematics';RequiredPrototype:'schematic_1';AssemblyID:'storm';AssemblyEnglish:'storm bolter pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.rifle';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'assault rifle schematics';RequiredPrototype:'schematic_1';AssemblyID:'rifle';AssemblyEnglish:'assault rifle';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.energy';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'energy pistol schematics';RequiredPrototype:'schematic_1';AssemblyID:'energy';AssemblyEnglish:'energy pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.assault';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'burst cannon schematics';RequiredPrototype:'schematic_1';AssemblyID:'assault';AssemblyEnglish:'burst cannon';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.vbfg9000';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'VBFG9000 schematics';RequiredPrototype:'schematic_1';AssemblyID:'vbfg9000';AssemblyEnglish:'VBFG9000';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.envboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'environmental boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'envboots';AssemblyEnglish:'environmental boots';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.fireshield';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fire shield schematics';RequiredPrototype:'schematic_1';AssemblyID:'fireshield';AssemblyEnglish:'fire shield';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.nanoskin';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber skin armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'nanoskin';AssemblyEnglish:'nanofiber skin armor';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.gravity';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'antigrav boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'gravity';AssemblyEnglish:'antigrav boots';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.hyperblaster';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'hyperblaster schematics';RequiredPrototype:'schematic_1';AssemblyID:'hyperblaster';AssemblyEnglish:'hyperblaster';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.fdshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'focused double shotgun schematics';RequiredPrototype:'schematic_1';AssemblyID:'fdshotgun';AssemblyEnglish:'focused double shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.nanomanufacture';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanomanufacture ammo schematics';RequiredPrototype:'schematic_1';AssemblyID:'nanomanufacture';AssemblyEnglish:'nanomanufacture ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.nsharpnel';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nano-shrapnel schematics';RequiredPrototype:'schematic_1';AssemblyID:'nsharpnel';AssemblyEnglish:'nano-shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.demolition';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'demolition ammo schematics';RequiredPrototype:'schematic_1';AssemblyID:'demolition';AssemblyEnglish:'demolition ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.cybernano';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cybernano armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'cybernano';AssemblyEnglish:'cybernano armor';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.biggest';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'biggest fucking gun schematics';RequiredPrototype:'schematic_1';AssemblyID:'biggest';AssemblyEnglish:'biggest fucking gun';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.ripper';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ripper schematics';RequiredPrototype:'schematic_1';AssemblyID:'ripper';AssemblyEnglish:'ripper';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.cerboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'cerboots';AssemblyEnglish:'cerberus boots';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.cerarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'cerarmor';AssemblyEnglish:'cerberus armor';Kind:2),
 (EventID:'item.name.aspect.schematic.armory.mother';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'Mother-In-Law schematics';RequiredPrototype:'schematic_1';AssemblyID:'mother';AssemblyEnglish:'Mother-In-Law';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.chainsword';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'chainsword schematics';RequiredPrototype:'schematic_0';AssemblyID:'chainsword';AssemblyEnglish:'chainsword';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.pblade';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'piercing blade schematics';RequiredPrototype:'schematic_0';AssemblyID:'pblade';AssemblyEnglish:'piercing blade';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.speedloader';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'speedloader pistol schematics';RequiredPrototype:'schematic_0';AssemblyID:'speedloader';AssemblyEnglish:'speedloader pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.elephant';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'elephant gun schematics';RequiredPrototype:'schematic_0';AssemblyID:'elephant';AssemblyEnglish:'elephant gun';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.gatling';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'gatling gun schematics';RequiredPrototype:'schematic_0';AssemblyID:'gatling';AssemblyEnglish:'gatling gun';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.micro';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'micro launcher schematics';RequiredPrototype:'schematic_0';AssemblyID:'micro';AssemblyEnglish:'micro launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.tarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'tarmor';AssemblyEnglish:'tactical armor';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.tboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'tboots';AssemblyEnglish:'tactical boots';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.nanofiber';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'nanofiber';AssemblyEnglish:'nanofiber armor';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.high';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'high power weapon schematics';RequiredPrototype:'schematic_0';AssemblyID:'high';AssemblyEnglish:'high power weapon';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.power';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'power armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'power';AssemblyEnglish:'power armor';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.tshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical shotgun schematics';RequiredPrototype:'schematic_0';AssemblyID:'tshotgun';AssemblyEnglish:'tactical shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.plate';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tower shield schematics';RequiredPrototype:'schematic_0';AssemblyID:'plate';AssemblyEnglish:'tower shield';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.fparmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'fparmor';AssemblyEnglish:'fireproof armor';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.fpboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'fpboots';AssemblyEnglish:'fireproof boots';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.balarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ballistic armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'balarmor';AssemblyEnglish:'ballistic armor';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.plasmatic';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'plasmatic shrapnel schematics';RequiredPrototype:'schematic_0';AssemblyID:'plasmatic';AssemblyEnglish:'plasmatic shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.gboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'gboots';AssemblyEnglish:'grappling boots';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.grarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'grarmor';AssemblyEnglish:'grappling armor';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.lavboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'lava boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'lavboots';AssemblyEnglish:'lava boots';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.double';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'double chainsaw schematics';RequiredPrototype:'schematic_0';AssemblyID:'double';AssemblyEnglish:'double chainsaw';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.tacticalrl';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical rocket launcher schematics';RequiredPrototype:'schematic_0';AssemblyID:'tacticalrl';AssemblyEnglish:'tactical rocket launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.storm';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'storm bolter pistol schematics';RequiredPrototype:'schematic_0';AssemblyID:'storm';AssemblyEnglish:'storm bolter pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.rifle';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'assault rifle schematics';RequiredPrototype:'schematic_0';AssemblyID:'rifle';AssemblyEnglish:'assault rifle';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.energy';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'energy pistol schematics';RequiredPrototype:'schematic_0';AssemblyID:'energy';AssemblyEnglish:'energy pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.assault';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'burst cannon schematics';RequiredPrototype:'schematic_0';AssemblyID:'assault';AssemblyEnglish:'burst cannon';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.vbfg9000';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'VBFG9000 schematics';RequiredPrototype:'schematic_0';AssemblyID:'vbfg9000';AssemblyEnglish:'VBFG9000';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.envboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'environmental boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'envboots';AssemblyEnglish:'environmental boots';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.fireshield';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fire shield schematics';RequiredPrototype:'schematic_0';AssemblyID:'fireshield';AssemblyEnglish:'fire shield';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.nanoskin';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber skin armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'nanoskin';AssemblyEnglish:'nanofiber skin armor';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.gravity';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'antigrav boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'gravity';AssemblyEnglish:'antigrav boots';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.hyperblaster';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'hyperblaster schematics';RequiredPrototype:'schematic_0';AssemblyID:'hyperblaster';AssemblyEnglish:'hyperblaster';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.fdshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'focused double shotgun schematics';RequiredPrototype:'schematic_0';AssemblyID:'fdshotgun';AssemblyEnglish:'focused double shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.nanomanufacture';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanomanufacture ammo schematics';RequiredPrototype:'schematic_0';AssemblyID:'nanomanufacture';AssemblyEnglish:'nanomanufacture ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.nsharpnel';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nano-shrapnel schematics';RequiredPrototype:'schematic_0';AssemblyID:'nsharpnel';AssemblyEnglish:'nano-shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.demolition';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'demolition ammo schematics';RequiredPrototype:'schematic_0';AssemblyID:'demolition';AssemblyEnglish:'demolition ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.cybernano';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cybernano armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'cybernano';AssemblyEnglish:'cybernano armor';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.biggest';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'biggest fucking gun schematics';RequiredPrototype:'schematic_0';AssemblyID:'biggest';AssemblyEnglish:'biggest fucking gun';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.ripper';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ripper schematics';RequiredPrototype:'schematic_0';AssemblyID:'ripper';AssemblyEnglish:'ripper';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.cerboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'cerboots';AssemblyEnglish:'cerberus boots';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.cerarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'cerarmor';AssemblyEnglish:'cerberus armor';Kind:2),
 (EventID:'item.name.aspect.schematic.centralprocessing.mother';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'Mother-In-Law schematics';RequiredPrototype:'schematic_0';AssemblyID:'mother';AssemblyEnglish:'Mother-In-Law';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.chainsword';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'chainsword schematics';RequiredPrototype:'schematic_1';AssemblyID:'chainsword';AssemblyEnglish:'chainsword';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.pblade';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'piercing blade schematics';RequiredPrototype:'schematic_1';AssemblyID:'pblade';AssemblyEnglish:'piercing blade';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.speedloader';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'speedloader pistol schematics';RequiredPrototype:'schematic_1';AssemblyID:'speedloader';AssemblyEnglish:'speedloader pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.elephant';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'elephant gun schematics';RequiredPrototype:'schematic_1';AssemblyID:'elephant';AssemblyEnglish:'elephant gun';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.gatling';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'gatling gun schematics';RequiredPrototype:'schematic_1';AssemblyID:'gatling';AssemblyEnglish:'gatling gun';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.micro';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'micro launcher schematics';RequiredPrototype:'schematic_1';AssemblyID:'micro';AssemblyEnglish:'micro launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.tarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'tarmor';AssemblyEnglish:'tactical armor';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.tboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'tboots';AssemblyEnglish:'tactical boots';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.nanofiber';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'nanofiber';AssemblyEnglish:'nanofiber armor';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.high';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'high power weapon schematics';RequiredPrototype:'schematic_1';AssemblyID:'high';AssemblyEnglish:'high power weapon';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.power';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'power armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'power';AssemblyEnglish:'power armor';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.tshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical shotgun schematics';RequiredPrototype:'schematic_1';AssemblyID:'tshotgun';AssemblyEnglish:'tactical shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.plate';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tower shield schematics';RequiredPrototype:'schematic_1';AssemblyID:'plate';AssemblyEnglish:'tower shield';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.fparmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'fparmor';AssemblyEnglish:'fireproof armor';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.fpboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'fpboots';AssemblyEnglish:'fireproof boots';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.balarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ballistic armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'balarmor';AssemblyEnglish:'ballistic armor';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.plasmatic';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'plasmatic shrapnel schematics';RequiredPrototype:'schematic_1';AssemblyID:'plasmatic';AssemblyEnglish:'plasmatic shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.gboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'gboots';AssemblyEnglish:'grappling boots';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.grarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'grarmor';AssemblyEnglish:'grappling armor';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.lavboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'lava boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'lavboots';AssemblyEnglish:'lava boots';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.double';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'double chainsaw schematics';RequiredPrototype:'schematic_1';AssemblyID:'double';AssemblyEnglish:'double chainsaw';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.tacticalrl';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical rocket launcher schematics';RequiredPrototype:'schematic_1';AssemblyID:'tacticalrl';AssemblyEnglish:'tactical rocket launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.storm';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'storm bolter pistol schematics';RequiredPrototype:'schematic_1';AssemblyID:'storm';AssemblyEnglish:'storm bolter pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.rifle';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'assault rifle schematics';RequiredPrototype:'schematic_1';AssemblyID:'rifle';AssemblyEnglish:'assault rifle';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.energy';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'energy pistol schematics';RequiredPrototype:'schematic_1';AssemblyID:'energy';AssemblyEnglish:'energy pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.assault';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'burst cannon schematics';RequiredPrototype:'schematic_1';AssemblyID:'assault';AssemblyEnglish:'burst cannon';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.vbfg9000';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'VBFG9000 schematics';RequiredPrototype:'schematic_1';AssemblyID:'vbfg9000';AssemblyEnglish:'VBFG9000';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.envboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'environmental boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'envboots';AssemblyEnglish:'environmental boots';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.fireshield';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fire shield schematics';RequiredPrototype:'schematic_1';AssemblyID:'fireshield';AssemblyEnglish:'fire shield';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.nanoskin';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber skin armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'nanoskin';AssemblyEnglish:'nanofiber skin armor';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.gravity';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'antigrav boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'gravity';AssemblyEnglish:'antigrav boots';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.hyperblaster';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'hyperblaster schematics';RequiredPrototype:'schematic_1';AssemblyID:'hyperblaster';AssemblyEnglish:'hyperblaster';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.fdshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'focused double shotgun schematics';RequiredPrototype:'schematic_1';AssemblyID:'fdshotgun';AssemblyEnglish:'focused double shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.nanomanufacture';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanomanufacture ammo schematics';RequiredPrototype:'schematic_1';AssemblyID:'nanomanufacture';AssemblyEnglish:'nanomanufacture ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.nsharpnel';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nano-shrapnel schematics';RequiredPrototype:'schematic_1';AssemblyID:'nsharpnel';AssemblyEnglish:'nano-shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.demolition';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'demolition ammo schematics';RequiredPrototype:'schematic_1';AssemblyID:'demolition';AssemblyEnglish:'demolition ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.cybernano';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cybernano armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'cybernano';AssemblyEnglish:'cybernano armor';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.biggest';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'biggest fucking gun schematics';RequiredPrototype:'schematic_1';AssemblyID:'biggest';AssemblyEnglish:'biggest fucking gun';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.ripper';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ripper schematics';RequiredPrototype:'schematic_1';AssemblyID:'ripper';AssemblyEnglish:'ripper';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.cerboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus boots schematics';RequiredPrototype:'schematic_1';AssemblyID:'cerboots';AssemblyEnglish:'cerberus boots';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.cerarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus armor schematics';RequiredPrototype:'schematic_1';AssemblyID:'cerarmor';AssemblyEnglish:'cerberus armor';Kind:2),
 (EventID:'item.name.aspect.schematic.deimoslab.mother';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'Mother-In-Law schematics';RequiredPrototype:'schematic_1';AssemblyID:'mother';AssemblyEnglish:'Mother-In-Law';Kind:2),
 (EventID:'item.name.aspect.schematic.house.chainsword';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'chainsword schematics';RequiredPrototype:'schematic_2';AssemblyID:'chainsword';AssemblyEnglish:'chainsword';Kind:2),
 (EventID:'item.name.aspect.schematic.house.pblade';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'piercing blade schematics';RequiredPrototype:'schematic_2';AssemblyID:'pblade';AssemblyEnglish:'piercing blade';Kind:2),
 (EventID:'item.name.aspect.schematic.house.speedloader';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'speedloader pistol schematics';RequiredPrototype:'schematic_2';AssemblyID:'speedloader';AssemblyEnglish:'speedloader pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.house.elephant';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'elephant gun schematics';RequiredPrototype:'schematic_2';AssemblyID:'elephant';AssemblyEnglish:'elephant gun';Kind:2),
 (EventID:'item.name.aspect.schematic.house.gatling';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'gatling gun schematics';RequiredPrototype:'schematic_2';AssemblyID:'gatling';AssemblyEnglish:'gatling gun';Kind:2),
 (EventID:'item.name.aspect.schematic.house.micro';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'micro launcher schematics';RequiredPrototype:'schematic_2';AssemblyID:'micro';AssemblyEnglish:'micro launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.house.tarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'tarmor';AssemblyEnglish:'tactical armor';Kind:2),
 (EventID:'item.name.aspect.schematic.house.tboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'tboots';AssemblyEnglish:'tactical boots';Kind:2),
 (EventID:'item.name.aspect.schematic.house.nanofiber';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'nanofiber';AssemblyEnglish:'nanofiber armor';Kind:2),
 (EventID:'item.name.aspect.schematic.house.high';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'high power weapon schematics';RequiredPrototype:'schematic_2';AssemblyID:'high';AssemblyEnglish:'high power weapon';Kind:2),
 (EventID:'item.name.aspect.schematic.house.power';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'power armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'power';AssemblyEnglish:'power armor';Kind:2),
 (EventID:'item.name.aspect.schematic.house.tshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical shotgun schematics';RequiredPrototype:'schematic_2';AssemblyID:'tshotgun';AssemblyEnglish:'tactical shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.house.plate';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tower shield schematics';RequiredPrototype:'schematic_2';AssemblyID:'plate';AssemblyEnglish:'tower shield';Kind:2),
 (EventID:'item.name.aspect.schematic.house.fparmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'fparmor';AssemblyEnglish:'fireproof armor';Kind:2),
 (EventID:'item.name.aspect.schematic.house.fpboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'fpboots';AssemblyEnglish:'fireproof boots';Kind:2),
 (EventID:'item.name.aspect.schematic.house.balarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ballistic armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'balarmor';AssemblyEnglish:'ballistic armor';Kind:2),
 (EventID:'item.name.aspect.schematic.house.plasmatic';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'plasmatic shrapnel schematics';RequiredPrototype:'schematic_2';AssemblyID:'plasmatic';AssemblyEnglish:'plasmatic shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.house.gboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'gboots';AssemblyEnglish:'grappling boots';Kind:2),
 (EventID:'item.name.aspect.schematic.house.grarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'grarmor';AssemblyEnglish:'grappling armor';Kind:2),
 (EventID:'item.name.aspect.schematic.house.lavboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'lava boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'lavboots';AssemblyEnglish:'lava boots';Kind:2),
 (EventID:'item.name.aspect.schematic.house.double';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'double chainsaw schematics';RequiredPrototype:'schematic_2';AssemblyID:'double';AssemblyEnglish:'double chainsaw';Kind:2),
 (EventID:'item.name.aspect.schematic.house.tacticalrl';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical rocket launcher schematics';RequiredPrototype:'schematic_2';AssemblyID:'tacticalrl';AssemblyEnglish:'tactical rocket launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.house.storm';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'storm bolter pistol schematics';RequiredPrototype:'schematic_2';AssemblyID:'storm';AssemblyEnglish:'storm bolter pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.house.rifle';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'assault rifle schematics';RequiredPrototype:'schematic_2';AssemblyID:'rifle';AssemblyEnglish:'assault rifle';Kind:2),
 (EventID:'item.name.aspect.schematic.house.energy';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'energy pistol schematics';RequiredPrototype:'schematic_2';AssemblyID:'energy';AssemblyEnglish:'energy pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.house.assault';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'burst cannon schematics';RequiredPrototype:'schematic_2';AssemblyID:'assault';AssemblyEnglish:'burst cannon';Kind:2),
 (EventID:'item.name.aspect.schematic.house.vbfg9000';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'VBFG9000 schematics';RequiredPrototype:'schematic_2';AssemblyID:'vbfg9000';AssemblyEnglish:'VBFG9000';Kind:2),
 (EventID:'item.name.aspect.schematic.house.envboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'environmental boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'envboots';AssemblyEnglish:'environmental boots';Kind:2),
 (EventID:'item.name.aspect.schematic.house.fireshield';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fire shield schematics';RequiredPrototype:'schematic_2';AssemblyID:'fireshield';AssemblyEnglish:'fire shield';Kind:2),
 (EventID:'item.name.aspect.schematic.house.nanoskin';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber skin armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'nanoskin';AssemblyEnglish:'nanofiber skin armor';Kind:2),
 (EventID:'item.name.aspect.schematic.house.gravity';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'antigrav boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'gravity';AssemblyEnglish:'antigrav boots';Kind:2),
 (EventID:'item.name.aspect.schematic.house.hyperblaster';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'hyperblaster schematics';RequiredPrototype:'schematic_2';AssemblyID:'hyperblaster';AssemblyEnglish:'hyperblaster';Kind:2),
 (EventID:'item.name.aspect.schematic.house.fdshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'focused double shotgun schematics';RequiredPrototype:'schematic_2';AssemblyID:'fdshotgun';AssemblyEnglish:'focused double shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.house.nanomanufacture';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanomanufacture ammo schematics';RequiredPrototype:'schematic_2';AssemblyID:'nanomanufacture';AssemblyEnglish:'nanomanufacture ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.house.nsharpnel';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nano-shrapnel schematics';RequiredPrototype:'schematic_2';AssemblyID:'nsharpnel';AssemblyEnglish:'nano-shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.house.demolition';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'demolition ammo schematics';RequiredPrototype:'schematic_2';AssemblyID:'demolition';AssemblyEnglish:'demolition ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.house.cybernano';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cybernano armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'cybernano';AssemblyEnglish:'cybernano armor';Kind:2),
 (EventID:'item.name.aspect.schematic.house.biggest';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'biggest fucking gun schematics';RequiredPrototype:'schematic_2';AssemblyID:'biggest';AssemblyEnglish:'biggest fucking gun';Kind:2),
 (EventID:'item.name.aspect.schematic.house.ripper';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ripper schematics';RequiredPrototype:'schematic_2';AssemblyID:'ripper';AssemblyEnglish:'ripper';Kind:2),
 (EventID:'item.name.aspect.schematic.house.cerboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'cerboots';AssemblyEnglish:'cerberus boots';Kind:2),
 (EventID:'item.name.aspect.schematic.house.cerarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'cerarmor';AssemblyEnglish:'cerberus armor';Kind:2),
 (EventID:'item.name.aspect.schematic.house.mother';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'Mother-In-Law schematics';RequiredPrototype:'schematic_2';AssemblyID:'mother';AssemblyEnglish:'Mother-In-Law';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.chainsword';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'chainsword schematics';RequiredPrototype:'schematic_0';AssemblyID:'chainsword';AssemblyEnglish:'chainsword';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.pblade';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'piercing blade schematics';RequiredPrototype:'schematic_0';AssemblyID:'pblade';AssemblyEnglish:'piercing blade';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.speedloader';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'speedloader pistol schematics';RequiredPrototype:'schematic_0';AssemblyID:'speedloader';AssemblyEnglish:'speedloader pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.elephant';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'elephant gun schematics';RequiredPrototype:'schematic_0';AssemblyID:'elephant';AssemblyEnglish:'elephant gun';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.gatling';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'gatling gun schematics';RequiredPrototype:'schematic_0';AssemblyID:'gatling';AssemblyEnglish:'gatling gun';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.micro';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'micro launcher schematics';RequiredPrototype:'schematic_0';AssemblyID:'micro';AssemblyEnglish:'micro launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.tarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'tarmor';AssemblyEnglish:'tactical armor';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.tboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'tboots';AssemblyEnglish:'tactical boots';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.nanofiber';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'nanofiber';AssemblyEnglish:'nanofiber armor';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.high';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'high power weapon schematics';RequiredPrototype:'schematic_0';AssemblyID:'high';AssemblyEnglish:'high power weapon';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.power';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'power armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'power';AssemblyEnglish:'power armor';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.tshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical shotgun schematics';RequiredPrototype:'schematic_0';AssemblyID:'tshotgun';AssemblyEnglish:'tactical shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.plate';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tower shield schematics';RequiredPrototype:'schematic_0';AssemblyID:'plate';AssemblyEnglish:'tower shield';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.fparmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'fparmor';AssemblyEnglish:'fireproof armor';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.fpboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'fpboots';AssemblyEnglish:'fireproof boots';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.balarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ballistic armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'balarmor';AssemblyEnglish:'ballistic armor';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.plasmatic';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'plasmatic shrapnel schematics';RequiredPrototype:'schematic_0';AssemblyID:'plasmatic';AssemblyEnglish:'plasmatic shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.gboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'gboots';AssemblyEnglish:'grappling boots';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.grarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'grarmor';AssemblyEnglish:'grappling armor';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.lavboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'lava boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'lavboots';AssemblyEnglish:'lava boots';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.double';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'double chainsaw schematics';RequiredPrototype:'schematic_0';AssemblyID:'double';AssemblyEnglish:'double chainsaw';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.tacticalrl';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical rocket launcher schematics';RequiredPrototype:'schematic_0';AssemblyID:'tacticalrl';AssemblyEnglish:'tactical rocket launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.storm';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'storm bolter pistol schematics';RequiredPrototype:'schematic_0';AssemblyID:'storm';AssemblyEnglish:'storm bolter pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.rifle';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'assault rifle schematics';RequiredPrototype:'schematic_0';AssemblyID:'rifle';AssemblyEnglish:'assault rifle';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.energy';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'energy pistol schematics';RequiredPrototype:'schematic_0';AssemblyID:'energy';AssemblyEnglish:'energy pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.assault';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'burst cannon schematics';RequiredPrototype:'schematic_0';AssemblyID:'assault';AssemblyEnglish:'burst cannon';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.vbfg9000';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'VBFG9000 schematics';RequiredPrototype:'schematic_0';AssemblyID:'vbfg9000';AssemblyEnglish:'VBFG9000';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.envboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'environmental boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'envboots';AssemblyEnglish:'environmental boots';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.fireshield';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fire shield schematics';RequiredPrototype:'schematic_0';AssemblyID:'fireshield';AssemblyEnglish:'fire shield';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.nanoskin';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber skin armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'nanoskin';AssemblyEnglish:'nanofiber skin armor';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.gravity';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'antigrav boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'gravity';AssemblyEnglish:'antigrav boots';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.hyperblaster';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'hyperblaster schematics';RequiredPrototype:'schematic_0';AssemblyID:'hyperblaster';AssemblyEnglish:'hyperblaster';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.fdshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'focused double shotgun schematics';RequiredPrototype:'schematic_0';AssemblyID:'fdshotgun';AssemblyEnglish:'focused double shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.nanomanufacture';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanomanufacture ammo schematics';RequiredPrototype:'schematic_0';AssemblyID:'nanomanufacture';AssemblyEnglish:'nanomanufacture ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.nsharpnel';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nano-shrapnel schematics';RequiredPrototype:'schematic_0';AssemblyID:'nsharpnel';AssemblyEnglish:'nano-shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.demolition';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'demolition ammo schematics';RequiredPrototype:'schematic_0';AssemblyID:'demolition';AssemblyEnglish:'demolition ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.cybernano';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cybernano armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'cybernano';AssemblyEnglish:'cybernano armor';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.biggest';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'biggest fucking gun schematics';RequiredPrototype:'schematic_0';AssemblyID:'biggest';AssemblyEnglish:'biggest fucking gun';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.ripper';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ripper schematics';RequiredPrototype:'schematic_0';AssemblyID:'ripper';AssemblyEnglish:'ripper';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.cerboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus boots schematics';RequiredPrototype:'schematic_0';AssemblyID:'cerboots';AssemblyEnglish:'cerberus boots';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.cerarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus armor schematics';RequiredPrototype:'schematic_0';AssemblyID:'cerarmor';AssemblyEnglish:'cerberus armor';Kind:2),
 (EventID:'item.name.aspect.schematic.toxinrefinery.mother';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'Mother-In-Law schematics';RequiredPrototype:'schematic_0';AssemblyID:'mother';AssemblyEnglish:'Mother-In-Law';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.chainsword';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'chainsword schematics';RequiredPrototype:'schematic_2';AssemblyID:'chainsword';AssemblyEnglish:'chainsword';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.pblade';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'piercing blade schematics';RequiredPrototype:'schematic_2';AssemblyID:'pblade';AssemblyEnglish:'piercing blade';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.speedloader';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'speedloader pistol schematics';RequiredPrototype:'schematic_2';AssemblyID:'speedloader';AssemblyEnglish:'speedloader pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.elephant';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'elephant gun schematics';RequiredPrototype:'schematic_2';AssemblyID:'elephant';AssemblyEnglish:'elephant gun';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.gatling';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'gatling gun schematics';RequiredPrototype:'schematic_2';AssemblyID:'gatling';AssemblyEnglish:'gatling gun';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.micro';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'micro launcher schematics';RequiredPrototype:'schematic_2';AssemblyID:'micro';AssemblyEnglish:'micro launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.tarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'tarmor';AssemblyEnglish:'tactical armor';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.tboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'tboots';AssemblyEnglish:'tactical boots';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.nanofiber';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'nanofiber';AssemblyEnglish:'nanofiber armor';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.high';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'high power weapon schematics';RequiredPrototype:'schematic_2';AssemblyID:'high';AssemblyEnglish:'high power weapon';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.power';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'power armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'power';AssemblyEnglish:'power armor';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.tshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical shotgun schematics';RequiredPrototype:'schematic_2';AssemblyID:'tshotgun';AssemblyEnglish:'tactical shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.plate';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tower shield schematics';RequiredPrototype:'schematic_2';AssemblyID:'plate';AssemblyEnglish:'tower shield';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.fparmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'fparmor';AssemblyEnglish:'fireproof armor';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.fpboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fireproof boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'fpboots';AssemblyEnglish:'fireproof boots';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.balarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ballistic armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'balarmor';AssemblyEnglish:'ballistic armor';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.plasmatic';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'plasmatic shrapnel schematics';RequiredPrototype:'schematic_2';AssemblyID:'plasmatic';AssemblyEnglish:'plasmatic shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.gboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'gboots';AssemblyEnglish:'grappling boots';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.grarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'grappling armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'grarmor';AssemblyEnglish:'grappling armor';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.lavboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'lava boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'lavboots';AssemblyEnglish:'lava boots';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.double';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'double chainsaw schematics';RequiredPrototype:'schematic_2';AssemblyID:'double';AssemblyEnglish:'double chainsaw';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.tacticalrl';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'tactical rocket launcher schematics';RequiredPrototype:'schematic_2';AssemblyID:'tacticalrl';AssemblyEnglish:'tactical rocket launcher';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.storm';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'storm bolter pistol schematics';RequiredPrototype:'schematic_2';AssemblyID:'storm';AssemblyEnglish:'storm bolter pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.rifle';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'assault rifle schematics';RequiredPrototype:'schematic_2';AssemblyID:'rifle';AssemblyEnglish:'assault rifle';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.energy';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'energy pistol schematics';RequiredPrototype:'schematic_2';AssemblyID:'energy';AssemblyEnglish:'energy pistol';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.assault';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'burst cannon schematics';RequiredPrototype:'schematic_2';AssemblyID:'assault';AssemblyEnglish:'burst cannon';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.vbfg9000';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'VBFG9000 schematics';RequiredPrototype:'schematic_2';AssemblyID:'vbfg9000';AssemblyEnglish:'VBFG9000';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.envboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'environmental boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'envboots';AssemblyEnglish:'environmental boots';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.fireshield';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'fire shield schematics';RequiredPrototype:'schematic_2';AssemblyID:'fireshield';AssemblyEnglish:'fire shield';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.nanoskin';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanofiber skin armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'nanoskin';AssemblyEnglish:'nanofiber skin armor';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.gravity';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'antigrav boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'gravity';AssemblyEnglish:'antigrav boots';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.hyperblaster';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'hyperblaster schematics';RequiredPrototype:'schematic_2';AssemblyID:'hyperblaster';AssemblyEnglish:'hyperblaster';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.fdshotgun';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'focused double shotgun schematics';RequiredPrototype:'schematic_2';AssemblyID:'fdshotgun';AssemblyEnglish:'focused double shotgun';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.nanomanufacture';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nanomanufacture ammo schematics';RequiredPrototype:'schematic_2';AssemblyID:'nanomanufacture';AssemblyEnglish:'nanomanufacture ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.nsharpnel';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'nano-shrapnel schematics';RequiredPrototype:'schematic_2';AssemblyID:'nsharpnel';AssemblyEnglish:'nano-shrapnel';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.demolition';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'demolition ammo schematics';RequiredPrototype:'schematic_2';AssemblyID:'demolition';AssemblyEnglish:'demolition ammo';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.cybernano';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cybernano armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'cybernano';AssemblyEnglish:'cybernano armor';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.biggest';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'biggest fucking gun schematics';RequiredPrototype:'schematic_2';AssemblyID:'biggest';AssemblyEnglish:'biggest fucking gun';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.ripper';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'ripper schematics';RequiredPrototype:'schematic_2';AssemblyID:'ripper';AssemblyEnglish:'ripper';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.cerboots';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus boots schematics';RequiredPrototype:'schematic_2';AssemblyID:'cerboots';AssemblyEnglish:'cerberus boots';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.cerarmor';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'cerberus armor schematics';RequiredPrototype:'schematic_2';AssemblyID:'cerarmor';AssemblyEnglish:'cerberus armor';Kind:2),
 (EventID:'item.name.aspect.schematic.vaults.mother';SemanticID:'item.name.schematic';EnglishTemplate:'{{assembly}} schematics';ExpectedPrefix:'';ExpectedFixed:'Mother-In-Law schematics';RequiredPrototype:'schematic_2';AssemblyID:'mother';AssemblyEnglish:'Mother-In-Law';Kind:2)
);
function ValidateBase(const aPrototypeID, aEnglish: AnsiString): Boolean;
var i: SizeInt;
begin
 for i:=0 to High(BaseNames) do if (BaseNames[i].ID=aPrototypeID) and (BaseNames[i].English=aEnglish) then Exit(True);
 Exit(False);
end;
function ValidateTransition(const aPrototypeID, aAspectID, aBeforeEnglish, aAfterEnglish: AnsiString): Boolean;
var i: SizeInt;
begin
 for i:=0 to High(Rules) do if Rules[i].EventID=aAspectID then with Rules[i] do begin
  if (RequiredPrototype<>'') and (RequiredPrototype<>aPrototypeID) then Exit(False);
  if Kind=1 then Exit(aAfterEnglish=ExpectedPrefix+aBeforeEnglish);
  Exit(aAfterEnglish=ExpectedFixed);
 end;
 Exit(False);
end;
function RenderAspect(const aPrototypeID, aAspectID, aPriorPresentation: AnsiString): AnsiString;
var i: SizeInt;
begin
 for i:=0 to High(Rules) do if Rules[i].EventID=aAspectID then with Rules[i] do begin
  if (RequiredPrototype<>'') and (RequiredPrototype<>aPrototypeID) then Exit(aPriorPresentation);
  if Kind=1 then Exit(DRLText(SemanticID,EnglishTemplate,[DRLStringParam('name',aPriorPresentation)]));
  if Kind=2 then Exit(DRLText(SemanticID,EnglishTemplate,[DRLStringParam('assembly',DRLRegistryText('mod_array',AssemblyID,'base_game','name',AssemblyEnglish))]));
  Exit(DRLText(SemanticID,EnglishTemplate));
 end;
 Exit(aPriorPresentation);
end;
initialization
 DRLItemNameBaseValidator:=@ValidateBase;
 DRLItemNameTransitionValidator:=@ValidateTransition;
 DRLItemNameAspectRenderer:=@RenderAspect;
end.
