{ Generated reviewed DRL help presentation mapping, GPL-2.0.
  Original source line sequence is retained for exact runtime identity checking. }
unit drlsemantichelp;
{$mode objfpc}{$H+}
interface
function DRLHelpTopicIndex(const aID: AnsiString): Integer;
function DRLHelpSourceLineCount(aTopic: Integer): Integer;
function DRLHelpSourceLine(aTopic, aLine: Integer): AnsiString;
function DRLHelpParagraphCount(aTopic: Integer): Integer;
function DRLHelpParagraphText(aTopic, aParagraph: Integer): AnsiString;
function DRLHelpTopicTitle(aTopic: Integer; const aOriginalTitle: AnsiString): AnsiString;
implementation
uses SysUtils, drlsemantictext;
type THelpDocumentRange = record
  ID: AnsiString;
  FirstLine, LineCount, FirstBlock, BlockCount: Integer;
end;
const CHelpDocuments: array[0..7] of THelpDocumentRange = (
  (ID: 'intro'; FirstLine: 0; LineCount: 18; FirstBlock: 0; BlockCount: 9),
  (ID: 'start'; FirstLine: 18; LineCount: 250; FirstBlock: 9; BlockCount: 73),
  (ID: 'keys'; FirstLine: 268; LineCount: 67; FirstBlock: 82; BlockCount: 27),
  (ID: 'mouse'; FirstLine: 335; LineCount: 20; FirstBlock: 109; BlockCount: 11),
  (ID: 'gamepad'; FirstLine: 355; LineCount: 52; FirstBlock: 120; BlockCount: 21),
  (ID: 'feedback'; FirstLine: 407; LineCount: 47; FirstBlock: 141; BlockCount: 39),
  (ID: 'disclaim'; FirstLine: 454; LineCount: 9; FirstBlock: 180; BlockCount: 5),
  (ID: 'credits'; FirstLine: 463; LineCount: 117; FirstBlock: 185; BlockCount: 39)
);
const CHelpSourceLines: array[0..579] of AnsiString = (
  '{rIntroduction}',
  '',
  '{rDRL} (abbr. for D, the Roguelike) is, as the name implies, a',
  'roguelike game. If you don''t know what a roguelike is... checkout ',
  'wikipedia -- {Bhttp://en.wikipedia.org/wiki/Roguelike}.',
  '',
  'DRL is inspired by a famous 1993 FPS hellish shooter. You''re',
  'the sole surviving marine from a squad sent to investigate a distress call',
  'from the moonbase of Phobos.  It turns out that all hell has broken loose',
  'on the plant... literally.',
  '',
  'Your quest in DRL is to descend into the moonbase complex, find the',
  'source of this evil outbreak, and destroy it at all costs.',
  '',
  'Unlike many other roguelikes, DRL is intended to be simple and easy to',
  'get into. To that end, there is a limited inventory, maps of the size of',
  'one screen, and one item per tile. The number of keys you need to ',
  'remember is also quite small compared to many other games in its genre.',
  '{rGetting Started}',
  '',
  'When you first start a game of DRL, you''re presented with a menu screen',
  'with a few different options:',
  '',
  '{YNew game} will, well, start a new game!',
  '{YChallenge game} is initially locked, and becomes unlocked after you reach',
  'Corporal rank (need to survive 10 levels for it). Challenge games force you',
  'to play the game a certain way (e.g. using only melee), and you can raise',
  'your player rank in DRL by completing them. As your rank goes higher, ',
  'more challenges will be made available to you.',
  '{YCustom game} brings up a selection screen where you can view and load',
  'modules. Modules are player-created levels, episodes, or entirely new games',
  'that bring a completely new experience to the DRL engine.',
  '{YShow highscores} displays the highscore list, not surprisingly.',
  '{YShow player} displays your player statistics, which include your player ',
  'rank, number of kills, and number of wins. It has several screens which',
  'can be scrolled with the arrow keys.',
  '{YHelp} displays the help screen, which contains the info you are',
  'currently reading.',
  '',
  'For now, select {YNew game} with the arrow keys and press ENTER to start',
  'your very first game of DRL!',
  '',
  'Before you start your game, you have to make a few decisions. The first is',
  'the difficulty level. At the beginning, only three difficulty levels are',
  'available: "I''m too young to die", "Hey, Not Too Rough", and "Hurt Me',
  'Plenty". At higher difficulties, more monsters appear and tougher monsters',
  'appear earlier. "Ultra-Violence" and "Nightmare!" difficulties are unlocked',
  'as your player rank rises. At Nightmare! difficulty, only the most insane',
  'DRL warriors will stand a chance!',
  '',
  'The second decision is choosing a character class. Classes differ by ',
  'starting perks, availability of one advanced trait as basic, and each of',
  'them has a different set of Master Traits.',
  '',
  'The third decision you have to make is what your name will be in the game.',
  'You can figure that much on your own, right? You can also leave it blank',
  'and wear the name of a random legendary warrior...',
  '',
  'The fourth and final choice to make is select a starting "trait". ',
  'Traits are upgrades or "perks" that you earn when you gain levels in ',
  'DRL (by killing monsters). Traits can raise your max health, let you',
  'run faster, deal more damage per shot, or otherwise make you more awesome.',
  'Some traits can be levelled up individually.',
  '',
  'You''ll notice a few traits aren''t available. Some are "Advanced Traits",',
  'and require you to learn a normal trait first. Advanced Traits are more',
  'situational but quite effective, too. The rest are master traits, which',
  'require you to take a specific set of traits (and block off a few other',
  'traits) and give you some sort of great unique bonus. But hey, don''t think',
  'about it too hard. Just pick one you like and move on.',
  '',
  'And that''s it, you''re ready to play the game! After a brief intro, you will',
  'be greeted with something like this (ASCII map is present if playing in',
  'ASCII mode):',
  '',
  '{d---------------------------------------------------------------------------}',
  ' Welcome to DRL...',
  ' ##########',
  ' #@.........',
  ' #..........',
  ' #.........',
  ' #.........',
  ' #........',
  ' #........',
  ' #.......',
  ' #......',
  ' #....',
  ' #..',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ' {bDRLguy}{d                     Armor : }{lnone}',
  ' {dHealth:}{r 100%}{d Exp:}{l  1}{d/}{l0%}{l    Weapon: }{lpistol (2d4) [6/6]}',
  ' cautious                                                  {rPhobos Base Entry}',
  '{d---------------------------------------------------------------------------}',
  '                             {bThe Starting Screen}',
  '',
  'This is a map of the first level of the moonbase on Phobos. The whole level',
  'is exactly the size of the screen. Walk around (using the arrow keys or',
  'numpad) and get used to the interface. Don''t get yourself killed!',
  '',
  'Take a look at the screen. It is divided into three parts. On top you have',
  'the "message area", made of two lines of text. Watch this space carefully',
  '-- it may notify you of impending danger or tell you that you''re out of',
  'ammo (poor sob!).',
  '',
  'On the bottom you have the status bar. The top line displays your name, and',
  'below it is the most important stat -- your health. If this one drops',
  'below one percent, you''re dead, dude - nothing can save you. Scanning ',
  'to the right you can see the experience indicator. The first number is your',
  'character level -- the higher it is, the tougher you are. The second number',
  'is your experience displayed as a percentage. Each character level requires',
  'a certain experience amount needed to achieve it.',
  '',
  'Below your health and experience is "tactics". By default your tactic is',
  '"cautious". This tactic gives no benefits or disadvantages. If you press',
  'X once, it will change to "running" (note that changing tactics takes',
  'some in-game time). With this tactic you have increased movement speed,',
  'dodge chance, and defense bonus, but have a smaller chance to hit and',
  'reduced melee damage. After some time spent running (or after pressing',
  'X again), you will get "tired". Being tired has no effects, positive',
  'or negative (like cautious), but while tired, you can''t run again. You can',
  'return to the cautious tactic by leveling up, gaining health by most',
  'methods, or descending to next level. Since running is limited in this way,',
  'try not to waste it. At the same time, however, remember to use it, as they',
  'don''t stockpile for later levels.',
  '',
  'In the column to the right of that, you have two indicators, "Armor" and',
  '"Weapon", that show you what armor and weapon you have equipped. For',
  'weapons, the number in brackets indicates the damage that the weapon',
  'deals, and the two numbers in square brackets indicate the current-loaded',
  'ammo and clip size for that weapon (e.g., [4/6] means you have four',
  'bullets in a magazine that can hold six).',
  '',
  'Between the status bar and message bar, there''s the map. The "@" sign with',
  'the cursor below it -- that''s you (aren''t you ugly?). See any letters',
  'nearby? It may be a "T"ree, but chances are it''s the enemy. Kill''em all.',
  'The "#" are walls, "+" is a closed door, "/" an open door. Dots are normal',
  'floor. Red dots are either Phobos''s ugly rock landscape (on the first',
  'level), or blood (anywhere else).',
  '',
  'Press "i" to see your inventory. It''s pretty empty, right? Your character',
  'starts equipped with a few things -- your trusty pistol (already equipped),',
  'a handful of ammo, and a couple of med-packs. To check equipped item,',
  'press "e" in-game to see the full list (which includes boots and a second',
  'weapon slot).',
  '',
  'Your pistol and ammo are not going to last you very long, though.  Press',
  '"g" to pick up new weapons (represented by "}") and ammo ("|").  If you',
  'walk around that first level you''re likely to run into some small medkits',
  '(red "+") that you can pick up and add to your inventory. Later on you',
  'might find other consumable items, they''re all "+"s. Press "i" at any time',
  'and a consumable to use it at any time. If you ever want to drop something',
  '(usually to make room for new weapons or items), press "Backspace" in the',
  'inventory screen to drop items.',
  '',
  'Along the way, you''re bound to run into levers ("&") and barrels ("0"). To',
  'pull a lever, stand on it and press "SPACE" to use them. The effects are',
  'random, so pull them at your own peril! And if you''ve ever played a shooter',
  'you know what to expect with barrels: They all explode quite nicely, but',
  'with varying effects depending on the barrel. (Be aware that levers are',
  'activated with the same button as using items -- in this case, open up',
  'your inventory and use the item from there by selecting it and pressing',
  'ENTER.)',
  '',
  'As you go deeper into the base, you''ll also find some power-ups ("^"). They',
  'are used as soon as you pick them up, and several contain powerful effect,',
  'so use them wisely.',
  '',
  'Oh, I almost forgot! To shoot, just press "f" to fire at the currently ',
  'selected target! You can swap between visible targets using "TAB", or ',
  'hold "Ctrl" to move the target reticule manually with the arrow keys.',
  'Some weapons allow an alternative fire mode, such as the chainfiring ',
  'mode of the chaingun - to use it, press "SHIFT-f".',
  '',
  'Ok, I hear you cry -- "Out of ammo!" Don''t panic. Press "r" to reload your',
  'weapon (Some weapons allow you an alternative reload by pressing SHIFT-r).',
  'Reloading the correct ammo is automatic if you have it in your inventory.',
  'But what if you don''t? You can try pounding on the enemy with your fists',
  'or a hand-to-hand weapon -- to do that just walk into him.  Pick up a',
  'Berserk Pack or a chainsaw (or at least a knife) and you can do some',
  'serious damage that way!',
  '',
  'Getting hit too frequently when trying to approach an enemy (or when',
  'running from him)? Try not to move in a straight line -- move diagonally,',
  'as this increases your chance to dodge. If you don''t want to approach or',
  'retreat from the enemy, but also don''t want to be hit often, try moving',
  'from side-to-side, perpendicular to the direction of enemy, as this',
  'gives you the same bonus as moving diagonally). Sometimes, in emergencies,',
  'switching to the running tactic and using both of these tricks at once will',
  'give you a much greater chance to dodge than normal.',
  '',
  'In the equipment menu (remember, press "e") you''ll see that you have a',
  'primary weapon equipped and a secondary weapon at hand.  By pressing "z"',
  'you can switch your primary out for your secondary.  This is faster than',
  'equipping a new weapon from your inventory and it saves you valuable',
  'space.  It''s also quite useful in a firefight, when the situation can',
  'change at any moment!',
  '',
  'Hey, you think you''re cool because you found some armor? Think again. Look,',
  'there are three numbers by the armor. The first two in square brackets are',
  '[current damage resistance/maximum damage resistance]. The second one is ',
  'your armor''s health. 100% means it''s undamaged, 1% is almost destroyed.',
  'The more damaged an armor is, the lower its actual resistance is. Keep an',
  'eye on those numbers!',
  '',
  'Additionally each armor may grant additional resistance to specific damage ',
  'types. This information can be obtained in the inventory and equipment ',
  'screens.',
  '',
  'Try to check out player information screen by pressing "p" -- some useful',
  'information is written there. First, there are your main parameters:',
  'movement, firing, and reloading speeds, as well as your chance to hit with',
  'the weapon you currently have equipped (from point blank range). Next are',
  'the more passive statistics: your player and dungeon level, amount of',
  'played turns, and your score so far. At the bottom you can find parameters',
  'of equipment that you are currently wearing: damage, firing and reloading',
  'speeds, and accuracy for weapons; and protection value, durability, and',
  'movement and knockback modifiers for armor and boots (yes, armor and boots',
  'can affect your movement speed and chance to be knocked back by powerful',
  'attacks).',
  '',
  'There are five types of items in this game:',
  '',
  '1) {!Common} - These items are... "common"? You will see them all across the',
  'game, and what you should rely on. Most are generated randomly, but you',
  'will find some are guaranteed in certain places (as a reward for completing',
  'a special level, for example). Common weapons and armor accept 1/1, 3/2,',
  'and 5/3 mods, respectively, depending on the level of your Whizkid trait.',
  '',
  '2) {CAssemblies} - These items can be assembled from other items, usually ',
  'common, by modding them with a specific set of mods. Experiment, as',
  'discovered (assembled) assemblies will be recorded in your player data and',
  'can be accessed with the "A" key during the game.',
  '',
  '3) {VExotic} - These items are rarer and more powerful than common items.',
  'They can potentially appear more than once per game, but are more often',
  'than not found in special levels. Exotic weapons and armor can hold the',
  ' same amounts of mods that their common counterparts do.',
  '',
  '4) {GUniques} - Unique items, as the name suggests, can only appear once per',
  'game. Some of them just have cool stats, while others have special',
  'abilities, and each of them come with a unique name. No unique item is',
  'guaranteed, although they can appear in special levels, and they are quite',
  'rare otherwise. Most uniques cannot be modded, but those that do can only',
  'be modded if the player is playing the Technician class.',
  '',
  '5) {YArtifacts} - Artifact items are similar to unique items, except that they',
  'can only appear in very specific special levels, while never appearing',
  'randomly. Finding and collecting these items is almost always a very',
  'challenging task.',
  '',
  'Mods (Displayed by a " symbol) are little packs that enhance your weaponry',
  'or armor. Most equipment you find can be modded, so try to cover up their',
  'weaknesses by modding them.',
  '',
  'Whenever you see something that you aren''t familiar with, press "l" to',
  'trigger the Look command -- moving the cursor with the arrow keys will',
  'show what''s under the cursor in the message bar. You can also press "h"',
  'in-game to open up the help menu.',
  '',
  'Happy fragging!',
  '{rControls}',
  '',
  '  Most keybindings can be redefined via the file Settings menu. The ',
  '  following set describes the standard layout, and does not reflect',
  '  any changes you may have made to your keybindings.',
  '',
  '  {!Escape}      -- Exit menu, or show game menu (Save/Quit/Help/etc)',
  '  {!Arrows}      -- Walking around (PgUp, PgDn, Home, End diagonally!)',
  '  {!Arrows+Ctrl} -- Manually move target reticule',
  '  {!TAB}         -- Switch between targets',
  '  ',
  '  {!h}       -- Run on-line help',
  '  {!SPACE}   -- Action - open doors, close doors, use levers/switches or ',
  '            go down stairs (you won''t be able to come back!)',
  '  {!g}       -- Pick up item from floor',
  '  {!SHIFT-g} -- Use/wield/wear item from floor/pull lever/switch',
  '  {!f}       -- Fire of equipped weapon',
  '  {!SHIFT-f} -- Alternative Fire of equipped weapon (if available)',
  '  {!r}       -- Reload equipped weapon',
  '  {!SHIFT-r} -- Reload both when dual-wielding or ',
  '                special reload weapon (if present)',
  '  {!m}       -- more info about targeted enemy',
  '  {!SHIFT-m} -- more info about self',
  '  {!z}       -- Swap weapon (with prepared weapon)',
  '  {!w}       -- Wait',
  '  {!i}       -- Show inventory',
  '  {!e}       -- Show or change equipment/show traits',
  '  {!l}       -- Toggle LookMode ({!Escape} to exit)',
  '  {!u}       -- Unload weapon from inventory/from ground',
  '  {!p}       -- Show screen with character info (parameters of player',
  '            and his equipment)',
  '  {!y}       -- Show character traits',
  '  {!a}       -- Show known assemblies',
  '  {!s}       -- Show previous messages',
  '  {!,}(comma)-- repeat move command (also, {!SHIFT}-direction, or {!SHIFT}-w)',
  '  {!x}       -- change tactic',
  '  {!1}..{!9} -- weapon quick keys, set them up in the inventory screen',
  '',
  '{rInventory screen}',
  '',
  '  Select item and press Enter to do the default action on a given item.',
  '  Wearable items will switch if one is already worn.',
  '',
  '  {!Backspace} -- drop selected item',
  '  {!1}..{!9}     -- mark as quick use/wear/wield',
  '  ',
  '{rEquipment screen}',
  '',
  '  Selecting a worn item will unequip it. Selecting an empty slot will',
  '  let you choose an item. Note though, that switching through the',
  '  inventory screen is faster.',
  '  ',
  '  {!Backspace} -- drop selected item',
  '  {!Tab}       -- swap item with item in inventory',
  '  ',
  '{rManual targeting (legacy option)}',
  '',
  '  {!t}       -- Manual targeting of equipped weapon',
  '  {!SHIFT-r} -- Alternative manual targeting of equipped weapon (if available)',
  '',
  '{rKeys while manual targeting}',
  '   ',
  '  {!Arrows}      -- move target line',
  '  {!TAB}         -- toggle target',
  '  {!m}           -- more information',
  '  {!f},{!SPACE},{!LMB} -- fire',
  '  {!RMB},{!Escape}  -- cancel',
  '{rMouse controls}',
  '',
  'LMB, MMB, RMB is left/middle/right mouse button:',
  '',
  '  {!LMB}             -- travel to given destination, open door if next to it, ',
  '                     melee attack if on enemy and next to him. Travel needs',
  '                     to target explored square, and is automatic as long as',
  '                     there are no enemies in sight, otherwise just one move',
  '  {!LMB} on {!self}     -- if on stairs, descend, if on lever - pull, if on item',
  '                     then pickup, else inventory',
  '  {!Alt-LMB} on {!self} -- inventory',
  '',
  '  {!RMB}             -- fire at the targeted square or enemy, reload if ',
  '                     magazine empty',
  '  {!RMB} on {!self}     -- reload',
  '',
  '  {!MMB}             -- hold to pan view',
  '  {!MMB} on {!self}     -- swap weapons',
  '',
  '  {!SCROLLWHEEL}     -- change weapon (enters quick weapon choice)',
  '{rController}',
  '',
  'Movement is done by moving the {!Left Stick} to the desired direction and',
  'confirming it with the {!{$controller_gameplay_move}} button.',
  '',
  '{rBasic actions}',
  '',
  'Holding {!{$controller_gameplay_modifier_alt}} will enable alternative actions as below',
  'and add hint info on the targeted square.',
  '',
  '{!{$controller_gameplay_move|5}} - move',
  '   (with {!{$controller_gameplay_modifier_alt}} held) move targeting reticule',
  '{!{$controller_gameplay_action|5}} - pickup item or activate stairs/lever,',
  '   (with {!{$controller_gameplay_modifier_alt}} held) use item from ground',
  '   (with {!LStick} direction) action (open/close door)',
  '{!{$controller_gameplay_fire|5}} - Fire',
  '   (with {!{$controller_gameplay_modifier_alt}} held) alternative fire (if present)',
  '{!{$controller_gameplay_reload|5}} - Reload',
  '   (with {!{$controller_gameplay_modifier_alt}} held) alternative/dual reload (if present)',
  '{!{$controller_gameplay_player|5}} - open inventory (use {!Left}/{!Right} or shoulders',
  '   to change panels), with {!{$controller_gameplay_modifier_alt}} held - open equipment',
  '{!{$controller_gameplay_menu|5}} - game menu',
  '{!{$controller_gameplay_target_prev|5}} - previous target',
  '{!{$controller_gameplay_target_next|5}} - next target',
  '{!{$controller_gameplay_active|5}} - (press) use active class skill (i.e. {!Adrenaline})',
  '{!{$controller_gameplay_swap|5}} - (press) swap weapon with prepared weapon',
  '   (with {!{$controller_gameplay_modifier_alt}}) held - unload weapon from ground or inventory',
  '{!{$controller_gameplay_up},{$controller_gameplay_down},{$controller_gameplay_left},{$controller_gameplay_right}} - move targeting reticule',
  '             (might be removed in the future)',
  '{!{$controller_gameplay_modifier_run|5}} -- hold to show quickslots,',
  '   {!{$controller_gameplay_up},{$controller_gameplay_down},{$controller_gameplay_left},{$controller_gameplay_right}} direction to use',
  '{!{$controller_gameplay_modifier_alt}+{$controller_gameplay_move}} -- more info on targeted enemy (or self if none), ',
  '         hold {!{$controller_gameplay_modifier_run}+{$controller_gameplay_modifier_alt}} to force self info',
  '',
  '{rUI}',
  '',
  '{!A} - confirm, {!B} - cancel, {!D-Pad} selection, also {!RShoulder} and',
  '{!LShoulder} to change panels.',
  '',
  '{rInventory/Equipment}',
  '',
  '{!RShoulder}/{!LShoulder} - change panels.',
  '{!Y} - drop ( with {!RTrigger} drop and unload weapon)',
  '{!X} - swap item in Equipment',
  '{!LTrigger+DPad} - assign quickslot to direction',
  '',
  '{rFlowing movement}',
  '',
  'After a move you can hold the {!{$controller_gameplay_move}} button and change direction with the',
  '{!Left Stick} to do multiple moves - this works if there are no enemies',
  'in sight, you will automatically stop if an enemy appears. You will also',
  'not automatically move into hazardous terrain, such as lava or acid.',
  '{rFeedback}',
  '',
  'I await your feedback! Mail me at admin@chaosforge.org. Tell me what you',
  'like, what you don''t, and submit the bug reports :). The official webpage',
  'of {rDRL} is',
  '',
  '{B  https://drl.chaosforge.org/}',
  '',
  'DRL has it''s own forum, that can be found at',
  '',
  '{B  https://forum.chaosforge.org/}',
  '',
  'There''s a DRL dedicated channel on the Jupiter Hell discord server:',
  '',
  '{B  https://discord.gg/jupiterhell}',
  '',
  'ChaosForge and myself also have official X profiles:',
  '',
  '{B  https://x.com/chaosforge_org}',
  '{B  https://x.com/epyoncf}',
  '',
  'The primary source for DRL guides, information and spoilers is the ',
  'DRL Wiki',
  '',
  '{B  https://drl.chaosforge.org/wiki/}',
  '',
  'Game Hunter has a great channel full of DRL Tutorials on youtube:',
  '',
  '{B  http://www.youtube.com/user/TheUberHunter}',
  '',
  'Announces of new releases will be placed on the official website, X, and',
  'Discord.',
  '',
  'Please visit the site of ChaosForge, to give a try at my other ',
  'roguelike games:',
  '',
  '{B  https://chaosforge.org/}',
  '',
  'DRL has a commercial version, set in the Jupiter Hell universe, you can',
  'buy it to support the development of both the free and commercial',
  'versions. ',
  '',
  '{B  https://jupiterhellclassic.com/}',
  '',
  'Jupiter Hell is the spiritual successor to DRL:',
  '',
  '{B  https://jupiterhell.com/}',
  '{rDisclaimer}',
  '',
  'This game is Freeware but with some limitations. Re-distribution ',
  '(cd-magazines, other websites) etc. is allowed as long as the author ',
  'is informed (admin@chaosforge.org). If you wish to include it in a printed',
  'magazine, I''d be happy to receive a complementary copy in return.',
  '',
  'THERE IS NO WARRANTY OF ANY KIND. I TAKE NO RESPONSIBILTY FOR ANY DAMAGE',
  'CAUSED BY THIS SOFTWARE. USE IT AT YOUR OWN RISK.',
  '{rCredits}',
  '',
  'Credits in this particular production go to Ilya Bely, for feedback, ideas',
  'and the enthusiasm that allowed me to actually finish something I started,',
  'and (my oh my!) release it...',
  '',
  'Many thanks go to Derek Yu for tiles and graphics for the graphics version.',
  'Many thanks to Lukasz Sliwinski, for a ton of additional tilesets, doodads,',
  'animations and other additional graphics for the graphical version.',
  '',
  'Thanks to my first beta-testers: Joseph Hewitt, Igor Savin, Timo Viitanen,',
  'ABCGi, David Damerell and Andrzej Kosnikowski.',
  '',
  'Special thanks to tehtmi and Game Hunter for direct help with coding, ',
  'especially AI and bugfixing!',
  '',
  'Big thanks to Simon Volpert for the DRL special level music tracks, and',
  'Game Hunter for the youtube DRL tutorials!',
  '',
  'High quality remixes of the original D music used in the graphical ',
  'version are a courtesy of Sonic Clang ( http://sonicclang.ringdev.com/ ) ',
  'used with permission.',
  '',
  'High quality recreation of the original D sounds used in the graphical ',
  'version is a courtesy of Per Kristian Risvik ( http://www.perkristian.net )',
  'used with permission.',
  '',
  'Original MIDI tracks and sound effects are of course by Id Software.',
  '',
  'Special thanks goes to all the DRL forum regulars, especially (but not ',
  'only!) to Aki, Anticheese, Dervis, Derek Yu, jake250, Malek, Santiago ',
  'Zapata, Thomas, Jorge Alonso, tehtmi, Game Hunter, UnderAPaleGreySky, ',
  'Jered Cain and Turgor for providing valuable ideas to DRL.',
  '',
  'Also, a big thanks to the #chaosforge IRC Channel Lurkers and Regulars :).',
  '',
  'Thanks to Malek and Derek Yu for the talent descriptions.',
  '',
  'Also big thanks goes to MaiZure for his help with marketing and PR :)',
  '',
  'Finally a big thanks to Gargulec, for PR, press releases, ideas, motivation',
  'kicks and being epic in general!',
  '',
  'And of course a *huge* thanks to the company, who created the original D,',
  'which in many was (as seen here) provides us with tons of entertainment',
  'even more than 30 years after it''s release...',
  '',
  'He''s the list of the TOP 15 people who keep ChaosForge running, based on ',
  'donations:',
  '',
  '1. thelaptop',
  '2. MaiZure',
  '3. Game Hunter',
  '4. Tavana',
  '5. alias',
  '6. tehtmi',
  '7. UnderAPaleGreySky',
  '8. Blade',
  '9. zaimoni',
  '10. Kaz',
  '11. Uranium',
  '12. Fidsah',
  '13. DaEezT',
  '14. Anarchic Fox',
  '15. Tuor Huorson',
  '',
  '(same numbers note ex aequo result)',
  '',
  'The alphabetically sorted list of great people that have donated :',
  '2DeviationsOut, AcidLead, adhominem, aEj, AeoniX, Aerdan, Agetian, ahoge,',
  'aimozg, Aki, Akisu, Alesak, alias, AlterAsc, Althalaus, alver, Anacone, ',
  'Anarchic Fox, Ander Hammer, Aoanla, appuru, areacode212, Arenot2be, ',
  'Argent Hawk, asche, Ashannar, AtTheGates, AukonDK, awebster, Azirel, ',
  'Baphomet, barmaley, Battleguy, BDR, beef623, BehroozWolf, bfg9001, ',
  'bgrunge, BirdoPrey, Blade, Blood, briareoh, BrickGun , brokenfury8585, ',
  'Brutalist, bumdum, Bunkov, Burrito Al Pastor, Burzmali, Buzzard, ',
  'buzzbomber, byrel, capn.lee, duomo, ceb, ceb, Chawlz, Cheesybox, Chief, ',
  'Cirrus, Cocodor, Corporate Dog, Cotonou, Count0, D1g1talDragon, DaEezT, ',
  'Damerell, danielhiryu, Darren Grey, Davidek, DeathDealer, Deaven, Derek ',
  'Yu, Dervis, Dihotom, Dimdamm, doshu, dougjoe2e, drugon, dtsund, ',
  'DuBistKomisch, Dubris, dying_sphynx, Eb, ecmwie, EfronLicht, Egor, ',
  'ehushagen, El Gringo, Elephant, elswyyr, enne, Essegi, Estwald, fallout, ',
  'Fanta Hege, FantomFang, Farquar, felttippen, Fidsah, fire_and_ice, ',
  'Flame_US3r, FlynnTheAvatar, Fobbah, fooziex, fwoop, Game Hunter, Gamera, ',
  'Gargulec, General Patton, GenTechJ, GermanJoey, gilgatex, Goatmeat, ',
  'Grassi, GrAVit, grillkick, Grim, GrimmC, grommile, Guillaume Voisine, ',
  'Gulthorpe, gunthos, Hamster, Handro, Herschel, Hjassan, Igor Savin, ',
  'Iltavuo, IronBeer, Iskander, Ivan Kanis, j1r, jonypawks, Joseph Hewitt, ',
  'Jouniz, jvecer, JysusCryst, Kashi, Kaz, Kazinsal, KhaaL, Khallis, ',
  'Killiox, Klear, KoboldPrime,, Kohlrabi, Kolya, konijn, Kriminel, Kvaak, ',
  'Lagonazer, Lekon, LinuxIsFinanciallyViable, lishain, lnxr0x, Lochness, ',
  'LordSloth, Lprsti99, LuckyDee, lyconaut, Mackeary, Madrayken, Madtrixr, ',
  'MaiZure, MarsGuyPhil, Marxist, maso, Matt_S, Mazinkaiser, mcz117chief, ',
  'MEDIEVAL_MIKU, michailv, MICu, mihey1993, MoArtis, Mogul, Moog, Mrazerty, ',
  'mrblonde, MY SPATULA, Nachtfischer, naib, NamoDyn, Napsterbater, neadlak, ',
  'Neolander, Nightwolf, nilhaus, Nillo, Nomad, Nori, notule, NullPointer, ',
  'okult, olberg, Olesh, Omega Tyrant, Oogle, papercuts6, Passionario, ',
  'Peter5930, PFL, phirt, phlebas, phrzn, Picklish, pndrev, ppiixx, Project ',
  'Dark Fox, PSG-01, Q2ZOv, qbert911, Radiocarbon, raekuul, Rax, Raz, ',
  'rchandra, reamer_rick, Reef Blastbody, rekenne, repvblic, Reverend ',
  'Bizarre, RickVoid, Rook, salinger, saltylicorice, samspot, scotherns, ',
  'Sdlonyer55, Seacow, Septa, Sereg, Seven Deadly Sins, Shadow Fox, ',
  'Shancial, shark20061, Shinji_Ikari_9th, Shroomsy, siema, Sihoiba, Sirdec, ',
  'Skiv, skylisdr, slartie, slave, Smokey899, snids, So_1337, spacedust, ',
  'spiderwebby, spillblood, spooky fox, SquidgyB, srimech, ssfsx17, stants, ',
  'stargazer-3, Stargoat, Steve, Stormlock, Styro, Super Jamie, ',
  'Super_Bricklayer, SuperVGA, Sylph, TameTick, Tavana, tbradshaw, tehtmi, ',
  'Teku, Templeton, termith, Test-0, Thann, TheDrill, theduck101, thelaptop, ',
  'Thexare, Thomas, Tim James, tootboot, torch, Tormuse, Tuor Huorson, ',
  'Tupeco, UAC421, Uite, UltimateChaos, UnderAPaleGreySky, ungin, Uranium, ',
  'Valgard, VANDAM, Vestin, VinylScratch, vurt, White Rider, wolis, ',
  'WorthlessBums, XC3N, Xi over Xi-bar, xpsg, Yamstis, Yando The Man, you, ',
  'yupsi, zaimoni, zakastra, Zalminen, zchris13, Zeb, ZellSF, zeroDi and',
  'ZicherCZ',
  ' ',
  'Also thanks to the whole crew of {Brec.games.roguelike.development} for',
  'the years spent together and the warm welcome of my game!'
);
const CHelpBlocks: array[0..223] of record ID, English: AnsiString; end = (
  (ID: 'help.body.intro.title'; English: '{rIntroduction}'),
  (ID: ''; English: ''),
  (ID: 'help.body.intro.roguelike'; English: '{rDRL} (abbr. for D, the Roguelike) is, as the name implies, a'#10'roguelike game. If you don''t know what a roguelike is... checkout '#10'wikipedia -- {Bhttp://en.wikipedia.org/wiki/Roguelike}.'),
  (ID: ''; English: ''),
  (ID: 'help.body.intro.premise'; English: 'DRL is inspired by a famous 1993 FPS hellish shooter. You''re'#10'the sole surviving marine from a squad sent to investigate a distress call'#10'from the moonbase of Phobos.  It turns out that all hell has broken loose'#10'on the plant... literally.'),
  (ID: ''; English: ''),
  (ID: 'help.body.intro.mission'; English: 'Your quest in DRL is to descend into the moonbase complex, find the'#10'source of this evil outbreak, and destroy it at all costs.'),
  (ID: ''; English: ''),
  (ID: 'help.body.intro.accessible-design'; English: 'Unlike many other roguelikes, DRL is intended to be simple and easy to'#10'get into. To that end, there is a limited inventory, maps of the size of'#10'one screen, and one item per tile. The number of keys you need to '#10'remember is also quite small compared to many other games in its genre.'),
  (ID: 'help.body.start.title'; English: '{rGetting Started}'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.menu-introduction'; English: 'When you first start a game of DRL, you''re presented with a menu screen'#10'with a few different options:'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.menu-options'; English: '{YNew game} will, well, start a new game!'#10'{YChallenge game} is initially locked, and becomes unlocked after you reach'#10'Corporal rank (need to survive 10 levels for it). Challenge games force you'#10'to play the game a certain way (e.g. using only melee), and you can raise'#10'your player rank in DRL by completing them. As your rank goes higher, '#10'more challenges will be made available to you.'#10'{YCustom game} brings up a selection screen where you can view and load'#10'modules. Modules are player-created levels, episodes, or entirely new games'#10'that bring a completely new experience to the DRL engine.'#10'{YShow highscores} displays the highscore list, not surprisingly.'#10'{YShow player} displays your player statistics, which include your player '#10'rank, number of kills, and number of wins. It has several screens which'#10'can be scrolled with the arrow keys.'#10'{YHelp} displays the help screen, which contains the info you are'#10'currently reading.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.start-first-game'; English: 'For now, select {YNew game} with the arrow keys and press ENTER to start'#10'your very first game of DRL!'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.difficulty'; English: 'Before you start your game, you have to make a few decisions. The first is'#10'the difficulty level. At the beginning, only three difficulty levels are'#10'available: "I''m too young to die", "Hey, Not Too Rough", and "Hurt Me'#10'Plenty". At higher difficulties, more monsters appear and tougher monsters'#10'appear earlier. "Ultra-Violence" and "Nightmare!" difficulties are unlocked'#10'as your player rank rises. At Nightmare! difficulty, only the most insane'#10'DRL warriors will stand a chance!'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.class'; English: 'The second decision is choosing a character class. Classes differ by '#10'starting perks, availability of one advanced trait as basic, and each of'#10'them has a different set of Master Traits.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.character-name'; English: 'The third decision you have to make is what your name will be in the game.'#10'You can figure that much on your own, right? You can also leave it blank'#10'and wear the name of a random legendary warrior...'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.starting-trait'; English: 'The fourth and final choice to make is select a starting "trait". '#10'Traits are upgrades or "perks" that you earn when you gain levels in '#10'DRL (by killing monsters). Traits can raise your max health, let you'#10'run faster, deal more damage per shot, or otherwise make you more awesome.'#10'Some traits can be levelled up individually.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.advanced-master-traits'; English: 'You''ll notice a few traits aren''t available. Some are "Advanced Traits",'#10'and require you to learn a normal trait first. Advanced Traits are more'#10'situational but quite effective, too. The rest are master traits, which'#10'require you to take a specific set of traits (and block off a few other'#10'traits) and give you some sort of great unique bonus. But hey, don''t think'#10'about it too hard. Just pick one you like and move on.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.screen-introduction'; English: 'And that''s it, you''re ready to play the game! After a brief intro, you will'#10'be greeted with something like this (ASCII map is present if playing in'#10'ASCII mode):'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.screen-example'; English: '{d---------------------------------------------------------------------------}'#10' Welcome to DRL...'#10' ##########'#10' #@.........'#10' #..........'#10' #.........'#10' #.........'#10' #........'#10' #........'#10' #.......'#10' #......'#10' #....'#10' #..'#10#10#10#10#10#10#10#10#10#10' {bDRLguy}{d                     Armor : }{lnone}'#10' {dHealth:}{r 100%}{d Exp:}{l  1}{d/}{l0%}{l    Weapon: }{lpistol (2d4) [6/6]}'#10' cautious                                                  {rPhobos Base Entry}'#10'{d---------------------------------------------------------------------------}'#10'                             {bThe Starting Screen}'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.first-floor'; English: 'This is a map of the first level of the moonbase on Phobos. The whole level'#10'is exactly the size of the screen. Walk around (using the arrow keys or'#10'numpad) and get used to the interface. Don''t get yourself killed!'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.message-area'; English: 'Take a look at the screen. It is divided into three parts. On top you have'#10'the "message area", made of two lines of text. Watch this space carefully'#10'-- it may notify you of impending danger or tell you that you''re out of'#10'ammo (poor sob!).'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.health-experience'; English: 'On the bottom you have the status bar. The top line displays your name, and'#10'below it is the most important stat -- your health. If this one drops'#10'below one percent, you''re dead, dude - nothing can save you. Scanning '#10'to the right you can see the experience indicator. The first number is your'#10'character level -- the higher it is, the tougher you are. The second number'#10'is your experience displayed as a percentage. Each character level requires'#10'a certain experience amount needed to achieve it.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.tactics'; English: 'Below your health and experience is "tactics". By default your tactic is'#10'"cautious". This tactic gives no benefits or disadvantages. If you press'#10'X once, it will change to "running" (note that changing tactics takes'#10'some in-game time). With this tactic you have increased movement speed,'#10'dodge chance, and defense bonus, but have a smaller chance to hit and'#10'reduced melee damage. After some time spent running (or after pressing'#10'X again), you will get "tired". Being tired has no effects, positive'#10'or negative (like cautious), but while tired, you can''t run again. You can'#10'return to the cautious tactic by leveling up, gaining health by most'#10'methods, or descending to next level. Since running is limited in this way,'#10'try not to waste it. At the same time, however, remember to use it, as they'#10'don''t stockpile for later levels.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.equipment-status'; English: 'In the column to the right of that, you have two indicators, "Armor" and'#10'"Weapon", that show you what armor and weapon you have equipped. For'#10'weapons, the number in brackets indicates the damage that the weapon'#10'deals, and the two numbers in square brackets indicate the current-loaded'#10'ammo and clip size for that weapon (e.g., [4/6] means you have four'#10'bullets in a magazine that can hold six).'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.map-symbols'; English: 'Between the status bar and message bar, there''s the map. The "@" sign with'#10'the cursor below it -- that''s you (aren''t you ugly?). See any letters'#10'nearby? It may be a "T"ree, but chances are it''s the enemy. Kill''em all.'#10'The "#" are walls, "+" is a closed door, "/" an open door. Dots are normal'#10'floor. Red dots are either Phobos''s ugly rock landscape (on the first'#10'level), or blood (anywhere else).'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.inventory-equipment'; English: 'Press "i" to see your inventory. It''s pretty empty, right? Your character'#10'starts equipped with a few things -- your trusty pistol (already equipped),'#10'a handful of ammo, and a couple of med-packs. To check equipped item,'#10'press "e" in-game to see the full list (which includes boots and a second'#10'weapon slot).'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.pickup-consumables'; English: 'Your pistol and ammo are not going to last you very long, though.  Press'#10'"g" to pick up new weapons (represented by "}") and ammo ("|").  If you'#10'walk around that first level you''re likely to run into some small medkits'#10'(red "+") that you can pick up and add to your inventory. Later on you'#10'might find other consumable items, they''re all "+"s. Press "i" at any time'#10'and a consumable to use it at any time. If you ever want to drop something'#10'(usually to make room for new weapons or items), press "Backspace" in the'#10'inventory screen to drop items.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.levers-barrels'; English: 'Along the way, you''re bound to run into levers ("&") and barrels ("0"). To'#10'pull a lever, stand on it and press "SPACE" to use them. The effects are'#10'random, so pull them at your own peril! And if you''ve ever played a shooter'#10'you know what to expect with barrels: They all explode quite nicely, but'#10'with varying effects depending on the barrel. (Be aware that levers are'#10'activated with the same button as using items -- in this case, open up'#10'your inventory and use the item from there by selecting it and pressing'#10'ENTER.)'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.powerups'; English: 'As you go deeper into the base, you''ll also find some power-ups ("^"). They'#10'are used as soon as you pick them up, and several contain powerful effect,'#10'so use them wisely.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.fire-targeting'; English: 'Oh, I almost forgot! To shoot, just press "f" to fire at the currently '#10'selected target! You can swap between visible targets using "TAB", or '#10'hold "Ctrl" to move the target reticule manually with the arrow keys.'#10'Some weapons allow an alternative fire mode, such as the chainfiring '#10'mode of the chaingun - to use it, press "SHIFT-f".'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.reload-melee'; English: 'Ok, I hear you cry -- "Out of ammo!" Don''t panic. Press "r" to reload your'#10'weapon (Some weapons allow you an alternative reload by pressing SHIFT-r).'#10'Reloading the correct ammo is automatic if you have it in your inventory.'#10'But what if you don''t? You can try pounding on the enemy with your fists'#10'or a hand-to-hand weapon -- to do that just walk into him.  Pick up a'#10'Berserk Pack or a chainsaw (or at least a knife) and you can do some'#10'serious damage that way!'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.dodging'; English: 'Getting hit too frequently when trying to approach an enemy (or when'#10'running from him)? Try not to move in a straight line -- move diagonally,'#10'as this increases your chance to dodge. If you don''t want to approach or'#10'retreat from the enemy, but also don''t want to be hit often, try moving'#10'from side-to-side, perpendicular to the direction of enemy, as this'#10'gives you the same bonus as moving diagonally). Sometimes, in emergencies,'#10'switching to the running tactic and using both of these tricks at once will'#10'give you a much greater chance to dodge than normal.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.prepared-weapon'; English: 'In the equipment menu (remember, press "e") you''ll see that you have a'#10'primary weapon equipped and a secondary weapon at hand.  By pressing "z"'#10'you can switch your primary out for your secondary.  This is faster than'#10'equipping a new weapon from your inventory and it saves you valuable'#10'space.  It''s also quite useful in a firefight, when the situation can'#10'change at any moment!'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.armor-durability'; English: 'Hey, you think you''re cool because you found some armor? Think again. Look,'#10'there are three numbers by the armor. The first two in square brackets are'#10'[current damage resistance/maximum damage resistance]. The second one is '#10'your armor''s health. 100% means it''s undamaged, 1% is almost destroyed.'#10'The more damaged an armor is, the lower its actual resistance is. Keep an'#10'eye on those numbers!'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.damage-resistance'; English: 'Additionally each armor may grant additional resistance to specific damage '#10'types. This information can be obtained in the inventory and equipment '#10'screens.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.player-information'; English: 'Try to check out player information screen by pressing "p" -- some useful'#10'information is written there. First, there are your main parameters:'#10'movement, firing, and reloading speeds, as well as your chance to hit with'#10'the weapon you currently have equipped (from point blank range). Next are'#10'the more passive statistics: your player and dungeon level, amount of'#10'played turns, and your score so far. At the bottom you can find parameters'#10'of equipment that you are currently wearing: damage, firing and reloading'#10'speeds, and accuracy for weapons; and protection value, durability, and'#10'movement and knockback modifiers for armor and boots (yes, armor and boots'#10'can affect your movement speed and chance to be knocked back by powerful'#10'attacks).'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.item-types'; English: 'There are five types of items in this game:'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.common-items'; English: '1) {!Common} - These items are... "common"? You will see them all across the'#10'game, and what you should rely on. Most are generated randomly, but you'#10'will find some are guaranteed in certain places (as a reward for completing'#10'a special level, for example). Common weapons and armor accept 1/1, 3/2,'#10'and 5/3 mods, respectively, depending on the level of your Whizkid trait.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.assemblies'; English: '2) {CAssemblies} - These items can be assembled from other items, usually '#10'common, by modding them with a specific set of mods. Experiment, as'#10'discovered (assembled) assemblies will be recorded in your player data and'#10'can be accessed with the "A" key during the game.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.exotic-items'; English: '3) {VExotic} - These items are rarer and more powerful than common items.'#10'They can potentially appear more than once per game, but are more often'#10'than not found in special levels. Exotic weapons and armor can hold the'#10' same amounts of mods that their common counterparts do.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.unique-items'; English: '4) {GUniques} - Unique items, as the name suggests, can only appear once per'#10'game. Some of them just have cool stats, while others have special'#10'abilities, and each of them come with a unique name. No unique item is'#10'guaranteed, although they can appear in special levels, and they are quite'#10'rare otherwise. Most uniques cannot be modded, but those that do can only'#10'be modded if the player is playing the Technician class.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.artifacts'; English: '5) {YArtifacts} - Artifact items are similar to unique items, except that they'#10'can only appear in very specific special levels, while never appearing'#10'randomly. Finding and collecting these items is almost always a very'#10'challenging task.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.mod-packs'; English: 'Mods (Displayed by a " symbol) are little packs that enhance your weaponry'#10'or armor. Most equipment you find can be modded, so try to cover up their'#10'weaknesses by modding them.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.look-help'; English: 'Whenever you see something that you aren''t familiar with, press "l" to'#10'trigger the Look command -- moving the cursor with the arrow keys will'#10'show what''s under the cursor in the message bar. You can also press "h"'#10'in-game to open up the help menu.'),
  (ID: ''; English: ''),
  (ID: 'help.body.start.closing'; English: 'Happy fragging!'),
  (ID: 'help.body.keys.title'; English: '{rControls}'),
  (ID: ''; English: ''),
  (ID: 'help.body.keys.binding-notice'; English: '  Most keybindings can be redefined via the file Settings menu. The '#10'  following set describes the standard layout, and does not reflect'#10'  any changes you may have made to your keybindings.'),
  (ID: ''; English: ''),
  (ID: 'help.body.keys.navigation'; English: '  {!Escape}      -- Exit menu, or show game menu (Save/Quit/Help/etc)'#10'  {!Arrows}      -- Walking around (PgUp, PgDn, Home, End diagonally!)'#10'  {!Arrows+Ctrl} -- Manually move target reticule'#10'  {!TAB}         -- Switch between targets'),
  (ID: ''; English: '  '),
  (ID: 'help.body.keys.game-actions'; English: '  {!h}       -- Run on-line help'#10'  {!SPACE}   -- Action - open doors, close doors, use levers/switches or '#10'            go down stairs (you won''t be able to come back!)'#10'  {!g}       -- Pick up item from floor'#10'  {!SHIFT-g} -- Use/wield/wear item from floor/pull lever/switch'#10'  {!f}       -- Fire of equipped weapon'#10'  {!SHIFT-f} -- Alternative Fire of equipped weapon (if available)'#10'  {!r}       -- Reload equipped weapon'#10'  {!SHIFT-r} -- Reload both when dual-wielding or '#10'                special reload weapon (if present)'#10'  {!m}       -- more info about targeted enemy'#10'  {!SHIFT-m} -- more info about self'#10'  {!z}       -- Swap weapon (with prepared weapon)'#10'  {!w}       -- Wait'#10'  {!i}       -- Show inventory'#10'  {!e}       -- Show or change equipment/show traits'#10'  {!l}       -- Toggle LookMode ({!Escape} to exit)'#10'  {!u}       -- Unload weapon from inventory/from ground'#10'  {!p}       -- Show screen with character info (parameters of player'#10'            and his equipment)'#10'  {!y}       -- Show character traits'#10'  {!a}       -- Show known assemblies'#10'  {!s}       -- Show previous messages'#10'  {!,}(comma)-- repeat move command (also, {!SHIFT}-direction, or {!SHIFT}-w)'#10'  {!x}       -- change tactic'#10'  {!1}..{!9} -- weapon quick keys, set them up in the inventory screen'),
  (ID: ''; English: ''),
  (ID: 'help.body.keys.inventory-title'; English: '{rInventory screen}'),
  (ID: ''; English: ''),
  (ID: 'help.body.keys.inventory-default'; English: '  Select item and press Enter to do the default action on a given item.'#10'  Wearable items will switch if one is already worn.'),
  (ID: ''; English: ''),
  (ID: 'help.body.keys.inventory-keys'; English: '  {!Backspace} -- drop selected item'#10'  {!1}..{!9}     -- mark as quick use/wear/wield'),
  (ID: ''; English: '  '),
  (ID: 'help.body.keys.equipment-title'; English: '{rEquipment screen}'),
  (ID: ''; English: ''),
  (ID: 'help.body.keys.equipment-default'; English: '  Selecting a worn item will unequip it. Selecting an empty slot will'#10'  let you choose an item. Note though, that switching through the'#10'  inventory screen is faster.'),
  (ID: ''; English: '  '),
  (ID: 'help.body.keys.equipment-keys'; English: '  {!Backspace} -- drop selected item'#10'  {!Tab}       -- swap item with item in inventory'),
  (ID: ''; English: '  '),
  (ID: 'help.body.keys.legacy-target-title'; English: '{rManual targeting (legacy option)}'),
  (ID: ''; English: ''),
  (ID: 'help.body.keys.legacy-target-keys'; English: '  {!t}       -- Manual targeting of equipped weapon'#10'  {!SHIFT-r} -- Alternative manual targeting of equipped weapon (if available)'),
  (ID: ''; English: ''),
  (ID: 'help.body.keys.target-title'; English: '{rKeys while manual targeting}'),
  (ID: ''; English: '   '),
  (ID: 'help.body.keys.target-keys'; English: '  {!Arrows}      -- move target line'#10'  {!TAB}         -- toggle target'#10'  {!m}           -- more information'#10'  {!f},{!SPACE},{!LMB} -- fire'#10'  {!RMB},{!Escape}  -- cancel'),
  (ID: 'help.body.mouse.title'; English: '{rMouse controls}'),
  (ID: ''; English: ''),
  (ID: 'help.body.mouse.button-definitions'; English: 'LMB, MMB, RMB is left/middle/right mouse button:'),
  (ID: ''; English: ''),
  (ID: 'help.body.mouse.left-button'; English: '  {!LMB}             -- travel to given destination, open door if next to it, '#10'                     melee attack if on enemy and next to him. Travel needs'#10'                     to target explored square, and is automatic as long as'#10'                     there are no enemies in sight, otherwise just one move'#10'  {!LMB} on {!self}     -- if on stairs, descend, if on lever - pull, if on item'#10'                     then pickup, else inventory'#10'  {!Alt-LMB} on {!self} -- inventory'),
  (ID: ''; English: ''),
  (ID: 'help.body.mouse.right-button'; English: '  {!RMB}             -- fire at the targeted square or enemy, reload if '#10'                     magazine empty'#10'  {!RMB} on {!self}     -- reload'),
  (ID: ''; English: ''),
  (ID: 'help.body.mouse.middle-button'; English: '  {!MMB}             -- hold to pan view'#10'  {!MMB} on {!self}     -- swap weapons'),
  (ID: ''; English: ''),
  (ID: 'help.body.mouse.wheel'; English: '  {!SCROLLWHEEL}     -- change weapon (enters quick weapon choice)'),
  (ID: 'help.body.gamepad.title'; English: '{rController}'),
  (ID: ''; English: ''),
  (ID: 'help.body.gamepad.movement'; English: 'Movement is done by moving the {!Left Stick} to the desired direction and'#10'confirming it with the {!{$controller_gameplay_move}} button.'),
  (ID: ''; English: ''),
  (ID: 'help.body.gamepad.actions-title'; English: '{rBasic actions}'),
  (ID: ''; English: ''),
  (ID: 'help.body.gamepad.alternate-modifier'; English: 'Holding {!{$controller_gameplay_modifier_alt}} will enable alternative actions as below'#10'and add hint info on the targeted square.'),
  (ID: ''; English: ''),
  (ID: 'help.body.gamepad.actions'; English: '{!{$controller_gameplay_move|5}} - move'#10'   (with {!{$controller_gameplay_modifier_alt}} held) move targeting reticule'#10'{!{$controller_gameplay_action|5}} - pickup item or activate stairs/lever,'#10'   (with {!{$controller_gameplay_modifier_alt}} held) use item from ground'#10'   (with {!LStick} direction) action (open/close door)'#10'{!{$controller_gameplay_fire|5}} - Fire'#10'   (with {!{$controller_gameplay_modifier_alt}} held) alternative fire (if present)'#10'{!{$controller_gameplay_reload|5}} - Reload'#10'   (with {!{$controller_gameplay_modifier_alt}} held) alternative/dual reload (if present)'#10'{!{$controller_gameplay_player|5}} - open inventory (use {!Left}/{!Right} or shoulders'#10'   to change panels), with {!{$controller_gameplay_modifier_alt}} held - open equipment'#10'{!{$controller_gameplay_menu|5}} - game menu'#10'{!{$controller_gameplay_target_prev|5}} - previous target'#10'{!{$controller_gameplay_target_next|5}} - next target'#10'{!{$controller_gameplay_active|5}} - (press) use active class skill (i.e. {!Adrenaline})'#10'{!{$controller_gameplay_swap|5}} - (press) swap weapon with prepared weapon'#10'   (with {!{$controller_gameplay_modifier_alt}}) held - unload weapon from ground or inventory'#10'{!{$controller_gameplay_up},{$controller_gameplay_down},{$controller_gameplay_left},{$controller_gameplay_right}} - move targeting reticule'#10'             (might be removed in the future)'#10'{!{$controller_gameplay_modifier_run|5}} -- hold to show quickslots,'#10'   {!{$controller_gameplay_up},{$controller_gameplay_down},{$controller_gameplay_left},{$controller_gameplay_right}} direction to use'#10'{!{$controller_gameplay_modifier_alt}+{$controller_gameplay_move}} -- more info on targeted enemy (or self if none), '#10'         hold {!{$controller_gameplay_modifier_run}+{$controller_gameplay_modifier_alt}} to force self info'),
  (ID: ''; English: ''),
  (ID: 'help.body.gamepad.ui-title'; English: '{rUI}'),
  (ID: ''; English: ''),
  (ID: 'help.body.gamepad.ui-controls'; English: '{!A} - confirm, {!B} - cancel, {!D-Pad} selection, also {!RShoulder} and'#10'{!LShoulder} to change panels.'),
  (ID: ''; English: ''),
  (ID: 'help.body.gamepad.equipment-title'; English: '{rInventory/Equipment}'),
  (ID: ''; English: ''),
  (ID: 'help.body.gamepad.equipment-controls'; English: '{!RShoulder}/{!LShoulder} - change panels.'#10'{!Y} - drop ( with {!RTrigger} drop and unload weapon)'#10'{!X} - swap item in Equipment'#10'{!LTrigger+DPad} - assign quickslot to direction'),
  (ID: ''; English: ''),
  (ID: 'help.body.gamepad.continuous-movement-title'; English: '{rFlowing movement}'),
  (ID: ''; English: ''),
  (ID: 'help.body.gamepad.continuous-movement'; English: 'After a move you can hold the {!{$controller_gameplay_move}} button and change direction with the'#10'{!Left Stick} to do multiple moves - this works if there are no enemies'#10'in sight, you will automatically stop if an enemy appears. You will also'#10'not automatically move into hazardous terrain, such as lava or acid.'),
  (ID: 'help.body.feedback.title'; English: '{rFeedback}'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.email'; English: 'I await your feedback! Mail me at admin@chaosforge.org. Tell me what you'#10'like, what you don''t, and submit the bug reports :). The official webpage'#10'of {rDRL} is'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.website'; English: '{B  https://drl.chaosforge.org/}'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.forum-description'; English: 'DRL has it''s own forum, that can be found at'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.forum'; English: '{B  https://forum.chaosforge.org/}'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.discord-description'; English: 'There''s a DRL dedicated channel on the Jupiter Hell discord server:'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.discord'; English: '{B  https://discord.gg/jupiterhell}'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.social-description'; English: 'ChaosForge and myself also have official X profiles:'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.social'; English: '{B  https://x.com/chaosforge_org}'#10'{B  https://x.com/epyoncf}'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.wiki-description'; English: 'The primary source for DRL guides, information and spoilers is the '#10'DRL Wiki'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.wiki'; English: '{B  https://drl.chaosforge.org/wiki/}'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.tutorials-description'; English: 'Game Hunter has a great channel full of DRL Tutorials on youtube:'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.tutorials'; English: '{B  http://www.youtube.com/user/TheUberHunter}'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.release-news'; English: 'Announces of new releases will be placed on the official website, X, and'#10'Discord.'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.other-games-description'; English: 'Please visit the site of ChaosForge, to give a try at my other '#10'roguelike games:'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.other-games'; English: '{B  https://chaosforge.org/}'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.classic-description'; English: 'DRL has a commercial version, set in the Jupiter Hell universe, you can'#10'buy it to support the development of both the free and commercial'#10'versions. '),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.classic'; English: '{B  https://jupiterhellclassic.com/}'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.successor-description'; English: 'Jupiter Hell is the spiritual successor to DRL:'),
  (ID: ''; English: ''),
  (ID: 'help.body.feedback.successor'; English: '{B  https://jupiterhell.com/}'),
  (ID: 'help.body.disclaim.title'; English: '{rDisclaimer}'),
  (ID: ''; English: ''),
  (ID: 'help.body.disclaim.redistribution'; English: 'This game is Freeware but with some limitations. Re-distribution '#10'(cd-magazines, other websites) etc. is allowed as long as the author '#10'is informed (admin@chaosforge.org). If you wish to include it in a printed'#10'magazine, I''d be happy to receive a complementary copy in return.'),
  (ID: ''; English: ''),
  (ID: 'help.body.disclaim.warranty'; English: 'THERE IS NO WARRANTY OF ANY KIND. I TAKE NO RESPONSIBILTY FOR ANY DAMAGE'#10'CAUSED BY THIS SOFTWARE. USE IT AT YOUR OWN RISK.'),
  (ID: 'help.body.credits.title'; English: '{rCredits}'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.ilya-bely'; English: 'Credits in this particular production go to Ilya Bely, for feedback, ideas'#10'and the enthusiasm that allowed me to actually finish something I started,'#10'and (my oh my!) release it...'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.graphics'; English: 'Many thanks go to Derek Yu for tiles and graphics for the graphics version.'#10'Many thanks to Lukasz Sliwinski, for a ton of additional tilesets, doodads,'#10'animations and other additional graphics for the graphical version.'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.beta-testers'; English: 'Thanks to my first beta-testers: Joseph Hewitt, Igor Savin, Timo Viitanen,'#10'ABCGi, David Damerell and Andrzej Kosnikowski.'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.coding'; English: 'Special thanks to tehtmi and Game Hunter for direct help with coding, '#10'especially AI and bugfixing!'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.music-tutorials'; English: 'Big thanks to Simon Volpert for the DRL special level music tracks, and'#10'Game Hunter for the youtube DRL tutorials!'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.sonic-clang-permission'; English: 'High quality remixes of the original D music used in the graphical '#10'version are a courtesy of Sonic Clang ( http://sonicclang.ringdev.com/ ) '#10'used with permission.'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.per-kristian-permission'; English: 'High quality recreation of the original D sounds used in the graphical '#10'version is a courtesy of Per Kristian Risvik ( http://www.perkristian.net )'#10'used with permission.'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.id-software'; English: 'Original MIDI tracks and sound effects are of course by Id Software.'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.forum-regulars'; English: 'Special thanks goes to all the DRL forum regulars, especially (but not '#10'only!) to Aki, Anticheese, Dervis, Derek Yu, jake250, Malek, Santiago '#10'Zapata, Thomas, Jorge Alonso, tehtmi, Game Hunter, UnderAPaleGreySky, '#10'Jered Cain and Turgor for providing valuable ideas to DRL.'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.irc'; English: 'Also, a big thanks to the #chaosforge IRC Channel Lurkers and Regulars :).'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.trait-descriptions'; English: 'Thanks to Malek and Derek Yu for the talent descriptions.'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.marketing'; English: 'Also big thanks goes to MaiZure for his help with marketing and PR :)'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.gargulec'; English: 'Finally a big thanks to Gargulec, for PR, press releases, ideas, motivation'#10'kicks and being epic in general!'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.original-game'; English: 'And of course a *huge* thanks to the company, who created the original D,'#10'which in many was (as seen here) provides us with tons of entertainment'#10'even more than 30 years after it''s release...'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.top-donors-description'; English: 'He''s the list of the TOP 15 people who keep ChaosForge running, based on '#10'donations:'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.top-donors'; English: '1. thelaptop'#10'2. MaiZure'#10'3. Game Hunter'#10'4. Tavana'#10'5. alias'#10'6. tehtmi'#10'7. UnderAPaleGreySky'#10'8. Blade'#10'9. zaimoni'#10'10. Kaz'#10'11. Uranium'#10'12. Fidsah'#10'13. DaEezT'#10'14. Anarchic Fox'#10'15. Tuor Huorson'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.donor-ties'; English: '(same numbers note ex aequo result)'),
  (ID: ''; English: ''),
  (ID: 'help.body.credits.all-donors'; English: 'The alphabetically sorted list of great people that have donated :'#10'2DeviationsOut, AcidLead, adhominem, aEj, AeoniX, Aerdan, Agetian, ahoge,'#10'aimozg, Aki, Akisu, Alesak, alias, AlterAsc, Althalaus, alver, Anacone, '#10'Anarchic Fox, Ander Hammer, Aoanla, appuru, areacode212, Arenot2be, '#10'Argent Hawk, asche, Ashannar, AtTheGates, AukonDK, awebster, Azirel, '#10'Baphomet, barmaley, Battleguy, BDR, beef623, BehroozWolf, bfg9001, '#10'bgrunge, BirdoPrey, Blade, Blood, briareoh, BrickGun , brokenfury8585, '#10'Brutalist, bumdum, Bunkov, Burrito Al Pastor, Burzmali, Buzzard, '#10'buzzbomber, byrel, capn.lee, duomo, ceb, ceb, Chawlz, Cheesybox, Chief, '#10'Cirrus, Cocodor, Corporate Dog, Cotonou, Count0, D1g1talDragon, DaEezT, '#10'Damerell, danielhiryu, Darren Grey, Davidek, DeathDealer, Deaven, Derek '#10'Yu, Dervis, Dihotom, Dimdamm, doshu, dougjoe2e, drugon, dtsund, '#10'DuBistKomisch, Dubris, dying_sphynx, Eb, ecmwie, EfronLicht, Egor, '#10'ehushagen, El Gringo, Elephant, elswyyr, enne, Essegi, Estwald, fallout, '#10'Fanta Hege, FantomFang, Farquar, felttippen, Fidsah, fire_and_ice, '#10'Flame_US3r, FlynnTheAvatar, Fobbah, fooziex, fwoop, Game Hunter, Gamera, '#10'Gargulec, General Patton, GenTechJ, GermanJoey, gilgatex, Goatmeat, '#10'Grassi, GrAVit, grillkick, Grim, GrimmC, grommile, Guillaume Voisine, '#10'Gulthorpe, gunthos, Hamster, Handro, Herschel, Hjassan, Igor Savin, '#10'Iltavuo, IronBeer, Iskander, Ivan Kanis, j1r, jonypawks, Joseph Hewitt, '#10'Jouniz, jvecer, JysusCryst, Kashi, Kaz, Kazinsal, KhaaL, Khallis, '#10'Killiox, Klear, KoboldPrime,, Kohlrabi, Kolya, konijn, Kriminel, Kvaak, '#10'Lagonazer, Lekon, LinuxIsFinanciallyViable, lishain, lnxr0x, Lochness, '#10'LordSloth, Lprsti99, LuckyDee, lyconaut, Mackeary, Madrayken, Madtrixr, '#10'MaiZure, MarsGuyPhil, Marxist, maso, Matt_S, Mazinkaiser, mcz117chief, '#10'MEDIEVAL_MIKU, michailv, MICu, mihey1993, MoArtis, Mogul, Moog, Mrazerty, '#10'mrblonde, MY SPATULA, Nachtfischer, naib, NamoDyn, Napsterbater, neadlak, '#10'Neolander, Nightwolf, nilhaus, Nillo, Nomad, Nori, notule, NullPointer, '#10'okult, olberg, Olesh, Omega Tyrant, Oogle, papercuts6, Passionario, '#10'Peter5930, PFL, phirt, phlebas, phrzn, Picklish, pndrev, ppiixx, Project '#10'Dark Fox, PSG-01, Q2ZOv, qbert911, Radiocarbon, raekuul, Rax, Raz, '#10'rchandra, reamer_rick, Reef Blastbody, rekenne, repvblic, Reverend '#10'Bizarre, RickVoid, Rook, salinger, saltylicorice, samspot, scotherns, '#10'Sdlonyer55, Seacow, Septa, Sereg, Seven Deadly Sins, Shadow Fox, '#10'Shancial, shark20061, Shinji_Ikari_9th, Shroomsy, siema, Sihoiba, Sirdec, '#10'Skiv, skylisdr, slartie, slave, Smokey899, snids, So_1337, spacedust, '#10'spiderwebby, spillblood, spooky fox, SquidgyB, srimech, ssfsx17, stants, '#10'stargazer-3, Stargoat, Steve, Stormlock, Styro, Super Jamie, '#10'Super_Bricklayer, SuperVGA, Sylph, TameTick, Tavana, tbradshaw, tehtmi, '#10'Teku, Templeton, termith, Test-0, Thann, TheDrill, theduck101, thelaptop, '#10'Thexare, Thomas, Tim James, tootboot, torch, Tormuse, Tuor Huorson, '#10'Tupeco, UAC421, Uite, UltimateChaos, UnderAPaleGreySky, ungin, Uranium, '#10'Valgard, VANDAM, Vestin, VinylScratch, vurt, White Rider, wolis, '#10'WorthlessBums, XC3N, Xi over Xi-bar, xpsg, Yamstis, Yando The Man, you, '#10'yupsi, zaimoni, zakastra, Zalminen, zchris13, Zeb, ZellSF, zeroDi and'#10'ZicherCZ'),
  (ID: ''; English: ' '),
  (ID: 'help.body.credits.community'; English: 'Also thanks to the whole crew of {Brec.games.roguelike.development} for'#10'the years spent together and the warm welcome of my game!')
);
function DRLHelpTopicIndex(const aID: AnsiString): Integer;
var i: Integer;
begin
  for i := 0 to High(CHelpDocuments) do
    if CHelpDocuments[i].ID = aID then Exit(i);
  Exit(-1);
end;
function DRLHelpSourceLineCount(aTopic: Integer): Integer;
begin
  if (aTopic < 0) or (aTopic > High(CHelpDocuments)) then Exit(0);
  Exit(CHelpDocuments[aTopic].LineCount);
end;
function DRLHelpSourceLine(aTopic, aLine: Integer): AnsiString;
begin
  if (aTopic < 0) or (aTopic > High(CHelpDocuments)) then
    raise EArgumentException.Create('Unknown DRL help topic');
  if (aLine < 0) or (aLine >= CHelpDocuments[aTopic].LineCount) then
    raise EArgumentException.Create('DRL help source line out of bounds');
  Exit(CHelpSourceLines[CHelpDocuments[aTopic].FirstLine + aLine]);
end;
function DRLHelpParagraphCount(aTopic: Integer): Integer;
begin
  if (aTopic < 0) or (aTopic > High(CHelpDocuments)) then Exit(0);
  Exit(CHelpDocuments[aTopic].BlockCount);
end;
function DRLHelpParagraphText(aTopic, aParagraph: Integer): AnsiString;
var iBlock: Integer;
begin
  if (aTopic < 0) or (aTopic > High(CHelpDocuments)) then
    raise EArgumentException.Create('Unknown DRL help topic');
  if (aParagraph < 0) or (aParagraph >= CHelpDocuments[aTopic].BlockCount) then
    raise EArgumentException.Create('DRL help paragraph out of bounds');
  iBlock := CHelpDocuments[aTopic].FirstBlock + aParagraph;
  if CHelpBlocks[iBlock].ID = '' then Exit(CHelpBlocks[iBlock].English);
  Exit(DRLText(CHelpBlocks[iBlock].ID, CHelpBlocks[iBlock].English));
end;
function DRLHelpTopicTitle(aTopic: Integer; const aOriginalTitle: AnsiString): AnsiString;
begin
  if (aTopic < 0) or (aTopic > High(CHelpDocuments)) then Exit(aOriginalTitle);
  if (CHelpDocuments[aTopic].ID = 'intro') and
     (aOriginalTitle = 'Introduction') then
    Exit(DRLText('help.topic.intro', aOriginalTitle));
  if (CHelpDocuments[aTopic].ID = 'start') and
     (aOriginalTitle = 'Getting started') then
    Exit(DRLText('help.topic.start', aOriginalTitle));
  if (CHelpDocuments[aTopic].ID = 'gamepad') and
     (aOriginalTitle = 'Gamepad controls') then
    Exit(DRLText('help.topic.gamepad', aOriginalTitle));
  if (CHelpDocuments[aTopic].ID = 'keys') and
     (aOriginalTitle = 'Keyboard controls') then
    Exit(DRLText('help.topic.keys', aOriginalTitle));
  if (CHelpDocuments[aTopic].ID = 'mouse') and
     (aOriginalTitle = 'Mouse controls') then
    Exit(DRLText('help.topic.mouse', aOriginalTitle));
  if (CHelpDocuments[aTopic].ID = 'feedback') and
     (aOriginalTitle = 'Feedback') then
    Exit(DRLText('help.topic.feedback', aOriginalTitle));
  if (CHelpDocuments[aTopic].ID = 'disclaim') and
     (aOriginalTitle = 'Disclaimer') then
    Exit(DRLText('help.topic.disclaim', aOriginalTitle));
  if (CHelpDocuments[aTopic].ID = 'credits') and
     (aOriginalTitle = 'Credits') then
    Exit(DRLText('help.topic.credits', aOriginalTitle));
  Exit(aOriginalTitle);
end;
end.
