/* Retired one-shot final corrections; baseline bytes remain immutable. */
const fs=require('fs'),assert=require('assert/strict'),path=require('path');const dir='migration/ui-residual-message-data';
const f='logic/player-util.c';let s=fs.readFileSync(f,'utf8');assert.ok(!s.includes('#include "web-ui-residual-text.h"'));const b='/* AB_UI_RESIDUAL_BEGIN */',e='/* AB_UI_RESIDUAL_END */';s=s.replace('#include "angband.h"','#include "angband.h"'+b+'\n#ifdef __EMSCRIPTEN__\n#include "web-ui-residual-text.h"\n#endif\n'+e);fs.writeFileSync(f,s);
const helper='logic/web-ui-residual-text.c';s=fs.readFileSync(helper,'utf8');const old='{struct ab_semantic_event e;ab_semantic_event_begin(&e,"","ui","choice-dialog","__value:native_fallback",0,-1);ab_semantic_param_begin(&e,"number","integer");ab_semantic_json_int32(&e,(unsigned char)fallback);ab_semantic_param_end(&e);ab_semantic_event_emit_control(&e);}';assert.ok(s.includes(old));s=s.replace(old,'{char key[2]={fallback,0};struct ab_ui_param p=AB_UI_OPAQUE("key","display_token",key);ab_ui_emit(NULL,"fallback","ui.residual.choice.fallback",&p,1);}');fs.writeFileSync(helper,s);
let m=JSON.parse(fs.readFileSync(dir+'/source-manifest.json','utf8'));const en=JSON.parse(fs.readFileSync(dir+'/en.json','utf8')),ja=JSON.parse(fs.readFileSync(dir+'/ja.json','utf8'));
const entry={id:'ui.residual.choice.fallback',english:'Default response: {key}',japanese:'初期応答：{key}',parameters:[{name:'key',type:'display_token'}],source_role:'original_character_fallback',sources:[{file:'logic/ui-input.c',function:'get_char',original_expression:'key.code = fallback;'}],status:'source_connected_unbuilt'};assert.ok(!en[entry.id]);m.entries.push(entry);en[entry.id]=entry.english;ja[entry.id]=entry.japanese;m.catalog_entries=m.entries.length;
for(const entry of m.entries){for(const source of entry.sources??[]){if(source.function==='player_revert_shape')source.function='player_get_resume_normal_shape';if(source.function==='original quantity caller'){const native=fs.readFileSync(m.baseline+'/'+path.basename(source.file),'utf8');const at=native.indexOf(source.original_expression);assert.ok(at>=0,entry.id);const prefix=native.slice(0,at).replace(/\/\*[\s\S]*?\*\/|\/\/[^\n]*|"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'/g,x=>x.replace(/[^\r\n]/g,' '));const declarations=[...prefix.matchAll(/(?:^|\n)(?:static\s+)?(?:void|bool|int|char|enum\s+\w+)\s+(\w+)\s*\([^;{}]*\)\s*\{/g)];assert.ok(declarations.length,entry.id);source.function=declarations.at(-1)[1];source.line=native.slice(0,at).split('\n').length;}}
 if(entry.id==='ui.residual.quantity.limits')entry.sources=['int amt = 1;','if (amt > max) amt = max;','if (amt < 0) amt = 0;'].map(original_expression=>({file:'logic/ui-input.c',function:'textui_get_quantity',original_expression}));
}
for(const[p,v]of[[dir+'/source-manifest.json',m],[dir+'/en.json',en],[dir+'/ja.json',ja]])fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');
const test='tests/ui-residual-semantic-integration.test.mjs';s=fs.readFileSync(test,'utf8').replace('all27 immutable phase baselines','all29 immutable phase baselines').replace('manifest.source_files.length,27','manifest.source_files.length,29').replaceAll('252 reviewed EN/JA entries','282 reviewed EN/JA entries').replaceAll('manifest.entries.length,252','manifest.entries.length,282').replaceAll('Object.keys(en).length,252','Object.keys(en).length,282');s+=`\n
test('common dialogs consume exact producer facts with original maximum/editor/choice policies intact',()=>{
 const ui=read('logic/ui-input.c'),native=stripResidual(ui);
 assert.ok(native.includes('if (max != 1)'));assert.ok(native.includes('get_string(prompt, buf, 7)'));assert.ok(native.includes("if ((buf[0] == '*') || isalpha((unsigned char)buf[0])) amt = max;"));
 assert.ok(native.includes("if (key.code >= 'A' && key.code <= 'Z') key.code += 32;"));assert.ok(native.includes('if (!strchr(options, (char)key.code))'));
 assert.ok(ui.indexOf('ab_ur_quantity_capture(&ab_quantity,prompt,max,amt)')<ui.indexOf('ab_ur_quantity_begin(&ab_quantity)'));
 const helper=read('logic/web-ui-residual-text.c');assert.ok(helper.includes('owned.address!=address'));assert.ok(helper.includes('memset(pending,0,sizeof(*pending))'));assert.ok(helper.includes('call->active=true'));
 assert.ok(ui.includes('AB_UR_QUANTITY_RESULT(&ab_quantity,')&&ui.includes('AB_UR_QUANTITY_RETURN(&ab_quantity,'));assert.ok(helper.includes('ab_semantic_json_int32(&e,(int32_t)limit-1)'));
 const store=read('logic/ui-store.c');assert.ok(store.includes('AB_UR_QUANTITY_WORD(&ab_qty,1,')&&store.includes('AB_UR_QUANTITY_WORD(&ab_qty,0,'));assert.ok(store.includes('AB_UR_QUANTITY_OWNED(&ab_qty,true,num,')&&store.includes('AB_UR_QUANTITY_OWNED(&ab_qty,false,0,'));
 assert.equal(manifest.dialog_phase.quantity_calls,13);assert.equal(manifest.dialog_phase.choice_calls,2);assert.equal(manifest.dialog_phase.native_text_max_bytes,6);
});
test('only three note templates declare the original90 minusNUL1 minusprefix3 scalar display budget',()=>{
 const entries=manifest.entries.filter(e=>e.native_output_max_bytes!==undefined);assert.deepEqual(entries.map(e=>e.id).sort(),['ui.residual.note.action','ui.residual.note.plain','ui.residual.note.say']);
 for(const e of entries){const proof=e.native_output_budget_source;assert.equal(e.native_output_max_bytes,86);assert.equal(proof.buffer_bytes-proof.nul_bytes-proof.prefix_bytes,86);assert.ok(stripResidual(read(proof.file)).includes(proof.buffer_expression));assert.ok(stripResidual(read(proof.file)).includes(proof.omitted_prefix_expression));}
});\n`;fs.writeFileSync(test,s);
console.log(JSON.stringify({entries:m.entries.length,exact_header_added:true,new_tests:2}));