// Only source/data reads and metadata checks; no Cargo, guard, or WebAssembly execution.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../..');
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const handoffPath = path.join(root, 'evidence/native-v5-handoff.json');
const handoffBytes = fs.readFileSync(handoffPath);
const handoff = JSON.parse(handoffBytes);
const names = ['core-functional.png', 'core-tiles.png', 'overmap-functional.png', 'overmap-tiles.png', 'tile_config.json', 'tileset.txt'];
assert.equal(handoff.source_commit, '7b2efa5cea38e4d4d97dd0e63b28b9148623da59');
assert.equal(handoff.preload_files.length, 6);
const source = fs.readFileSync(path.join(here, 'src/lib.rs'), 'utf8');
const tests = fs.readFileSync(path.join(here, 'src/tests.rs'), 'utf8');
const assetBlock = source.split('pub const ASSETS:')[1].split('/// Rejection precedence')[0];
const assetRecords = [...assetBlock.matchAll(/AssetIdentity\s*\{\s*name:\s*"([^"]+)",\s*bytes:\s*([0-9_]+),\s*digest_words:\s*\[([\s\S]*?)\],\s*\}/g)];
assert.equal(assetRecords.length, 6);
const files = handoff.preload_files.map((record, index) => {
  assert.equal(path.basename(record.path), names[index]);
  const bytes = fs.readFileSync(record.path);
  assert.equal(bytes.length, record.bytes);
  assert.equal(hash(bytes), record.sha256);
  const [match, name, length, wordSource] = assetRecords[index];
  assert.equal(name, names[index]);
  assert.equal(Number(length.replaceAll('_', '')), record.bytes);
  const words = [...wordSource.matchAll(/0x([0-9a-f]{8})/g)].map(match => match[1]);
  assert.equal(words.length, 8);
  assert.equal(words.join(''), record.sha256);
  assert.ok(tests.includes(record.sha256), 'independent native-test hexadecimal fixture required');
  return { index, name, path: record.path, bytes: bytes.length, sha256: hash(bytes) };
});
const abiNames = ['cdda_v5_policy_version', 'cdda_v5_asset_count', 'cdda_v5_validate_asset', 'cdda_v5_new_profile_option_count', 'cdda_v5_new_profile_option_kind'];
assert.deepEqual([...source.matchAll(/pub extern "C" fn ([a-z0-9_]+)/g)].map(match => match[1]), abiNames);
assert.equal([...source.matchAll(/#\[unsafe\(no_mangle\)\]/g)].length, 5);
const functionBody = source.slice(source.indexOf('pub extern "C" fn cdda_v5_validate_asset('), source.indexOf('/// Number of native string instructions'));
const argumentsBody = functionBody.slice(functionBody.indexOf('(') + 1, functionBody.indexOf(') ->'));
assert.equal([...argumentsBody.matchAll(/:\s*u32/g)].length, 10);
assert.ok(!argumentsBody.includes('*'), 'ABI may not accept host pointers');
assert.ok(!/(?:std::(?:fs|thread|time|collections)|static\s+mut|unsafe\s*\{|extern\s*"C"\s*\{|\b(?:Vec|Box|String|rand)\b)/.test(source), 'policy must remain scalar/pure/no imports or allocations');
assert.equal([...tests.matchAll(/#\[test\]/g)].length, 5);
const expectedOptions = [['USE_LANG', 'ja'], ['TILES', 'cdda16_combined_ready'], ['OVERMAP_TILES', 'cdda16_combined_ready']];
const optionBlock = source.split('pub const NEW_PROFILE_OPTIONS:')[1].split('/// Returns no instructions')[0];
assert.deepEqual([...optionBlock.matchAll(/name:\s*"([^"]+)",\s*value:\s*"([^"]+)"/g)].map(match => [match[1], match[2]]), expectedOptions);
assert.ok(source.includes('ProfilePresence::Existing => &[]'));
const manifest = fs.readFileSync(path.join(here, 'Cargo.toml'), 'utf8');
assert.ok(manifest.includes('[dependencies]\n\n'), 'empty dependency section required');
const lock = fs.readFileSync(path.join(here, 'Cargo.lock'), 'utf8');
assert.equal([...lock.matchAll(/\[\[package\]\]/g)].length, 1);
const pins = ['Cargo.toml', 'Cargo.lock', 'rustfmt.toml', 'NOTICE.txt', 'src/lib.rs', 'src/tests.rs', 'validate-source.mjs'].map(relative => {
  const file = path.join(here, relative), bytes = fs.readFileSync(file);
  return { path: file, bytes: bytes.length, sha256: hash(bytes) };
});
const result = { schemaVersion: 1, status: 'source-and-six-actual-parent-assets-verified', checkedAt: new Date().toISOString(), policyVersion: 1, originalSourceCommit: handoff.source_commit, handoff: { path: handoffPath, bytes: handoffBytes.length, sha256: hash(handoffBytes) }, files, pins, abiNames, expectedOptions, nativeTestsPrepared: 5, RustTestsExecuted: false, CargoExecuted: false, WindowsGuardLoaded: false, engineRuntimeVerified: false, allGameArtworkComplete: false, externalPublication: false };
fs.writeFileSync(path.join(here, 'source-validation.json'), JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify({ status: result.status, files: files.length, abi: abiNames.length, nativeTestsPrepared: 5 }));
