import './locale-refresh.test.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,rmSync,mkdirSync,writeFileSync,readdirSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {applyPatches,verifyCatalogs,generateOverlay,sha256,buildSemanticHelpUnit,buildSemanticRegistryUnit} from './generate.mjs';
import {buildRegistryTerms,scanRegistrySource,lookupRegistryTerm,verifyRegistrySources} from './registry-terms.mjs';
import {scanMessageCalls,buildMessageInventory} from './message-inventory.mjs';
import {staticLevelMessages,verifyStaticLevelMessages} from './lua-level-message-translations.mjs';
import {dynamicMessageCalls,producerMessages,verifyDynamicMessages} from './lua-dynamic-message-translations.mjs';
import {buildMigrationPlan} from './migration-plan.mjs';
import {helpSegments,buildHelpCatalog} from './help-bodies.mjs';
import {tokens,render} from './render.mjs';
import {scanSource} from '../port/tools/inventory-texts.mjs';
import {verifyPascalViewTranslations} from './pascal-view-translations.mjs';
import {verifyChallengeFields} from './registry-challenges.mjs';
import {buildTextDispositions} from './text-dispositions.mjs';
import {verifyHistoryPresentation,semanticHistorySidecarSchema} from './history-presentation.mjs';
import {auditPascalUses,pascalUses} from './audit-pascal-uses.mjs';
import {curatePaddingSites,paddingCalls} from './padding-sites.mjs';
import {curateRuntimePathSites,runtimePathSourcePins,equipmentSlotTerms} from './runtime-path-sites.mjs';
import {curateModificationNotices,modificationNoticeText} from './modification-notices.mjs';
import {browserPresentationOverrides} from './browser-ui-overrides.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../upstream/drl');
const manifest=JSON.parse(readFileSync(path.join(here,'manifest.json'),'utf8'));
const english=readFileSync(path.join(here,'en.json')),japanese=readFileSync(path.join(here,'ja.json'));
const {en,ja}=verifyCatalogs(manifest,english,japanese);
test('small Rust embedding contract is identical to reviewed manifest',()=>{
 const c=JSON.parse(readFileSync(path.join(here,'contract.json'),'utf8'));
 assert.equal(c.schema,1);assert.equal(c.grammar,'native-vtig-markup+double-brace-named-parameters');assert.deepEqual(c.parameters,manifest.parameters);
});
test('every reviewed ID has equal locales and an explicit typed parameter contract',()=>{
 assert.ok(Object.keys(en).length>=1650);assert.deepEqual(Object.keys(en),Object.keys(ja));
 const contracts=manifest.parameters;
 for(const id of Object.keys(en)){
   const p=Object.fromEntries(Object.entries(contracts[id]).map(([k,v])=>[k,v==='integer'?3:'external-value']));
   assert.equal(typeof render(en,contracts,id,p),'string');assert.equal(typeof render(ja,contracts,id,p),'string');
 }
});
test('all original Pascal and Lua hashes and injection-site offsets roundtrip',()=>{
 for(const [file,lock]of Object.entries(manifest.sources)){
  const bytes=readFileSync(path.join(root,file));assert.equal(sha256(bytes),lock.sha256);
  for(const patch of manifest.patches.filter(p=>p.file===file))assert.equal(bytes.toString('utf8').slice(patch.start,patch.end),patch.original);
  const transformed=applyPatches(bytes,lock,manifest.patches.filter(p=>p.file===file));
  assert.equal(scanSource(transformed,file.endsWith('.lua')?'lua':'pascal').diagnostics.length,0,`${file} malformed quoted source`);
 }
});
test('source mutation is rejected before source transformation',()=>{
 const file=Object.keys(manifest.sources)[0],bytes=readFileSync(path.join(root,file));
 assert.throws(()=>applyPatches(Buffer.concat([bytes,Buffer.from(' ')]),manifest.sources[file],[]),/provenance/);
});
test('mutated source-site offsets and overlapping patch sites are rejected',()=>{
 const file=Object.keys(manifest.sources)[0],bytes=readFileSync(path.join(root,file)),ps=manifest.patches.filter(p=>p.file===file);
 assert.throws(()=>applyPatches(bytes,manifest.sources[file],[{...ps[0],original:'not the expected source'}]),/site mismatch/);
 assert.throws(()=>applyPatches(bytes,manifest.sources[file],[ps[1],ps[1]]),/Overlapping/);
 assert.throws(()=>applyPatches(bytes,manifest.sources[file],[{...ps[0],start:-1}]),/bounds/);
});
test('generator refuses pristine source or its parent as output',()=>{
 assert.throws(()=>generateOverlay({sourceRoot:root,outputRoot:root}),/outside upstream/);
 assert.throws(()=>generateOverlay({sourceRoot:root,outputRoot:path.dirname(root)}),/outside upstream/);
});
test('generated bytes reproducible and pristine inputs unchanged',()=>{
 const tmp=mkdtempSync(path.join(os.tmpdir(),'drl-localization-'));
 try {
  const a=generateOverlay({sourceRoot:root,outputRoot:path.join(tmp,'a')}),b=generateOverlay({sourceRoot:root,outputRoot:path.join(tmp,'b')});
  assert.deepEqual(a,b);assert.equal(a.fullGameLocalizationComplete,false);assert.equal(a.browserRustResolverConnected,false);
  for(const f of a.files){assert.deepEqual(readFileSync(path.join(tmp,'a',f.file)),readFileSync(path.join(tmp,'b',f.file)));assert.equal(sha256(readFileSync(path.join(root,f.file))),f.sourceSha256);}
 }finally{rmSync(tmp,{recursive:true});}
});
test('catalog mutation is rejected before transformation',()=>{
 assert.throws(()=>verifyCatalogs(manifest,english,Buffer.from(japanese.toString().replace('自動','automatic'))),/Catalog provenance/);
});
test('named parameter contract detects omissions, extra arguments and numeric types',()=>{
 const c=manifest.parameters;
 assert.throws(()=>render(ja,c,'menu.seed.value'),/set mismatch/);
 assert.throws(()=>render(ja,c,'menu.seed.value',{seed:1,other:2}),/set mismatch/);
 for(const seed of ['1',NaN,Infinity,1.2,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>render(ja,c,'menu.seed.value',{seed}),/safe integer/);
 assert.throws(()=>render(ja,c,'menu.save.version.engine',{version:3}),/string/);
 assert.throws(()=>render(ja,c,'unknown.text.id'),/Unknown semantic/);
});
test('literal VTIG markup and configurable input/control hints survive',()=>{
 assert.equal(render(en,manifest.parameters,'menu.save.version.engine',{version:'0.10.11'}),'Save engine version : {!0.10.11}');
 assert.equal(render(ja,manifest.parameters,'menu.save.version.engine',{version:'0.10.11'}),'セーブのエンジンバージョン：{!0.10.11}');
 assert.match(render(ja,manifest.parameters,'settings.hint.keys'),/\{\$input_uidrop\}/);
 assert.match(ja['settings.option.group_messages.description'],/\{\^3\}/);
});
test('string parameters remain verbatim and are never recursively translated/formatted',()=>{
 const external='Player 日本 Alice {{missing}} {!raw}';
 assert.equal(render(ja,manifest.parameters,'settings.module.missing',{module:external}),`${external}（見つかりません）`);
 assert.equal(render(en,manifest.parameters,'settings.module.missing',{module:external}),`${external} (missing)`);
});
test('Japanese can reorder and repeat named parameters without English fragments',()=>{
 assert.equal(render({t:'{{b}}・{{a}}・{{a}}'},{t:{a:'string',b:'string'}},'t',{a:'甲',b:'乙'}),'乙・甲・甲');
});
test('signed Int64 values remain exact without JavaScript double rounding',()=>{
 assert.equal(render({t:'{{count}}'},{t:{count:'integer'}},'t',{count:9223372036854775807n}),'9223372036854775807');
 assert.equal(render({t:'{{count}}'},{t:{count:'integer'}},'t',{count:-9223372036854775808n}),'-9223372036854775808');
 assert.throws(()=>render({t:'{{count}}'},{t:{count:'integer'}},'t',{count:9223372036854775808n}),/Int64/);
});
test('malformed placeholders fail while original single-brace grammar remains literal',()=>{
 for(const s of ['{{x','{{not-valid}}','{{}}'])assert.throws(()=>tokens(s),/placeholder/);
 assert.deepEqual(tokens('{Rdanger} {$input_ok} {0} {^3}'),[{literal:'{Rdanger} {$input_ok} {0} {^3}'}]);
});
test('all 28 visible configuration names and descriptions have exact semantic pairs',()=>{
 const names=Object.keys(en).filter(id=>/^settings\.option\.[a-z_]+\.name$/.test(id));assert.equal(names.length,28);
 for(const id of names)assert.ok(Object.hasOwn(ja,id.replace(/\.name$/,'.description')));
 const original=readFileSync(path.join(root,'src/drlconfiguration.pas'),'utf8');
 const explicitNames=scanSource(original,'pascal').tokens.filter((t,i,a)=>t.raw==='SetName'&&a[i+2]?.kind==='string');assert.equal(explicitNames.length,28);
 const output=applyPatches(Buffer.from(original),manifest.sources['src/drlconfiguration.pas'],manifest.patches.filter(p=>p.file==='src/drlconfiguration.pas'));
 assert.equal((output.match(/\.SetName\(\s*DRLText\('settings\.option\./g)||[]).length,28);
 assert.equal((output.match(/\.SetDescription\(\s*DRLText\('settings\.option\./g)||[]).length,28);
});
test('all 73 nonempty official input action IDs retain exact English metadata',()=>{
 const src=readFileSync(path.join(root,'src/drlkeybindings.pas'),'utf8');let count=0;
 const groups={};
 for(const line of src.split('\n')){
  const ts=scanSource(line,'pascal').tokens.filter(t=>t.kind==='string');
  if(ts.length!==4||!ts[0].value.startsWith('input_'))continue;
  const [id,group,name,desc]=ts.map(t=>t.value);count++;
  assert.equal(en[`${id}.name`],name);assert.equal(en[`${id}.description`],desc);groups[group]=(groups[group]??0)+1;
 }
 assert.equal(count,73);assert.ok(groups.keybindings_movement>0);
});
test('controller action IDs/defaults and original constant records remain intact',()=>{
 const file='src/drlcontrollerbindings.pas',original=readFileSync(path.join(root,file),'utf8');
 const output=applyPatches(Buffer.from(original),manifest.sources[file],manifest.patches.filter(p=>p.file===file));
 const begin=original.indexOf('const ControllerBindingInfo'),end=original.indexOf('procedure RegisterControllerBindings');
 assert.ok(output.includes(original.slice(begin,end)));
 assert.equal(Object.keys(en).filter(k=>/^controller_gameplay_.*\.name$/.test(k)).length,16);
});
test('state/select/description const records remain byte-exact and are resolved at use',()=>{
 const file='src/drlsettingsview.pas',original=readFileSync(path.join(root,file),'utf8');
 const output=applyPatches(Buffer.from(original),manifest.sources[file],manifest.patches.filter(p=>p.file===file));
 assert.ok(output.includes(original.slice(original.indexOf('const CStates'),original.indexOf('constructor TSettingsView.Create;\nvar'))));
 assert.match(output,/DRLText\(CStateTextIDs\[FState\]/);assert.match(output,/DRLText\(CSubTextIDs\[i\]\.Name/);
 assert.match(output,/DRLText\('settings.value.enabled'/);
});
test('main menu original challenge/new-game requirements and stored IDs are preserved',()=>{
 const file='src/drlmainmenuview.pas',original=readFileSync(path.join(root,file),'utf8');
 const output=applyPatches(Buffer.from(original),manifest.sources[file],manifest.patches.filter(p=>p.file===file));
 assert.ok(output.includes(original.slice(original.indexOf('var ChallengeType'),original.indexOf('// Trials remain hidden'))));
 assert.match(output,/ChallengeType\[1\]\.Allow := \(iSkill > 0\)/);
 assert.match(output,/FResult.Seed := Cardinal\( iSeed \)/);assert.match(output,/DeleteFile\( ModuleUserPath \+ 'save' \)/);
});
test('all eight core help topic titles and both quick primers reviewed',()=>{
 assert.equal(Object.keys(en).filter(id=>id.startsWith('help.topic.')).length,8);
 assert.equal(Object.keys(en).filter(id=>id.startsWith('help.primer.keyboard.')).length,10);
 assert.equal(Object.keys(en).filter(id=>id.startsWith('help.primer.controller.')).length,10);
 assert.equal(Object.keys(en).filter(id=>id.startsWith('help.body.')).length,116);
});
test('all eight original help documents hash-check and regenerate identical reviewed data',()=>{
 const data=JSON.parse(readFileSync(path.join(here,'help-catalog.json'),'utf8'));
 assert.deepEqual(buildHelpCatalog(root),data);assert.equal(data.documents.length,8);assert.equal(data.entries.length,116);
 assert.equal(sha256(readFileSync(path.join(here,'help-catalog.json'))),manifest.catalogs.helpCatalogSha256);
 for(const d of data.documents){assert.equal(sha256(readFileSync(path.join(root,d.file))),d.sha256);assert.deepEqual(helpSegments(readFileSync(path.join(root,d.file),'utf8')).lines,d.lines);}
});
test('help paragraph boundaries completely cover every source line without omission/reordering',()=>{
 const data=JSON.parse(readFileSync(path.join(here,'help-catalog.json'),'utf8'));
 for(const d of data.documents){
  assert.deepEqual(d.segments.flatMap(s=>s.lines),d.lines);
  for(const s of d.segments){assert.deepEqual(d.lines.slice(s.firstLine,s.firstLine+s.lines.length),s.lines);if(s.id){assert.equal(en[s.id],s.lines.join('\n'));assert.ok(Object.hasOwn(ja,s.id));}}
 }
});
test('generated help unit retains exact English line guards and semantic paragraph calls',()=>{
 const data=JSON.parse(readFileSync(path.join(here,'help-catalog.json'),'utf8')),unit=buildSemanticHelpUnit(data);
 assert.equal(scanSource(unit,'pascal').diagnostics.length,0);
 for(const id of data.entries.map(e=>e.id))assert.ok(unit.includes(id));
 assert.match(unit,/DRLText\(CHelpBlocks\[iBlock\]\.ID, CHelpBlocks\[iBlock\]\.English\)/);
 const loader=readFileSync(path.join(here,'overlay/src/drlhelp.pas'),'utf8');
 assert.match(loader,/iEntry\.FText\[iLine\] <> DRLHelpSourceLine/);assert.match(loader,/if iMatches then iEntry\.FSemanticTopic := iTopic;/);assert.doesNotMatch(loader,/FText\.Clear/);
});
test('help default-controller binding substitutions preserve all configured IDs, widths and repetitions',()=>{
 for(const id of Object.keys(en).filter(k=>k.startsWith('help.body.'))){
  const controls=s=>Array.from(s.matchAll(/\{\$[^{}]+\}/g),m=>m[0]).sort();assert.deepEqual(controls(en[id]),controls(ja[id]));
 }
});
test('source disclaimer conditions and no-warranty terms are explicitly retained in Japanese',()=>{
 assert.match(ja['help.body.disclaim.redistribution'],/作者（admin@chaosforge\.org）に知らせることを条件/);
 assert.match(ja['help.body.disclaim.redistribution'],/見本誌を一部/);assert.match(ja['help.body.disclaim.warranty'],/いかなる種類の保証もありません/);
 assert.match(ja['help.body.disclaim.warranty'],/責任を負いません/);assert.match(ja['help.body.disclaim.warranty'],/自己の責任/);
});
test('audio attribution does not turn source permission into a new redistributable grant',()=>{
 for(const id of ['sonic-clang-permission','per-kristian-permission']){assert.match(en[`help.body.credits.${id}`],/used with permission/);assert.match(ja[`help.body.credits.${id}`],/許可を得て使用/);}
 assert.match(ja['help.body.credits.sonic-clang-permission'],/Sonic Clang/);assert.match(ja['help.body.credits.per-kristian-permission'],/Per Kristian Risvik/);assert.match(ja['help.body.credits.id-software'],/Id Software/);
});
test('all external URLs/email and donor usernames retain exact spelling and donor list order',()=>{
 for(const id of Object.keys(en).filter(k=>k.startsWith('help.body.'))){
  const refs=s=>Array.from(s.matchAll(/https?:\/\/[^\s}\)]+|admin@chaosforge\.org/g),m=>m[0]);assert.deepEqual(refs(en[id]),refs(ja[id]));
 }
 assert.equal(ja['help.body.credits.top-donors'],en['help.body.credits.top-donors']);
 assert.equal(ja['help.body.credits.all-donors'].split('\n').slice(1).join('\n'),en['help.body.credits.all-donors'].split('\n').slice(1).join('\n'));
});
test('ASCII example map and embedded example username remain stable while status labels translate',()=>{
 const id='help.body.start.screen-example';assert.match(ja[id],/DRLguy/);assert.match(ja[id],/体力/);assert.match(ja[id],/ピストル/);
 const map=s=>s.split('\n').filter(l=>/^ #[#@.]+$/.test(l));assert.deepEqual(map(en[id]),map(ja[id]));
});
test('registry catalog reproduces all reviewed metadata against the pinned 83 Lua files',()=>{
 const data=JSON.parse(readFileSync(path.join(here,'registration-term-catalog.json'),'utf8'));
 assert.deepEqual(buildRegistryTerms(root),data);
 assert.equal(Object.keys(verifyRegistrySources(root).sources).length,83);
 assert.equal(sha256(readFileSync(path.join(here,'registration-term-catalog.json'))),manifest.catalogs.registryCatalogSha256);
 assert.equal(data.preserveOriginalEnglishDomainStrings,true);assert.equal(data.runtimeAdapterConnected,false);
});
test('every reviewed registry field has an exact original literal source site and equal canonical EN/JA',()=>{
 const data=JSON.parse(readFileSync(path.join(here,'registration-term-catalog.json'),'utf8'));
 for(const record of data.metadata)for(const [field,term]of Object.entries(record.fields)){
  assert.ok(data.fieldRoles[record.category].includes(field));
  const lock=data.sourceFiles[term.source.file],bytes=readFileSync(path.join(root,term.source.file));assert.equal(sha256(bytes),lock.sha256);
  assert.equal(bytes.toString('utf8').slice(term.source.offset,term.source.endOffset),term.source.raw);
  if(term.derivation){
   assert.ok(['guarded-original-default-plural','guarded-generated-corpse-name','guarded-generated-default-natural-attack-name'].includes(term.derivation.kind));assert.equal(scanSource(term.source.raw,'lua').tokens[0].value,term.derivation.sourceEnglish);
   const expected=term.derivation.kind==='guarded-original-default-plural'?term.derivation.sourceEnglish+'s':term.derivation.kind==='guarded-generated-corpse-name'?term.derivation.sourceEnglish+' corpse':'ranged attack';assert.equal(term.english,expected);
   const p=term.derivation.producer,producer=readFileSync(path.join(root,p.file),'utf8');assert.equal(producer.slice(p.offset,p.endOffset),p.raw);assert.equal(sha256(Buffer.from(producer)),data.sourceFiles[p.file].sha256);
  }else assert.equal(scanSource(term.source.raw,'lua').tokens[0].value,term.english);
  assert.equal(en[term.semanticId],term.english);assert.equal(ja[term.semanticId],data.japaneseCatalog[term.semanticId]);assert.deepEqual(manifest.parameters[term.semanticId],{});
 }
});
test('all original being, item and trait literal descriptions and all names are reviewed by field role',()=>{
 const d=JSON.parse(readFileSync(path.join(here,'registration-term-catalog.json'),'utf8'));
 const count=(category,field)=>d.metadata.filter(e=>e.category===category&&e.fields[field]).length;
 assert.equal(count('being','name'),40);assert.equal(count('being','desc'),40);assert.equal(count('item','name'),172);assert.equal(count('item','desc'),130);
 assert.equal(count('cell','name'),51);assert.equal(count('cell','blname'),13);assert.equal(count('trait','name'),35);assert.equal(count('trait','desc'),34);assert.equal(count('mod_array','name'),42);assert.equal(count('mod_array','request_desc'),12);
 assert.equal(count('being','name_plural'),40);assert.ok(d.metadata.length>=336);assert.ok(d.pending.length>0);assert.equal(d.generatedNamesAndRuntimeOverridesCovered,false);
});
test('registry presentation lookup is scoped by category, original ID, scope, field and English guard',()=>{
 const d=JSON.parse(readFileSync(path.join(here,'registration-term-catalog.json'),'utf8'));
 for(const e of d.metadata)for(const [field,t]of Object.entries(e.fields)){
  const request={category:e.category,registryId:e.registryId,scope:e.scope,field,english:t.english};
  assert.equal(lookupRegistryTerm(d,request,'en'),t.english);assert.equal(lookupRegistryTerm(d,request,'ja'),d.japaneseCatalog[t.semanticId]);
  for(const wrong of [{registryId:'custom-id'},{category:'custom-category'},{scope:'custom-module'},{field:'internal-id'},{english:t.english+' custom override'}])assert.equal(lookupRegistryTerm(d,{...request,...wrong}),wrong.english??t.english);
 }
 assert.throws(()=>lookupRegistryTerm(d,{english:3}),/English guard/);
});
test('registry source locks reject mutation and traversal independently of generated catalogs',()=>{
 const lock=verifyRegistrySources(root),file=Object.keys(lock.sources)[0];
 assert.throws(()=>verifyRegistrySources(root,{sources:{[file]:{...lock.sources[file],sha256:'00'.repeat(32)}}}),/provenance/);
 assert.throws(()=>verifyRegistrySources(root,{sources:{'../escape.lua':lock.sources[file]}}),/Unsafe/);
});
test('registry extraction skips comments, nested tables and hook-local assignments',()=>{
 const source=`-- register_item "fake" {name="not a name"}\nregister_item "actual" { name="Real", desc="Description", nested={name="Nested"}, OnUse=function(self) if true then local desc="hook text" end end }`;
 const entries=scanRegistrySource(source,'bin/data/drl/test.lua');assert.equal(entries.length,1);
 assert.equal(entries[0].registryId,'actual');assert.equal(entries[0].fields.name.value,'Real');assert.equal(entries[0].fields.desc.value,'Description');
});
test('generated registry helper is exact typed lookup with safe original fallback',()=>{
 const d=JSON.parse(readFileSync(path.join(here,'registration-term-catalog.json'),'utf8')),unit=buildSemanticRegistryUnit(d);
 assert.equal(scanSource(unit,'pascal').diagnostics.length,0);assert.match(unit,/Category = aCategory/);assert.match(unit,/RegistryID = aRegistryID/);assert.match(unit,/Scope = aScope/);assert.match(unit,/Field = aField/);assert.match(unit,/if English <> aEnglish then Exit\(aEnglish\)/);
 assert.match(unit,/Exit\(DRLText\(ID, aEnglish\)\)/);
});
test('original English item and being getters, published Desc and BFG name comparisons remain intact',()=>{
 for(const [file,start,end]of [
  ['src/dfitem.pas','function TItem.Description : Ansistring;','function TItem.GetAltFireName : AnsiString;'],
  ['src/dfitem.pas','function    TItem.GetName(','destructor  TItem.Destroy;'],
  ['src/dfbeing.pas','function TBeing.GetName(known : boolean) : string;','function  TBeing.WoundStatus']
 ]){
  const original=readFileSync(path.join(root,file),'utf8'),output=applyPatches(Buffer.from(original),manifest.sources[file],manifest.patches.filter(p=>p.file===file));
  const portion=original.slice(original.indexOf(start),original.indexOf(end));assert.ok(portion.length>20);
  // The added presentation methods sit before GetAltFireName; the original block itself is exact.
  assert.ok(output.includes(portion));
 }
 const item=readFileSync(path.join(here,'overlay/src/dfitem.pas'),'utf8');assert.match(item,/property Desc\s+: AnsiString\s+read Description;/);
 const mechanics=readFileSync(path.join(root,'bin/data/drl/assemblies.lua'),'utf8');assert.equal((mechanics.match(/item\.name == "nuclear BFG 9000"/g)||[]).length,2);
 const assembled=readFileSync(path.join(here,'overlay/bin/data/drl/assemblies.lua'),'utf8');assert.equal((assembled.match(/item\.name == "nuclear BFG 9000"/g)||[]).length,2);
});
test('presentation name projection retains descriptor suffixes and original getter evaluations',()=>{
 const source=readFileSync(path.join(here,'item-semantic-methods.pas'),'utf8');
 assert.match(source,/PresentationNameValue\(GetName\(aKnown, aSingle\), aKnown\)/);
 assert.match(source,/if Copy\(iEnglish, 1, Length\(iPrefix\)\) <> iPrefix then Exit\(iEnglish\)/);
 assert.match(source,/Copy\(iEnglish, Length\(iPrefix\) \+ 1, Length\(iEnglish\)\)/);
 assert.equal((source.match(/ProtectedRunHook\(/g)||[]).length,1);
 assert.doesNotMatch(source,/\bName\s*:=|\bFAmount\s*:=|\bFSpeedCount\s*:=/);
});
test('message inventory excludes declarations/comments and accounts for exact original argument spans',()=>{
 const d=JSON.parse(readFileSync(path.join(here,'message-inventory.json'),'utf8'));assert.deepEqual(buildMessageInventory(root),d);
 assert.equal(d.counts.calls,540);assert.equal(d.counts.byLanguage.lua,420);assert.equal(d.counts.byLanguage.pascal,120);
 for(const c of d.calls){const source=readFileSync(path.join(root,c.file),'utf8');assert.equal(source.slice(c.start,c.end),c.original);for(const a of c.arguments)if(a.start!==null)assert.equal(source.slice(a.start,a.end),a.source);}
 assert.equal(scanMessageCalls('-- ui.msg("comment")\nfunction being:msg(a,b) end\nui.msg("real")','lua','fixture.lua').length,1);
});
test('every curated gameplay source site is an original message call, unique, patched and catalogued',()=>{
 const d=JSON.parse(readFileSync(path.join(here,'message-inventory.json'),'utf8')),sites=JSON.parse(readFileSync(path.join(here,'gameplay-sites.json'),'utf8')),seen=new Set();
 for(const s of sites.reviewed){
  assert.ok(!seen.has(s.key));seen.add(s.key);const c=d.calls.find(c=>c.key===s.key);assert.ok(c,s.key);assert.equal(c.original,s.source);
  assert.ok(manifest.patches.some(p=>p.file===c.file&&p.start===c.start&&p.end===c.end&&p.replacement===s.replacement));
  for(const id of [s.id,s.observerId,...s.variantIds??[]].filter(Boolean))assert.ok(Object.hasOwn(en,id),id);
 }
 assert.ok(sites.reviewed.length>=400);assert.equal(sites.allGameplayMessagesCovered,false);
});
test('semantic action wrappers preserve cost, silence and visibility while bypassing printf',()=>{
 const source=readFileSync(path.join(here,'being-semantic-methods.pas'),'utf8');
 assert.match(source,/if aCost <> 0 then Dec\(FSpeedCount, aCost\)/);assert.match(source,/if FSilentAction then Exit\(False\)/);assert.match(source,/if FSilentAction then Exit\(True\)/);assert.match(source,/else if isVisible then/);
 assert.match(source,/IO\.Msg\(DRLText\(aID, aEnglish, aParams\)\)/);assert.doesNotMatch(source,/\bFormat\(/);assert.doesNotMatch(source,/\bRNG\b|GameRNG|Random\(/);
 const item='100% armor {{unknown}}';assert.equal(render(ja,manifest.parameters,'message.item-picked-up',{item}),`${item}を拾った。`);
});
test('all reload variants are complete messages with subject and item contracts',()=>{
 for(const suffix of ['normal','quick','ground','quick-ground'])assert.deepEqual(manifest.parameters['message.reload.'+suffix+'.player'],{item:'string'});
 for(const suffix of ['normal','ground'])assert.deepEqual(manifest.parameters['message.reload.'+suffix+'.observer'],{subject:'string',item:'string'});
 const source=readFileSync(path.join(here,'overlay/src/dfbeing.pas'),'utf8');assert.match(source,/SemanticEmote\(IIf\(iIsPack, IIf\(iIsGround,/);
 assert.ok(source.includes('iOldName := iOldItem.GetName(false);'));assert.match(source,/iOldDisplayName := iOldItem\.PresentationNameValue\(iOldName, False\)/);
});
test('165 special-level messages have complete source guards, Japanese bodies and original VTIG topology',()=>{
 const verified=verifyStaticLevelMessages(root);assert.equal(verified.reviewedMessages,165);assert.equal(verified.pendingCalls,1);
 for(const m of staticLevelMessages){assert.equal(en[m.id],m.english);assert.equal(ja[m.id],m.japanese);assert.ok(manifest.patches.some(p=>p.file===m.file&&p.id===m.id));}
});
test('all ten original plot bodies are complete semantic messages with exact English fallback',()=>{
 const calls=scanMessageCalls(readFileSync(path.join(root,'bin/data/drl/plot.lua'),'utf8'),'lua','bin/data/drl/plot.lua');assert.equal(calls.length,10);
 for(const c of calls){const p=manifest.patches.find(p=>p.file===c.file&&p.start===c.start);assert.ok(p);assert.equal(en[p.id],c.arguments[0].strings[0].value);assert.ok(/[\u3040-\u30ff\u3400-\u9fff]/u.test(ja[p.id]));}
});
test('Lua semantic API has typed decimal integer parameters and registry guards without mutating domain names',()=>{
 const adapter=readFileSync(path.join(here,'lua-semantic-adapter.pas'),'utf8');assert.match(adapter,/TryStrToInt64\(iValue, iInteger\)/);assert.match(adapter,/IntToStr\(iInteger\) <> iValue/);assert.match(adapter,/iSize > 16/);assert.ok(adapter.indexOf('iSize > 16')<adapter.indexOf('iCount := Integer(iSize)'));
 const io=readFileSync(path.join(here,'overlay/src/drlio.pas'),'utf8');assert.match(io,/name : 'semantic_text'; func : @lua_ui_semantic_text/);assert.match(io,/name : 'registry_text'; func : @lua_ui_registry_text/);
});
test('browser UI overrides and native/platform adapter errors retain separate explicit catalog coverage',()=>{
 for(const [f,prefix]of [['../port/locales/gameui','game.'],['../experiments/lua-wasi/adapter-errors','error.lua.adapter.']]){
  const e=JSON.parse(readFileSync(path.resolve(here,f+'-en.json'),'utf8')),j=JSON.parse(readFileSync(path.resolve(here,f+'-ja.json'),'utf8'));
  for(const [id,value]of Object.entries(e)){const override=prefix==='game.'?browserPresentationOverrides[id]:undefined;assert.ok(id.startsWith(prefix));assert.equal(en[id],override?.[0]??value);assert.equal(ja[id],override?.[1]??j[id]);assert.deepEqual(manifest.parameters[id],{});}
 }
 assert.equal(Object.keys(en).filter(id=>id.startsWith('error.lua.platform.')).length,3);
});
test('dynamic Lua English templates reconstruct complete original argument values with captured typed parameters',()=>{
 const result=verifyDynamicMessages(root);assert.equal(result.reviewedDynamicCalls,25);assert.equal(result.finiteDispatchCalls,6);assert.equal(result.reviewedTemplates,53);assert.equal(result.pendingCalls,1);
 for(const row of dynamicMessageCalls)for(const m of row.messages){assert.equal(en[m.id],m.english);assert.equal(ja[m.id],m.japanese);assert.deepEqual(manifest.parameters[m.id],Object.fromEntries(m.bindings.map(b=>[b.name,b.type])));}
 for(const p of producerMessages){assert.equal(en[p.id],p.english);assert.equal(ja[p.id],p.japanese);}
});
test('finite random feelings preserve the original RNG call count, order and source English identities',()=>{
 for(const f of ['bin/data/drl/generator.lua','bin/data/drl/generators.lua','bin/data/drl/rooms.lua','bin/data/drl/levels/mterebus.lua']){
  const original=readFileSync(path.join(root,f),'utf8'),output=readFileSync(path.join(here,'overlay',f),'utf8');
  const rng=s=>scanSource(s,'lua').tokens.filter((t,n,ts)=>t.kind==='identifier'&&['random','random_pick','roll'].includes(t.raw)&&['math','table','weight_table'].includes(ts[n-2]?.raw)).map(t=>t.raw);
  assert.deepEqual(rng(output),rng(original),f);
 }
 const output=readFileSync(path.join(here,'overlay/bin/data/drl/generators.lua'),'utf8');
 for(const p of producerMessages.filter(p=>p.producerKind==='local-presentation-table-field'))assert.ok(output.includes(JSON.stringify(p.english)));
 const rooms=readFileSync(path.join(here,'overlay/bin/data/drl/rooms.lua'),'utf8');assert.match(rooms,/function\(selected\) return ui.semantic_feeling\(selected.id, selected.english\) end\)\(table.random_pick/);
});
test('lever sensing and first pickup quotes use explicit scoped registry fields while their original prototypes remain English',()=>{
 const d=JSON.parse(readFileSync(path.join(here,'registration-term-catalog.json'),'utf8'));
 assert.equal(d.metadata.filter(r=>r.fields.good).length,29);assert.equal(d.metadata.filter(r=>r.fields.firstmsg).length,17);assert.equal(d.metadata.filter(r=>r.fields.warning).length,5);
 const item=readFileSync(path.join(here,'overlay/bin/data/core/item.lua'),'utf8');assert.ok(item.includes('self.name          = "overcharged "..self.name'));
 assert.match(item,/ui.registry_text\("item", self.id, "base_game", "good", good\)/);
 const main=readFileSync(path.join(here,'overlay/bin/data/core/main.lua'),'utf8');assert.match(main,/ui.registry_text\("item", ip.id, "base_game", "firstmsg", ip.firstmsg\)/);
});
test('migration accounting is reproducible and separates original, browser, adapter and unshipped scopes',()=>{
 const plan=buildMigrationPlan();assert.deepEqual(plan,JSON.parse(readFileSync(path.join(here,'migration-plan.json'),'utf8')));
 assert.equal(plan.counts.reviewedMessageCalls+plan.counts.pendingMessageCalls,540);assert.equal(plan.counts.catalogDomains.browserUi,67);
 assert.equal(plan.counts.pendingByDisposition['debug-module-not-in-production-asset-pack'],9);assert.equal(plan.counts.pendingByDisposition['bundled-module-separate-overlay'],1);
 assert.equal(plan.fullGameLocalizationComplete,false);assert.equal(Object.values(plan.counts.catalogDomains).reduce((a,b)=>a+b,0),Object.keys(en).length);
});
test('complete authored Pascal views preserve exact original formats, controls and indexed English constants',()=>{
 const checked=verifyPascalViewTranslations(root,{manifest:{patches:[]}});assert.equal(checked.reviewedSites,262);assert.equal(checked.semanticIds,243);assert.equal(checked.formatSites,18);assert.equal(checked.sourceFiles,13);
 for(const [f,helper,constant]of [['drlassemblyview','DRLViewAssemblyTier',"TypeName : array[0..2] of string = ('Basic','Advanced','Master')"],['dfhof','DRLViewBadgeTier',"BadgeLevelName : array[1..6] of string = (' Bronze ',' Silver ','  Gold  ','Platinum','Diamond ','Angelic ')"]]){
  const output=readFileSync(path.join(here,'overlay/src',f+'.pas'),'utf8');assert.ok(output.includes(`function ${helper}(`));assert.ok(output.includes(constant));
 }
 const hud=readFileSync(path.join(here,'overlay/src/drlio.pas'),'utf8');assert.match(hud,/VTIG_Length\( iDesc \)/);
 assert.equal(ja['view.hud.percent-health-labels'],'体力:        経験   /      武:');assert.equal(ja['view.hud.health-labels'],'体力:          経験        武:');
});
test('all active challenge display fields are reviewed while current requirements and identity ratings stay original',()=>{
 const checked=verifyChallengeFields(root);assert.equal(checked.outputFields.length,67);
 const d=JSON.parse(readFileSync(path.join(here,'registration-term-catalog.json'),'utf8'));assert.equal(d.metadata.filter(r=>r.category==='challenge').length,15);
 for(const r of d.metadata.filter(r=>r.category==='challenge'))for(const term of Object.values(r.fields))assert.equal(en[term.semanticId],term.english);
 assert.equal(d.pending.filter(r=>r.category==='challenge').length,0);
});
test('feeling presentation leaves native English state and saved bytes unchanged and uses an exact typed replay whitelist',()=>{
 const lua=readFileSync(path.join(here,'overlay/bin/data/core/ui.lua'),'utf8');assert.match(lua,/ui\.semantic_text\(record.semantic_id, record.english, record.parameters, true\)/);assert.match(lua,/level.feeling = level.feeling \.\. " " \.\. msg/);assert.match(lua,/ui\.repeat_semantic_feeling\(level.feeling\)/);
 const original=readFileSync(path.join(root,'src/dflevel.pas'),'utf8'),output=readFileSync(path.join(here,'overlay/src/dflevel.pas'),'utf8');
 for(const line of original.split(/\r?\n/).filter(s=>/FFeeling.*Stream|Stream.*FFeeling/.test(s)))assert.ok(output.includes(line));
 assert.ok(output.includes("FFeeling := GetString('welcome');"));
 const boundary=readFileSync(path.join(here,'drlsemantictext.pas'),'utf8');assert.match(boundary,/function DRLEnglishText/);assert.match(boundary,/RenderSemanticText\(aID, aEnglish, aParams, False\)/);
 const validator=readFileSync(path.join(here,'overlay/src/drlsemanticfeelcatalog.pas'),'utf8');assert.match(validator,/DRLSemanticFeelingValidator := @DRLValidateFeelingRequest/);assert.match(validator,/CFeelingTexts\[i\]\.English<>aEnglish/);assert.match(validator,/Exit\(False\)/);
 const unit=readFileSync(path.join(here,'drlsemanticfeelings.pas'),'utf8');assert.match(unit,/stream.Free/);assert.doesNotMatch(unit,/\bFFeeling\b|\bRandom\(/);
});
test('death presentation callback is translated separately from persisted result-description producers',()=>{
 const original=readFileSync(path.join(root,'bin/data/drl/main.lua'),'utf8'),output=readFileSync(path.join(here,'overlay/bin/data/drl/main.lua'),'utf8');
 assert.ok(output.includes('ui.semantic_text("message.death.visible"'));assert.ok(output.includes('ui.being_name(being, true, true)'));
 const a=original.indexOf('function drl.GetResultDescription'),b=original.indexOf('\nfunction ',a+1);assert.ok(a>=0);assert.ok(output.includes(original.slice(a,b<0?original.length:b)));
});
test('every original lexical candidate has a pinned and transparent disposition without scanner IDs becoming translations',()=>{
 const report=buildTextDispositions(),saved=JSON.parse(readFileSync(path.join(here,'text-dispositions.json'),'utf8'));assert.deepEqual(report,saved);
 assert.equal(report.counts.literalCandidates,13759);assert.equal(report.counts.documentNonemptyLines,5009);assert.equal(report.counts.dynamicProducerCandidates,753);assert.equal(report.counts.unscannedFiles,72);
 assert.equal(Object.values(report.counts.literalDispositions).reduce((a,b)=>a+b,0),13759);assert.ok(report.counts.literalDispositions['pending-ambiguous-literal-role-review']>0);assert.equal(report.fullGameLocalizationComplete,false);
 for(const r of [...report.literals,...report.documents,...report.dynamicSources,...report.unscannedFiles])assert.ok(report.reasons[r.disposition]);
});
test('every statically authored semantic reference in emitted source has canonical locale and parameter records',()=>{
 function walk(dir){for(const e of readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())walk(f);else if(/\.(?:pas|lua)$/.test(f)){
  const language=f.endsWith('.lua')?'lua':'pascal',ts=scanSource(readFileSync(f,'utf8'),language).tokens;
  for(let n=0;n<ts.length;n++)if(['DRLText','DRLEnglishText','semantic_text','semantic_feeling'].includes(ts[n].raw)&&ts[n+1]?.raw==='('&&ts[n+2]?.kind==='string'){
   const id=ts[n+2].value;
   if(['+','..'].includes(ts[n+3]?.raw)){assert.ok(id.endsWith('.')&&Object.keys(en).some(k=>k.startsWith(id)),`${f}: dynamic semantic prefix ${id}`);continue;}
   assert.ok(Object.hasOwn(en,id),`${f}: ${id}`);assert.ok(Object.hasOwn(ja,id));assert.ok(Object.hasOwn(manifest.parameters,id));
  }
 }} }
 walk(path.join(here,'overlay'));
});
test('all generated presentation units are UTF8 lexical sources and remain outside pristine upstream',()=>{
 for(const f of ['drlsemantictext','drlsemantichelp','drlsemanticregistry','drlsemanticfeelings','drlsemanticfeelcatalog','drlsemanticitemnames','drlsemanticitemcatalog','drlsemanticperks','drlsemanticviewterms','drlsemantichistory','drlsemantichistorycatalog']){
  const s=readFileSync(path.join(here,'overlay/src',f+'.pas'),'utf8');assert.equal(scanSource(s,'pascal').diagnostics.length,0,f);assert.match(s,new RegExp(`unit ${f};`,'i'));
 }
});
test('every semantic patch references a reviewed canonical ID rather than a Lua expression or scanner candidate',()=>{
 for(const p of manifest.patches)if(p.id!==null){assert.ok(Object.hasOwn(en,p.id),`${p.file}: ${p.id}`);assert.ok(Object.hasOwn(ja,p.id));assert.ok(Object.hasOwn(manifest.parameters,p.id));}
});
test('all executable original history producers preserve English and have guarded complete semantic projections',()=>{
 const checked=verifyHistoryPresentation(root,{manifest});assert.equal(checked.reviewedHistoryCalls,83);assert.equal(checked.luaHistoryCalls,81);assert.equal(checked.nativeHistoryCalls,2);assert.equal(checked.semanticIds,525);assert.equal(checked.templateCases,1050);assert.equal(checked.englishReconstructions,148);assert.equal(checked.nativeOrBrowserExecuted,false);
 assert.equal(semanticHistorySidecarSchema.maximumRecords,4096);assert.equal(semanticHistorySidecarSchema.maximumJSONBytes,1048576);
 const io=readFileSync(path.join(here,'overlay/src/drlio.pas'),'utf8');assert.match(io,/DRLSemanticHistorySource := @DRLReadOriginalHistory/);assert.match(io,/DRLSemanticHistoryCurrentSource := @DRLReadCurrentOriginalHistory/);assert.match(io,/aIndex > Int64\(Count\)/);assert.match(io,/VarIsStr\(Value\)/);assert.match(io,/const lua_ui_lib : array\[0\.\.31\]/);
 assert.match(io,/name : 'remember_semantic_history'; func : @lua_ui_remember_semantic_history/);assert.match(io,/name : 'presentation_history'; func : @lua_ui_presentation_history/);
});
test('all 72 unrecognized original files have byte hashes, actual formats and explicit asset/text limitations',()=>{
 const report=buildTextDispositions();assert.equal(report.unscannedFiles.length,72);assert.equal(report.binaryAudit.currentBrowserPackedUnrecognizedFiles,0);
 for(const f of report.unscannedFiles){assert.match(f.sha256,/^[a-f0-9]{64}$/);assert.ok(f.actualFormat);assert.ok(f.originalProductionScope);assert.ok(f.textAudit);}
 const roles=report.literalRoleReview;assert.ok(roles.counts.adjudicated>2000);assert.ok(roles.counts.pendingUnresolved>0);for(const r of roles.adjudications){assert.equal(r.translated,false);assert.equal(r.originalDomainModified,false);assert.ok(r.sourceContextGuard.sha256);}
});
test('every emitted Pascal unit avoids interface/implementation duplicate dependencies',()=>{
 const report=auditPascalUses();assert.ok(report.dependencies.some(x=>x.file==='dfbeing.pas'));assert.deepEqual(report.duplicates,[]);
 const fixture=pascalUses('unit fixture; interface uses Alpha; { uses Hidden; } implementation uses alpha, Beta; end.');
 assert.equal(fixture.interface[0].name,'alpha');assert.equal(fixture.implementation[0].name,'alpha');assert.equal(fixture.implementation.length,2);
});

test('generated feeling and history parameter contracts preserve the Pascal enum type',()=>{
 for(const unit of ['drlsemanticfeelcatalog','drlsemantichistorycatalog']){
  const source=readFileSync(path.join(here,'overlay/src',unit+'.pas'),'utf8');
  assert.match(source,/Kind:\s*TDRLTextParamKind;/);
  assert.doesNotMatch(source,/Kind:\s*(?:Byte|Integer|LongInt);/);
  assert.doesNotMatch(source,/\bKind:\s*[01](?:\)|;)/);
  assert.match(source,/Kind:DRL_TEXT_INTEGER/);
 }
 const history=readFileSync(path.join(here,'overlay/src/drlsemantichistorycatalog.pas'),'utf8');
 assert.match(history,/Kind:DRL_TEXT_STRING/);
});

test('all reviewed translated padding calls use the column-safe adapter without touching domain producers',()=>{
 const report=JSON.parse(readFileSync(path.join(here,'padding-sites.json'),'utf8'));
 assert.equal(report.counts.originalCalls,80);assert.equal(report.counts.translatedOrMixed,68);
 assert.equal(report.counts.alreadySafe,4);assert.equal(report.counts.adapterCalls,66);
 assert.equal(report.counts.addedPaddingPatches,61);assert.equal(report.counts.embeddedAdapterCalls,5);
 assert.equal(report.counts.retainedAsciiOrEmpty,10);assert.equal(report.domainFieldsAndCatalogsUnchanged,true);
 let originalCalls=0,adaptedCalls=0,retainedCalls=0;
 for(const [f,pin]of Object.entries(report.sources)){
  const original=readFileSync(path.join(root,f));assert.equal(sha256(original),pin.sha256);
  originalCalls+=paddingCalls(original.toString('utf8')).length;
  const output=readFileSync(path.join(here,'overlay',f),'utf8'),calls=paddingCalls(output);
  adaptedCalls+=calls.filter(c=>c.callee==='VTIG_Padded').length;retainedCalls+=calls.filter(c=>c.callee==='Padded').length;
  for(const r of report.records.filter(r=>r.file===f&&r.disposition==='retained-original-ascii-padding'))assert.ok(output.includes(r.original));
 }
 assert.equal(originalCalls,80);assert.equal(adaptedCalls,67);assert.equal(retainedCalls,10);
 const hof=readFileSync(path.join(here,'overlay/src/dfhof.pas'),'utf8');
 for(const fragment of ["iName  := iElement.GetAttribute('name');","iKill  := iElement.GetAttribute('killed');","iScoreEntry.SetAttribute('killed', VS );"])assert.ok(hof.includes(fragment));
 for(const expression of ['GetDiffScore(iDiffID)','GetDiffDeaths(iDiffID)','GetDiffKills(iDiffID)'])assert.ok(hof.includes('VTIG_Padded('+expression));
 const mutated=readFileSync(path.join(root,'src/dfhof.pas'),'utf8').replace('Padded(iString,40)','Padded(iString,41)');
 assert.throws(()=>curatePaddingSites({file:f=>f==='src/dfhof.pas'?mutated:readFileSync(path.join(root,f),'utf8'),patches:[]}),/Padding source hash changed: src\/dfhof\.pas/);
});

test('inventory presentation clips by columns in the browser and retains the original native branch',()=>{
 const report=JSON.parse(readFileSync(path.join(here,'padding-sites.json'),'utf8')),output=readFileSync(path.join(here,'overlay/src/drlplayerview.pas'),'utf8');
 assert.equal(report.clip.browserOnly,true);assert.equal(report.clip.nativeBranchUnchanged,true);
 assert.ok(output.includes('iEntry.Name  := aItem.PresentationDescription;'));
 assert.ok(output.includes(report.clip.replacement));
 assert.match(report.clip.replacement,/\{\$IFDEF DRL_WASM\}[\s\S]*VTIG_Length\( iEntry\.Name \) > 47[\s\S]*VTIG_Padded\(iEntry\.Name, 47\);[\s\S]*\{\$ELSE\}/);
 assert.ok(report.clip.replacement.includes(report.clip.original));
 assert.doesNotMatch(report.clip.replacement,/\b(?:Random|Roll|GetName|SetName|AddPerk|RemovePerk)\b/);
});

test('next runtime producers preserve exact English values, typed versions, newlines and engine controls',()=>{
 const report=JSON.parse(readFileSync(path.join(here,'runtime-path-sites.json'),'utf8'));
 assert.equal(report.entries.length,17);assert.equal(report.projections.length,3);
 assert.deepEqual(report.counts,{newCatalogIds:17,targetTitles:5,startupGetters:4,tutorialHints:8,presentationProjections:3,existingSlotIds:5,addedProducerPatches:19,amendedExistingSemanticPatches:1,helperPatches:1});
 for(const [f,pin]of Object.entries(runtimePathSourcePins))assert.equal(sha256(readFileSync(path.join(root,f))),pin);
 for(const r of report.entries){
  const source=readFileSync(path.join(root,r.file),'utf8');
  assert.equal(source.slice(r.start,r.end),r.original);assert.equal(sha256(Buffer.from(r.original)),r.originalExpressionSha256);
  assert.equal(en[r.id],r.english);assert.equal(ja[r.id],r.japanese);assert.deepEqual(manifest.parameters[r.id],r.parameters);
  const p=manifest.patches.filter(p=>p.file===r.file&&p.start===r.start&&p.end===r.end);assert.equal(p.length,1);assert.equal(p[0].replacement,r.replacement);
  const ts=scanSource(r.original,r.file.endsWith('.lua')?'lua':'pascal').tokens;
  for(const version of ['0.10.11a','external-version-identity']){
   const params=r.version?{version}:{};
   const originalValue=r.version?ts[0].value+version+ts[4].value:ts[0].value;
   assert.equal(render(en,manifest.parameters,r.id,params),originalValue);
  }
  const control=s=>Array.from(s.matchAll(/\{\$[^{}]+\}/g),x=>x[0]).sort();
  assert.deepEqual(control(r.english),control(r.japanese));
  const styles=s=>Array.from(s.replace(/\{\{[a-z][a-z0-9_]*\}\}/g,'').matchAll(/\{([!a-zA-Z])/g),x=>x[1]).sort();
  assert.deepEqual(styles(r.english),styles(r.japanese));
  assert.equal(r.english.endsWith('\n'),r.japanese.endsWith('\n'));
 }
 for(const id of ['startup.logo-text','startup.first-run'])assert.ok(en[id].endsWith('\n')&&ja[id].endsWith('\n'));
 for(const id of ['startup.motd','startup.logo-box'])assert.ok(!en[id].endsWith('\n')&&!ja[id].endsWith('\n'));
 assert.equal(ja['startup.first-run'].includes('DRLを初めて'),true);
});

test('target and tutorial title migration leaves targeting decisions and ordered hint branches intact',()=>{
 const report=JSON.parse(readFileSync(path.join(here,'runtime-path-sites.json'),'utf8'));
 for(const f of ['src/drlbase.pas','bin/data/drl/levels/intro.lua']){
  const original=readFileSync(path.join(root,f)),prior=manifest.patches.filter(p=>p.file===f&&p.kind!=='semantic-runtime-path');
  const after=applyPatches(original,manifest.sources[f],manifest.patches.filter(p=>p.file===f));
  const before=applyPatches(original,manifest.sources[f],prior);let restored=after;
  for(const r of report.entries.filter(r=>r.file===f)){
   assert.equal(restored.split(r.replacement).length,2);restored=restored.replace(r.replacement,r.original);
   assert.doesNotMatch(r.replacement,/\b(?:random|visual_random|HandleCommand|OnApply|SetName)\b/i);
  }
  assert.equal(restored,before);
 }
 const targets=report.entries.filter(r=>r.role==='target-title');assert.equal(targets.length,5);
 const chain=targets.filter(r=>r.id.startsWith('view.target.chain.'));assert.equal(chain.length,3);
 assert.deepEqual(chain.map(r=>r.english.match(/\{([GYR])/)[1]),['G','Y','R']);
 const base=readFileSync(path.join(here,'overlay/src/drlbase.pas'),'utf8');
 for(const literal of ["iFireTitle  := '';","else begin iFireTitle := ''; iTarget := Player.Position; end;","if iFireTitle <> '' then","if aAlt then iCommand := COMMAND_ALTFIRE;"])assert.ok(base.includes(literal));
 const intro=readFileSync(path.join(here,'overlay/bin/data/drl/levels/intro.lua'),'utf8');
 assert.equal((intro.match(/ui\.set_hint\(""\)/g)??[]).length,2);
 assert.equal((intro.match(/ui\.set_hint\(ui\.semantic_text\("message\.tutorial\.intro\./g)??[]).length,8);
});

test('startup localization preserves logo art, versions, contributor identities and English custom fields',()=>{
 const original=readFileSync(path.join(root,'bin/data/drl/main.lua'),'utf8'),output=readFileSync(path.join(here,'overlay/bin/data/drl/main.lua'),'utf8');
 function block(source,name){const start=source.indexOf('function drl.'+name+'('),end=source.indexOf('\nfunction ',start+1);assert.ok(start>=0);return source.slice(start,end<0?source.length:end);}
 for(const name of ['GetLogoTexture','GetRandomName','GetQuitMessage'])assert.equal(block(output,name),block(original,name));
 const menuOriginal=readFileSync(path.join(root,'src/drlmainmenuview.pas'),'utf8'),menuOutput=readFileSync(path.join(here,'overlay/src/drlmainmenuview.pas'),'utf8');
 const logoArt=s=>s.slice(s.indexOf('procedure TMainMenuView.RenderASCIILogo;'));
 assert.ok(menuOriginal.includes('procedure TMainMenuView.RenderASCIILogo;'));assert.equal(logoArt(menuOutput),logoArt(menuOriginal));
 for(const [id,values]of [
  ['startup.logo-box',['Kornel Kisielewicz','Derek Yu','Lukasz Sliwinski']],
  ['startup.logo-text',['tehtmi','Game Hunter','shark20061','add','brisbang','Sonic Clang','Simon Volpert','Per Kristian Risvik','version.txt','facebook.com/ChaosForge','x.com/chaosforge_org','discord.gg/jupiterhell']],
  ['startup.first-run',['D**m the Roguelike','https://drl.chaosforge.org/','http://discord.gg/jupiterhell','http://forum.chaosforge.org/','@chaosforge_org','@epyoncf']],
  ['startup.motd',['jupiterhellclassic.com']]
 ])for(const value of values)assert.ok(en[id].includes(value)&&ja[id].includes(value));
 assert.equal((block(output,'GetLogoBox').match(/value=VERSION_MODULE/g)??[]).length,1);
 assert.equal((block(output,'GetLogoText').match(/value=VERSION_ENGINE/g)??[]).length,1);
});

test('equipment, feeling and scroll-swap use typed guarded projections without changing domain producers',()=>{
 const report=JSON.parse(readFileSync(path.join(here,'runtime-path-sites.json'),'utf8'));
 const source=readFileSync(path.join(here,'overlay/src/drlplayerview.pas'),'utf8');
 assert.ok(source.includes('iEntry.Name  := DRLViewSlotName(iSlot, SlotName(iSlot));'));
 assert.ok(source.includes("DRLStringParam('feeling', DRLRepeatSemanticFeeling(DRL.Level.Feeling))"));
 assert.equal((source.match(/function DRLViewSlotName\(/g)??[]).length,1);
 for(const [slot,id,english]of equipmentSlotTerms){
  assert.equal(en[id],english);assert.deepEqual(manifest.parameters[id],{});
  assert.ok(report.slotHelper.includes(`${slot}: if aEnglish = '${english}' then`));
  assert.ok(report.slotHelper.includes(`Exit(DRLText('${id}', aEnglish));`));
 }
 assert.ok(report.slotHelper.includes('Exit(aEnglish);'));
 assert.doesNotMatch(report.slotHelper,/\b(?:Random|SlotName|SetName|Assign|WriteToStream)\b/);
 const feelingView=JSON.parse(readFileSync(path.join(here,'view-sites.json'),'utf8')).records.find(r=>r.id==='view.level.feeling');
 assert.equal(feelingView.bindings[0].originalExpression,'DRL.Level.Feeling');
 assert.equal(feelingView.bindings[0].presentationExpression,'DRLRepeatSemanticFeeling(DRL.Level.Feeling)');
 assert.deepEqual(feelingView.englishReconstruction.argumentExpressions,['DRL.Level.Feeling']);
 assert.ok(readFileSync(path.join(here,'overlay/src/drlhudviews.pas'),'utf8').includes('IO.HintOverlay := FArray[ FIndex ].PresentationDescription;'));
 const originalData=readFileSync(path.join(root,'src/dfdata.pas'),'utf8'),outputData=readFileSync(path.join(here,'overlay/src/dfdata.pas'),'utf8');
 const slotBody=s=>s.slice(s.indexOf('function SlotName',s.indexOf('implementation')),s.indexOf('function DamageTypeName',s.indexOf('implementation')));
 assert.equal(slotBody(outputData),slotBody(originalData));
 for(const r of report.projections)assert.doesNotMatch(r.replacement,/DRL\.Level\.Feeling\s*:=|\biItem\.Name\s*:=|\bRandom\b|WriteToStream/);
});

test('runtime-path authoring rejects altered source pins and changed existing semantic parent contracts',()=>{
 const report=JSON.parse(readFileSync(path.join(here,'runtime-path-sites.json'),'utf8'));
 const originalFeeling="DRLText('view.level.feeling', '  Level feel   : {!{{feeling}}}', [DRLStringParam('feeling', DRL.Level.Feeling)])";
 function baseline(){return structuredClone(manifest.patches.filter(p=>!['semantic-runtime-path','runtime-path-projection','runtime-path-enum-helper'].includes(p.kind))).map(p=>p.id==='view.level.feeling'?{...p,replacement:originalFeeling}:p);}
 const file=f=>readFileSync(path.join(root,f),'utf8');
 for(const f of Object.keys(runtimePathSourcePins))assert.throws(()=>curateRuntimePathSites({file:other=>file(other)+(other===f?'\n':''),catalog:()=>{},patches:baseline()}),/Runtime-path source hash changed/);
 const wrong=baseline();wrong.find(p=>p.id==='view.level.feeling').replacement+=' ';
 assert.throws(()=>curateRuntimePathSites({file,catalog:()=>{},patches:wrong}),/Runtime character feeling semantic parent changed/);
 const catalog={};const rebuilt=curateRuntimePathSites({file,catalog:(id,english,japanese,parameters)=>catalog[id]={english,japanese,parameters},patches:baseline()});
 assert.deepEqual(rebuilt.entries,report.entries);assert.deepEqual(rebuilt.projections,report.projections);
 assert.equal(Object.keys(catalog).length,17);
});

test('modified GPL upstream sources carry deterministic dated comments without changing original headers',()=>{
 const report=JSON.parse(readFileSync(path.join(here,'modification-notices.json'),'utf8'));
 assert.equal(report.license,'GPL-2.0');assert.equal(report.requirement,'section 2(a)');assert.equal(report.date,'2026-10-02');
 assert.equal(report.modifiedSourceFiles,72);assert.equal(report.records.length,72);assert.equal(report.pristineUpstreamChanged,false);
 for(const [f,pin]of Object.entries(manifest.sources)){
  const original=readFileSync(path.join(root,f)),source=original.toString('utf8'),ps=manifest.patches.filter(p=>p.file===f),notice=ps.filter(p=>p.kind==='dated-modification-notice');
  assert.equal(sha256(original),pin.sha256);
  const rawTransform=applyPatches(original,pin,ps.filter(p=>p.kind!=='dated-modification-notice'));
  const output=readFileSync(path.join(here,'overlay',f),'utf8');
  assert.equal(output,applyPatches(original,pin,ps));
  if(rawTransform===source){assert.equal(notice.length,0);assert.equal(output,source);continue;}
  assert.equal(notice.length,1);assert.equal(notice[0].original,'');assert.equal(notice[0].start,source.charCodeAt(0)===0xfeff?1:0);
  assert.equal(output.split(modificationNoticeText).length,2);
  assert.equal(output.replace(notice[0].replacement,''),rawTransform);
  assert.ok(f.endsWith('.pas')?notice[0].replacement.startsWith('{ '):notice[0].replacement.startsWith('-- '));
 }
 const fakeFile=f=>f.endsWith('.pas')?'unit probe; interface implementation end.\r\n':'return 1\n';
 const fixturePatches=[{file:'probe.pas',start:5,end:10,original:'probe',replacement:'adapted'},{file:'probe.lua',start:7,end:8,original:'1',replacement:'2'},{file:'unchanged.lua',start:7,end:8,original:'1',replacement:'1'}];
 const fixture=curateModificationNotices({file:fakeFile,patches:fixturePatches});assert.equal(fixture.records.length,2);
 assert.ok(fixture.records.find(r=>r.file==='probe.pas').replacement.endsWith('\r\n'));assert.ok(fixture.records.find(r=>r.file==='probe.lua').replacement.endsWith('\n'));
 assert.equal(fixture.records.some(r=>r.file==='unchanged.lua'),false);
 assert.throws(()=>curateModificationNotices({file:fakeFile,patches:fixturePatches}),/Duplicate dated modification notice/);
});
