/** Executable accounting of reviewed presentation sites; never executes original Lua. */
import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const read=f=>JSON.parse(readFileSync(path.join(here,f),'utf8'));
const group=(rows,key)=>Object.fromEntries([...new Set(rows.map(key))].sort().map(k=>[k,rows.filter(r=>key(r)===k).length]));
export function buildMigrationPlan(){
 const inventory=read('message-inventory.json'),sites=read('gameplay-sites.json'),registry=read('registration-term-catalog.json'),catalog=read('en.json'),manifest=read('manifest.json');
 const reviewed=new Map(sites.reviewed.map(r=>[r.key,r]));
 if(reviewed.size!==sites.reviewed.length)throw Error('Duplicate reviewed call key');
 for(const r of reviewed.values())if(!inventory.calls.some(c=>c.key===r.key))throw Error(`Unknown reviewed call ${r.key}`);
 const pending=inventory.calls.filter(c=>!reviewed.has(c.key)).map(c=>{
  let disposition='migrate-complete-typed-event',reason='Original literal or composed event still needs a reviewed semantic template and typed presentation values.';
  if(c.file==='bin/godmode.lua'){disposition='debug-module-not-in-production-asset-pack';reason='Original developer godmode messages are inventoried separately; preserve disabled/debug-only production disposition.';}
  else if(c.file.startsWith('bin/modules/')){disposition='bundled-module-separate-overlay';reason='Bundled classic module has its own scope and must be translated before being offered.';}
  else if(c.language==='lua'&&c.classification==='runtime_value_or_dispatch'){disposition='localize-reviewed-producer-retain-generic-dispatch';reason='Generic text dispatcher must preserve custom modules; enumerate and localize finite original producers instead of matching rendered English.';}
  else if(c.language==='pascal'&&['aText','aPlayerText','aBeingText','State.ToString'].some(v=>c.original.includes(v))){disposition='retained-legacy-dispatch-with-reviewed-typed-callers';reason='Original generic callback/signature remains compatible. Only reviewed source callers use the separate typed semantic seam; custom callers may retain original English.';}
  else if(c.file==='src/dfbeing.pas'&&c.line===2300){disposition='retained-dispatch-of-reviewed-death-producer';reason='Original death dispatcher remains unchanged. Both original drl.GetDeathMessage presentation branches have source-guarded semantic IDs; persistent result-description strings remain English.';}
  return {key:c.key,file:c.file,line:c.line,classification:c.classification,language:c.language,sourceSha256:inventory.sourceFiles[c.file].sha256,original:c.original,disposition,reason};
 });
 const ids=Object.keys(catalog),registryDispositions=registry.pending.map(r=>{
  const reviewed=registry.reviewedNonliteralFieldBranches.find(x=>x.registryId===r.registryId&&r.field==='description');
  const implemented=reviewed&&reviewed.branches.every(b=>manifest.patches.some(p=>p.id===b.id&&p.file===r.file));
  return{...r,disposition:implemented?'reviewed-complete-typed-function-branches':'pending-field-role-or-template-review',...(implemented?{semanticIds:reviewed.branches.map(b=>b.id)}:{}),reason:implemented?'Original field is a function, not a literal. All original branches are source-guarded complete semantic templates; requirements and domain IDs remain unchanged.':r.reason};
 });
 const domains={originalPresentation:ids.filter(id=>!id.startsWith('game.')&&!id.startsWith('error.lua.adapter.')&&!id.startsWith('error.lua.platform.')&&!id.startsWith('error.text.lua.')).length,browserUi:ids.filter(id=>id.startsWith('game.')).length,packedLuaAbiDiagnostics:ids.filter(id=>id.startsWith('error.lua.adapter.')).length,luaSemanticAdapterDiagnostics:ids.filter(id=>id.startsWith('error.text.lua.')).length,cPlatformDiagnostics:ids.filter(id=>id.startsWith('error.lua.platform.')).length};
 if(Object.values(domains).reduce((a,b)=>a+b,0)!==ids.length)throw Error('Catalog domain accounting mismatch');
 return {schema:1,sourceCommit:manifest.sourceCommit,fullGameLocalizationComplete:false,counts:{catalogIds:ids.length,catalogDomains:domains,messageCalls:inventory.calls.length,productionMessageCalls:inventory.calls.length-pending.filter(r=>['debug-module-not-in-production-asset-pack','bundled-module-separate-overlay'].includes(r.disposition)).length,excludedUnshippedMessageCalls:pending.filter(r=>['debug-module-not-in-production-asset-pack','bundled-module-separate-overlay'].includes(r.disposition)).length,firstArgumentLiteralBearingCalls:inventory.counts.literalBearingCalls,reviewedMessageCalls:reviewed.size,pendingMessageCalls:pending.length,productionPendingMessageCalls:pending.filter(r=>!['debug-module-not-in-production-asset-pack','bundled-module-separate-overlay'].includes(r.disposition)).length,reviewedByLanguage:group(inventory.calls.filter(c=>reviewed.has(c.key)),c=>c.language),pendingByLanguage:group(pending,c=>c.language),pendingByDisposition:group(pending,c=>c.disposition),registryFields:Object.keys(registry.englishCatalog).length,registryEntries:registry.metadata.length,registryPendingCandidates:registry.pending.length,registryUntranslatedFieldCandidates:registryDispositions.filter(r=>r.disposition==='pending-field-role-or-template-review').length,registryCandidateDispositions:group(registryDispositions,r=>r.disposition),registryPendingByCategory:group(registry.pending,r=>r.category)},pendingMessageCalls:pending,registryPendingCandidates:registryDispositions,
  generatedNamePlan:[
   {event:'core/main.lua:53,58 corpse generation',internalId:'beingId + corpse',plan:'23 original generated corpse names have source-guarded metadata; retain English names/internal IDs and resolve display-only field consumers.',status:'source-guarded-metadata-tested-runtime-pending'},
   {event:'core/main.lua:304,306 natural weapon generation',internalId:'nat_ + beingId',plan:'21 original natural-attack names and three hit descriptions have source-guarded metadata. Resolve item presentation using actual generated IDs and English guard.',status:'source-guarded-metadata-tested-runtime-pending'},
   {event:'core/main.lua register_being default plural',internalId:'unchanged being ID',plan:'33 default and seven explicit plural fields resolve via being registry; original Lua name_plural stays English.',status:'source-overlay-tested-runtime-pending'},
   {event:'core/item.lua item:apply_mod_array and DRL assembly OnApply hooks',internalId:'original item ID and persistent QWord UID',plan:'44 original assembly name assignments append presentation-only events. 297 finite rules including 252 schematic variants use prototype/name/UID guards and a bounded versioned JSON sidecar; both nuclear BFG 9000 comparisons remain English.',status:'source-overlay-and-sidecar-oracle-tested-native-runtime-pending'},
   {event:'core/item.lua item:overcharge and unique weapon mode hooks',internalId:'original item ID and persistent QWord UID',plan:'Original overcharge assignment appends a guarded presentation event; all six schematic producers capture assembly IDs. Three unique weapon mode groups change statistics only and have no name renames.',status:'source-overlay-and-sidecar-oracle-tested-native-runtime-pending'},
   {event:'typed Lua message noun parameters after item renames',internalId:'original item object and original English Name',plan:'Several authored Lua message parameters still resolve the original prototype name using registry English guards. Renamed Name values fall back to English; connect the structured item-name sidecar through a narrow explicit item-object presentation callback.',status:'pending-explicit-item-object-presentation-seam'},
   {event:'stored historical item names after arbitrary aspect chains',internalId:'original history index and original English item prototype',plan:'83 executable history producers preserve English storage and capture typed event records. Finite original assembly/overcharge history names project contextually; arbitrary deeper chains require immutable captured aspect-chain provenance and retain English until then.',status:'finite-source-projection-tested-deeper-aspect-chain-pending'}
  ],
  milestones:[
   {name:'settings, main menu, input metadata and eight original help bodies',status:'source-overlay-tested',validation:'All exact source offsets, source hashes, original English fallback, controls and EN/JA contracts verified with lightweight Node tests.'},
   {name:'original registry names and baseline descriptions',status:'source-overlay-tested-partial',validation:'Exact category/ID/scope/field/English guards; Pascal display-only methods keep original published Name/Desc and mechanics-sensitive comparisons.'},
   {name:'original gameplay message migration',status:'in-progress',validation:'Reviewed complete static and typed events are counted by original call key. Pending original calls remain explicitly listed.'},
   {name:'registry fields, structured names, statistics/mortem/awards and view text',status:'source-overlay-tested-full-inventory-still-pending',validation:'Reviewed registry fields, original mortem templates, archived score projection, view sites and 83 history producers are implemented. Broader original literal/producer roles and historical arbitrary item chains remain explicitly pending.'},
   {name:'native full-unit compile and real browser integration',status:'parent-integration-required',validation:'Lightweight source tests do not establish full native compilation, Rust callback connection, CJK layout, save/resume or actual game-flow behavior.'}
  ]};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const plan=buildMigrationPlan();writeFileSync(path.join(here,'migration-plan.json'),JSON.stringify(plan,null,2)+'\n');console.log(JSON.stringify(plan.counts));
}
