/** Bounded verification for authored localization boundary only; does not run DRL. */
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {sha256,generateOverlay} from './generate.mjs';
import {buildMigrationPlan} from './migration-plan.mjs';
import {buildTextDispositions} from './text-dispositions.mjs';
import {auditPascalUses} from './audit-pascal-uses.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.dirname(here);
const manifest=JSON.parse(readFileSync(path.join(here,'manifest.json'),'utf8'));
const previousVerification=JSON.parse(readFileSync(path.join(here,'verification.json'),'utf8'));
mkdirSync(path.join(here,'probe-build'),{recursive:true});mkdirSync(path.join(here,'tests-output'),{recursive:true});
function run(name,exe,args){
 const result=spawnSync(exe,args,{cwd:root,encoding:'utf8',timeout:60000,maxBuffer:2*1024*1024,windowsHide:true});
 const output=(result.stdout??'')+(result.stderr??'');writeFileSync(path.join(here,'tests-output',name+'.log'),output);
 if(result.error||result.status!==0)throw Error(`${name} failed: ${result.error?.message??output}`);
 return {status:result.status,output,command:[exe,...args]};
}
const generated=generateOverlay();
const dependencyAudit=auditPascalUses();writeFileSync(path.join(here,'pascal-uses-audit.json'),JSON.stringify(dependencyAudit,null,2)+'\n');
if(dependencyAudit.duplicates.length)throw Error('Duplicate emitted Pascal interface/implementation dependencies');
const migration=buildMigrationPlan();
writeFileSync(path.join(here,'migration-plan.json'),JSON.stringify(migration,null,2)+'\n');
const dispositions=buildTextDispositions();writeFileSync(path.join(here,'text-dispositions.json'),JSON.stringify(dispositions,null,2)+'\n');
writeFileSync(path.join(here,'literal-role-review.json'),JSON.stringify(dispositions.literalRoleReview,null,2)+'\n');
const tests=run('node-contracts',process.execPath,['--test','--test-reporter=tap','localization/localization.test.mjs']);
const testCount=Number(/^# pass (\d+)$/m.exec(tests.output)?.[1]);if(!testCount)throw Error('No executed Node test count');
const sidecarChecks=run('feeling-sidecar-oracle',process.execPath,['localization/feeling-sidecar-test.mjs']);
const sidecarResult=JSON.parse(sidecarChecks.output);if(!Number.isInteger(sidecarResult.passed)||sidecarResult.passed<=0)throw Error('No executed sidecar oracle checks');
const itemChecks=run('item-name-sidecar-oracle',process.execPath,['localization/item-name-sidecar-test.mjs']);const itemResult=JSON.parse(itemChecks.output);if(!Number.isInteger(itemResult.passed)||itemResult.passed<=0)throw Error('No executed item sidecar checks');
const lightweight=process.argv.includes('--no-native');
const compiler=path.join(root,'toolchain/fpc-win64-snapshot/bin/i386-win32/ppcrossx64.exe');
const build=path.join(here,'probe-build');
let native={status:'not run in this lightweight verification; earlier boundary-only results retained separately'};
if(!lightweight){
 const compiled=run('pascal-compile',compiler,['-n',`-Fu${path.join(root,'toolchain/fpc-win64-snapshot/units/x86_64-win64/rtl')}`,`-Fu${here}`,`-FU${build}`,`-FE${build}`,'-osemantic-probe.exe',path.join(here,'semantic-probe.pas')]);
 const executed=run('pascal-run',path.join(build,'semantic-probe.exe'),[]);
 const nativeCount=Number(/Semantic Pascal checks: (\d+)/.exec(executed.output)?.[1]);if(!nativeCount)throw Error('No executed native check count');
 native={passed:nativeCount,failed:0,compiler:'Free Pascal 3.3.1 official 2026-09-22 win64 snapshot',compileCommand:compiled.command,runCommand:executed.command,executableSha256:sha256(readFileSync(path.join(build,'semantic-probe.exe')))};
}
const report={schema:1,sourceCommit:manifest.sourceCommit,fullGameLocalizationComplete:false,catalogIds:generated.catalogIds,catalogDomains:migration.counts.catalogDomains,reusedInputIds:173,newOriginalPresentationIds:migration.counts.catalogDomains.originalPresentation-173,patchedFiles:generated.sourceFiles,patches:generated.patches,directSemanticSites:generated.sourceSites,help:generated.help,registry:generated.registry,messageCoverage:migration.counts,generatedFullUnitsCompiled:false,nodeTests:{passed:testCount,failed:0,command:tests.command},authoredPascalBoundaryChecks:native,fullDRLExecuted:false,browserResolverConnected:false,files:{}};
report.feelings=generated.feelings;report.textCandidateDispositions=dispositions.counts;report.feelingSidecarOracle={passed:sidecarResult.passed,failed:0,command:sidecarChecks.command,nativePascalExecution:false};
report.itemNames=generated.itemNames;report.itemNameSidecarOracle={passed:itemResult.passed,failed:0,command:itemChecks.command,nativePascalExecution:false};
report.history=generated.history;report.literalRoleReview=dispositions.literalRoleReview.counts;report.binaryAudit=dispositions.binaryAudit;
report.pascalDependencyAudit={units:dependencyAudit.units,duplicateInterfaceImplementationUses:0,nativeCompilerExecuted:false};
const padding=JSON.parse(readFileSync(path.join(here,'padding-sites.json'),'utf8'));
report.presentationPadding={...padding.counts,sourceFiles:Object.keys(padding.sources).length,domainFieldsAndCatalogsUnchanged:true,nativeClipBranchPreserved:true,nativeAdapterRuntimeVerified:false};
const runtimePath=JSON.parse(readFileSync(path.join(here,'runtime-path-sites.json'),'utf8'));
report.nextRuntimePath={...runtimePath.counts,sourceFiles:Object.keys(runtimePath.sources).length,originalDomainFieldsAndSaveStringsPreserved:true,asciiLogoAndVersionValuesPreserved:true,nativeCompiled:false,browserExecuted:false};
const notices=JSON.parse(readFileSync(path.join(here,'modification-notices.json'),'utf8'));
report.licenseModificationNotices={license:notices.license,requirement:notices.requirement,date:notices.date,modifiedSourceFiles:notices.modifiedSourceFiles,pristineUpstreamChanged:false};
for(const f of ['en.json','ja.json','contract.json','manifest.json','drlsemantictext.pas','generate.mjs','render.mjs','semantic-probe.pas','localization.test.mjs','verify.mjs','help-bodies.mjs','help-catalog.json','registry-terms.mjs','registry-descriptions.mjs','registry-extra-fields.mjs','registry-story-fields.mjs','registry-awards.mjs','registry-perks-ranks.mjs','registry-challenges.mjs','registry-generated-fields.mjs','registry-sites.mjs','misc-registry-sites.mjs','registration-term-catalog.json','registry-sources.lock.json','item-semantic-methods.pas','being-semantic-methods.pas','gameplay-sites.mjs','gameplay-sites.json','message-inventory.mjs','message-inventory.json','lua-semantic-adapter.pas','lua-sites.mjs','lua-core-sites.mjs','lua-dynamic-sites.mjs','lua-dynamic-message-translations.mjs','lua-base-message-translations.mjs','lua-level-message-translations.mjs','pascal-view-translations.mjs','view-sites.mjs','view-sites.json','drlsemanticfeelings.pas','semantic-feeling-sites.mjs','feeling-sidecar-test.mjs','death-producer-sites.mjs','death-producer-sites.json','text-dispositions.mjs','text-dispositions.json','migration-plan.mjs','migration-plan.json'])report.files[f]={sha256:sha256(readFileSync(path.join(here,f)))};
for(const f of ['pascal-combat-translations.mjs','combat-sites.json','registry-display-sites.mjs','registry-display-sites.json','registry-display-integration.mjs','drlsemanticitemnames.pas','item-name-catalog.mjs','item-name-aspects.mjs','item-name-aspects.json','item-name-sidecar-test.mjs','trait-history-sites.mjs','mortem-translations.mjs','mortem-sites.json'])report.files[f]={sha256:sha256(readFileSync(path.join(here,f)))};
for(const f of ['history-presentation.mjs','drlsemantichistory.pas','history-sites.json','mortem-score-sites.json','literal-role-review.mjs','literal-role-review.json','unrecognized-files-audit.json'])report.files[f]={sha256:sha256(readFileSync(path.join(here,f)))};
for(const f of ['audit-pascal-uses.mjs','pascal-uses-audit.json'])report.files[f]={sha256:sha256(readFileSync(path.join(here,f)))};
for(const f of ['padding-sites.mjs','padding-sites.json'])report.files[f]={sha256:sha256(readFileSync(path.join(here,f)))};
for(const f of ['runtime-path-sites.mjs','runtime-path-sites.json'])report.files[f]={sha256:sha256(readFileSync(path.join(here,f)))};
for(const f of ['modification-notices.mjs','modification-notices.json'])report.files[f]={sha256:sha256(readFileSync(path.join(here,f)))};
report.files['browser-ui-overrides.mjs']={sha256:sha256(readFileSync(path.join(here,'browser-ui-overrides.mjs')))};
const localeRefresh=JSON.parse(readFileSync(path.join(here,'locale-refresh-sites.json'),'utf8'));
report.localeRefresh={...localeRefresh.counts,sourceFiles:Object.keys(localeRefresh.sources).length,rawOfficialHelpBytesRetained:true,inputBindingMapsRebuiltForLocale:false,actualNativeCompiled:false,actualBrowserLocaleRefreshVerified:false,remainingCachedViews:['main-menu startup and choices','inventory/equipment/traits/character','detail and assembly views','hints and targets','messages/plots/confirmations/choices/reports']};
for(const f of ['locale-refresh-sites.mjs','locale-refresh-sites.json','locale-refresh.test.mjs'])report.files[f]={sha256:sha256(readFileSync(path.join(here,f)))};
if(previousVerification.historyReaderBridge)report.historyReaderBridge=previousVerification.historyReaderBridge;
report.files['history-reader-stack.test.mjs']={sha256:sha256(readFileSync(path.join(here,'history-reader-stack.test.mjs')))};
writeFileSync(path.join(here,'verification.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({catalogIds:report.catalogIds,nodeTestsPassed:testCount,authoredPascalChecksPassed:native.passed??null,fullDRLExecuted:false}));
