// Source-reviewed roles, not new Rust ParameterKind variants or live producers.
export const SOURCE_COMMIT = '7b2efa5cea38e4d4d97dd0e63b28b9148623da59';
export const UPSTREAM = 'C:/Users/kit/gameme/jnethack/jrouge/cataclysm-dda/upstream/Cataclysm-DDA-' + SOURCE_COMMIT;
export const CONVERTED = {
  'cdda.character_creation.profession.requirement_completed': {
    parameter: 'achievement_name', kind: 'term', count: 1,
    function: 'assemble_profession_details', source: 'src/newcharacter.cpp', lines: [2264, 2277, 2281, 2282, 2283],
    argument: 'sorted_profs[cur_id]->get_requirement().value()->name()',
    identity: 'native required achievement_id and its currently loaded name definition binding',
    owner: 'achievement translation leaf; no username or assembled profession name',
    nativeWrapper: 'colorize(formatted message,c_green) + newline; the format itself also ends in newline',
  },
  'cdda.character_creation.scenario.requirement_completed': {
    parameter: 'achievement_name', kind: 'term', count: 1,
    function: 'assemble_scenario_details', source: 'src/newcharacter.cpp', lines: [3485, 3504, 3514, 3517, 3518],
    argument: 'scenRequirement.value()->name()',
    identity: 'native scenRequirement achievement_id and its currently loaded name definition binding',
    owner: 'achievement translation leaf; no username or assembled scenario name',
    nativeWrapper: 'colorize(formatted message,c_green) + newline; format has no trailing newline',
  },
  'cdda.core.fault.fault_blade_cracked.description': {
    parameter: 'item_type_name', kind: 'term', count: 1,
    function: 'item::get_fault_description', source: 'src/item.cpp', lines: [7804, 7806],
    argument: 'type->nname( 1 )', identity: 'the actual resolved base itype definition and its name binding',
    owner: 'base itype translation leaf, explicitly distinct from item::tname/variant/instance assembly',
    nativeWrapper: 'string_format(f_id.obj().description(),type->nname(1)); no wrapper markup added here',
  },
};
export const WITNESSES = {
  'src/newcharacter.cpp': ['static std::string assemble_profession_details(',
    String.raw`_( "Completed \"%s\"\n" )`, 'sorted_profs[cur_id]->get_requirement().value()->name()',
    'static std::string assemble_scenario_details(', String.raw`_( "Completed \"%s\"" )`,
    'scenRequirement.value()->name()'],
  'src/achievement.h': ['const translation &name() const {', 'return name_;', 'std::vector<std::pair<achievement_id, mod_id>> src;'],
  'src/achievement.cpp': ['void achievement::load(', 'mandatory( jo, was_loaded, "name", name_ );'],
  'src/string_formatter.h': ['is_translation = std::is_same_v<std::decay_t<T>, translation>',
    'return string_formatter_set_temp_buffer( sf, value.translated() );', 'return string_format( format.translated(),'],
  'src/translation.h': ['std::string translated( int num = 1 ) const;'],
  'src/translation.cpp': ['std::string translation::translated( const int num ) const'],
  'src/item.cpp': ['std::string item::get_fault_description( const fault_id &f_id ) const',
    'return string_format( f_id.obj().description(), type->nname( 1 ) );'],
  'src/fault.cpp': ['std::string fault::description() const', 'return description_.translated();',
    'mandatory( jo, was_loaded, "description", description_ );'],
  'src/itype.cpp': ['std::string itype::nname( unsigned int quantity ) const',
    'if( phase == phase_id::LIQUID )', 'quantity = 1;', 'return name.translated( quantity );'],
  'src/game.cpp': ['There appears to be a dangerous <color_red>%s</color> at your destination.',
    'danger_field.second.name()'],
  'src/field.h': ['std::string name() const {', 'return type.obj().get_name( intensity - 1 );'],
  'src/field_type.h': ['std::string get_name( int level = 0 ) const {', 'return get_intensity_level( level ).name.translated();'],
  'src/ranged.cpp': ['void target_ui::draw_controls_list( int text_y )',
    '[%s] to unload the %s after quitting.', '[%s] to keep the %s loaded after quitting.',
    'bound_key( "TOGGLE_UNLOAD_RAS_WEAPON" ).short_description()', 'relevant->tname()'],
  'src/mattack_actors.cpp': ['miss_msg_u', 'no_dmg_msg_u', 'hit_dmg_u',
    'z.name(), body_part_name_accusative( bp_id )', 'z.disp_name( false, true ) : _( "Something" )'],
  'src/monster.cpp': ['std::string monster::name( unsigned int quantity ) const',
    'return nickname;', 'unique monster name', 'fused mission monster'],
};
export function blockedOwnership(id) {
  if (id === 'cdda.game.movement.dangerous_field_named') return {
    class: 'rich-color-and-intensity-leaf-producer-required', source: 'src/game.cpp', lines: [14115, 14121, 14122],
    arguments: [{ position: 1, role: 'field_name', expression: 'danger_field.second.name()',
      owner: 'resolved field_type plus native intensity-1 level; field.h:67–68,field_type.h:242–243' }],
    reason: 'Red markup must remain structured; plain-text RawCatalog has no rich-text program consumer. Preserve already selected field/intensity identity.',
  };
  if (id.startsWith('cdda.ranged.aiming.action.')) return {
    class: 'keybinding-and-composite-item-name-required', source: 'src/ranged.cpp', lines: [3995, 4078, 4079, 4080, 4083, 4084, 4085],
    arguments: [{ position: 1, role: 'key_binding', expression: 'bound_key("TOGGLE_UNLOAD_RAS_WEAPON").short_description()',
      owner: 'exact native binding input type/key sequence/modifier/display policy; no current ParameterKind can express it' },
    { position: 2, role: 'weapon_display_name', expression: 'relevant->tname()',
      owner: 'recursive native item instance name assembly, variants/prefixes/contents/possibly user-provided names' }],
    reason: 'Neither an input key description nor assembled item name is a plain localized Term or arbitrary UserText.',
  };
  return {
    class: id.includes('.npc.') ? 'monster-display-name-and-receiver-substitution-required' : 'monster-display-name-required',
    source: 'src/mattack_actors.cpp', lines: [383, 394, 721, 722, 758, 760, 768, 770, 903, 905, 977, 981],
    arguments: [{ position: 1, role: 'attacker_display_name',
      expression: 'z.name() for uncanny dodge; call-time visible z.disp_name(false,true) or Something for normal dodge/armor; recomputed at on_damage for hit',
      owner: 'native monster leaf/nickname/unique/fused-name composition and exact visibility branch' }],
    evaluatedButUnusedArgument: 'position2:body_part_name_accusative(bp_id or selected damage body part); all six Android templates only reference position1',
    implicitNpcNameToken: id.includes('.npc.') ? '<npcname> expands with receiver virtual disp_name() after printf, for NPC or monster non-player branch; actual dispatch/visibility/logging must be preserved by future integration' : null,
    reason: 'Current Term resolves one zero-parameter leaf and cannot preserve the selected display-name program. Player-given monster nickname is a future UserText operand; unique/fused origins remain unaudited. NPC names/professions/snippets may already be localized. External names must remain verbatim.',
  };
}
// Independent targeted reader audit; originals stay untouched and unexecuted.
export const NATIVE_MESSAGE_READERS = {
  'src/creature.h': { sha256: 'e0945df61cfafe1aebef0b9b6b6d3d4cd35b1576bdbd07312b98f7938400aa8e',
    lines: [1100,1142], function: 'Creature::add_msg_player_or_npc variadic adapters',
    contract: 'Both candidate templates are formatted with the same forwarded arguments before virtual receiver dispatch; all six Android templates ignore evaluated bodypart arg2.' },
  'src/creature.cpp': { sha256: 'a485fd0025128cfb7708731560528aa59b7a9b64790f2cd42c0e668bbd05afdc',
    lines: [3408,3411,3495,3503], function: 'replace_with_npc_name / translation message adapter',
    contract: 'The NPC-name token expands after printf, using virtual disp_name and all-occurrences replacement; translation adapter translates both candidates.' },
  'src/character.cpp': { sha256: '6e67b293b21aacaa8bd8e4690672f4573840ef188a63420f1ead07b1cc4c655c',
    lines: [871,890,910,925,5711,5713], function: 'Character::disp_name/get_name/profession/add_msg_player_or_npc',
    contract: 'Character emits player branch; virtual NPC/monster overrides differ. play_name/name and profession composition have distinct ownership.' },
  'src/npc.cpp': { sha256: '63834f7cd24b873190bf162154bc7b7a8ceb906faa33eee277f3794c7689b41b',
    lines: [536,544,3190,3209,3948,3955], function: 'npc::load_npc_template/display_name/add_msg_player_or_npc',
    contract: 'NPC branch requires avatar-backed sees(map,*this), not attacker point visibility. Template name/profession may include translated leaves and SNIPPET expansion; no NPC-control exception found in this chain.' },
  'src/monster.cpp': { sha256: '1e97e552c5633a9cb8b79efa5e966b09dd3487999b29d55a3fcda4ebf5db8abc',
    lines: [706,725,759,765,3697,3711], function: 'monster::name/disp_name/add_msg_player_or_npc',
    contract: 'Nickname wins over unique/fused decoration; disp_name adds localized article/capitalization. Monster receiver can select non-player branch and expand NPC-name token.' },
  'src/monster.h': { sha256: '90db6d9385e833594c23624b2c95ddd8d84fe17aa9f7c7dbce52d1db38dd08cc',
    lines: [565,580,582], function: 'monster name ownership fields',
    contract: 'Nickname is expressly player-given; unique_name and mission_fused string origins are not established by this audit.' },
  'src/mtype.cpp': { sha256: 'c009cb60af5d66fb503d7e981a88b78948e2526cf60d2e6223996df4d46d8cca',
    lines: [341,343], function: 'mtype::nname', contract: 'Raw translation leaf only, preceding monster display-name composition.' },
  'src/output.cpp': { sha256: '3ca681eeda796f33a518ecf8a9ec8ea1de0d1d49130e52b84d02237a4637fa82',
    lines: [2681,2694], function: 'replace_substring', contract: 'Original true flag replaces all token occurrences; no replacement implementation is added by this slice.' },
  'src/messages.cpp': { sha256: 'dc74bc27ec31824ed7fdc88112f736a7d559ea94f7dc5f3041de5143356f7843',
    lines: [182,208,464,471], function: 'Messages::add_msg / message sink', contract: 'Empty/inactive/debug suppression, decoration, cooldown/coalescing/enqueue remain original; no new NPC-control mode is inferred.' },
  'src/game.cpp': { sha256: '197398412f600802c611045b0e1b63551fadf3653f4bff13f57ecca9f80e5af3',
    lines: [14463,14475], function: 'get_player_character/get_player_view/get_avatar', contract: 'All return g->u in this source; no controlled-NPC redirect is inferred.' },
};
