import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createCoreHost,createCoreStorage,canonicalFileTimes,ERRNO} from '../web/core-host.mjs';
const zero=()=>({atime:'0',mtime:'0',ctime:'0'}),max='18446744073709551615';
const digest=bytes=>createHash('sha256').update(Uint8Array.from(bytes)).digest('hex');
function database(initial){let value=initial;const db={createObjectStore(){},close(){},transaction(){const tx={};tx.objectStore=()=>({put(next){queueMicrotask(()=>{value=structuredClone(next);tx.oncomplete?.();});},get(){const req={};queueMicrotask(()=>{req.result=structuredClone(value);req.onsuccess?.();tx.oncomplete?.();});return req;}});return tx;}};return {change(fn){fn(value);},open(){const req={};queueMicrotask(()=>{req.result=db;req.onupgradeneeded?.();req.onsuccess?.();});return req;}};}
function abi(){const metadata=new Map([[3,zero()],[4,{atime:'7',mtime:'9',ctime:'11'}],[5,zero()]]),operations=[];let clocks=0;const platform=({operation:o})=>{operations.push(o);const fd=o.fd??(o.path==='user/file'?4:o.path==='asset'?5:99);if(!metadata.has(fd))return {filesystem:{errno:o.fd===undefined?ERRNO.NOENT:ERRNO.BADF,value:null}};let value=null;if(o.op.startsWith('stat'))value={kind:fd===3?'directory':'file',bytes:0,readonly:fd===5};else if(o.op.startsWith('get'))value={...metadata.get(fd)};else if(o.op.startsWith('set')){if(fd===5)return {filesystem:{errno:ERRNO.ROFS,value:null}};const old=metadata.get(fd);metadata.set(fd,{atime:o.atime??old.atime,mtime:o.mtime??old.mtime,ctime:o.ctime});}else throw Error('Unexpected timestamp fixture op '+o.op);return {filesystem:{errno:0,value}};};const memory=new WebAssembly.Memory({initial:1}),host=createCoreHost({platform,now:()=>{clocks++;return 27000;}});host.bind({memory});return {metadata,operations,memory,view:new DataView(memory.buffer),wasi:host.imports.wasi_snapshot_preview1,host,get clocks(){return clocks;}};}
function pathBytes(memory,text){const b=new TextEncoder().encode(text);new Uint8Array(memory.buffer,400,b.length).set(b);return b.length;}
test('timestamp ABI preserves u64 values and partial updates in native stat offsets',()=>{const a=abi();assert.equal(a.wasi.fd_filestat_set_times(4,BigInt(max),0n,1),0);assert.deepEqual(a.metadata.get(4),{atime:max,mtime:'9',ctime:'27000000000'});assert.equal(a.wasi.fd_filestat_get(4,800),0);assert.equal(a.view.getBigUint64(840,true),BigInt(max));assert.equal(a.view.getBigUint64(848,true),9n);assert.equal(a.view.getBigUint64(856,true),27000000000n);assert.deepEqual(a.host.unsupportedImports(),[]);});
test('NOW flags read one clock while omitted fields and zero flags retain metadata',()=>{const a=abi();assert.equal(a.wasi.fd_filestat_set_times(4,1n,2n,10),0);assert.equal(a.clocks,1);assert.deepEqual(a.metadata.get(4),{atime:'27000000000',mtime:'27000000000',ctime:'27000000000'});const old={...a.metadata.get(4)},count=a.operations.length;assert.equal(a.wasi.fd_filestat_set_times(4,0n,0n,0),0);assert.equal(a.clocks,1);assert.deepEqual(a.metadata.get(4),old);assert.equal(a.operations.length,count+1);assert.equal(a.operations.at(-1).op,'stat_fd');});
test('conflicting flags, readonly assets, stale descriptors and invalid ranges reject atomically',()=>{const a=abi(),before={...a.metadata.get(4)};for(const flags of [3,12,16])assert.equal(a.wasi.fd_filestat_set_times(4,1n,2n,flags),ERRNO.INVAL);assert.equal(a.operations.length,0);assert.deepEqual(a.metadata.get(4),before);assert.equal(a.wasi.fd_filestat_set_times(5,1n,2n,5),ERRNO.ROFS);assert.deepEqual(a.metadata.get(5),zero());assert.equal(a.wasi.fd_filestat_set_times(99,1n,2n,5),ERRNO.BADF);const calls=a.operations.length;assert.equal(a.wasi.fd_filestat_get(4,65535),ERRNO.FAULT);assert.equal(a.operations.length,calls);});
test('path timestamp ABI applies preview1 lookup/flag validation and retained stat times',()=>{const a=abi(),n=pathBytes(a.memory,'user/file');assert.equal(a.wasi.path_filestat_set_times(3,1,400,n,9007199254740993n,BigInt(max),5),0);assert.equal(a.wasi.path_filestat_get(3,0,400,n,800),0);assert.equal(a.view.getBigUint64(840,true),9007199254740993n);assert.equal(a.view.getBigUint64(848,true),BigInt(max));const old={...a.metadata.get(4)};assert.equal(a.wasi.path_filestat_set_times(3,2,400,n,1n,2n,5),ERRNO.INVAL);assert.deepEqual(a.metadata.get(4),old);});
function source(){const data=[1,2,255],root={atime:max,mtime:'8',ctime:'9'},file={atime:'9007199254740993',mtime:max,ctime:'11'};return ({operation:o})=>({filesystem:{errno:0,value:o.op==='list_writable'?[{path:'/user',stat:{kind:'directory',bytes:0}},{path:'/user/保存.sav',stat:{kind:'file',bytes:data.length}}]:o.op==='get_times'?root:o.op==='get_path_times'?o.path==='user'?zero():file:o.op==='open'?{fd:4}:o.op==='read'?{bytes:data,count:data.length}:null}});}
function candidate(operations){return ({operation:o})=>{operations.push(o);return {filesystem:{errno:0,value:o.op==='open'?{fd:9}:o.op==='write'?{count:o.bytes.length}:null}};};}
test('version 2 protects and restores exact file and root timestamps with native bytes',async()=>{const db=database(),storage=createCoreStorage({identity:'original-source',indexedDB:db});await storage.save(source());const snapshot=await storage.readSnapshot();assert.equal(snapshot.version,2);assert.equal(snapshot.root_times.atime,max);assert.match(snapshot.metadata_sha256,/^[a-f0-9]{64}$/);const file=snapshot.entries.find(e=>e.kind==='file');assert.equal(file.times.mtime,max);assert.equal(file.times.atime,'9007199254740993');const operations=[],target=candidate(operations);assert.equal(await storage.restore({createPlatform:()=>target,mountAssets:()=>{}}),target);assert.deepEqual(operations.find(o=>o.op==='set_path_times'&&o.path==='user/保存.sav'),{op:'set_path_times',dir_fd:3,path:'user/保存.sav',...file.times});assert.deepEqual(operations.at(-1),{op:'set_times',fd:3,...snapshot.root_times});assert.deepEqual(operations.find(o=>o.op==='write').bytes,[1,2,255]);});
test('legacy version 1 migrates missing timestamp metadata to zero without changing native bytes',async()=>{const native=[0,255,65],db=database({version:1,format:'drl-original-core-files',identity:'original-source',entries:[{path:'/save',kind:'file',bytes:native,sha256:digest(native)}]}),storage=createCoreStorage({identity:'original-source',indexedDB:db});const migrated=await storage.readSnapshot();assert.equal(migrated.version,2);assert.deepEqual(migrated.root_times,zero());assert.deepEqual(migrated.entries[0].times,zero());assert.deepEqual(Array.from(migrated.entries[0].bytes),native);const operations=[];await storage.restore({createPlatform:()=>candidate(operations),mountAssets:()=>{}});assert.deepEqual(operations.find(o=>o.op==='write').bytes,native);assert.deepEqual(operations.at(-1),{op:'set_times',fd:3,...zero()});});
test('malformed or tampered metadata and unsupported versions fail before creating a restore candidate',async()=>{for(const corrupt of [s=>{s.root_times.atime='01';},s=>{s.entries[1].times.mtime='18446744073709551616';},s=>{s.entries[1].times.mtime='12';},s=>{s.root_times.ctime='12';},s=>{s.version=3;}]){const db=database(),storage=createCoreStorage({identity:'original-source',indexedDB:db});await storage.save(source());db.change(corrupt);let created=0;await assert.rejects(storage.restore({createPlatform:()=>{created++;return candidate([]);},mountAssets:()=>{}}));assert.equal(created,0);}for(const bad of [{atime:0,mtime:'0',ctime:'0'},{atime:'0',mtime:'0',ctime:'0',extra:'0'},{atime:'+1',mtime:'0',ctime:'0'}])assert.throws(()=>canonicalFileTimes(bad));});
import {readFile} from 'node:fs/promises';
import {rustPlatform} from '../web/core-host.mjs';
async function actualPlatform(){const data=await readFile(new URL('../dist/drl_web_port.wasm',import.meta.url));return rustPlatform((await WebAssembly.instantiate(data,{})).instance);}
const fileRequest=(platform,operation)=>{const result=platform({kind:'file_system',operation}).filesystem;assert.equal(result.errno,0,JSON.stringify(operation));return result.value;};
const writeFlags={create:true,exclusive:true,truncate:false,writable:true,append:false,directory:false};
test('actual Rust and WASI retain timestamps on an owned read-only descriptor',async()=>{const platform=await actualPlatform();fileRequest(platform,{op:'mkdir',dir_fd:3,path:'user'});let {fd}=fileRequest(platform,{op:'open',dir_fd:3,path:'user/save',flags:writeFlags});fileRequest(platform,{op:'write',fd,bytes:[4,5]});fileRequest(platform,{op:'close',fd});({fd}=fileRequest(platform,{op:'open',dir_fd:3,path:'user/save',flags:{...writeFlags,create:false,exclusive:false,writable:false}}));const memory=new WebAssembly.Memory({initial:1}),host=createCoreHost({platform,now:()=>123});host.bind({memory});const wasi=host.imports.wasi_snapshot_preview1;assert.equal(wasi.fd_filestat_set_times(fd,9007199254740993n,BigInt(max),5),0);assert.equal(wasi.fd_filestat_get(fd,800),0);const view=new DataView(memory.buffer);assert.equal(view.getBigUint64(840,true),9007199254740993n);assert.equal(view.getBigUint64(848,true),BigInt(max));assert.deepEqual(fileRequest(platform,{op:'get_times',fd}),{atime:'9007199254740993',mtime:max,ctime:'123000000'});assert.deepEqual(fileRequest(platform,{op:'stat_fd',fd}),{kind:'file',bytes:2,readonly:false});fileRequest(platform,{op:'close',fd});assert.equal(wasi.fd_filestat_set_times(fd,0n,0n,5),ERRNO.BADF);});
test('actual Rust denies mounted-asset timestamps and confines path metadata',async()=>{const platform=await actualPlatform();fileRequest(platform,{op:'mount_asset',path:'data/original.asc',bytes:[65]});const {fd}=fileRequest(platform,{op:'open',dir_fd:3,path:'data/original.asc',flags:{...writeFlags,create:false,exclusive:false,writable:false}});const memory=new WebAssembly.Memory({initial:1}),host=createCoreHost({platform});host.bind({memory});const wasi=host.imports.wasi_snapshot_preview1;assert.equal(wasi.fd_filestat_set_times(fd,1n,2n,5),ERRNO.ROFS);const length=pathBytes(memory,'../escape');assert.equal(wasi.path_filestat_set_times(3,0,400,length,1n,2n,5),ERRNO.NOTCAPABLE);assert.deepEqual(fileRequest(platform,{op:'get_times',fd}),zero());assert.deepEqual(host.unsupportedImports(),[]);});
test('actual Rust version 2 restore preserves root and native-file metadata in a fresh adapter',async()=>{const original=await actualPlatform();fileRequest(original,{op:'mkdir',dir_fd:3,path:'user'});const {fd}=fileRequest(original,{op:'open',dir_fd:3,path:'user/save',flags:writeFlags});fileRequest(original,{op:'write',fd,bytes:[0,255,18]});fileRequest(original,{op:'set_times',fd,atime:'9007199254740993',mtime:max,ctime:'31'});fileRequest(original,{op:'close',fd});fileRequest(original,{op:'set_times',fd:3,atime:max,mtime:'33',ctime:'34'});const storage=createCoreStorage({identity:'actual-original-source',indexedDB:database()});await storage.save(original);const restored=await storage.restore({createPlatform:actualPlatform,mountAssets:()=>{}});assert.notEqual(restored,original);assert.deepEqual(fileRequest(restored,{op:'get_times',fd:3}),{atime:max,mtime:'33',ctime:'34'});assert.deepEqual(fileRequest(restored,{op:'get_path_times',dir_fd:3,path:'user/save'}),{atime:'9007199254740993',mtime:max,ctime:'31'});const opened=fileRequest(restored,{op:'open',dir_fd:3,path:'user/save',flags:{...writeFlags,create:false,exclusive:false,writable:false}});assert.deepEqual(fileRequest(restored,{op:'read',fd:opened.fd,length:3}).bytes,[0,255,18]);});
