import test from "node:test";
import assert from "node:assert/strict";
import {readFile,writeFile,mkdir,mkdtemp,rm} from "node:fs/promises";
import {spawn} from "node:child_process";
import {createServer} from "node:http";
import path from "node:path";
import os from "node:os";
import {fileURLToPath} from "node:url";
import {createHash} from "node:crypto";
import {createCoreHost,createCoreStorage,rustPlatform,ERRNO,WasiExit} from "../web/core-host.mjs";
const root=fileURLToPath(new URL("../../",import.meta.url));
const port=fileURLToPath(new URL("../",import.meta.url));
const encoder=new TextEncoder(),decoder=new TextDecoder();
let wasm;
async function platform(){wasm??=await readFile(path.join(port,"dist/drl_web_port.wasm"));return rustPlatform((await WebAssembly.instantiate(wasm,{})).instance);}
async function setup(options={}){const api=await platform(),memory=new WebAssembly.Memory({initial:4});const host=createCoreHost({platform:api,...options});host.bind({memory});return {api,memory,host,wasi:host.imports.wasi_snapshot_preview1,bridge:host.imports.drl_host,view:new DataView(memory.buffer)};}
function request(api,operation){const result=api({kind:"file_system",operation}).filesystem;assert.equal(result.errno,0,JSON.stringify(operation));return result.value;}
function name(memory,text,offset=400){const bytes=encoder.encode(text);new Uint8Array(memory.buffer,offset,bytes.length).set(bytes);return bytes.length;}
function iovec(view,offset,length,pointer=100){view.setUint32(pointer,offset,true);view.setUint32(pointer+4,length,true);return pointer;}
function open(memory,wasi,view,text,{flags=0,oflags=1,rights=0x08e001ffn}={}){assert.equal(wasi.path_open(3,0,400,name(memory,text),oflags,rights,rights,flags,300),0);return view.getUint32(300,true);}

test("mock ABI rejects invalid ranges before any platform request",()=>{let calls=0;const memory=new WebAssembly.Memory({initial:1}),host=createCoreHost({platform:()=>{calls++;throw new Error("unexpected platform call");}});host.bind({memory});const view=new DataView(memory.buffer);iovec(view,65535,4);assert.equal(host.imports.wasi_snapshot_preview1.fd_write(4,100,1,300),ERRNO.FAULT);assert.equal(calls,0);assert.equal(host.imports.wasi_snapshot_preview1.args_get(-1,100),ERRNO.FAULT);assert.equal(calls,0);assert.equal(host.imports.wasi_snapshot_preview1.fd_prestat_dir_name(3,1000,1),0);assert.equal(new Uint8Array(memory.buffer)[1000],47);});
test("mock semantic ABI delegates typed parameters and host locale without substitutions",()=>{const calls=[],memory=new WebAssembly.Memory({initial:1}),host=createCoreHost({platform:request=>{calls.push(request);return {semantic:{text:request.english?"Marine Alice":"海兵 Alice"}};}});host.bind({memory});const request={kind:"native_text",id:"being.player",parameters:{name:{kind:"string",value:"Alice"}},english:true},length=name(memory,JSON.stringify(request));assert.equal(host.imports.drl_host.resolve_text(400,length,0,0),12);assert.equal(calls[0].english,false);assert.deepEqual(calls[0].parameters,request.parameters);host.setLanguage("en");assert.equal(host.imports.drl_host.resolve_text(400,length,1000,20),12);assert.equal(decoder.decode(new Uint8Array(memory.buffer,1000,12)),"Marine Alice");assert.throws(()=>host.setLanguage("xx"),/Unsupported DRL locale/);});
test("mock WASI records unsupported operations and preserves 64-bit outputs",()=>{let request;const memory=new WebAssembly.Memory({initial:1}),host=createCoreHost({platform:value=>{request=value;return {filesystem:{errno:0,value:{offset:"9007199254740993"}}};}});host.bind({memory});const wasi=host.imports.wasi_snapshot_preview1;assert.equal(wasi.fd_seek(4,9007199254740993n,0,500),0);assert.equal(request.operation.offset,"9007199254740993");assert.equal(new DataView(memory.buffer).getBigUint64(500,true),9007199254740993n);assert.equal(wasi.fd_sync(4),ERRNO.NOTSUP);assert.deepEqual(host.unsupportedImports(),["fd_sync"]);});

function mockIndexedDB(){let snapshot,commits=0;const db={createObjectStore(){},close(){},transaction(){const tx={};tx.objectStore=()=>({put(value){queueMicrotask(()=>{snapshot=structuredClone(value);commits++;tx.oncomplete?.();});},get(){const request={};queueMicrotask(()=>{request.result=structuredClone(snapshot);request.onsuccess?.();tx.oncomplete?.();});return request;}});return tx;}};return {get commits(){return commits;},corrupt(callback){callback(snapshot);},open(){const request={};queueMicrotask(()=>{request.result=db;request.onupgradeneeded?.();request.onsuccess?.();});return request;}};}
test("mock IndexedDB waits for commit, checks native file hashes, restores a fresh candidate",async()=>{const db=mockIndexedDB(),calls=[];const storage=createCoreStorage({identity:"source-hash:engine-hash",indexedDB:db});const source=request=>{const op=request.operation;calls.push(op.op);let value=null;if(op.op==="list_writable")value=[{path:"/user",stat:{kind:"directory",bytes:0}},{path:"/user/save.sav",stat:{kind:"file",bytes:5}}];if(op.op==="get_path_times"||op.op==="get_times")value={atime:"0",mtime:"0",ctime:"0"};if(op.op==="open")value={fd:4};if(op.op==="read")value={bytes:[0,1,2,255,4],count:5};return {filesystem:{errno:0,value}};};assert.deepEqual(await storage.save(source),{files:1,bytes:5});assert.equal(db.commits,1);assert.deepEqual(calls,["list_writable","get_times","get_path_times","get_path_times","open","read","close"]);let created=0;const restoreCalls=[];const candidate=request=>{const op=request.operation;restoreCalls.push(op);return {filesystem:{errno:0,value:op.op==="open"?{fd:4}:op.op==="write"?{count:op.bytes.length}:null}};};assert.equal(await storage.restore({createPlatform:()=>{created++;return candidate;},mountAssets:()=>{}}),candidate);assert.equal(created,1);assert.deepEqual(restoreCalls.map(x=>x.op),["mkdir","set_path_times","open","write","close","set_path_times","set_times"]);assert.deepEqual(restoreCalls.find(x=>x.op==="write").bytes,[0,1,2,255,4]);db.corrupt(snapshot=>{snapshot.entries[1].bytes[0]=200;});await assert.rejects(storage.restore({createPlatform:()=>{created++;return candidate;},mountAssets:()=>{}}),/checksum/);assert.equal(created,1);});
test("mock restore failures leave active platform untouched and wrong identity fails before candidate",async()=>{const db=mockIndexedDB();const source=request=>({filesystem:{errno:0,value:request.operation.op==="list_writable"?[{path:"/save.sav",stat:{kind:"file",bytes:0}}]:request.operation.op==="open"?{fd:4}:["get_path_times","get_times"].includes(request.operation.op)?{atime:"0",mtime:"0",ctime:"0"}:null}});const storage=createCoreStorage({identity:"source-a",indexedDB:db});await storage.save(source);let created=0;await assert.rejects(createCoreStorage({identity:"source-b",indexedDB:db}).restore({createPlatform:()=>{created++;},mountAssets:()=>{}}),/identity/);assert.equal(created,0);await assert.rejects(storage.restore({createPlatform:()=>{created++;return ()=>({filesystem:{errno:29,value:null}});},mountAssets:()=>{}}),/errno 29/);assert.equal(created,1);assert.deepEqual(await storage.readSnapshot().then(x=>x.entries.map(y=>y.path)),["/save.sav"]);});
test("mock restore asks Rust to validate precreated writable-directory collisions",async()=>{const db=mockIndexedDB(),storage=createCoreStorage({identity:"source",indexedDB:db});await storage.save(request=>({filesystem:{errno:0,value:request.operation.op==="list_writable"?[{path:"/data",stat:{kind:"directory",bytes:0}}]:["get_path_times","get_times"].includes(request.operation.op)?{atime:"0",mtime:"0",ctime:"0"}:null}}));const candidate=request=>({filesystem:request.operation.op==="mkdir"?{errno:ERRNO.EXIST,value:null}:{errno:0,value:{kind:"directory",readonly:false,bytes:0}}});assert.equal(await storage.restore({createPlatform:()=>candidate,mountAssets:()=>{}}),candidate);await assert.rejects(storage.restore({createPlatform:()=>request=>({filesystem:request.operation.op==="mkdir"?{errno:ERRNO.EXIST,value:null}:{errno:0,value:{kind:"file",readonly:true,bytes:0}}}),mountAssets:()=>{}}),/conflicts/);});
test("mock absent native save is a normal null lookup and typed restore failure",async()=>{const storage=createCoreStorage({identity:"source",indexedDB:mockIndexedDB()});assert.equal(await storage.readSnapshot(),null);await assert.rejects(storage.restore({createPlatform:()=>{throw new Error("not called");},mountAssets:()=>{}}),error=>error.code==="no_save");});
test("mock CJK width and fitting delegate bytes unchanged to Rust helper contract",()=>{const memory=new WebAssembly.Memory({initial:1}),platform=()=>{throw new Error("not JSON");};platform.textColumns=data=>{assert.equal(decoder.decode(data),"名前");return 4;};platform.textFit=(data,columns)=>{assert.equal(decoder.decode(data),"名前");assert.equal(columns,2);return 3;};const host=createCoreHost({platform});host.bind({memory});const length=name(memory,"名前");assert.equal(host.imports.drl_host.text_columns(400,length),4);assert.equal(host.imports.drl_host.text_fit(400,length,2),3);});

test("Rust VFS is the state owner and routes errors through WASI errno",async()=>{const {api,memory,wasi,view}=await setup();assert.equal(wasi.path_filestat_get(3,0,400,name(memory,"missing"),500),ERRNO.NOENT);const fd=open(memory,wasi,view,"save.sav");assert.equal(request(api,{op:"stat_fd",fd}).kind,"file");assert.equal(wasi.fd_close(fd),0);assert.equal(wasi.fd_filestat_get(fd,500),ERRNO.BADF);assert.equal(wasi.fd_close(3),ERRNO.NOTCAPABLE);});
test("real Rust CJK helpers share initialized ABI buffer without changing RNG",async()=>{const api=await platform(),before=api({kind:"redraw",english:false}).checkpoint;assert.equal(api.textColumns(encoder.encode("名前")),4);assert.equal(api.textFit(encoder.encode("名前"),2),3);assert.equal(api.textColumns(Uint8Array.of(0xc0,0x80)),-1);assert.deepEqual(api({kind:"redraw",english:true}).checkpoint,before);});
test("iovecs marshal multi-chunk original file bytes through real Rust",async()=>{const {api,memory,wasi,view}=await setup();const fd=open(memory,wasi,view,"save.bin");const data=new Uint8Array(memory.buffer,20000,130000);for(let i=0;i<data.length;i++)data[i]=i%251;const expected=data.slice();iovec(view,20000,data.length);assert.equal(wasi.fd_write(fd,100,1,300),0);assert.equal(view.getUint32(300,true),130000);assert.equal(request(api,{op:"stat_fd",fd}).bytes,130000);assert.equal(wasi.fd_seek(fd,0n,0,304),0);data.fill(0);assert.equal(wasi.fd_read(fd,100,1,300),0);assert.deepEqual(data,expected);assert.equal(wasi.fd_tell(fd,304),0);assert.equal(view.getBigUint64(304,true),130000n);});
test("all iovecs and output pointers are validated before Rust mutates",async()=>{const {api,memory,wasi,view}=await setup();const fd=open(memory,wasi,view,"atomic.bin");iovec(view,500,4);iovec(view,memory.buffer.byteLength-1,50,108);assert.equal(wasi.fd_write(fd,100,2,300),ERRNO.FAULT);assert.equal(request(api,{op:"stat_fd",fd}).bytes,0);assert.equal(wasi.fd_write(fd,100,1,-1),ERRNO.FAULT);assert.equal(request(api,{op:"stat_fd",fd}).bytes,0);assert.equal(wasi.fd_read(fd,100,0xffffffff,300),ERRNO.INVAL);});
test("memory views refresh after actual WASM memory growth",async()=>{const {memory,wasi,view}=await setup();const fd=open(memory,wasi,view,"grow.bin");memory.grow(1);const current=new DataView(memory.buffer);iovec(current,262144,4);new Uint8Array(memory.buffer,262144,4).set([1,2,3,4]);assert.equal(wasi.fd_write(fd,100,1,300),0);assert.equal(current.getUint32(300,true),4);});
test("64-bit seeks stay BigInt and oversized file sizes fail explicitly",async()=>{const {memory,wasi,view}=await setup();const fd=open(memory,wasi,view,"large.bin");assert.equal(wasi.fd_seek(fd,9007199254740993n,0,304),0);assert.equal(view.getBigUint64(304,true),9007199254740993n);assert.equal(wasi.fd_seek(fd,-1n,0,304),ERRNO.INVAL);assert.equal(wasi.fd_seek(fd,0,0,304),ERRNO.INVAL);assert.equal(wasi.fd_filestat_set_size(fd,16777217n),ERRNO.INVAL);assert.equal(wasi.fd_seek(1,0n,0,304),ERRNO.SPIPE);});
test("readonly original assets, path traversal and invalid UTF8 are rejected by Rust",async()=>{const {api,memory,wasi,view}=await setup();request(api,{op:"mount_asset",path:"lua/core.lua",bytes:[1,2,3]});assert.equal(wasi.path_open(3,0,400,name(memory,"lua/core.lua"),0,64n,64n,0,300),69);assert.equal(wasi.path_open(3,0,400,name(memory,"../private"),0,2n,2n,0,300),ERRNO.NOTCAPABLE);new Uint8Array(memory.buffer,400,2).set([0xc0,0x80]);assert.equal(wasi.path_open(3,0,400,2,0,2n,2n,0,300),ERRNO.INVAL);const fd=open(memory,wasi,view,"lua/core.lua",{oflags:0,rights:2n});assert.equal(wasi.fd_filestat_get(fd,500),0);assert.equal(view.getBigUint64(532,true),3n);});
test("append and stat flags use Rust descriptor data",async()=>{const {memory,wasi,view}=await setup();const fd=open(memory,wasi,view,"append.bin",{flags:1});assert.equal(wasi.fd_fdstat_get(fd,500),0);assert.equal(view.getUint16(502,true),1);assert.equal(wasi.fd_fdstat_set_flags(fd,0),0);assert.equal(wasi.fd_fdstat_get(fd,500),0);assert.equal(view.getUint16(502,true),0);assert.equal(wasi.fd_fdstat_set_flags(fd,4),ERRNO.NOTSUP);assert.equal(wasi.fd_filestat_set_size(fd,20n),0);assert.equal(wasi.fd_filestat_get(fd,600),0);assert.equal(view.getBigUint64(632,true),20n);});
test("preopen is a single isolated '/' capability, not Windows host storage",async()=>{const {memory,wasi,view}=await setup();assert.equal(wasi.fd_prestat_get(3,500),0);assert.equal(view.getUint32(504,true),1);assert.equal(wasi.fd_prestat_dir_name(3,508,1),0);assert.equal(new Uint8Array(memory.buffer)[508],47);assert.equal(wasi.fd_prestat_get(4,500),ERRNO.BADF);assert.equal(wasi.fd_prestat_dir_name(3,508,0),ERRNO.INVAL);});
test("UTF8 directory entries, cookies and partial dirents follow preview1 layout",async()=>{const {memory,wasi,view}=await setup();open(memory,wasi,view,"日本語.sav");open(memory,wasi,view,"z.sav");assert.equal(wasi.fd_readdir(3,1000,1000,0n,300),0);const next=view.getBigUint64(1000,true),size=view.getUint32(1016,true);assert.equal(next,1n);assert.equal(view.getUint8(1020),4);const first=decoder.decode(new Uint8Array(memory.buffer,1024,size));assert.equal(first,"z.sav");assert.equal(wasi.fd_readdir(3,1000,25,1n,300),0);assert.equal(view.getUint32(300,true),25);assert.equal(view.getBigUint64(1000,true),2n);assert.equal(view.getUint32(1016,true),encoder.encode("日本語.sav").length);assert.equal(wasi.fd_readdir(3,1000,1000,9n,300),0);assert.equal(view.getUint32(300,true),0);});
test("rename, mkdir and unlink preserve Rust open-descriptor and asset policy",async()=>{const {memory,wasi,view}=await setup();assert.equal(wasi.path_create_directory(3,400,name(memory,"user")),0);const fd=open(memory,wasi,view,"user/old.sav");const n=name(memory,"user/old.sav"),m=name(memory,"user/new.sav",700);assert.equal(wasi.path_rename(3,400,n,3,700,m),0);assert.equal(wasi.path_unlink_file(3,700,m),ERRNO.NOTCAPABLE);assert.equal(wasi.fd_close(fd),0);assert.equal(wasi.path_unlink_file(3,700,m),0);assert.equal(wasi.path_remove_directory(3,400,name(memory,"user")),0);});
test("arguments and environment preserve Unicode strings and NUL terminators",async()=>{const {memory,wasi,view}=await setup({args:["drl","名前"],env:{LANG:"ja_JP.UTF-8"}});assert.equal(wasi.args_sizes_get(100,104),0);assert.equal(view.getUint32(100,true),2);assert.equal(view.getUint32(104,true),11);assert.equal(wasi.args_get(200,1000),0);assert.equal(view.getUint32(204,true),1004);assert.equal(decoder.decode(new Uint8Array(memory.buffer,1004,7)),"名前\0");assert.equal(wasi.environ_get(300,1100),0);assert.equal(decoder.decode(new Uint8Array(memory.buffer,1100,17)),"LANG=ja_JP.UTF-8\0");});
test("mock clock ABI nanoseconds and random chunking avoid any Rust/domain request",()=>{let draws=0;const memory=new WebAssembly.Memory({initial:4}),host=createCoreHost({platform:()=>{throw new Error("random/clock must not consume domain request");},now:()=>1700000000123,monotonic:()=>12.125,crypto:{getRandomValues(data){draws++;assert.ok(data.length<=65536);data.fill(7);return data;}}});host.bind({memory});const wasi=host.imports.wasi_snapshot_preview1,view=new DataView(memory.buffer);assert.equal(wasi.clock_time_get(0,0n,100),0);assert.equal(view.getBigUint64(100,true),1700000000123000000n);assert.equal(wasi.clock_time_get(1,0n,100),0);assert.equal(view.getBigUint64(100,true),12000000n);assert.equal(wasi.clock_time_get(2,0n,100),ERRNO.NOTSUP);assert.equal(wasi.random_get(1000,130000),0);assert.equal(draws,2);assert.equal(new Uint8Array(memory.buffer,1000,130000).every(x=>x===7),true);});
test("stdout has byte-preserving writes, stdin EOF and invalid directions are explicit",async()=>{let output=[];const {memory,wasi,view}=await setup({stdout:data=>output.push(...data)});const data=encoder.encode("日本語\n");new Uint8Array(memory.buffer,500,data.length).set(data);iovec(view,500,data.length);assert.equal(wasi.fd_write(1,100,1,300),0);assert.deepEqual(output,Array.from(data));assert.equal(wasi.fd_read(0,100,1,300),0);assert.equal(view.getUint32(300,true),0);assert.equal(wasi.fd_read(1,100,1,300),ERRNO.BADF);assert.equal(wasi.fd_write(0,100,1,300),ERRNO.BADF);assert.throws(()=>wasi.proc_exit(37),error=>error instanceof WasiExit&&error.code===37);});
test("unsupported imports return recorded NOTSUP and unknown namespaces reject before run",async()=>{const {host,wasi}=await setup();assert.equal(wasi.path_readlink(3,0,0,0,0,0),ERRNO.NOTSUP);assert.equal(wasi.sock_send(3,0,0,0,0),ERRNO.NOTSUP);assert.deepEqual(host.unsupportedImports(),["path_readlink","sock_send"]);const other=createCoreHost({platform:()=>{throw new Error("not called");}});const module=Uint8Array.from([0,97,115,109,1,0,0,0,1,4,1,96,0,0,2,13,1,3,98,97,100,5,104,101,108,108,111,0,0]);await assert.rejects(other.instantiate(module),/Unsupported core import: bad.hello/);});
test("original frame and draw packets are copied for pure Rust projection",async()=>{let received,draw;const {memory,bridge}=await setup({bridge:{frame:data=>received=data,drawCommand:(header,text)=>draw={header,text}}});const v=new DataView(memory.buffer);v.setUint32(1000,0x464c5244,true);v.setUint32(1004,1,true);v.setUint32(1008,80,true);v.setUint32(1012,25,true);bridge.frame(1000,24032);new Uint8Array(memory.buffer)[1040]=9;assert.equal(received.length,24032);assert.equal(received[40],0);v.setUint32(400,1,true);v.setUint32(404,0,true);new Uint8Array(memory.buffer,500,2).set([65,66]);bridge.draw_command(400,64,500,2);assert.deepEqual(draw.text,Uint8Array.of(65,66));assert.throws(()=>bridge.frame(1000,20),/frame length/);});
test("input and semantic strings cross typed packets without fallback",async()=>{const packet=new Uint8Array(128);new DataView(packet.buffer).setUint32(0,1,true);let peek;const {memory,bridge}=await setup({bridge:{pollEvent:value=>{peek=value;return packet;},eventPending:()=>true,resolveText:data=>{assert.equal(decoder.decode(data),'{"id":"game.name"}');return "名前";}}});assert.equal(bridge.poll_event(1000,128,1),1);assert.equal(peek,true);assert.equal(bridge.event_pending(),1);assert.equal(bridge.poll_event(1000,127,0),-1);const length=name(memory,'{"id":"game.name"}',400);assert.equal(bridge.resolve_text(400,length,0,0),6);assert.equal(bridge.resolve_text(400,length,1000,5),-1);assert.equal(bridge.resolve_text(400,length,1000,6),6);assert.equal(decoder.decode(new Uint8Array(memory.buffer,1000,6)),"名前");});

test("mock production drl_sleep aliases the proven suspension import and rejects missing JSPI",async()=>{
  const host=createCoreHost({platform:()=>{throw new Error("unexpected platform request");}});
  assert.equal(host.imports.drl_host.drl_sleep,host.imports.drl_host.sleep);
  if(!host.supportsJSPI)for(const name of ["sleep","drl_sleep"]){
    const namespace=encoder.encode("drl_host"),symbol=encoder.encode(name);
    const payload=[1,namespace.length,...namespace,symbol.length,...symbol,0,0];
    const module=Uint8Array.from([0,97,115,109,1,0,0,0,1,5,1,96,1,127,0,2,payload.length,...payload]);
    await assert.rejects(createCoreHost({platform:()=>{throw new Error("unexpected platform request");}}).instantiate(module),/requires WebAssembly\.Suspending\/promising/);
  }
});

test("directory inheriting rights permit libc child read/write without file access on the directory itself",async()=>{
  const {wasi,view}=await setup();assert.equal(wasi.fd_fdstat_get(3,500),0);
  assert.equal(view.getBigUint64(508,true)&66n,0n);
  assert.equal(view.getBigUint64(516,true)&66n,66n);
});
test("real Chrome executes official-source Pascal and committed Rust VFS IndexedDB resume",{skip:process.env.DRL_HOST_BROWSER!=="1",timeout:120000},async()=>{
  const profile=await mkdtemp(path.join(os.tmpdir(),"drl-core-host-browser-"));
  const routes=new Map([["/core-host.mjs",path.join(port,"web/core-host.mjs")],["/rust.wasm",path.join(port,"dist/drl_web_port.wasm")],["/hello.wasm",path.join(root,"toolchain/wasm-probe/hello-exnref.wasm")],["/suspend.wasm",path.join(root,"toolchain/wasm-probe/suspend.wasm")],["/filesystem.wasm",path.join(root,"toolchain/wasm-probe/filesystem.wasm")],["/mixed.wasm",path.join(root,"experiments/lua-wasi/mixed-build/mixed-probe-jspi.wasm")]]);
  const server=createServer(async(req,res)=>{try{const route=new URL(req.url,"http://127.0.0.1").pathname;if(route==="/"){res.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});res.end("<!doctype html><meta charset=utf-8><title>DRL original-core host verification</title><pre id=result></pre>");return;}const filename=routes.get(route);if(!filename){res.writeHead(404);res.end();return;}res.writeHead(200,{"Content-Type":route.endsWith(".mjs")?"text/javascript":"application/wasm","Cache-Control":"no-store"});res.end(await readFile(filename));}catch{res.writeHead(404);res.end();}});
  await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));
  const chrome=spawn("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",["--headless=new","--disable-gpu","--no-first-run","--no-default-browser-check","--disable-background-networking","--disable-component-update","--remote-debugging-port=0","--user-data-dir="+profile,"about:blank"],{windowsHide:true,stdio:["ignore","ignore","pipe"]});
  let socket,id=0,errorText="";const pending=new Map();chrome.stderr.on("data",chunk=>errorText+=chunk.toString());const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  async function until(callback){for(let i=0;i<300;i++){const value=await callback();if(value)return value;await delay(100);}throw new Error("Chrome timeout "+errorText.slice(-500));}
  function call(method,params={}){return new Promise((resolve,reject)=>{const key=++id,timer=setTimeout(()=>{pending.delete(key);reject(new Error("CDP timeout "+method));},30000);pending.set(key,{resolve,reject,timer});socket.send(JSON.stringify({id:key,method,params}));});}
  async function evaluate(expression){const r=await call("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
  const evidence={scope:"authored official-source Pascal capability probes and real Rust VFS; no complete DRL game claim",checks:[],started_at:new Date().toISOString()};
  try{
    const debug=await until(async()=>{try{return Number((await readFile(path.join(profile,"DevToolsActivePort"),"utf8")).split("\n")[0]);}catch{return false;}});
    const pages=await(await fetch("http://127.0.0.1:"+debug+"/json/list")).json();socket=new WebSocket(pages.find(x=>x.type==="page").webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener("open",resolve,{once:true});socket.addEventListener("error",reject,{once:true});});socket.addEventListener("message",event=>{const r=JSON.parse(event.data);const p=pending.get(r.id);if(p){pending.delete(r.id);clearTimeout(p.timer);r.error?p.reject(new Error(JSON.stringify(r.error))):p.resolve(r.result);}});
    await call("Page.enable");await call("Runtime.enable");await call("Page.navigate",{url:"http://127.0.0.1:"+server.address().port+"/"});await until(()=>evaluate("document.readyState==='complete'"));
    const result=await evaluate(`(async()=>{
      const {createCoreHost,rustPlatform,createCoreStorage}=await import('/core-host.mjs');
      const wasmBytes=await(await fetch('/rust.wasm')).arrayBuffer();
      const createPlatform=async()=>rustPlatform((await WebAssembly.instantiate(wasmBytes,{})).instance);
      const api=await createPlatform();const texts=[];
      const host=createCoreHost({platform:api,stdout:data=>texts.push(new TextDecoder().decode(data))});
      await host.instantiate(await(await fetch('/hello.wasm')).arrayBuffer());const exit=await host.start();
      const fs=(p,operation)=>{const result=p({kind:'file_system',operation}).filesystem;if(result.errno)throw new Error('filesystem '+result.errno);return result.value;};
      const flags={create:true,exclusive:true,truncate:false,writable:true,append:false,directory:false};
      fs(api,{op:'mount_asset',path:'lua/core.lua',bytes:[1,2,3]});fs(api,{op:'mkdir',dir_fd:3,path:'user'});fs(api,{op:'mount_asset',path:'data/probe.dat',bytes:[9,8,7]});
      const filesystemApi=await createPlatform();fs(filesystemApi,{op:'mkdir',dir_fd:3,path:'user'});fs(filesystemApi,{op:'mount_asset',path:'data/probe.dat',bytes:[9,8,7]});
      const filesystemTexts=[],filesystemOperations=[];
      const tracedFilesystem=request=>{const result=filesystemApi(request);if(filesystemOperations.length<200)filesystemOperations.push({operation:request.operation,result:result.filesystem});return result;};
      const filesystemHost=createCoreHost({platform:tracedFilesystem,stdout:data=>filesystemTexts.push(new TextDecoder().decode(data))});
      await filesystemHost.instantiate(await(await fetch('/filesystem.wasm')).arrayBuffer());
      let filesystemExit=null,filesystemFailure=null;
      try{filesystemExit=await filesystemHost.start();}catch(error){filesystemFailure={name:error.name,message:error.message,stack:error.stack};}
      const {fd}=fs(api,{op:'open',dir_fd:3,path:'user/save.sav',flags});fs(api,{op:'write',fd,bytes:[0,255,65,66,67]});fs(api,{op:'close',fd});
      const storage=createCoreStorage({identity:'official-source-probe:a6f9650:f89735a',databaseName:'drl-core-host-test'});
      const saved=await storage.save(api);const next=await storage.restore({createPlatform,mountAssets:p=>{fs(p,{op:'mount_asset',path:'lua/core.lua',bytes:[1,2,3]});fs(p,{op:'mount_asset',path:'data/probe.dat',bytes:[9,8,7]});}});
      const open=fs(next,{op:'open',dir_fd:3,path:'user/save.sav',flags:{...flags,create:false,exclusive:false,writable:false}});const restored=fs(next,{op:'read',fd:open.fd,length:65536}).bytes;fs(next,{op:'close',fd:open.fd});
      let rejected=false;try{await createCoreStorage({identity:'wrong-source',databaseName:'drl-core-host-test'}).restore({createPlatform,mountAssets:()=>{}});}catch{rejected=true;}
      const before=fs(api,{op:'stat_path',dir_fd:3,path:'user/save.sav'});let atomic=false;try{await storage.restore({createPlatform,mountAssets:p=>{fs(p,{op:'mount_asset',path:'lua/core.lua',bytes:[1,2,3]});throw new Error('deliberate mount failure');}});}catch{atomic=before.bytes===fs(api,{op:'stat_path',dir_fd:3,path:'user/save.sav'}).bytes;}
      const suspension=[];const suspender=createCoreHost({platform:await createPlatform(),stdout:data=>suspension.push(new TextDecoder().decode(data)),sleep:ms=>new Promise(resolve=>setTimeout(resolve,ms))});
      await suspender.instantiate(await(await fetch('/suspend.wasm')).arrayBuffer());let timerRan=false;setTimeout(()=>{timerRan=true;},0);const suspendedExit=await suspender.start();
      const mixedApi=await createPlatform();fs(mixedApi,{op:'mkdir',dir_fd:3,path:'probe'});const mixedOperations=[];
      const mixedPlatform=request=>{const result=mixedApi(request);if(mixedOperations.length<200)mixedOperations.push({operation:request.operation,result:result.filesystem});return result;};
      const mixedTexts=[];const mixedHost=createCoreHost({platform:mixedPlatform,stdout:data=>mixedTexts.push(new TextDecoder().decode(data))});await mixedHost.instantiate(await(await fetch('/mixed.wasm')).arrayBuffer());
      let mixedExit=null,mixedFailure=null,mixedResult=null;
      try{mixedExit=await mixedHost.start();}catch(error){mixedFailure={name:error.name,message:error.message,stack:error.stack};}
      const mixedLines=mixedTexts.join('');
      try{mixedResult=JSON.parse(mixedLines.slice(mixedLines.lastIndexOf('{')));}catch(error){mixedFailure??={name:error.name,message:error.message};}
      return {userAgent:navigator.userAgent,jspi:host.supportsJSPI,crossOriginIsolated,sharedMemoryRequired:false,exit,text:texts.join(''),unsupported:host.unsupportedImports(),saved,restored,rejected,atomic,suspendedExit,suspension:suspension.join(''),timerRan,filesystemExit,filesystemFailure,filesystemOperations,filesystemText:filesystemTexts.join(''),filesystemUnsupported:filesystemHost.unsupportedImports(),mixedExit,mixedResult,mixedLines,mixedFailure,mixedOperations,mixedUnsupported:mixedHost.unsupportedImports()};
    })()`);
    evidence.browser=result;
    assert.equal(result.mixedExit,0);assert.equal(result.mixedResult.suspended_pascal_callbacks,1);assert.equal(result.mixedResult.mixed_pascal_lua,true);assert.equal(result.mixedResult.protected_callback_error,true);assert.deepEqual(result.mixedUnsupported,[]);assert.equal(result.filesystemExit,0);assert.match(result.filesystemText,/filesystem probe: PASS/);assert.deepEqual(result.filesystemUnsupported,[]);assert.equal(result.jspi,true);assert.equal(result.crossOriginIsolated,false);assert.equal(result.exit,0);assert.match(result.text,/callback, heap, streams, exceptions, round passed/);assert.deepEqual(result.unsupported,[]);assert.deepEqual(result.restored,[0,255,65,66,67]);assert.equal(result.saved.files,1);assert.equal(result.rejected,true);assert.equal(result.atomic,true);assert.equal(result.suspendedExit,0);assert.equal(result.timerRan,true);assert.match(result.suspension,/passed after/);
    evidence.result="pass";evidence.browser=result;evidence.checks=["Actual official-source FPC Wasm executes callbacks, heap, streams, exceptions and ties-to-even Round","Installed Chrome JSPI suspends and resumes authored Pascal locals while browser timers run","Actual Pascal absolute /user and /data paths resolve through preopen /; stream, seek, rename, enumeration, readonly denial and deletion pass","Mixed Lua→Pascal→drl_host.sleep resumes retained heap/locals and protected pcall formatter via real Rust VFS","No SharedArrayBuffer, cross-origin isolation, experimental flags or browser setting changes","Rust-owned native file bytes commit to IndexedDB and restore into a fresh Rust instance","Wrong source identity and failed candidate restore reject without mutating active platform"];
    const source=await readFile(routes.get('/hello.wasm'));evidence.hello={bytes:source.length,sha256:createHash('sha256').update(source).digest('hex')};
  }catch(error){evidence.result="fail";evidence.error=error.stack;throw error;}
  finally{evidence.finished_at=new Date().toISOString();await mkdir(path.join(port,"tests/output"),{recursive:true});await writeFile(path.join(port,"tests/output/core-host-browser.json"),JSON.stringify(evidence,null,2));if(socket)await call("Browser.close").catch(()=>{});socket?.close();for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error("Browser closed"));}pending.clear();for(let i=0;i<20&&chrome.exitCode===null;i++)await delay(100);if(chrome.exitCode===null)chrome.kill();await new Promise(resolve=>server.close(resolve));const checked=path.resolve(profile),temp=path.resolve(os.tmpdir())+path.sep;if(checked.startsWith(temp)&&path.basename(checked).startsWith("drl-core-host-browser-"))await rm(checked,{recursive:true,force:true,maxRetries:8,retryDelay:200}).catch(()=>{});}
});
