use drl_web_port::logic::rng::{GameRng, RngState};

#[test]
fn canonical_mt19937_seed_vector() {
    // Original published mt19937ar seed 5489 vector, not generated by this implementation.
    let expected = [
        3499211612, 581869302, 3890346734, 3586334585, 545404204, 4161255391, 3922919429,
        949333985, 2715962298, 1323567403,
    ];
    let mut rng = GameRng::seeded(5489);
    for value in expected {
        assert_eq!(rng.next_u32(), value);
    }
}

#[test]
fn snapshot_restores_across_twist_boundaries() {
    for draws in [0, 1, 623, 624, 625, 1247, 1248] {
        let mut rng = GameRng::seeded(0xdead_beef);
        for _ in 0..draws {
            rng.next_u32();
        }
        let state = rng.snapshot();
        let mut restored = GameRng::restore(state).unwrap();
        for _ in 0..1300 {
            assert_eq!(rng.next_u32(), restored.next_u32());
        }
    }
}

#[test]
fn legacy_bounded_branch_and_rejection_preserve_draw_count() {
    let mut rng = GameRng::seeded(5489);
    assert_eq!(rng.bounded(6), 3499211612 % 6);
    assert_eq!(rng.snapshot().index, 1);
    let mut rng = GameRng::seeded(5489);
    assert_eq!(rng.bounded(0x8000_0001), 581869302); // First value rejected, second accepted.
    assert_eq!(rng.snapshot().index, 2);
    let mut rng = GameRng::seeded(5489);
    assert_eq!(rng.bounded(0x2_0000), 3499211612 & 0x1_ffff);
    assert_eq!(rng.snapshot().index, 1);
}

#[test]
fn degenerate_ranges_and_dice_do_not_consume_rng() {
    let mut rng = GameRng::seeded(11);
    let state = rng.snapshot();
    assert_eq!(rng.bounded(0), 0);
    assert_eq!(rng.inclusive(9, 2), 9);
    assert_eq!(rng.inclusive_i32(2, -2), 2);
    assert_eq!(rng.bounded_i32(-1), 0);
    assert_eq!(rng.dice(0, 6), 0);
    assert_eq!(rng.dice(3, 0), 0);
    assert_eq!(rng.dice(3, 1), 3);
    assert_eq!(rng.range_f32(0.0), 0.0);
    assert_eq!(rng.range_f32(f32::NAN), 0.0);
    assert_eq!(rng.inclusive_f32(3.0, 2.0), 3.0);
    assert_eq!(state, rng.snapshot());
}

#[test]
fn full_integer_ranges_and_bit_interpretation() {
    assert_eq!(GameRng::seeded(5489).inclusive(0, u32::MAX), 3499211612);
    assert_eq!(
        GameRng::seeded(5489).inclusive_i32(i32::MIN, i32::MAX),
        1351727964
    );
    assert_eq!(GameRng::seeded(5489).next_i32(), -795755684);
    assert_eq!(
        GameRng::seeded(5489).next_u64(),
        (3499211612_u64 << 32) | 581869302
    );
}

#[test]
fn float_reference_and_range_bounds() {
    assert_eq!(GameRng::seeded(5489).unit_f32(), 0.8147237_f32);
    assert!((GameRng::seeded(5489).unit_f64() - 0.8147236863931789).abs() < 1e-15);
    let mut rng = GameRng::seeded(42);
    for _ in 0..5000 {
        let value = rng.range_f32(0.01);
        assert!((0.0..0.01).contains(&value));
        let value = rng.inclusive_f32(-200.0, 10.0);
        assert!((-200.0..=10.0).contains(&value));
    }
}

#[test]
fn rejects_invalid_state_shape_and_index() {
    assert!(
        GameRng::restore(RngState {
            words: vec![1; 623],
            index: 0
        })
        .is_err()
    );
    assert!(
        GameRng::restore(RngState {
            words: vec![1; 624],
            index: 625
        })
        .is_err()
    );
}
