/* SPDX-License-Identifier: GPL-2.0-only */
/* Generated from pristine Angband 4.2.6 f3082213b73f3e463e3d0d60bff4b00462beae6e.
 * Canonical private source coordinates; never completed-text lookup. */
#ifndef ANGBAND_WEB_COMBAT_DATA_H
#define ANGBAND_WEB_COMBAT_DATA_H
static const struct { int code; bool plural; const char *id; } ab_combat_repository_aliases[] = {
 {MON_MSG_NONE, false, "angband.combat.reaction.is_hurt.singular"},
 {MON_MSG_NONE, true, "angband.combat.reaction.are_hurt.plural"},
 {MON_MSG_DIE, false, "angband.combat.reaction.dies.singular"},
 {MON_MSG_DIE, true, "angband.combat.reaction.die.plural"},
 {MON_MSG_DESTROYED, false, "angband.combat.reaction.is_destroyed.singular"},
 {MON_MSG_DESTROYED, true, "angband.combat.reaction.are_destroyed.plural"},
 {MON_MSG_RESIST_A_LOT, false, "angband.combat.reaction.resists_a_lot.singular"},
 {MON_MSG_RESIST_A_LOT, true, "angband.combat.reaction.resist_a_lot.plural"},
 {MON_MSG_HIT_HARD, false, "angband.combat.reaction.is_hit_hard.singular"},
 {MON_MSG_HIT_HARD, true, "angband.combat.reaction.are_hit_hard.plural"},
 {MON_MSG_RESIST, false, "angband.combat.reaction.resists.singular"},
 {MON_MSG_RESIST, true, "angband.combat.reaction.resist.plural"},
 {MON_MSG_IMMUNE, false, "angband.combat.reaction.is_immune.singular"},
 {MON_MSG_IMMUNE, true, "angband.combat.reaction.are_immune.plural"},
 {MON_MSG_RESIST_SOMEWHAT, false, "angband.combat.reaction.resists_somewhat.singular"},
 {MON_MSG_RESIST_SOMEWHAT, true, "angband.combat.reaction.resist_somewhat.plural"},
 {MON_MSG_UNAFFECTED, false, "angband.combat.reaction.is_unaffected.singular"},
 {MON_MSG_UNAFFECTED, true, "angband.combat.reaction.are_unaffected.plural"},
 {MON_MSG_SPAWN, false, "angband.combat.reaction.spawns.singular"},
 {MON_MSG_SPAWN, true, "angband.combat.reaction.spawn.plural"},
 {MON_MSG_HEALTHIER, false, "angband.combat.reaction.looks_healthier.singular"},
 {MON_MSG_HEALTHIER, true, "angband.combat.reaction.look_healthier.plural"},
 {MON_MSG_FALL_ASLEEP, false, "angband.combat.reaction.falls_asleep.singular"},
 {MON_MSG_FALL_ASLEEP, true, "angband.combat.reaction.fall_asleep.plural"},
 {MON_MSG_WAKES_UP, false, "angband.combat.reaction.wakes_up.singular"},
 {MON_MSG_WAKES_UP, true, "angband.combat.reaction.wake_up.plural"},
 {MON_MSG_CRINGE_LIGHT, false, "angband.combat.reaction.cringes_from_the_light.singular"},
 {MON_MSG_CRINGE_LIGHT, true, "angband.combat.reaction.cringe_from_the_light.plural"},
 {MON_MSG_SHRIVEL_LIGHT, false, "angband.combat.reaction.shrivels_away_in_the_light.singular"},
 {MON_MSG_SHRIVEL_LIGHT, true, "angband.combat.reaction.shrivel_away_in_the_light.plural"},
 {MON_MSG_LOSE_SKIN, false, "angband.combat.reaction.loses_some_skin.singular"},
 {MON_MSG_LOSE_SKIN, true, "angband.combat.reaction.lose_some_skin.plural"},
 {MON_MSG_DISSOLVE, false, "angband.combat.reaction.dissolves.singular"},
 {MON_MSG_DISSOLVE, true, "angband.combat.reaction.dissolve.plural"},
 {MON_MSG_CATCH_FIRE, false, "angband.combat.reaction.catches_fire.singular"},
 {MON_MSG_CATCH_FIRE, true, "angband.combat.reaction.catch_fire.plural"},
 {MON_MSG_BADLY_FROZEN, false, "angband.combat.reaction.is_badly_frozen.singular"},
 {MON_MSG_BADLY_FROZEN, true, "angband.combat.reaction.are_badly_frozen.plural"},
 {MON_MSG_SHUDDER, false, "angband.combat.reaction.shudders.singular"},
 {MON_MSG_SHUDDER, true, "angband.combat.reaction.shudder.plural"},
 {MON_MSG_CHANGE, false, "angband.combat.reaction.changes.singular"},
 {MON_MSG_CHANGE, true, "angband.combat.reaction.change.plural"},
 {MON_MSG_DISAPPEAR, false, "angband.combat.reaction.disappears.singular"},
 {MON_MSG_DISAPPEAR, true, "angband.combat.reaction.disappear.plural"},
 {MON_MSG_MORE_DAZED, false, "angband.combat.reaction.is_even_more_stunned.singular"},
 {MON_MSG_MORE_DAZED, true, "angband.combat.reaction.are_even_more_stunned.plural"},
 {MON_MSG_DAZED, false, "angband.combat.reaction.is_stunned.singular"},
 {MON_MSG_DAZED, true, "angband.combat.reaction.are_stunned.plural"},
 {MON_MSG_NOT_DAZED, false, "angband.combat.reaction.is_no_longer_stunned.singular"},
 {MON_MSG_NOT_DAZED, true, "angband.combat.reaction.are_no_longer_stunned.plural"},
 {MON_MSG_MORE_CONFUSED, false, "angband.combat.reaction.looks_more_confused.singular"},
 {MON_MSG_MORE_CONFUSED, true, "angband.combat.reaction.look_more_confused.plural"},
 {MON_MSG_CONFUSED, false, "angband.combat.reaction.looks_confused.singular"},
 {MON_MSG_CONFUSED, true, "angband.combat.reaction.look_confused.plural"},
 {MON_MSG_NOT_CONFUSED, false, "angband.combat.reaction.is_no_longer_confused.singular"},
 {MON_MSG_NOT_CONFUSED, true, "angband.combat.reaction.are_no_longer_confused.plural"},
 {MON_MSG_MORE_SLOWED, false, "angband.combat.reaction.looks_more_slowed.singular"},
 {MON_MSG_MORE_SLOWED, true, "angband.combat.reaction.look_more_slowed.plural"},
 {MON_MSG_SLOWED, false, "angband.combat.reaction.looks_slowed.singular"},
 {MON_MSG_SLOWED, true, "angband.combat.reaction.look_slowed.plural"},
 {MON_MSG_NOT_SLOWED, false, "angband.combat.reaction.speeds_up.singular"},
 {MON_MSG_NOT_SLOWED, true, "angband.combat.reaction.speed_up.plural"},
 {MON_MSG_MORE_HASTED, false, "angband.combat.reaction.looks_even_faster.singular"},
 {MON_MSG_MORE_HASTED, true, "angband.combat.reaction.look_even_faster.plural"},
 {MON_MSG_HASTED, false, "angband.combat.reaction.starts_moving_faster.singular"},
 {MON_MSG_HASTED, true, "angband.combat.reaction.start_moving_faster.plural"},
 {MON_MSG_NOT_HASTED, false, "angband.combat.reaction.slows_down.singular"},
 {MON_MSG_NOT_HASTED, true, "angband.combat.reaction.slow_down.plural"},
 {MON_MSG_MORE_AFRAID, false, "angband.combat.reaction.looks_more_terrified.singular"},
 {MON_MSG_MORE_AFRAID, true, "angband.combat.reaction.look_more_terrified.plural"},
 {MON_MSG_FLEE_IN_TERROR, false, "angband.combat.reaction.flees_in_terror.singular"},
 {MON_MSG_FLEE_IN_TERROR, true, "angband.combat.reaction.flee_in_terror.plural"},
 {MON_MSG_NOT_AFRAID, false, "angband.combat.reaction.is_no_longer_afraid.singular"},
 {MON_MSG_NOT_AFRAID, true, "angband.combat.reaction.are_no_longer_afraid.plural"},
 {MON_MSG_HELD, false, "angband.combat.reaction.is_frozen_to_the_spot.singular"},
 {MON_MSG_HELD, true, "angband.combat.reaction.are_frozen_to_the_spot.plural"},
 {MON_MSG_NOT_HELD, false, "angband.combat.reaction.can_move_again.singular"},
 {MON_MSG_NOT_HELD, true, "angband.combat.reaction.can_move_again.plural"},
 {MON_MSG_DISEN, false, "angband.combat.reaction.seems_less_magical.singular"},
 {MON_MSG_DISEN, true, "angband.combat.reaction.seem_less_magical.plural"},
 {MON_MSG_NOT_DISEN, false, "angband.combat.reaction.seems_magical_again.singular"},
 {MON_MSG_NOT_DISEN, true, "angband.combat.reaction.seem_magical_again.plural"},
 {MON_MSG_COMMAND, false, "angband.combat.reaction.falls_under_your_spell.singular"},
 {MON_MSG_COMMAND, true, "angband.combat.reaction.falls_under_your_spell.plural"},
 {MON_MSG_NOT_COMMAND, false, "angband.combat.reaction.is_no_longer_under_your_control.singular"},
 {MON_MSG_NOT_COMMAND, true, "angband.combat.reaction.is_no_longer_under_your_control.plural"},
 {MON_MSG_SHAPE_FAIL, false, "angband.combat.reaction.shimmers_for_a_moment.singular"},
 {MON_MSG_SHAPE_FAIL, true, "angband.combat.reaction.shimmers_for_a_moment.plural"},
 {MON_MSG_MORIA_DEATH, false, "angband.combat.reaction.you_hear_a_scream_of_agony.singular"},
 {MON_MSG_MORIA_DEATH, true, "angband.combat.reaction.you_hear_several_screams_of_agony.plural"},
 {MON_MSG_DISINTEGRATES, false, "angband.combat.reaction.disintegrates.singular"},
 {MON_MSG_DISINTEGRATES, true, "angband.combat.reaction.disintegrate.plural"},
 {MON_MSG_FREEZE_SHATTER, false, "angband.combat.reaction.freezes_and_shatters.singular"},
 {MON_MSG_FREEZE_SHATTER, true, "angband.combat.reaction.freeze_and_shatter.plural"},
 {MON_MSG_MANA_DRAIN, false, "angband.combat.reaction.loses_some_mana.singular"},
 {MON_MSG_MANA_DRAIN, true, "angband.combat.reaction.lose_some_mana.plural"},
 {MON_MSG_BRIEF_PUZZLE, false, "angband.combat.reaction.looks_briefly_puzzled.singular"},
 {MON_MSG_BRIEF_PUZZLE, true, "angband.combat.reaction.look_briefly_puzzled.plural"},
 {MON_MSG_MAINTAIN_SHAPE, false, "angband.combat.reaction.maintains_the_same_shape.singular"},
 {MON_MSG_MAINTAIN_SHAPE, true, "angband.combat.reaction.maintain_the_same_shape.plural"},
 {MON_MSG_UNHARMED, false, "angband.combat.reaction.is_unharmed.singular"},
 {MON_MSG_UNHARMED, true, "angband.combat.reaction.are_unharmed.plural"},
 {MON_MSG_APPEAR, false, "angband.combat.reaction.appears.singular"},
 {MON_MSG_APPEAR, true, "angband.combat.reaction.appear.plural"},
 {MON_MSG_HIT_AND_RUN, false, "angband.combat.reaction.there_is_a_puff_of_smoke.singular"},
 {MON_MSG_HIT_AND_RUN, true, "angband.combat.reaction.there_is_a_puff_of_smoke.plural"},
 {MON_MSG_QUAKE_DEATH, false, "angband.combat.reaction.is_embedded_in_rock.singular"},
 {MON_MSG_QUAKE_DEATH, true, "angband.combat.reaction.are_embedded_in_rock.plural"},
 {MON_MSG_QUAKE_HURT, false, "angband.combat.reaction.wails_out_in_pain.singular"},
 {MON_MSG_QUAKE_HURT, true, "angband.combat.reaction.wail_out_in_pain.plural"},
};
static const struct { int index, band; const char *singular, *plural; } ab_combat_pain_aliases[] = {
 {1, 0, "angband.combat.reaction.shrugs_off_the_attack.singular", "angband.combat.reaction.shrug_off_the_attack.plural"},
 {1, 1, "angband.combat.reaction.grunts_with_pain.singular", "angband.combat.reaction.grunt_with_pain.plural"},
 {1, 2, "angband.combat.reaction.cries_out_in_pain.singular", "angband.combat.reaction.cry_out_in_pain.plural"},
 {1, 3, "angband.combat.reaction.screams_in_pain.singular", "angband.combat.reaction.scream_in_pain.plural"},
 {1, 4, "angband.combat.reaction.screams_in_agony.singular", "angband.combat.reaction.scream_in_agony.plural"},
 {1, 5, "angband.combat.reaction.writhes_in_agony.singular", "angband.combat.reaction.writhe_in_agony.plural"},
 {1, 6, "angband.combat.reaction.cries_out_feebly.singular", "angband.combat.reaction.cry_out_feebly.plural"},
 {2, 0, "angband.combat.reaction.barely_notices.singular", "angband.combat.reaction.barely_notice.plural"},
 {2, 1, "angband.combat.reaction.flinches.singular", "angband.combat.reaction.flinch.plural"},
 {2, 2, "angband.combat.reaction.squelches.singular", "angband.combat.reaction.squelch.plural"},
 {2, 3, "angband.combat.reaction.quivers_in_pain.singular", "angband.combat.reaction.quiver_in_pain.plural"},
 {2, 4, "angband.combat.reaction.writhes_about.singular", "angband.combat.reaction.writhe_about.plural"},
 {2, 5, "angband.combat.reaction.writhes_in_agony.singular", "angband.combat.reaction.writhe_in_agony.plural"},
 {2, 6, "angband.combat.reaction.jerks_limply.singular", "angband.combat.reaction.jerk_limply.plural"},
 {3, 0, "angband.combat.reaction.shrugs_off_the_attack.singular", "angband.combat.reaction.shrug_off_the_attack.plural"},
 {3, 1, "angband.combat.reaction.snarls_with_pain.singular", "angband.combat.reaction.snarl_with_pain.plural"},
 {3, 2, "angband.combat.reaction.yelps_in_pain.singular", "angband.combat.reaction.yelp_in_pain.plural"},
 {3, 3, "angband.combat.reaction.howls_in_pain.singular", "angband.combat.reaction.howl_in_pain.plural"},
 {3, 4, "angband.combat.reaction.howls_in_agony.singular", "angband.combat.reaction.howl_in_agony.plural"},
 {3, 5, "angband.combat.reaction.writhes_in_agony.singular", "angband.combat.reaction.writhe_in_agony.plural"},
 {3, 6, "angband.combat.reaction.yelps_feebly.singular", "angband.combat.reaction.yelp_feebly.plural"},
 {4, 0, "angband.combat.reaction.ignores_the_attack.singular", "angband.combat.reaction.ignore_the_attack.plural"},
 {4, 1, "angband.combat.reaction.grunts_with_pain.singular", "angband.combat.reaction.grunt_with_pain.plural"},
 {4, 2, "angband.combat.reaction.squeals_in_pain.singular", "angband.combat.reaction.squeal_in_pain.plural"},
 {4, 3, "angband.combat.reaction.shrieks_in_pain.singular", "angband.combat.reaction.shriek_in_pain.plural"},
 {4, 4, "angband.combat.reaction.shrieks_in_agony.singular", "angband.combat.reaction.shriek_in_agony.plural"},
 {4, 5, "angband.combat.reaction.writhes_in_agony.singular", "angband.combat.reaction.writhe_in_agony.plural"},
 {4, 6, "angband.combat.reaction.cries_out_feebly.singular", "angband.combat.reaction.cry_out_feebly.plural"},
 {5, 0, "angband.combat.reaction.barely_notices.singular", "angband.combat.reaction.barely_notice.plural"},
 {5, 1, "angband.combat.reaction.hisses.singular", "angband.combat.reaction.hiss.plural"},
 {5, 2, "angband.combat.reaction.rears_up_in_anger.singular", "angband.combat.reaction.rear_up_in_anger.plural"},
 {5, 3, "angband.combat.reaction.hisses_furiously.singular", "angband.combat.reaction.hiss_furiously.plural"},
 {5, 4, "angband.combat.reaction.writhes_about.singular", "angband.combat.reaction.writhe_about.plural"},
 {5, 5, "angband.combat.reaction.writhes_in_agony.singular", "angband.combat.reaction.writhe_in_agony.plural"},
 {5, 6, "angband.combat.reaction.jerks_limply.singular", "angband.combat.reaction.jerk_limply.plural"},
 {6, 0, "angband.combat.reaction.shrugs_off_the_attack.singular", "angband.combat.reaction.shrug_off_the_attack.plural"},
 {6, 1, "angband.combat.reaction.snarls.singular", "angband.combat.reaction.snarl.plural"},
 {6, 2, "angband.combat.reaction.growls_angrily.singular", "angband.combat.reaction.growl_angrily.plural"},
 {6, 3, "angband.combat.reaction.hisses_in_pain.singular", "angband.combat.reaction.hiss_in_pain.plural"},
 {6, 4, "angband.combat.reaction.mewls_in_pain.singular", "angband.combat.reaction.mewl_in_pain.plural"},
 {6, 5, "angband.combat.reaction.hisses_in_agony.singular", "angband.combat.reaction.hiss_in_agony.plural"},
 {6, 6, "angband.combat.reaction.mewls_pitifully.singular", "angband.combat.reaction.mewl_pitifully.plural"},
 {7, 0, "angband.combat.reaction.ignores_the_attack.singular", "angband.combat.reaction.ignore_the_attack.plural"},
 {7, 1, "angband.combat.reaction.drones_angrily.singular", "angband.combat.reaction.drone_angrily.plural"},
 {7, 2, "angband.combat.reaction.scuttles_about.singular", "angband.combat.reaction.scuttle_about.plural"},
 {7, 3, "angband.combat.reaction.twitches_in_pain.singular", "angband.combat.reaction.twitch_in_pain.plural"},
 {7, 4, "angband.combat.reaction.jerks_in_pain.singular", "angband.combat.reaction.jerk_in_pain.plural"},
 {7, 5, "angband.combat.reaction.jerks_in_agony.singular", "angband.combat.reaction.jerk_in_agony.plural"},
 {7, 6, "angband.combat.reaction.jerks_feebly.singular", "angband.combat.reaction.jerk_feebly.plural"},
 {8, 0, "angband.combat.reaction.shrugs_off_the_attack.singular", "angband.combat.reaction.shrug_off_the_attack.plural"},
 {8, 1, "angband.combat.reaction.flaps_angrily.singular", "angband.combat.reaction.flap_angrily.plural"},
 {8, 2, "angband.combat.reaction.jeers_in_pain.singular", "angband.combat.reaction.jeer_in_pain.plural"},
 {8, 3, "angband.combat.reaction.squawks_with_pain.singular", "angband.combat.reaction.squawk_with_pain.plural"},
 {8, 4, "angband.combat.reaction.twitters_in_agony.singular", "angband.combat.reaction.twitter_in_agony.plural"},
 {8, 5, "angband.combat.reaction.flutters_about.singular", "angband.combat.reaction.flutter_about.plural"},
 {8, 6, "angband.combat.reaction.chirps_feebly.singular", "angband.combat.reaction.chirp_feebly.plural"},
 {9, 0, "angband.combat.reaction.ignores_the_attack.singular", "angband.combat.reaction.ignore_the_attack.plural"},
 {9, 1, "angband.combat.reaction.jerks.singular", "angband.combat.reaction.jerk.plural"},
 {9, 2, "angband.combat.reaction.rattles.singular", "angband.combat.reaction.rattle.plural"},
 {9, 3, "angband.combat.reaction.clatters.singular", "angband.combat.reaction.clatter.plural"},
 {9, 4, "angband.combat.reaction.shakes.singular", "angband.combat.reaction.shake.plural"},
 {9, 5, "angband.combat.reaction.staggers.singular", "angband.combat.reaction.stagger.plural"},
 {9, 6, "angband.combat.reaction.crumples.singular", "angband.combat.reaction.crumple.plural"},
 {10, 0, "angband.combat.reaction.ignores_the_attack.singular", "angband.combat.reaction.ignore_the_attack.plural"},
 {10, 1, "angband.combat.reaction.grunts.singular", "angband.combat.reaction.grunt.plural"},
 {10, 2, "angband.combat.reaction.jerks.singular", "angband.combat.reaction.jerk.plural"},
 {10, 3, "angband.combat.reaction.moans.singular", "angband.combat.reaction.moan.plural"},
 {10, 4, "angband.combat.reaction.groans.singular", "angband.combat.reaction.groan.plural"},
 {10, 5, "angband.combat.reaction.hesitates.singular", "angband.combat.reaction.hesitate.plural"},
 {10, 6, "angband.combat.reaction.staggers.singular", "angband.combat.reaction.stagger.plural"},
 {11, 0, "angband.combat.reaction.ignores_the_attack.singular", "angband.combat.reaction.ignore_the_attack.plural"},
 {11, 1, "angband.combat.reaction.spins_fiercely.singular", "angband.combat.reaction.spin_fiercely.plural"},
 {11, 2, "angband.combat.reaction.swirls_about.singular", "angband.combat.reaction.swirl_about.plural"},
 {11, 3, "angband.combat.reaction.twists_around.singular", "angband.combat.reaction.twist_around.plural"},
 {11, 4, "angband.combat.reaction.spins_slowly.singular", "angband.combat.reaction.spin_slowly.plural"},
 {11, 5, "angband.combat.reaction.swirls_weakly.singular", "angband.combat.reaction.swirl_weakly.plural"},
 {11, 6, "angband.combat.reaction.twists_limply.singular", "angband.combat.reaction.twist_limply.plural"},
 {12, 0, "angband.combat.reaction.laughs_off_the_attack.singular", "angband.combat.reaction.laugh_off_the_attack.plural"},
 {12, 1, "angband.combat.reaction.sneers.singular", "angband.combat.reaction.sneer.plural"},
 {12, 2, "angband.combat.reaction.scowls.singular", "angband.combat.reaction.scowl.plural"},
 {12, 3, "angband.combat.reaction.bellows_in_rage.singular", "angband.combat.reaction.bellow_in_rage.plural"},
 {12, 4, "angband.combat.reaction.screams_in_fury.singular", "angband.combat.reaction.scream_in_fury.plural"},
 {12, 5, "angband.combat.reaction.grunts.singular", "angband.combat.reaction.grunt.plural"},
 {12, 6, "angband.combat.reaction.winces.singular", "angband.combat.reaction.wince.plural"},
};
static const struct { int index, power, field; const char *id; } ab_combat_spell_aliases[] = {
 {RSF_SHRIEK, 0, 4, "angband.combat.spell_lore.shriek_for_help"},
 {RSF_SHRIEK, 0, 0, "angband.combat.spell.makes_a_high_pitched_shriek"},
 {RSF_SHRIEK, 0, 1, "angband.combat.spell.something_makes_a_high_pitched_shriek"},
 {RSF_WHIP, 0, 4, "angband.combat.spell_lore.lash_you_if_nearby"},
 {RSF_WHIP, 0, 0, "angband.combat.spell.lashes_at_you_with_a_whip"},
 {RSF_WHIP, 0, 1, "angband.combat.spell.you_hear_a_crack"},
 {RSF_SPIT, 0, 4, "angband.combat.spell_lore.spit_at_you_from_a_distance"},
 {RSF_SPIT, 0, 0, "angband.combat.spell.spits_at_you"},
 {RSF_SPIT, 0, 1, "angband.combat.spell.you_hear_a_soft_sound"},
 {RSF_SHOT, 0, 4, "angband.combat.spell_lore.fling_pebbles"},
 {RSF_SHOT, 0, 0, "angband.combat.spell.slings_a_pebble_at"},
 {RSF_SHOT, 0, 1, "angband.combat.spell.you_hear_something_fly_through_the_air"},
 {RSF_SHOT, 0, 2, "angband.combat.spell.slings_a_pebble_but_misses"},
 {RSF_SHOT, 25, 4, "angband.combat.spell_lore.sling_lead_shots"},
 {RSF_SHOT, 25, 0, "angband.combat.spell.slings_a_leaden_pellet_at"},
 {RSF_SHOT, 25, 1, "angband.combat.spell.you_hear_something_whirl_through_the_air"},
 {RSF_SHOT, 25, 2, "angband.combat.spell.slings_a_leaden_pellet_but_misses"},
 {RSF_SHOT, 50, 4, "angband.combat.spell_lore.sling_seeker_shots"},
 {RSF_SHOT, 50, 0, "angband.combat.spell.slings_a_seeker_shot_at"},
 {RSF_SHOT, 50, 1, "angband.combat.spell.you_hear_something_heavy_whirl_through_the_air"},
 {RSF_SHOT, 50, 2, "angband.combat.spell.slings_a_seeker_shot_but_misses"},
 {RSF_ARROW, 0, 4, "angband.combat.spell_lore.fire_small_arrows"},
 {RSF_ARROW, 0, 0, "angband.combat.spell.fires_a_small_arrow"},
 {RSF_ARROW, 0, 1, "angband.combat.spell.you_hear_a_soft_twang"},
 {RSF_ARROW, 0, 2, "angband.combat.spell.fires_a_small_arrow_but_misses"},
 {RSF_ARROW, 16, 4, "angband.combat.spell_lore.fire_arrows"},
 {RSF_ARROW, 16, 0, "angband.combat.spell.fires_an_arrow"},
 {RSF_ARROW, 16, 1, "angband.combat.spell.you_hear_a_twang"},
 {RSF_ARROW, 16, 2, "angband.combat.spell.fires_an_arrow_but_misses"},
 {RSF_ARROW, 32, 4, "angband.combat.spell_lore.fire_large_arrows"},
 {RSF_ARROW, 32, 0, "angband.combat.spell.fires_a_large_arrow"},
 {RSF_ARROW, 32, 1, "angband.combat.spell.you_hear_a_loud_twang"},
 {RSF_ARROW, 32, 2, "angband.combat.spell.fires_a_large_arrow_but_misses"},
 {RSF_ARROW, 48, 4, "angband.combat.spell_lore.fire_seeker_arrows"},
 {RSF_ARROW, 48, 0, "angband.combat.spell.fires_a_seeker_arrow"},
 {RSF_ARROW, 48, 1, "angband.combat.spell.you_hear_a_loud_thwang"},
 {RSF_ARROW, 48, 2, "angband.combat.spell.fires_a_seeker_arrow_but_misses"},
 {RSF_BOLT, 0, 4, "angband.combat.spell_lore.fire_small_bolts"},
 {RSF_BOLT, 0, 0, "angband.combat.spell.fires_a_little_bolt"},
 {RSF_BOLT, 0, 1, "angband.combat.spell.you_hear_a_soft_twung"},
 {RSF_BOLT, 0, 2, "angband.combat.spell.fires_a_little_bolt_but_misses"},
 {RSF_BOLT, 25, 4, "angband.combat.spell_lore.fire_bolts"},
 {RSF_BOLT, 25, 0, "angband.combat.spell.fires_a_crossbow_bolt"},
 {RSF_BOLT, 25, 1, "angband.combat.spell.you_hear_a_twung"},
 {RSF_BOLT, 25, 2, "angband.combat.spell.fires_a_crossbow_bolt_but_misses"},
 {RSF_BOLT, 50, 4, "angband.combat.spell_lore.fire_seeker_bolts"},
 {RSF_BOLT, 50, 0, "angband.combat.spell.fires_a_seeker_bolt"},
 {RSF_BOLT, 50, 1, "angband.combat.spell.you_hear_a_loud_thwung"},
 {RSF_BOLT, 50, 2, "angband.combat.spell.fires_a_seeker_bolt_but_misses"},
 {RSF_BR_ACID, 0, 4, "angband.combat.spell_lore.acid"},
 {RSF_BR_ACID, 0, 0, "angband.combat.spell.breathes_acid"},
 {RSF_BR_ACID, 0, 1, "angband.combat.spell.you_hear_an_acrid_roar"},
 {RSF_BR_ELEC, 0, 4, "angband.combat.spell_lore.lightning"},
 {RSF_BR_ELEC, 0, 0, "angband.combat.spell.breathes_lightning"},
 {RSF_BR_ELEC, 0, 1, "angband.combat.spell.you_hear_a_crackling_roar"},
 {RSF_BR_FIRE, 0, 0, "angband.combat.spell.breathes_fire"},
 {RSF_BR_FIRE, 0, 1, "angband.combat.spell.you_hear_a_scorching_roar"},
 {RSF_BR_FIRE, 0, 4, "angband.combat.spell_lore.fire"},
 {RSF_BR_COLD, 0, 4, "angband.combat.spell_lore.frost"},
 {RSF_BR_COLD, 0, 0, "angband.combat.spell.breathes_frost"},
 {RSF_BR_COLD, 0, 1, "angband.combat.spell.you_hear_a_whooshing_roar"},
 {RSF_BR_POIS, 0, 4, "angband.combat.spell_lore.poison"},
 {RSF_BR_POIS, 0, 0, "angband.combat.spell.breathes_poison"},
 {RSF_BR_POIS, 0, 1, "angband.combat.spell.you_hear_a_sickening_roar"},
 {RSF_BR_NETH, 0, 4, "angband.combat.spell_lore.nether"},
 {RSF_BR_NETH, 0, 0, "angband.combat.spell.breathes_nether"},
 {RSF_BR_NETH, 0, 1, "angband.combat.spell.you_hear_an_eerie_roar"},
 {RSF_BR_LIGHT, 0, 4, "angband.combat.spell_lore.light"},
 {RSF_BR_LIGHT, 0, 0, "angband.combat.spell.breathes_light"},
 {RSF_BR_LIGHT, 0, 1, "angband.combat.spell.you_hear_a_humming_roar"},
 {RSF_BR_DARK, 0, 4, "angband.combat.spell_lore.darkness"},
 {RSF_BR_DARK, 0, 0, "angband.combat.spell.breathes_darkness"},
 {RSF_BR_DARK, 0, 1, "angband.combat.spell.you_hear_a_hushing_roar"},
 {RSF_BR_SOUN, 0, 4, "angband.combat.spell_lore.sound"},
 {RSF_BR_SOUN, 0, 0, "angband.combat.spell.breathes_sound"},
 {RSF_BR_SOUN, 0, 1, "angband.combat.spell.you_hear_an_echoing_roar"},
 {RSF_BR_CHAO, 0, 4, "angband.combat.spell_lore.chaos"},
 {RSF_BR_CHAO, 0, 0, "angband.combat.spell.breathes_chaos"},
 {RSF_BR_CHAO, 0, 1, "angband.combat.spell.you_hear_a_cacophonous_roar"},
 {RSF_BR_DISE, 0, 4, "angband.combat.spell_lore.disenchantment"},
 {RSF_BR_DISE, 0, 0, "angband.combat.spell.breathes_disenchantment"},
 {RSF_BR_DISE, 0, 1, "angband.combat.spell.you_hear_a_dissipating_roar"},
 {RSF_BR_NEXU, 0, 4, "angband.combat.spell_lore.nexus"},
 {RSF_BR_NEXU, 0, 0, "angband.combat.spell.breathes_nexus"},
 {RSF_BR_NEXU, 0, 1, "angband.combat.spell.you_hear_a_tearing_roar"},
 {RSF_BR_TIME, 0, 4, "angband.combat.spell_lore.time"},
 {RSF_BR_TIME, 0, 0, "angband.combat.spell.breathes_time"},
 {RSF_BR_TIME, 0, 1, "angband.combat.spell.you_remember_hearing_a_roar"},
 {RSF_BR_INER, 0, 4, "angband.combat.spell_lore.inertia"},
 {RSF_BR_INER, 0, 0, "angband.combat.spell.breathes_inertia"},
 {RSF_BR_INER, 0, 1, "angband.combat.spell.you_hear_a_thrumming_roar"},
 {RSF_BR_GRAV, 0, 4, "angband.combat.spell_lore.gravity"},
 {RSF_BR_GRAV, 0, 0, "angband.combat.spell.breathes_gravity"},
 {RSF_BR_GRAV, 0, 1, "angband.combat.spell.you_hear_a_heavy_roar"},
 {RSF_BR_SHAR, 0, 4, "angband.combat.spell_lore.shards"},
 {RSF_BR_SHAR, 0, 0, "angband.combat.spell.breathes_shards"},
 {RSF_BR_SHAR, 0, 1, "angband.combat.spell.you_hear_a_shattering_roar"},
 {RSF_BR_PLAS, 0, 4, "angband.combat.spell_lore.plasma"},
 {RSF_BR_PLAS, 0, 0, "angband.combat.spell.breathes_plasma"},
 {RSF_BR_PLAS, 0, 1, "angband.combat.spell.you_hear_a_hissing_roar"},
 {RSF_BR_WALL, 0, 4, "angband.combat.spell_lore.force"},
 {RSF_BR_WALL, 0, 0, "angband.combat.spell.breathes_force"},
 {RSF_BR_WALL, 0, 1, "angband.combat.spell.you_hear_a_staccato_roar"},
 {RSF_BR_MANA, 0, 4, "angband.combat.spell_lore.mana"},
 {RSF_BR_MANA, 0, 0, "angband.combat.spell.breathes_raw_magic"},
 {RSF_BR_MANA, 0, 1, "angband.combat.spell.you_hear_a_scintillating_roar"},
 {RSF_BOULDER, 0, 4, "angband.combat.spell_lore.throw_boulders"},
 {RSF_BOULDER, 0, 0, "angband.combat.spell.hurls_a_boulder"},
 {RSF_BOULDER, 0, 1, "angband.combat.spell.you_hear_a_grunt_of_exertion"},
 {RSF_BOULDER, 0, 2, "angband.combat.spell.hurls_a_boulder_but_misses"},
 {RSF_WEAVE, 0, 4, "angband.combat.spell_lore.weave_webs"},
 {RSF_WEAVE, 0, 0, "angband.combat.spell.weaves_a_web"},
 {RSF_WEAVE, 0, 1, "angband.combat.spell.you_hear_soft_rustling"},
 {RSF_BA_ACID, 0, 4, "angband.combat.spell_lore.produce_acid_balls"},
 {RSF_BA_ACID, 0, 0, "angband.combat.spell.casts_a_ball_of_acid"},
 {RSF_BA_ACID, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BA_ELEC, 0, 4, "angband.combat.spell_lore.produce_lightning_balls"},
 {RSF_BA_ELEC, 0, 0, "angband.combat.spell.casts_a_ball_of_lightning"},
 {RSF_BA_ELEC, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BA_FIRE, 0, 4, "angband.combat.spell_lore.produce_fire_balls"},
 {RSF_BA_FIRE, 0, 0, "angband.combat.spell.casts_a_ball_of_fire"},
 {RSF_BA_FIRE, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BA_FIRE, 80, 4, "angband.combat.spell_lore.produce_firestorms"},
 {RSF_BA_FIRE, 80, 0, "angband.combat.spell.conjures_up_a_firestorm"},
 {RSF_BA_FIRE, 80, 1, "angband.combat.spell.something_murmurs_deeply"},
 {RSF_BA_COLD, 0, 4, "angband.combat.spell_lore.produce_balls_of_cold"},
 {RSF_BA_COLD, 0, 0, "angband.combat.spell.casts_a_ball_of_frost"},
 {RSF_BA_COLD, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BA_COLD, 80, 4, "angband.combat.spell_lore.produce_blizzards"},
 {RSF_BA_COLD, 80, 0, "angband.combat.spell.calls_up_a_blizzard"},
 {RSF_BA_COLD, 80, 1, "angband.combat.spell.something_chants_coldly"},
 {RSF_BA_POIS, 0, 4, "angband.combat.spell_lore.produce_poison_balls"},
 {RSF_BA_POIS, 0, 0, "angband.combat.spell.casts_a_venomous_cloud"},
 {RSF_BA_POIS, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BA_POIS, 60, 4, "angband.combat.spell_lore.produce_storms_of_poison"},
 {RSF_BA_POIS, 60, 0, "angband.combat.spell.unleashes_a_storm_of_corrosive_toxins"},
 {RSF_BA_POIS, 60, 1, "angband.combat.spell.something_murmurs_viciously"},
 {RSF_BA_SHAR, 0, 4, "angband.combat.spell_lore.produce_shardstorms"},
 {RSF_BA_SHAR, 0, 0, "angband.combat.spell.calls_up_a_whirlwind_of_shards"},
 {RSF_BA_SHAR, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BA_SHAR, 70, 4, "angband.combat.spell_lore.invoke_storms_of_knives"},
 {RSF_BA_SHAR, 70, 0, "angband.combat.spell.invokes_a_storm_of_knives"},
 {RSF_BA_SHAR, 70, 1, "angband.combat.spell.something_chants_powerfully"},
 {RSF_BA_NETH, 0, 4, "angband.combat.spell_lore.produce_nether_balls"},
 {RSF_BA_NETH, 0, 0, "angband.combat.spell.casts_a_ball_of_nether"},
 {RSF_BA_NETH, 0, 1, "angband.combat.spell.something_whispers_nastily"},
 {RSF_BA_NETH, 80, 4, "angband.combat.spell_lore.produce_nether_storms"},
 {RSF_BA_NETH, 80, 0, "angband.combat.spell.creates_a_storm_of_nether_magics"},
 {RSF_BA_NETH, 80, 1, "angband.combat.spell.something_intones_with_deadly_menace"},
 {RSF_BA_WATE, 0, 4, "angband.combat.spell_lore.produce_water_balls"},
 {RSF_BA_WATE, 0, 0, "angband.combat.spell.creates_a_whirlpool_of_water"},
 {RSF_BA_WATE, 0, 1, "angband.combat.spell.something_gurgles"},
 {RSF_BA_MANA, 0, 4, "angband.combat.spell_lore.invoke_mana_storms"},
 {RSF_BA_MANA, 0, 0, "angband.combat.spell.invokes_a_storm_of_raw_magic"},
 {RSF_BA_MANA, 0, 1, "angband.combat.spell.something_screams_loudly"},
 {RSF_BA_HOLY, 0, 4, "angband.combat.spell_lore.cast_orbs_of_draining"},
 {RSF_BA_HOLY, 0, 0, "angband.combat.spell.casts_an_orb_of_draining"},
 {RSF_BA_HOLY, 0, 1, "angband.combat.spell.something_chants"},
 {RSF_BA_DARK, 0, 4, "angband.combat.spell_lore.produce_balls_of_darkness"},
 {RSF_BA_DARK, 0, 0, "angband.combat.spell.casts_a_ball_of_darkness"},
 {RSF_BA_DARK, 0, 1, "angband.combat.spell.something_mumbles_loudly"},
 {RSF_BA_DARK, 70, 4, "angband.combat.spell_lore.invoke_darkness_storms"},
 {RSF_BA_DARK, 70, 0, "angband.combat.spell.invokes_a_storm_of_darkness"},
 {RSF_BA_DARK, 70, 1, "angband.combat.spell.something_chants_powerfully"},
 {RSF_BA_LIGHT, 0, 4, "angband.combat.spell_lore.produce_balls_of_light"},
 {RSF_BA_LIGHT, 0, 0, "angband.combat.spell.casts_a_ball_of_light"},
 {RSF_BA_LIGHT, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BA_LIGHT, 70, 4, "angband.combat.spell_lore.invoke_starbursts"},
 {RSF_BA_LIGHT, 70, 0, "angband.combat.spell.invokes_a_starburst"},
 {RSF_BA_LIGHT, 70, 1, "angband.combat.spell.something_chants_powerfully"},
 {RSF_STORM, 0, 4, "angband.combat.spell_lore.create_storms"},
 {RSF_STORM, 0, 0, "angband.combat.spell.creates_a_little_storm"},
 {RSF_STORM, 0, 1, "angband.combat.spell.something_gurgles"},
 {RSF_STORM, 80, 4, "angband.combat.spell_lore.create_tempests"},
 {RSF_STORM, 80, 0, "angband.combat.spell.creates_a_tempest_of_wind_and_water"},
 {RSF_STORM, 80, 1, "angband.combat.spell.something_chants_fluidly"},
 {RSF_DRAIN_MANA, 0, 4, "angband.combat.spell_lore.drain_mana"},
 {RSF_DRAIN_MANA, 0, 0, "angband.combat.spell.drains_your_mana_away"},
 {RSF_DRAIN_MANA, 0, 1, "angband.combat.spell.something_moans"},
 {RSF_MIND_BLAST, 0, 4, "angband.combat.spell_lore.cause_mind_blasting"},
 {RSF_MIND_BLAST, 0, 0, "angband.combat.spell.gazes_at_with_psionic_energy"},
 {RSF_MIND_BLAST, 0, 1, "angband.combat.spell.something_focuses_on_your_mind"},
 {RSF_MIND_BLAST, 0, 3, "angband.combat.spell_save.you_shake_off_a_pounding_headache"},
 {RSF_BRAIN_SMASH, 0, 4, "angband.combat.spell_lore.cause_brain_smashing"},
 {RSF_BRAIN_SMASH, 0, 0, "angband.combat.spell.smashes_with_psionic_energy"},
 {RSF_BRAIN_SMASH, 0, 1, "angband.combat.spell.something_focuses_on_your_mind"},
 {RSF_BRAIN_SMASH, 0, 3, "angband.combat.spell_save.you_shake_off_a_splitting_migraine"},
 {RSF_WOUND, 0, 4, "angband.combat.spell_lore.cause_light_wounds"},
 {RSF_WOUND, 0, 0, "angband.combat.spell.points_at_and_curses"},
 {RSF_WOUND, 0, 1, "angband.combat.spell.something_curses"},
 {RSF_WOUND, 0, 3, "angband.combat.spell_save.your_body_tingles_briefly"},
 {RSF_WOUND, 16, 4, "angband.combat.spell_lore.cause_medium_wounds"},
 {RSF_WOUND, 16, 0, "angband.combat.spell.points_at_and_curses_horribly"},
 {RSF_WOUND, 16, 1, "angband.combat.spell.something_curses_horribly"},
 {RSF_WOUND, 16, 3, "angband.combat.spell_save.your_body_pulsates_briefly"},
 {RSF_WOUND, 32, 4, "angband.combat.spell_lore.cause_serious_wounds"},
 {RSF_WOUND, 32, 0, "angband.combat.spell.points_at_and_incants_terribly"},
 {RSF_WOUND, 32, 1, "angband.combat.spell.something_incants_terribly"},
 {RSF_WOUND, 32, 3, "angband.combat.spell_save.your_body_shakes_briefly"},
 {RSF_WOUND, 50, 4, "angband.combat.spell_lore.cause_critical_wounds"},
 {RSF_WOUND, 50, 0, "angband.combat.spell.points_at_screaming_words_of_peril"},
 {RSF_WOUND, 50, 1, "angband.combat.spell.something_cries_out_wrathfully"},
 {RSF_WOUND, 50, 3, "angband.combat.spell_save.your_body_shudders_briefly"},
 {RSF_WOUND, 80, 4, "angband.combat.spell_lore.cause_mortal_wounds"},
 {RSF_WOUND, 80, 0, "angband.combat.spell.points_at_and_screams_the_word_die"},
 {RSF_WOUND, 80, 1, "angband.combat.spell.something_screams_the_word_die"},
 {RSF_WOUND, 80, 3, "angband.combat.spell_save.your_body_spasms_briefly"},
 {RSF_BO_ACID, 0, 4, "angband.combat.spell_lore.produce_acid_bolts"},
 {RSF_BO_ACID, 0, 0, "angband.combat.spell.casts_a_bolt_of_acid"},
 {RSF_BO_ACID, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BO_ELEC, 0, 4, "angband.combat.spell_lore.produce_lightning_bolts"},
 {RSF_BO_ELEC, 0, 0, "angband.combat.spell.casts_a_bolt_of_lightning"},
 {RSF_BO_ELEC, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BO_FIRE, 0, 4, "angband.combat.spell_lore.produce_fire_bolts"},
 {RSF_BO_FIRE, 0, 0, "angband.combat.spell.casts_a_bolt_of_fire"},
 {RSF_BO_FIRE, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BO_COLD, 0, 4, "angband.combat.spell_lore.produce_frost_bolts"},
 {RSF_BO_COLD, 0, 0, "angband.combat.spell.casts_a_bolt_of_frost"},
 {RSF_BO_COLD, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BO_POIS, 0, 4, "angband.combat.spell_lore.produce_poison_bolts"},
 {RSF_BO_POIS, 0, 0, "angband.combat.spell.spews_a_stream_of_poison"},
 {RSF_BO_POIS, 0, 1, "angband.combat.spell.something_retches"},
 {RSF_BO_NETH, 0, 4, "angband.combat.spell_lore.produce_nether_bolts"},
 {RSF_BO_NETH, 0, 0, "angband.combat.spell.casts_a_bolt_of_nether"},
 {RSF_BO_NETH, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BO_WATE, 0, 4, "angband.combat.spell_lore.produce_water_bolts"},
 {RSF_BO_WATE, 0, 0, "angband.combat.spell.fires_a_jet_of_water"},
 {RSF_BO_WATE, 0, 1, "angband.combat.spell.something_gurgles"},
 {RSF_BO_MANA, 0, 4, "angband.combat.spell_lore.produce_mana_bolts"},
 {RSF_BO_MANA, 0, 0, "angband.combat.spell.casts_a_bolt_of_raw_magic"},
 {RSF_BO_MANA, 0, 1, "angband.combat.spell.something_screams"},
 {RSF_BO_PLAS, 0, 4, "angband.combat.spell_lore.produce_plasma_bolts"},
 {RSF_BO_PLAS, 0, 0, "angband.combat.spell.casts_a_bolt_of_plasma"},
 {RSF_BO_PLAS, 0, 1, "angband.combat.spell.something_screams"},
 {RSF_BO_ICE, 0, 4, "angband.combat.spell_lore.produce_ice_bolts"},
 {RSF_BO_ICE, 0, 0, "angband.combat.spell.shoots_a_spear_of_ice"},
 {RSF_BO_ICE, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_MISSILE, 0, 4, "angband.combat.spell_lore.produce_magic_missiles"},
 {RSF_MISSILE, 0, 0, "angband.combat.spell.fires_a_magic_missile"},
 {RSF_MISSILE, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BE_ELEC, 0, 4, "angband.combat.spell_lore.shoot_sparks_of_lightning"},
 {RSF_BE_ELEC, 0, 0, "angband.combat.spell.shoots_a_spark_of_lightning_at"},
 {RSF_BE_ELEC, 0, 1, "angband.combat.spell.you_feel_a_crackling_in_the_air"},
 {RSF_BE_NETH, 0, 4, "angband.combat.spell_lore.hurl_lances_of_nether"},
 {RSF_BE_NETH, 0, 0, "angband.combat.spell.hurls_a_lance_of_nether"},
 {RSF_BE_NETH, 0, 1, "angband.combat.spell.something_murmurs_a_deadly_word"},
 {RSF_BE_NETH, 80, 4, "angband.combat.spell_lore.shoot_rays_of_death"},
 {RSF_BE_NETH, 80, 0, "angband.combat.spell.unleashes_a_ray_of_death"},
 {RSF_BE_NETH, 80, 1, "angband.combat.spell.something_intones_with_deadly_menace"},
 {RSF_SCARE, 0, 4, "angband.combat.spell_lore.terrify"},
 {RSF_SCARE, 0, 0, "angband.combat.spell.conjures_up_scary_horrors"},
 {RSF_SCARE, 0, 1, "angband.combat.spell.something_makes_scary_noises"},
 {RSF_SCARE, 0, 3, "angband.combat.spell_save.you_fight_off_a_sense_of_dread"},
 {RSF_BLIND, 0, 4, "angband.combat.spell_lore.blind"},
 {RSF_BLIND, 0, 0, "angband.combat.spell.sets_off_a_blinding_flash"},
 {RSF_BLIND, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_BLIND, 0, 3, "angband.combat.spell_save.you_repel_a_sudden_bleariness"},
 {RSF_CONF, 0, 4, "angband.combat.spell_lore.confuse"},
 {RSF_CONF, 0, 0, "angband.combat.spell.conjures_up_weird_things"},
 {RSF_CONF, 0, 1, "angband.combat.spell.something_messes_with_your_mind"},
 {RSF_CONF, 0, 3, "angband.combat.spell_save.you_retain_your_presence_of_mind"},
 {RSF_SLOW, 0, 4, "angband.combat.spell_lore.slow"},
 {RSF_SLOW, 0, 0, "angband.combat.spell.tries_to_make_move_slowly"},
 {RSF_SLOW, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_SLOW, 0, 3, "angband.combat.spell_save.you_fight_off_a_sense_of_sluggishness"},
 {RSF_HOLD, 0, 4, "angband.combat.spell_lore.paralyze"},
 {RSF_HOLD, 0, 0, "angband.combat.spell.tries_to_make_stop_moving"},
 {RSF_HOLD, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_HOLD, 0, 3, "angband.combat.spell_save.you_fight_off_a_sense_of_torpidity"},
 {RSF_HASTE, 0, 4, "angband.combat.spell_lore.haste_self"},
 {RSF_HASTE, 0, 0, "angband.combat.spell.concentrates_on_body"},
 {RSF_HASTE, 0, 1, "angband.combat.spell.something_mutters"},
 {RSF_HEAL, 0, 4, "angband.combat.spell_lore.heal_self"},
 {RSF_HEAL, 0, 0, "angband.combat.spell.magically_starts_closing_wounds"},
 {RSF_HEAL, 0, 1, "angband.combat.spell.something_mutters"},
 {RSF_HEAL_KIN, 0, 4, "angband.combat.spell_lore.heal_kin"},
 {RSF_HEAL_KIN, 0, 0, "angband.combat.spell.tries_to_heal_comrades"},
 {RSF_HEAL_KIN, 0, 1, "angband.combat.spell.something_mutters"},
 {RSF_BLINK, 0, 4, "angband.combat.spell_lore.blink_self"},
 {RSF_BLINK, 0, 0, "angband.combat.spell.blinks"},
 {RSF_BLINK, 0, 1, "angband.combat.spell.something_mutters"},
 {RSF_TPORT, 0, 4, "angband.combat.spell_lore.teleport_self"},
 {RSF_TPORT, 0, 0, "angband.combat.spell.teleports_away"},
 {RSF_TPORT, 0, 1, "angband.combat.spell.something_makes_a_soft_pop"},
 {RSF_TELE_TO, 0, 4, "angband.combat.spell_lore.teleport_to"},
 {RSF_TELE_TO, 0, 0, "angband.combat.spell.commands_to_return"},
 {RSF_TELE_TO, 0, 1, "angband.combat.spell.something_commands_you_to_return"},
 {RSF_TELE_SELF_TO, 0, 4, "angband.combat.spell_lore.teleport_toward"},
 {RSF_TELE_SELF_TO, 0, 0, "angband.combat.spell.blinks_toward"},
 {RSF_TELE_SELF_TO, 0, 1, "angband.combat.spell.something_mutters"},
 {RSF_TELE_AWAY, 0, 4, "angband.combat.spell_lore.teleport_away"},
 {RSF_TELE_AWAY, 0, 0, "angband.combat.spell.commands_to_go_away"},
 {RSF_TELE_AWAY, 0, 1, "angband.combat.spell.something_commands_you_to_go_away"},
 {RSF_TELE_LEVEL, 0, 4, "angband.combat.spell_lore.teleport_level"},
 {RSF_TELE_LEVEL, 0, 0, "angband.combat.spell.commands_to_go_far_away"},
 {RSF_TELE_LEVEL, 0, 1, "angband.combat.spell.something_commands_you_to_go_far_away"},
 {RSF_TELE_LEVEL, 0, 3, "angband.combat.spell_save.you_feel_unstable_for_a_second_but_it_passes"},
 {RSF_DARKNESS, 0, 4, "angband.combat.spell_lore.create_darkness"},
 {RSF_DARKNESS, 0, 0, "angband.combat.spell.surrounds_in_darkness"},
 {RSF_DARKNESS, 0, 1, "angband.combat.spell.something_mumbles"},
 {RSF_TRAPS, 0, 4, "angband.combat.spell_lore.create_traps"},
 {RSF_TRAPS, 0, 0, "angband.combat.spell.cackles_evilly_about_traps"},
 {RSF_TRAPS, 0, 1, "angband.combat.spell.something_cackles_evilly"},
 {RSF_FORGET, 0, 4, "angband.combat.spell_lore.cause_amnesia"},
 {RSF_FORGET, 0, 0, "angband.combat.spell.tries_to_make_forget_things"},
 {RSF_FORGET, 0, 1, "angband.combat.spell.something_messes_with_your_mind"},
 {RSF_FORGET, 0, 3, "angband.combat.spell_save.you_retain_your_presence_of_mind"},
 {RSF_SHAPECHANGE, 0, 4, "angband.combat.spell_lore.change_shape"},
 {RSF_SHAPECHANGE, 0, 0, "angband.combat.spell.intones_strange_words"},
 {RSF_SHAPECHANGE, 0, 1, "angband.combat.spell.something_mutters"},
 {RSF_S_KIN, 0, 4, "angband.combat.spell_lore.summon_similar_monsters"},
 {RSF_S_KIN, 0, 0, "angband.combat.spell.summons_kin"},
 {RSF_S_KIN, 0, 1, "angband.combat.spell.you_hear_some_things_appear_nearby"},
 {RSF_S_MONSTER, 0, 4, "angband.combat.spell_lore.summon_a_monster"},
 {RSF_S_MONSTER, 0, 0, "angband.combat.spell.summons_a_companion"},
 {RSF_S_MONSTER, 0, 1, "angband.combat.spell.you_hear_something_appear_nearby"},
 {RSF_S_MONSTERS, 0, 4, "angband.combat.spell_lore.summon_monsters"},
 {RSF_S_MONSTERS, 0, 0, "angband.combat.spell.summons_some_friends"},
 {RSF_S_MONSTERS, 0, 1, "angband.combat.spell.you_hear_some_things_appear_nearby"},
 {RSF_S_ANIMAL, 0, 4, "angband.combat.spell_lore.summon_animals"},
 {RSF_S_ANIMAL, 0, 0, "angband.combat.spell.summons_animals"},
 {RSF_S_ANIMAL, 0, 1, "angband.combat.spell.you_hear_some_things_appear_nearby"},
 {RSF_S_SPIDER, 0, 4, "angband.combat.spell_lore.summon_spiders"},
 {RSF_S_SPIDER, 0, 0, "angband.combat.spell.summons_spiders"},
 {RSF_S_SPIDER, 0, 1, "angband.combat.spell.you_hear_chittering_things_appear_nearby"},
 {RSF_S_HOUND, 0, 4, "angband.combat.spell_lore.summon_hounds"},
 {RSF_S_HOUND, 0, 0, "angband.combat.spell.summons_hounds"},
 {RSF_S_HOUND, 0, 1, "angband.combat.spell.you_hear_barking_things_appear_nearby"},
 {RSF_S_HYDRA, 0, 4, "angband.combat.spell_lore.summon_hydras"},
 {RSF_S_HYDRA, 0, 0, "angband.combat.spell.summons_hydras"},
 {RSF_S_HYDRA, 0, 1, "angband.combat.spell.you_hear_some_things_appear_nearby"},
 {RSF_S_AINU, 0, 4, "angband.combat.spell_lore.summon_an_ainu"},
 {RSF_S_AINU, 0, 0, "angband.combat.spell.summons_an_ainu"},
 {RSF_S_AINU, 0, 1, "angband.combat.spell.you_hear_something_appear_nearby"},
 {RSF_S_DEMON, 0, 4, "angband.combat.spell_lore.summon_a_demon"},
 {RSF_S_DEMON, 0, 0, "angband.combat.spell.summons_a_demon"},
 {RSF_S_DEMON, 0, 1, "angband.combat.spell.you_hear_something_evil_appear_nearby"},
 {RSF_S_UNDEAD, 0, 4, "angband.combat.spell_lore.summon_an_undead"},
 {RSF_S_UNDEAD, 0, 0, "angband.combat.spell.summons_the_undead"},
 {RSF_S_UNDEAD, 0, 1, "angband.combat.spell.you_hear_something_creepy_appear_nearby"},
 {RSF_S_DRAGON, 0, 4, "angband.combat.spell_lore.summon_a_dragon"},
 {RSF_S_DRAGON, 0, 0, "angband.combat.spell.summons_a_dragon"},
 {RSF_S_DRAGON, 0, 1, "angband.combat.spell.you_hear_something_appear_nearby"},
 {RSF_S_HI_DEMON, 0, 4, "angband.combat.spell_lore.summon_greater_demons"},
 {RSF_S_HI_DEMON, 0, 0, "angband.combat.spell.summons_major_demons"},
 {RSF_S_HI_DEMON, 0, 1, "angband.combat.spell.you_hear_evil_things_appear_nearby"},
 {RSF_S_HI_UNDEAD, 0, 4, "angband.combat.spell_lore.summon_greater_undead"},
 {RSF_S_HI_UNDEAD, 0, 0, "angband.combat.spell.summons_fiends_of_darkness"},
 {RSF_S_HI_UNDEAD, 0, 1, "angband.combat.spell.you_hear_creepy_things_appear_nearby"},
 {RSF_S_HI_DRAGON, 0, 4, "angband.combat.spell_lore.summon_ancient_dragons"},
 {RSF_S_HI_DRAGON, 0, 0, "angband.combat.spell.summons_ancient_dragons"},
 {RSF_S_HI_DRAGON, 0, 1, "angband.combat.spell.you_hear_powerful_things_appear_nearby"},
 {RSF_S_WRAITH, 0, 4, "angband.combat.spell_lore.summon_ringwraiths"},
 {RSF_S_WRAITH, 0, 0, "angband.combat.spell.summons_ringwraiths"},
 {RSF_S_WRAITH, 0, 1, "angband.combat.spell.you_hear_powerful_things_appear_nearby"},
 {RSF_S_UNIQUE, 0, 4, "angband.combat.spell_lore.summon_uniques"},
 {RSF_S_UNIQUE, 0, 0, "angband.combat.spell.summons_servants"},
 {RSF_S_UNIQUE, 0, 1, "angband.combat.spell.you_hear_powerful_things_appear_nearby"},
};
static const struct { int race, index, kind; const char *id; } ab_combat_alternate_aliases[] = {
 {60, RSF_DRAIN_MANA, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {61, RSF_DRAIN_MANA, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {103, RSF_WOUND, MON_ALTMSG_SEEN, "angband.combat.spell.caws_three_times"},
 {103, RSF_WOUND, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_caws_three_times"},
 {127, RSF_DRAIN_MANA, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {164, RSF_DRAIN_MANA, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {188, RSF_BLIND, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {194, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_hums_softly"},
 {194, RSF_DARKNESS, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_hums_softly"},
 {194, RSF_SLOW, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_hums_softly"},
 {229, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_yips"},
 {246, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {262, RSF_SLOW, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_rumbles"},
 {265, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_chitters"},
 {265, RSF_TELE_SELF_TO, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_chitters"},
 {266, RSF_DRAIN_MANA, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {285, RSF_SLOW, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_rumbles"},
 {285, RSF_BO_ACID, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_rumbles"},
 {297, RSF_DARKNESS, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_howls"},
 {351, RSF_HOLD, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_hisses"},
 {351, RSF_BLIND, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_hisses"},
 {353, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {392, RSF_SHRIEK, MON_ALTMSG_SEEN, "angband.combat.spell.the_baleful_presence_of_inspires_your_enemies"},
 {392, RSF_DRAIN_MANA, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_drains_your_mana_away"},
 {392, RSF_HOLD, MON_ALTMSG_UNSEEN, "angband.combat.spell.your_muscles_lock_up_for_no_apparent_reason"},
 {392, RSF_SHRIEK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_inspires_your_enemies"},
 {394, RSF_BO_ELEC, MON_ALTMSG_UNSEEN, "angband.combat.spell.the_constant_crackling_subsides_briefly_and_then_resumes"},
 {394, RSF_TELE_SELF_TO, MON_ALTMSG_UNSEEN, "angband.combat.spell.the_constant_crackling_subsides_briefly_and_then_resumes"},
 {418, RSF_WOUND, MON_ALTMSG_SEEN, "angband.combat.spell.crackles_softly"},
 {418, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_crackles_softly"},
 {418, RSF_WOUND, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_crackles_softly"},
 {425, RSF_SLOW, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_chitters"},
 {425, RSF_BLIND, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_chitters"},
 {470, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {473, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {474, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {514, RSF_BLIND, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_rumbles"},
 {514, RSF_SLOW, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_rumbles"},
 {556, RSF_WOUND, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_clatters"},
 {556, RSF_DRAIN_MANA, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_clatters"},
 {556, RSF_BA_NETH, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_clatters"},
 {566, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {567, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {568, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {582, RSF_BA_ELEC, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_rumbles"},
 {582, RSF_BA_FIRE, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_rumbles"},
 {582, RSF_BO_PLAS, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_rumbles"},
 {584, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_slurps"},
 {589, RSF_BLINK, MON_ALTMSG_UNSEEN, "angband.combat.spell.something_hisses"},
};
static const struct { int code; const char *id; } ab_combat_projection_aliases[] = {
 {PROJ_ACID, "angband.combat.projection_lash.acid"},
 {PROJ_ELEC, "angband.combat.projection_lash.lightning"},
 {PROJ_FIRE, "angband.combat.projection_lash.fire"},
 {PROJ_COLD, "angband.combat.projection_lash.frost"},
 {PROJ_POIS, "angband.combat.projection_lash.venom"},
 {PROJ_LIGHT, "angband.combat.projection_lash.brightness"},
 {PROJ_DARK, "angband.combat.projection_lash.blackness"},
 {PROJ_SOUND, "angband.combat.projection_lash.sound"},
 {PROJ_SHARD, "angband.combat.projection_lash.razors"},
 {PROJ_NEXUS, "angband.combat.projection_lash.dislocation"},
 {PROJ_NETHER, "angband.combat.projection_lash.withering"},
 {PROJ_CHAOS, "angband.combat.projection_lash.confusion"},
 {PROJ_DISEN, "angband.combat.projection_lash.unmagic"},
 {PROJ_WATER, "angband.combat.projection_lash.water"},
 {PROJ_ICE, "angband.combat.projection_lash.icicles"},
 {PROJ_GRAVITY, "angband.combat.projection_lash.gravity"},
 {PROJ_INERTIA, "angband.combat.projection_lash.lassitude"},
 {PROJ_FORCE, "angband.combat.projection_lash.impact"},
 {PROJ_TIME, "angband.combat.projection_lash.ruination"},
 {PROJ_PLASMA, "angband.combat.projection_lash.living_fire"},
 {PROJ_METEOR, "angband.combat.projection_lash.meteoric_iron"},
 {PROJ_MANA, "angband.combat.projection_lash.raw_magic"},
 {PROJ_HOLY_ORB, "angband.combat.projection_lash.holy_power"},
};
static const struct { const char *method; int source_ordinal; const char *id; } ab_combat_blow_aliases[] = {
 {"HIT", 0, "angband.combat.blow_action.hits"},
 {"TOUCH", 0, "angband.combat.blow_action.touches"},
 {"PUNCH", 0, "angband.combat.blow_action.punches"},
 {"KICK", 0, "angband.combat.blow_action.kicks"},
 {"CLAW", 0, "angband.combat.blow_action.claws"},
 {"BITE", 0, "angband.combat.blow_action.bites"},
 {"STING", 0, "angband.combat.blow_action.stings"},
 {"BUTT", 0, "angband.combat.blow_action.butts"},
 {"CRUSH", 0, "angband.combat.blow_action.crushes"},
 {"ENGULF", 0, "angband.combat.blow_action.engulfs"},
 {"CRAWL", 0, "angband.combat.blow_action.crawls_on"},
 {"DROOL", 0, "angband.combat.blow_action.drools_on"},
 {"SPIT", 0, "angband.combat.blow_action.spits_on"},
 {"GAZE", 0, "angband.combat.blow_action.gazes_at"},
 {"WAIL", 0, "angband.combat.blow_action.wails_at"},
 {"SPORE", 0, "angband.combat.blow_action.releases_spores_at"},
 {"BEG", 0, "angband.combat.blow_action.begs_for_money"},
 {"INSULT", 0, "angband.combat.blow_action.insults"},
 {"INSULT", 1, "angband.combat.blow_action.insults_mother"},
 {"INSULT", 2, "angband.combat.blow_action.gives_the_finger"},
 {"INSULT", 3, "angband.combat.blow_action.humiliates"},
 {"INSULT", 4, "angband.combat.blow_action.defiles"},
 {"INSULT", 5, "angband.combat.blow_action.dances_around"},
 {"INSULT", 6, "angband.combat.blow_action.makes_obscene_gestures"},
 {"INSULT", 7, "angband.combat.blow_action.moons"},
 {"MOAN", 0, "angband.combat.blow_action.wants_his_mushrooms_back"},
 {"MOAN", 1, "angband.combat.blow_action.tells_to_get_off_his_land"},
 {"MOAN", 2, "angband.combat.blow_action.looks_for_his_dogs"},
 {"MOAN", 3, "angband.combat.blow_action.says_did_you_kill_my_fang"},
 {"MOAN", 4, "angband.combat.blow_action.asks_do_you_want_to_buy_any_mushrooms"},
 {"MOAN", 5, "angband.combat.blow_action.seems_sad_about_something"},
 {"MOAN", 6, "angband.combat.blow_action.asks_if_seen_his_dogs"},
 {"MOAN", 7, "angband.combat.blow_action.mumbles_something_about_mushrooms"},
};
static const struct { const char *method, *id; } ab_combat_blow_lore_aliases[] = {
 {"HIT", "angband.combat.blow_lore.hit"},
 {"TOUCH", "angband.combat.blow_lore.touch"},
 {"PUNCH", "angband.combat.blow_lore.punch"},
 {"KICK", "angband.combat.blow_lore.kick"},
 {"CLAW", "angband.combat.blow_lore.claw"},
 {"BITE", "angband.combat.blow_lore.bite"},
 {"STING", "angband.combat.blow_lore.sting"},
 {"BUTT", "angband.combat.blow_lore.butt"},
 {"CRUSH", "angband.combat.blow_lore.crush"},
 {"ENGULF", "angband.combat.blow_lore.engulf"},
 {"CRAWL", "angband.combat.blow_lore.crawl_on_you"},
 {"DROOL", "angband.combat.blow_lore.drool_on_you"},
 {"SPIT", "angband.combat.blow_lore.spit"},
 {"GAZE", "angband.combat.blow_lore.gaze"},
 {"WAIL", "angband.combat.blow_lore.wail"},
 {"SPORE", "angband.combat.blow_lore.release_spores"},
 {"BEG", "angband.combat.blow_lore.beg"},
 {"INSULT", "angband.combat.blow_lore.insult"},
 {"MOAN", "angband.combat.blow_lore.moan"},
};
#endif
