/* SPDX-License-Identifier: GPL-2.0-only */
/* Source enum + immutable field verification; not completed-English lookup. */
static const struct { int command; const char *lexeme,*id; } ab_check_commands[] = {
 {CMD_LOADFILE,"load a savefile","interface.check.command.loadfile"},
 {CMD_NEWGAME,"start a new game","interface.check.command.newgame"},
 {CMD_BIRTH_INIT,"start the character birth process","interface.check.command.birth_init"},
 {CMD_BIRTH_RESET,"go back to the beginning","interface.check.command.birth_reset"},
 {CMD_CHOOSE_RACE,"select race","interface.check.command.choose_race"},
 {CMD_CHOOSE_CLASS,"select class","interface.check.command.choose_class"},
 {CMD_BUY_STAT,"buy points in a stat","interface.check.command.buy_stat"},
 {CMD_SELL_STAT,"sell points in a stat","interface.check.command.sell_stat"},
 {CMD_RESET_STATS,"reset stats","interface.check.command.reset_stats"},
 {CMD_REFRESH_STATS,"refresh stats","interface.check.command.refresh_stats"},
 {CMD_ROLL_STATS,"roll new stats","interface.check.command.roll_stats"},
 {CMD_PREV_STATS,"use previously rolled stats","interface.check.command.prev_stats"},
 {CMD_NAME_CHOICE,"choose name","interface.check.command.name_choice"},
 {CMD_HISTORY_CHOICE,"write history","interface.check.command.history_choice"},
 {CMD_ACCEPT_CHARACTER,"accept character","interface.check.command.accept_character"},
 {CMD_GO_UP,"go up stairs","interface.check.command.go_up"},
 {CMD_GO_DOWN,"go down stairs","interface.check.command.go_down"},
 {CMD_WALK,"walk","interface.check.command.walk"},
 {CMD_RUN,"run","interface.check.command.run"},
 {CMD_EXPLORE,"explore","interface.check.command.explore"},
 {CMD_NAVIGATE_UP,"navigate up","interface.check.command.navigate_up"},
 {CMD_NAVIGATE_DOWN,"navigate down","interface.check.command.navigate_down"},
 {CMD_JUMP,"jump","interface.check.command.jump"},
 {CMD_OPEN,"open","interface.check.command.open"},
 {CMD_CLOSE,"close","interface.check.command.close"},
 {CMD_TUNNEL,"tunnel","interface.check.command.tunnel"},
 {CMD_HOLD,"stay still","interface.check.command.hold"},
 {CMD_DISARM,"disarm","interface.check.command.disarm"},
 {CMD_ALTER,"alter","interface.check.command.alter"},
 {CMD_STEAL,"steal","interface.check.command.steal"},
 {CMD_REST,"rest","interface.check.command.rest"},
 {CMD_SLEEP,"sleep","interface.check.command.sleep"},
 {CMD_PATHFIND,"walk","interface.check.command.pathfind"},
 {CMD_PICKUP,"pickup","interface.check.command.pickup"},
 {CMD_AUTOPICKUP,"autopickup","interface.check.command.autopickup"},
 {CMD_WIELD,"wear or wield","interface.check.command.wield"},
 {CMD_TAKEOFF,"take off","interface.check.command.takeoff"},
 {CMD_DROP,"drop","interface.check.command.drop"},
 {CMD_UNINSCRIBE,"un-inscribe","interface.check.command.uninscribe"},
 {CMD_AUTOINSCRIBE,"autoinscribe","interface.check.command.autoinscribe"},
 {CMD_EAT,"eat","interface.check.command.eat"},
 {CMD_QUAFF,"quaff","interface.check.command.quaff"},
 {CMD_USE_ROD,"zap","interface.check.command.use_rod"},
 {CMD_USE_STAFF,"use","interface.check.command.use_staff"},
 {CMD_USE_WAND,"aim","interface.check.command.use_wand"},
 {CMD_READ_SCROLL,"read","interface.check.command.read_scroll"},
 {CMD_ACTIVATE,"activate","interface.check.command.activate"},
 {CMD_REFILL,"refuel with","interface.check.command.refill"},
 {CMD_FIRE,"fire","interface.check.command.fire"},
 {CMD_THROW,"throw","interface.check.command.throw"},
 {CMD_INSCRIBE,"inscribe","interface.check.command.inscribe"},
 {CMD_STUDY,"study","interface.check.command.study"},
 {CMD_CAST,"cast","interface.check.command.cast"},
 {CMD_SELL,"sell","interface.check.command.sell"},
 {CMD_STASH,"stash","interface.check.command.stash"},
 {CMD_BUY,"buy","interface.check.command.buy"},
 {CMD_RETRIEVE,"retrieve","interface.check.command.retrieve"},
 {CMD_USE,"use","interface.check.command.use"},
 {CMD_RETIRE,"retire character","interface.check.command.retire"},
 {CMD_HELP,"help","interface.check.command.help"},
 {CMD_REPEAT,"repeat","interface.check.command.repeat"},
 {CMD_COMMAND_MONSTER,"make a monster act","interface.check.command.command_monster"},
 {CMD_SPOIL_ARTIFACT,"generate spoiler file for artifacts","interface.check.command.spoil_artifact"},
 {CMD_SPOIL_MON,"generate spoiler file for monsters","interface.check.command.spoil_mon"},
 {CMD_SPOIL_MON_BRIEF,"generate brief spoiler file for monsters","interface.check.command.spoil_mon_brief"},
 {CMD_SPOIL_OBJ,"generate spoiler file for objects","interface.check.command.spoil_obj"},
 {CMD_WIZ_ACQUIRE,"acquire objects","interface.check.command.wiz_acquire"},
 {CMD_WIZ_ADVANCE,"make character powerful","interface.check.command.wiz_advance"},
 {CMD_WIZ_BANISH,"banish nearby monsters","interface.check.command.wiz_banish"},
 {CMD_WIZ_CHANGE_ITEM_QUANTITY,"change number of an item","interface.check.command.wiz_change_item_quantity"},
 {CMD_WIZ_COLLECT_DISCONNECT_STATS,"collect statistics about disconnected levels","interface.check.command.wiz_collect_disconnect_stats"},
 {CMD_WIZ_COLLECT_OBJ_MON_STATS,"collect object/monster statistics","interface.check.command.wiz_collect_obj_mon_stats"},
 {CMD_WIZ_COLLECT_PIT_STATS,"collect pit statistics","interface.check.command.wiz_collect_pit_stats"},
 {CMD_WIZ_CREATE_ALL_ARTIFACT,"create all artifacts","interface.check.command.wiz_create_all_artifact"},
 {CMD_WIZ_CREATE_ALL_ARTIFACT_FROM_TVAL,"create all artifacts of a tval","interface.check.command.wiz_create_all_artifact_from_tval"},
 {CMD_WIZ_CREATE_ALL_OBJ,"create all objects","interface.check.command.wiz_create_all_obj"},
 {CMD_WIZ_CREATE_ALL_OBJ_FROM_TVAL,"create all objects of a tval","interface.check.command.wiz_create_all_obj_from_tval"},
 {CMD_WIZ_CREATE_ARTIFACT,"create artifact","interface.check.command.wiz_create_artifact"},
 {CMD_WIZ_CREATE_OBJ,"create object","interface.check.command.wiz_create_obj"},
 {CMD_WIZ_CREATE_TRAP,"create trap","interface.check.command.wiz_create_trap"},
 {CMD_WIZ_CURE_ALL,"cure everything","interface.check.command.wiz_cure_all"},
 {CMD_WIZ_CURSE_ITEM,"change a curse on an item","interface.check.command.wiz_curse_item"},
 {CMD_WIZ_DETECT_ALL_LOCAL,"detect everything nearby","interface.check.command.wiz_detect_all_local"},
 {CMD_WIZ_DETECT_ALL_MONSTERS,"detect all monsters","interface.check.command.wiz_detect_all_monsters"},
 {CMD_WIZ_DISPLAY_KEYLOG,"display keystroke log","interface.check.command.wiz_display_keylog"},
 {CMD_WIZ_DUMP_LEVEL_MAP,"write map of level","interface.check.command.wiz_dump_level_map"},
 {CMD_WIZ_EDIT_PLAYER_EXP,"change the player's experience","interface.check.command.wiz_edit_player_exp"},
 {CMD_WIZ_EDIT_PLAYER_GOLD,"change the player's gold","interface.check.command.wiz_edit_player_gold"},
 {CMD_WIZ_EDIT_PLAYER_START,"start editing the player","interface.check.command.wiz_edit_player_start"},
 {CMD_WIZ_EDIT_PLAYER_STAT,"edit one of the player's stats","interface.check.command.wiz_edit_player_stat"},
 {CMD_WIZ_HIT_ALL_LOS,"hit all monsters in LOS","interface.check.command.wiz_hit_all_los"},
 {CMD_WIZ_INCREASE_EXP,"increase experience","interface.check.command.wiz_increase_exp"},
 {CMD_WIZ_JUMP_LEVEL,"jump to a level","interface.check.command.wiz_jump_level"},
 {CMD_WIZ_LEARN_OBJECT_KINDS,"learn about kinds of objects","interface.check.command.wiz_learn_object_kinds"},
 {CMD_WIZ_MAGIC_MAP,"map local area","interface.check.command.wiz_magic_map"},
 {CMD_WIZ_PEEK_NOISE_SCENT,"peek at noise and scent","interface.check.command.wiz_peek_noise_scent"},
 {CMD_WIZ_PERFORM_EFFECT,"perform an effect","interface.check.command.wiz_perform_effect"},
 {CMD_WIZ_PLAY_ITEM,"play with item","interface.check.command.wiz_play_item"},
 {CMD_WIZ_PUSH_OBJECT,"push objects from square","interface.check.command.wiz_push_object"},
 {CMD_WIZ_QUERY_FEATURE,"highlight specific feature","interface.check.command.wiz_query_feature"},
 {CMD_WIZ_QUERY_SQUARE_FLAG,"query square flag","interface.check.command.wiz_query_square_flag"},
 {CMD_WIZ_QUIT_NO_SAVE,"quit without saving","interface.check.command.wiz_quit_no_save"},
 {CMD_WIZ_RECALL_MONSTER,"recall monster","interface.check.command.wiz_recall_monster"},
 {CMD_WIZ_RERATE,"rerate hitpoints","interface.check.command.wiz_rerate"},
 {CMD_WIZ_REROLL_ITEM,"reroll an item","interface.check.command.wiz_reroll_item"},
 {CMD_WIZ_STAT_ITEM,"get statistics for an item","interface.check.command.wiz_stat_item"},
 {CMD_WIZ_SUMMON_NAMED,"summon specific monster","interface.check.command.wiz_summon_named"},
 {CMD_WIZ_SUMMON_RANDOM,"summon random monsters","interface.check.command.wiz_summon_random"},
 {CMD_WIZ_TELEPORT_RANDOM,"teleport","interface.check.command.wiz_teleport_random"},
 {CMD_WIZ_TELEPORT_TO,"teleport to location","interface.check.command.wiz_teleport_to"},
 {CMD_WIZ_TWEAK_ITEM,"modify item attributes","interface.check.command.wiz_tweak_item"},
 {CMD_WIZ_WIPE_RECALL,"erase monster recall","interface.check.command.wiz_wipe_recall"},
 {CMD_WIZ_WIZARD_LIGHT,"wizard light the level","interface.check.command.wiz_wizard_light"},
};
