"""Verify the final source-only author refresh and preserved complete history."""
import hashlib
import json
from pathlib import Path

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[2]
OUT=HERE/'generated'
HISTORY=HERE/'source-history'


def load(path):return json.loads(path.read_text('utf-8'))
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    refresh=load(OUT/'author-provenance-refresh.json')
    complete=refresh['prior_complete_proposal_checkpoint']
    checkpoint_path=ROOT/complete['path']
    checkpoint=load(checkpoint_path)
    assert sha(checkpoint_path)==complete['sha256']
    old_root=checkpoint_path.parent/'proposal'
    for row in checkpoint['files']:
        assert sha(old_root/row['path'])==row['sha256']
        assert (old_root/row['path']).stat().st_size==row['bytes']
    old=load(old_root/'generated/catalog.source-reviewed.json')
    current=load(OUT/'catalog.source-reviewed.json')
    assert old['en']==current['en'] and old['argument_schemas']==current['argument_schemas']
    assert old['ja'].keys()==current['ja'].keys()
    review_path=ROOT/'locales/phase6/random-selected-text-batches-13-16.revised-source-verification.json'
    assert sha(review_path)=='5a38aca07ee0dac218e319140412523cacab2a686c57411678444d0a697807af'
    review=load(review_path)
    expected={r['id']:(r['initial_japanese'],r['revised_japanese']) for r in review['accepted_changes']}
    for ident,(before,after) in list(expected.items()):
        expected['variant.quoted.'+ident]=('「'+before+'」','「'+after+'」')
    actual={ident:(old['ja'][ident],value) for ident,value in current['ja'].items() if old['ja'][ident]!=value}
    assert actual==expected and len(actual)==6
    unchanged=[]
    for row in checkpoint['files']:
        name=row['path']
        if (name.startswith('generated/') and name not in (
                'generated/catalog.source-reviewed.json','generated/manifest.json','generated/determinism.json')) \
                or name in ('nh_resource_origin.c','nh_resource_origin.h'):
            assert sha(HERE/name)==row['sha256'],name+' original proposal artifact changed'
            unchanged.append(name)
    proof=load(OUT/'author-refresh-verification.json')
    assert proof['current_manifest_sha256']==sha(OUT/'manifest.json')
    assert proof['current_catalog_sha256']==sha(OUT/'catalog.source-reviewed.json')
    assert proof['current_verification_sha256']==sha(OUT/'verification.json')
    assert proof['unchanged_original_c_offset_owner_and_report_artifacts']==unchanged
    first=load(HISTORY/'refresh-first-generation.json')
    determinism=load(OUT/'determinism.json')
    assert determinism['two_full_generations_byte_identical'] is True
    assert determinism['first_generation_record_sha256']==sha(HISTORY/'refresh-first-generation.json')
    for name,digest in first['files'].items():
        if name!='determinism.json':assert sha(OUT/name)==digest,name+' final regenerated bytes changed'
    for name,digest in determinism['artifacts'].items():assert sha(OUT/name)==digest
    verification=load(OUT/'verification.json')
    assert verification['checks']['assertions']==54473 and verification['error_count']==0
    manifest=load(OUT/'manifest.json')
    assert manifest['counts']['runtime_approved']==0 and manifest['integration_applied'] is False
    assert manifest['compiler_run'] is manifest['browser_run'] is False
    report={'status':'final-source-only-refresh-verified','source_only':True,
            'preserved_complete_proposal_files':len(checkpoint['files']),
            'generated_files_compared_between_generations':first['file_count'],
            'source_assertions':verification['checks']['assertions'],
            'changed_japanese_base_frames':3,'derived_quoted_variants':3,
            'unchanged_original_c_offset_owner_and_report_artifacts':unchanged,
            'manifest_sha256':sha(OUT/'manifest.json'),
            'catalog_sha256':sha(OUT/'catalog.source-reviewed.json'),
            'author_refresh_verification_sha256':sha(OUT/'author-refresh-verification.json'),
            'runtime_approved':0,'compiler_node_browser_runs':0,
            'data_snapshot':'Phase4 CRLF snapshot only; LF replacement requires fresh certificates before wiring.'}
    print(json.dumps(report,ensure_ascii=False))


if __name__=='__main__':main()
