import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const output = process.argv[2];
const read = file => JSON.parse(fs.readFileSync(path.join(output, file), 'utf8'));
const summary = read('summary.json'), manifest = read('feature-manifest.json'), missing = read('ja-missing.json'), rejected = read('ja-rejected-placeholders.json');
assert.equal(summary.extractionErrors, 0, 'Source/config parsing must finish with no errors');
assert.equal(new Set(manifest.sourceAssignments.map(entry => entry.file)).size, summary.categories.source);
assert.equal(manifest.unclassifiedSources.length, 0, 'Every acquired source file must be assigned a feature/support family');
assert.equal(manifest.unclassifiedTypes.length, 0, 'Every JSON type value must be classified, including nested enums and non-game config');
for (const entry of manifest.dataAssignments) assert.equal(entry.scopeCounts.definitionObjects + entry.scopeCounts.nestedObjects + entry.scopeCounts.configurationObjects, entry.count);
assert.deepEqual(manifest.architecture.orderedLayers, ['logic', 'presentation', 'platform', 'input']);
assert.equal(missing.entries.length, missing.count);
assert.equal(missing.count, summary.catalogs.ja[0].untranslated);
assert.ok(missing.entries.every(entry => !entry.obsolete && !entry.flags.includes('fuzzy') && Object.values(entry.translations).some(value => !value)));
assert.equal(rejected.entries.length, rejected.count);
assert.equal(rejected.count, summary.catalogs.ja[0].placeholderMismatches);
assert.ok(manifest.webPackagingEvidence.some(entry => entry.text.includes('mods/MA')));
assert.ok(manifest.webPackagingEvidence.some(entry => entry.text.includes('gfx/Ultica_iso')));
assert.ok(manifest.boundaryEvidence.some(entry => entry.file === 'src/npctalk.cpp' && entry.span.start.line >= 2426 && entry.span.start.line <= 2437));
console.log(JSON.stringify({ verified: true, sourceCounts: summary.sourceCounts, text: summary.text, dataTypes: manifest.counts.dataTypes, featureFamilies: manifest.featureFamilies.length, missingJapanese: missing.count, rejectedJapanesePlaceholders: rejected.count, reportBytes: Object.fromEntries(fs.readdirSync(output).map(name => [name, fs.statSync(path.join(output, name)).size])) }, null, 2));
