/* SPDX-License-Identifier: GPL-2.0-only */
/* Exact original enum constants and parser-selected immutable trap fields. */
static const struct {int value;const char *id;} ab_ur_parser_ids[]={
 {PARSE_ERROR_NONE,"ui.residual.parser_error.none"},
 {PARSE_ERROR_BAD_EXPRESSION_STRING,"ui.residual.parser_error.bad_expression_string"},
 {PARSE_ERROR_ELEMENT_NAME_MISMATCH,"ui.residual.parser_error.element_name_mismatch"},
 {PARSE_ERROR_FIELD_TOO_LONG,"ui.residual.parser_error.field_too_long"},
 {PARSE_ERROR_GENERIC,"ui.residual.parser_error.generic"},
 {PARSE_ERROR_INTERNAL,"ui.residual.parser_error.internal"},
 {PARSE_ERROR_INVALID_ALLOCATION,"ui.residual.parser_error.invalid_allocation"},
 {PARSE_ERROR_INVALID_COLOR,"ui.residual.parser_error.invalid_color"},
 {PARSE_ERROR_INVALID_DICE,"ui.residual.parser_error.invalid_dice"},
 {PARSE_ERROR_INVALID_EFFECT,"ui.residual.parser_error.invalid_effect"},
 {PARSE_ERROR_INVALID_EXPRESSION,"ui.residual.parser_error.invalid_expression"},
 {PARSE_ERROR_INVALID_FLAG,"ui.residual.parser_error.invalid_flag"},
 {PARSE_ERROR_INVALID_ID_TYPE,"ui.residual.parser_error.invalid_id_type"},
 {PARSE_ERROR_INVALID_ITEM_NUMBER,"ui.residual.parser_error.invalid_item_number"},
 {PARSE_ERROR_INVALID_ITERATE,"ui.residual.parser_error.invalid_iterate"},
 {PARSE_ERROR_INVALID_LIGHTING,"ui.residual.parser_error.invalid_lighting"},
 {PARSE_ERROR_INVALID_MESSAGE,"ui.residual.parser_error.invalid_message"},
 {PARSE_ERROR_INVALID_MONSTER_BASE,"ui.residual.parser_error.invalid_monster_base"},
 {PARSE_ERROR_INVALID_MONSTER,"ui.residual.parser_error.invalid_monster"},
 {PARSE_ERROR_INVALID_MONSTER_ROLE,"ui.residual.parser_error.invalid_monster_role"},
 {PARSE_ERROR_INVALID_OBJ_PROP_CODE,"ui.residual.parser_error.invalid_obj_prop_code"},
 {PARSE_ERROR_INVALID_OPTION,"ui.residual.parser_error.invalid_option"},
 {PARSE_ERROR_INVALID_OPERATION,"ui.residual.parser_error.invalid_operation"},
 {PARSE_ERROR_INVALID_PLAY_PROP_CODE,"ui.residual.parser_error.invalid_play_prop_code"},
 {PARSE_ERROR_INVALID_PROPERTY,"ui.residual.parser_error.invalid_property"},
 {PARSE_ERROR_INVALID_SLAY,"ui.residual.parser_error.invalid_slay"},
 {PARSE_ERROR_INVALID_SPELL_FREQ,"ui.residual.parser_error.invalid_spell_freq"},
 {PARSE_ERROR_INVALID_SPELL_NAME,"ui.residual.parser_error.invalid_spell_name"},
 {PARSE_ERROR_INVALID_SPELL_STAT,"ui.residual.parser_error.invalid_spell_stat"},
 {PARSE_ERROR_INVALID_SUBTYPE,"ui.residual.parser_error.invalid_subtype"},
 {PARSE_ERROR_INVALID_VALUE,"ui.residual.parser_error.invalid_value"},
 {PARSE_ERROR_MISSING_BLOW_EFF_TYPE,"ui.residual.parser_error.missing_blow_eff_type"},
 {PARSE_ERROR_MISSING_FIELD,"ui.residual.parser_error.missing_field"},
 {PARSE_ERROR_MISSING_OBJ_PROP_TYPE,"ui.residual.parser_error.missing_obj_prop_type"},
 {PARSE_ERROR_MISSING_PLAY_PROP_TYPE,"ui.residual.parser_error.missing_play_prop_type"},
 {PARSE_ERROR_MISSING_RECORD_HEADER,"ui.residual.parser_error.missing_record_header"},
 {PARSE_ERROR_NO_ARTIFACT_NAME,"ui.residual.parser_error.no_artifact_name"},
 {PARSE_ERROR_NO_BUILDER_FOUND,"ui.residual.parser_error.no_builder_found"},
 {PARSE_ERROR_NO_FILE_FOUND,"ui.residual.parser_error.no_file_found"},
 {PARSE_ERROR_NO_KIND_FOR_EGO_TYPE,"ui.residual.parser_error.no_kind_for_ego_type"},
 {PARSE_ERROR_NO_KIND_FOUND,"ui.residual.parser_error.no_kind_found"},
 {PARSE_ERROR_NO_ROOM_FOUND,"ui.residual.parser_error.no_room_found"},
 {PARSE_ERROR_NON_SEQUENTIAL_RECORDS,"ui.residual.parser_error.non_sequential_records"},
 {PARSE_ERROR_NOT_NUMBER,"ui.residual.parser_error.not_number"},
 {PARSE_ERROR_NOT_RANDOM,"ui.residual.parser_error.not_random"},
 {PARSE_ERROR_NOT_SPECIAL_ARTIFACT,"ui.residual.parser_error.not_special_artifact"},
 {PARSE_ERROR_OBSOLETE_FILE,"ui.residual.parser_error.obsolete_file"},
 {PARSE_ERROR_OUT_OF_BOUNDS,"ui.residual.parser_error.out_of_bounds"},
 {PARSE_ERROR_OUT_OF_MEMORY,"ui.residual.parser_error.out_of_memory"},
 {PARSE_ERROR_REPEATED_DIRECTIVE,"ui.residual.parser_error.repeated_directive"},
 {PARSE_ERROR_TOO_FEW_ENTRIES,"ui.residual.parser_error.too_few_entries"},
 {PARSE_ERROR_TOO_MANY_ENTRIES,"ui.residual.parser_error.too_many_entries"},
 {PARSE_ERROR_UNBOUND_EXPRESSION,"ui.residual.parser_error.unbound_expression"},
 {PARSE_ERROR_UNDEFINED_DIRECTIVE,"ui.residual.parser_error.undefined_directive"},
 {PARSE_ERROR_UNRECOGNISED_BLOW,"ui.residual.parser_error.unrecognised_blow"},
 {PARSE_ERROR_UNRECOGNISED_BRAND,"ui.residual.parser_error.unrecognised_brand"},
 {PARSE_ERROR_UNRECOGNISED_SLAY,"ui.residual.parser_error.unrecognised_slay"},
 {PARSE_ERROR_UNRECOGNISED_CURSE,"ui.residual.parser_error.unrecognised_curse"},
 {PARSE_ERROR_UNRECOGNISED_TRAP,"ui.residual.parser_error.unrecognised_trap"},
 {PARSE_ERROR_UNRECOGNISED_TVAL,"ui.residual.parser_error.unrecognised_tval"},
 {PARSE_ERROR_UNRECOGNISED_SVAL,"ui.residual.parser_error.unrecognised_sval"},
 {PARSE_ERROR_UNRECOGNISED_PARAMETER,"ui.residual.parser_error.unrecognised_parameter"},
 {PARSE_ERROR_VAULT_TOO_BIG,"ui.residual.parser_error.vault_too_big"},
 {PARSE_ERROR_VAULT_DESC_WRONG_LENGTH,"ui.residual.parser_error.vault_desc_wrong_length"},
};
static const struct {int value;const char *id;} ab_ur_tval_ids[]={
 {TV_NULL,"ui.residual.tval.null"},
 {TV_CHEST,"ui.residual.tval.chest"},
 {TV_SHOT,"ui.residual.tval.shot"},
 {TV_ARROW,"ui.residual.tval.arrow"},
 {TV_BOLT,"ui.residual.tval.bolt"},
 {TV_BOW,"ui.residual.tval.bow"},
 {TV_DIGGING,"ui.residual.tval.digging"},
 {TV_HAFTED,"ui.residual.tval.hafted"},
 {TV_POLEARM,"ui.residual.tval.polearm"},
 {TV_SWORD,"ui.residual.tval.sword"},
 {TV_BOOTS,"ui.residual.tval.boots"},
 {TV_GLOVES,"ui.residual.tval.gloves"},
 {TV_HELM,"ui.residual.tval.helm"},
 {TV_CROWN,"ui.residual.tval.crown"},
 {TV_SHIELD,"ui.residual.tval.shield"},
 {TV_CLOAK,"ui.residual.tval.cloak"},
 {TV_SOFT_ARMOR,"ui.residual.tval.soft_armor"},
 {TV_HARD_ARMOR,"ui.residual.tval.hard_armor"},
 {TV_DRAG_ARMOR,"ui.residual.tval.drag_armor"},
 {TV_LIGHT,"ui.residual.tval.light"},
 {TV_AMULET,"ui.residual.tval.amulet"},
 {TV_RING,"ui.residual.tval.ring"},
 {TV_STAFF,"ui.residual.tval.staff"},
 {TV_WAND,"ui.residual.tval.wand"},
 {TV_ROD,"ui.residual.tval.rod"},
 {TV_SCROLL,"ui.residual.tval.scroll"},
 {TV_POTION,"ui.residual.tval.potion"},
 {TV_FLASK,"ui.residual.tval.flask"},
 {TV_FOOD,"ui.residual.tval.food"},
 {TV_MUSHROOM,"ui.residual.tval.mushroom"},
 {TV_MAGIC_BOOK,"ui.residual.tval.magic_book"},
 {TV_PRAYER_BOOK,"ui.residual.tval.prayer_book"},
 {TV_NATURE_BOOK,"ui.residual.tval.nature_book"},
 {TV_SHADOW_BOOK,"ui.residual.tval.shadow_book"},
 {TV_OTHER_BOOK,"ui.residual.tval.other_book"},
 {TV_GOLD,"ui.residual.tval.gold"},
};
static const struct {int index;const char *name,*desc,*id;} ab_ur_trap_ids[]={
 {0,"no trap","no trap","trap.label.no_trap"},
 {1,"glyph of warding","glyph of warding","trap.label.glyph_of_warding"},
 {2,"decoy","decoy","trap.label.decoy"},
 {3,"door lock","door lock","trap.label.door_lock"},
 {4,"web","web","trap.label.web"},
 {5,"trap door","trap door","trap.label.trap_door"},
 {6,"pit","pit","trap.label.pit"},
 {7,"pit","spiked pit","trap.label.pit"},
 {8,"pit","poison pit","trap.label.pit"},
 {9,"strange rune","rune of summon foe","trap.label.strange_rune"},
 {10,"strange rune","rune of summoning","trap.label.strange_rune"},
 {11,"strange rune","rune of necromancy","trap.label.strange_rune"},
 {12,"strange rune","rune of dragonsong","trap.label.strange_rune"},
 {13,"strange rune","hellhole","trap.label.strange_rune"},
 {14,"strange rune","teleport rune","trap.label.strange_rune"},
 {15,"discolored spot","fire trap","trap.label.discolored_spot"},
 {16,"discolored spot","acid trap","trap.label.discolored_spot"},
 {17,"dart trap","slow dart","trap.label.dart_trap"},
 {18,"dart trap","strength loss dart","trap.label.dart_trap"},
 {19,"dart trap","dexterity loss dart","trap.label.dart_trap"},
 {20,"dart trap","constitution loss dart","trap.label.dart_trap"},
 {21,"gas trap","blinding gas trap","trap.label.gas_trap"},
 {22,"gas trap","confusion gas trap","trap.label.gas_trap"},
 {23,"gas trap","poison gas trap","trap.label.gas_trap"},
 {24,"gas trap","sleep gas trap","trap.label.gas_trap"},
 {25,"alarm","aggravation trap","trap.label.alarm"},
 {26,"alarm","siren","trap.label.alarm"},
 {27,"explosion","mine trap","trap.label.explosion"},
 {28,"explosion","blast trap","trap.label.explosion"},
 {29,"mind blast trap","mind blasting trap","trap.label.mind_blast_trap"},
 {30,"mind blast trap","brain smashing trap","trap.label.mind_blast_trap"},
 {31,"ancient mechanism","rock fall trap","trap.label.ancient_mechanism"},
 {32,"ancient mechanism","earthquake trap","trap.label.ancient_mechanism"},
 {33,"ancient mechanism","block fall trap","trap.label.ancient_mechanism"},
 {34,"ancient mechanism","area blast trap","trap.label.ancient_mechanism"},
 {35,"trap","blinding flash trap","trap.label.trap"},
 {36,"trap","blinding trap","trap.label.trap"},
 {37,"trap","mana drain trap","trap.label.trap"},
 {38,"trap","knife trap","trap.label.trap"},
 {39,"trap","petrifying trap","trap.label.trap"},
};
