import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import os from 'node:os';
import {spawn} from 'node:child_process';

const buildRoot = path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/, '$1'));
const upstream = 'C:/Users/kit/gameme/jnethack/jrouge/cataclysm-dda/upstream/Cataclysm-DDA-7b2efa5cea38e4d4d97dd0e63b28b9148623da59';
const sdk = 'C:/Users/kit/emsdk';
const py = sdk + '/python/3.13.3_64bit/python.exe';
const emcc = sdk + '/upstream/emscripten/emcc.py';
const emxx = sdk + '/upstream/emscripten/em++.py';
const logs = path.join(buildRoot, 'logs');
const overlay = path.join(buildRoot, 'generated');
const cache = path.join(buildRoot, 'cache');
const ports = path.join(buildRoot, 'ports');
const objects = path.join(buildRoot, 'objects');
const output = path.join(buildRoot, 'output');
for (const p of [logs, overlay, cache, ports, objects, output]) fs.mkdirSync(p, {recursive:true});
const config = path.join(buildRoot, '.emscripten');
fs.writeFileSync(config, `NODE_JS = '${sdk}/node/24.19.0_64bit/node.exe'\nPYTHON = '${py}'\nLLVM_ROOT = '${sdk}/upstream/bin'\nBINARYEN_ROOT = '${sdk}/upstream'\nEMSCRIPTEN_ROOT = '${sdk}/upstream/emscripten'\n`);
const env = {...process.env, EM_CONFIG:config, EM_CACHE:cache, EM_PORTS:ports, EMCC_CORES:process.env.EMCC_CORES||'1', EMCC_BATCH_BUILD:'0', BINARYEN_CORES:'1'};
delete env.EMSDK;
delete env.EMSDK_NODE;
delete env.EMSDK_PYTHON;
// Both are generated by the official Makefile. They are isolated overlays here.
fs.writeFileSync(path.join(overlay, 'version.h'), '// NOLINT(cata-header-guard)\n#define VERSION "0.I-1 7b2efa5-jrogue-web-build"\n');
fs.writeFileSync(path.join(overlay, 'prefix.h'), '// NOLINT(cata-header-guard)\n#define PREFIX ""\n');

const sourcesIn = (dir, ext) => fs.readdirSync(path.join(upstream, dir)).filter(n => n.endsWith(ext)).sort().map(n => dir + '/' + n);
const cppSources = [...sourcesIn('src', '.cpp'), ...sourcesIn('src/third-party/flatbuffers', '.cpp'), ...[
  'imgui.cpp','imgui_demo.cpp','imgui_draw.cpp','imgui_stdlib.cpp','imgui_tables.cpp','imgui_widgets.cpp',
  'imgui_freetype.cpp','imgui_impl_sdl2.cpp','imgui_impl_sdlrenderer2.cpp',
].map(n => 'src/third-party/imgui/' + n)];
const cSources = ['common','compress','decompress'].flatMap(d => sourcesIn('src/third-party/zstd/' + d, '.c'));
const allSources = [...cppSources, ...cSources];
const commonFlags = ['-Os','-fsigned-char','-fexceptions','-DRELEASE','-DTILES','-DLOCALIZE','-DEMSCRIPTEN',
 '-DZSTD_STATIC_LINKING_ONLY','-DZSTD_DISABLE_ASM', '-I'+overlay, '-I'+upstream+'/src',
 '-isystem',upstream+'/src/third-party','-sUSE_SDL=2','-sUSE_SDL_IMAGE=2','-sUSE_SDL_TTF=2',
 '-sSDL2_IMAGE_FORMATS=["png"]'];
const warnings = ['-Wall','-Wextra','-Wformat-signedness','-Wlogical-op','-Wmissing-declarations','-Wmissing-noreturn',
 '-Wpedantic','-Wunused-macros','-Wno-gnu-zero-variadic-macro-arguments','-Wredundant-decls','-Wno-unknown-warning-option'];
const cppFlags = ['-std=c++17','-Wnon-virtual-dtor','-Wold-style-cast','-Woverloaded-virtual','-Wsuggest-override',
 '-Wzero-as-null-pointer-constant','-Wno-dangling-reference','-Wno-c++20-compat'];
const linkFlags = ['-sUSE_SDL=2','-sUSE_SDL_IMAGE=2','-sUSE_SDL_TTF=2','-sSDL2_IMAGE_FORMATS=["png"]','-fexceptions',
 '-sFORCE_FILESYSTEM','-sEXPORTED_RUNTIME_METHODS=["FS","stackTrace","jsStackTrace"]',
 '-sINITIAL_MEMORY=512MB','-sMAXIMUM_MEMORY=4GB','-sALLOW_MEMORY_GROWTH','-sSTACK_SIZE=262144',
 '-sASYNCIFY','-sASYNCIFY_STACK_SIZE=16384','-sENVIRONMENT=web','-lidbfs.js','-lembind',
 '-sWASM_BIGINT','-sMAX_WEBGL_VERSION=2','-Os','-sLZ4','-lz','-Wl,--threads=1'];
const sha256 = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const manifest = {upstream, upstreamCommit:'7b2efa5cea38e4d4d97dd0e63b28b9148623da59',upstreamTag:'0.I-1',
 officialCompiler:'3.1.51',actualCompiler:'6.0.8',makefileSha256:sha256(upstream+'/Makefile'),
 officialRecipeSha256:sha256(upstream+'/build-scripts/build-emscripten.sh'),
 cppSources, cSources,commonFlags,cppFlags,warnings,linkFlags,
 differences:['Generated headers isolated in task workspace; pristine upstream unchanged.',
 'Emscripten 6.0.8 installed on host rather than official pinned 3.1.51.',
 'Explicit -DEMSCRIPTEN restores the legacy platform macro used throughout 0.I-1; installed SDK6.0.8 defines only __EMSCRIPTEN__. Verified by compiler preprocessing probe.',
 'Werror omitted because compiler version differs; warnings retained. No gameplay code excluded.',
 'Dependency-free Node orchestration replaces GNU Make; same source enumeration and selected platform flags.']};
fs.writeFileSync(path.join(buildRoot, 'build-manifest.json'), JSON.stringify(manifest,null,2)+'\n');

function run(tool,args,name) {
 return new Promise(resolve => {
  const start=Date.now();
  const logPath=path.join(logs,name+'.log');
 const log=fs.createWriteStream(logPath);
  let closed=false;
  log.write(JSON.stringify({tool,args,cwd:buildRoot,EM_CONFIG:config,EM_CACHE:cache,EM_PORTS:ports,EMCC_CORES:env.EMCC_CORES,EMCC_BATCH_BUILD:env.EMCC_BATCH_BUILD,BINARYEN_CORES:env.BINARYEN_CORES})+'\n');
  const child=spawn(py,[tool,...args],{cwd:buildRoot,env,windowsHide:true,stdio:['ignore','pipe','pipe']});
  child.stdout.on('data',d=>log.write(d));child.stderr.on('data',d=>log.write(d));
  child.on('error',e=>{if(closed)return;closed=true;log.write(String(e));log.end(()=>resolve({name,code:-1,error:String(e),logPath}));});
  child.on('close',code=>{if(closed)return;closed=true;const result={name,code,milliseconds:Date.now()-start,logPath};log.end(()=>resolve(result));});
 });
}
const objectFor = source => path.join(objects,source.replace(/^src\//,'').replace(/\.(cpp|c)$/,'.o'));
const commandFor = source => {
 const c=source.endsWith('.c');
 return [...commonFlags,...warnings,...(c?['-std=c17','-x','c']:cppFlags),
 ...(source.includes('/third-party/')?['-w']:[]),'-MMD','-MP','-c',upstream+'/'+source,'-o',objectFor(source)];
};
const resultsPath=path.join(buildRoot,'compile-results.json');
const results=fs.existsSync(resultsPath)?JSON.parse(fs.readFileSync(resultsPath,'utf8')):[];
function usableObject(source) {
 if(!fs.existsSync(objectFor(source))) return false;
 const result=results.findLast(r=>r.source===source);
 if(!result||result.code!==0||!fs.existsSync(result.logPath)) return false;
 try {
  const firstLine=fs.readFileSync(result.logPath,'utf8').split('\n',1)[0];
  return JSON.stringify(JSON.parse(firstLine).args)===JSON.stringify(commandFor(source));
 } catch { return false; }
}
function saveResults() {
 const temporary=resultsPath+'.tmp';
 fs.writeFileSync(temporary,JSON.stringify(results,null,2)+'\n');
 fs.renameSync(temporary,resultsPath);
}
const arg=process.argv[2]||'--probe';
if(arg==='--probe') {
 const version=await run(emcc,['--version'],'compiler-version');console.log(JSON.stringify(version));
 const source='src/version.cpp';fs.mkdirSync(path.dirname(objectFor(source)),{recursive:true});
 const probe=await run(emxx,commandFor(source),'probe-version');console.log(JSON.stringify(probe));
 console.log(fs.readFileSync(probe.logPath,'utf8').slice(-12000));process.exitCode=probe.code;
} else if(arg==='--compile') {
 let jobs=Number(process.env.CDDA_BUILD_JOBS||1);
 if(!Number.isInteger(jobs)||jobs<1||jobs>2) throw new Error('CDDA_BUILD_JOBS must be 1 or 2 on this shared executor.');
 const freeMemoryBytes=os.freemem();
 if(jobs===2&&freeMemoryBytes<4*1024**3){console.log(JSON.stringify({memoryGuard:'Using one job: less than 4 GiB free RAM',freeMemoryBytes}));jobs=1;}
 // Verify SDK-sensitive browser paths early; linking still retains Makefile source order.
 const compilePriority=['src/main.cpp','src/sdltiles.cpp','src/input.cpp','src/emscripten_exception.cpp','src/filesystem.cpp'];
 const queue=[...compilePriority,...allSources.filter(s=>!compilePriority.includes(s))].filter(s=>!usableObject(s));
 let completed=allSources.length-queue.length, failed=false;
 console.log(JSON.stringify({total:allSources.length,remaining:queue.length,jobs,freeMemoryBytes}));
 await Promise.all(Array.from({length:jobs},async(_,workerIndex)=>{
  while(queue.length&&!failed) {
   if(workerIndex>0&&os.freemem()<4*1024**3){await new Promise(resolve=>setTimeout(resolve,1000));continue;}
   const source=queue.shift();fs.mkdirSync(path.dirname(objectFor(source)),{recursive:true});
   const result=await run(emxx,commandFor(source),'compile-'+source.replace(/[^a-zA-Z0-9_-]/g,'_'));
   results.push({...result,source});saveResults();
   completed++;console.log(JSON.stringify({...result,source,completed,total:allSources.length}));
   if(result.code!==0){failed=true;console.log(fs.readFileSync(result.logPath,'utf8').slice(-16000));}
  }
 }));
 console.log(JSON.stringify({completed,failed,remaining:queue.length}));process.exitCode=failed?1:0;
} else if(arg==='--link') {
 const missing=allSources.filter(s=>!usableObject(s));
 if(missing.length) throw new Error(`Missing ${missing.length} objects`);
 const response=path.join(buildRoot,'link-objects.rsp');
 fs.writeFileSync(response,allSources.map(s=>JSON.stringify(objectFor(s).replaceAll('\\','/'))).join('\n'));
 const result=await run(emxx,['@'+response,...linkFlags,'-Wl,--trace','-o',path.join(output,'cataclysm-tiles.js')],'link-engine');
 const linkLog=fs.readFileSync(result.logPath,'utf8');
 const tracedArchives=[...new Set([...linkLog.matchAll(/([^\r\n]+?\.a)(?:\(|\r?$)/gm)].map(m=>m[1].trim()).filter(p=>fs.existsSync(p)))];
 fs.writeFileSync(path.join(buildRoot,'used-sdk-archives.json'),JSON.stringify({linkResult:result.code,trace:'wasm-ld --trace',
  archives:tracedArchives.map(p=>({path:p,bytes:fs.statSync(p).size,sha256:sha256(p)}))},null,2)+'\n');
 if(result.code===0){
  const wasm=path.join(output,'cataclysm-tiles.wasm');
  const javascript=path.join(output,'cataclysm-tiles.js');
  const artifactEvidence={upstreamCommit:manifest.upstreamCommit,compiler:manifest.actualCompiler,wasmValid:WebAssembly.validate(fs.readFileSync(wasm)),
   files:[wasm,javascript].map(p=>({path:p,bytes:fs.statSync(p).size,sha256:sha256(p)})),runtimeBrowserVerified:false};
  fs.writeFileSync(path.join(buildRoot,'artifact-evidence.json'),JSON.stringify(artifactEvidence,null,2)+'\n');
  console.log(JSON.stringify(artifactEvidence));
  if(!artifactEvidence.wasmValid)throw new Error('Linked module failed WebAssembly binary validation');
 }
 console.log(JSON.stringify(result));console.log(fs.readFileSync(result.logPath,'utf8').slice(-16000));process.exitCode=result.code;
} else if(arg==='--manifest') console.log(JSON.stringify({cpp:cppSources.length,c:cSources.length,total:allSources.length,manifest:buildRoot+'/build-manifest.json'}));
else throw new Error('Use --probe, --compile, --link or --manifest');
