/* SPDX-License-Identifier: GPL-2.0-only; pinned source record identities. */
static const struct chest_binding chest_bindings[] = {
 {2,"POISON","A puff of green gas surrounds you!","angband.chest_trap.trigger.green_gas"},
 {4,"LOSE_STR","A small needle has pricked you!","angband.chest_trap.trigger.needle"},
 {8,"LOSE_CON","A small needle has pricked you!","angband.chest_trap.trigger.needle"},
 {16,"SUMMON","You are enveloped in a cloud of smoke!","angband.chest_trap.trigger.summoning_smoke"},
 {32,"PARALYZE","A puff of yellow gas surrounds you!","angband.chest_trap.trigger.yellow_gas"},
 {64,"EXPLODE","There is a sudden explosion! Everything inside the chest is destroyed!","angband.chest_trap.trigger.explosion"},
};
