"""Compile display-only locale dictionaries; original game strings stay English."""
import json
from pathlib import Path
import re
import argparse
import importlib.util

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
options = parser.parse_args()

ROOT = Path(__file__).resolve().parents[1]
document = json.loads((ROOT / "locales/ja/display.json").read_text(encoding="utf-8"))
entries = document["entries"]
for key,value in json.loads((ROOT/'locales/ja/composed.json').read_text(encoding='utf8'))['entries'].items():
    entries = {k:v for k,v in entries.items() if v['source'].lower()!=value['source'].lower()}
    entries[key] = value
spec = importlib.util.spec_from_file_location('locale_source', ROOT / 'tools/locale-source.py')
locale_source = importlib.util.module_from_spec(spec)
spec.loader.exec_module(locale_source)
coverage = {}
for category in locale_source.DISPLAY_CATEGORIES:
    english = json.loads((ROOT / f'locales/en/{category}.json').read_text(encoding='utf-8'))['entries']
    japanese = json.loads((ROOT / f'locales/ja/{category}.json').read_text(encoding='utf-8'))['entries']
    if set(english) != set(japanese):
        raise SystemExit(f'Japanese catalog coverage mismatch: {category}')
    patterns = {v['source'].strip().lower() for v in entries.values()}
    for key, value in japanese.items():
        pattern, arguments = locale_source.display_pattern(english[key])
        if value['source'] != english[key]['text'] or value['pattern'] != pattern:
            raise SystemExit('Stale Japanese source: ' + key)
        structural = not re.sub(r'\{\d+\}', '', pattern).strip() or pattern == 'the {0}'
        if (not value['text'] or value['text'] == pattern) and value['text'] != locale_source.PROJECT_TITLE and not value.get('preserve') and not structural:
            raise SystemExit('Missing Japanese translation: ' + key)
        if not value.get('preserve') and not structural and value['text'] != locale_source.PROJECT_TITLE and not re.search(r'[\u3000-\u30ff\u3400-\u9fff]', value['text']):
            raise SystemExit('Translation contains no Japanese: ' + key)
        if pattern.lower() not in patterns and not value.get('preserve'):
            kinds, domains = locale_source.runtime_arguments(value, pattern, arguments)
            entries[key] = {**value, 'source':pattern, '_kinds':kinds, '_domains':domains}
            patterns.add(pattern.lower())
    coverage[category] = {'entries':len(english), 'translated':sum(not v.get('preserve') for v in japanese.values()),
                          'preserved':sum(bool(v.get('preserve')) for v in japanese.values()), 'missing':0}
# Engine-generated plural names are not standalone C literals.
name_catalog = json.loads((ROOT/'locales/ja/content.json').read_text(encoding='utf8'))['entries']
for key, value in name_catalog.items():
    if len(value['pattern'])<32 and any('weaponTable' in (s.get('symbol') or '') for s in value.get('sources', [])):
        plural = value['pattern'] + 's'
        if plural.lower() not in {e['source'].lower() for e in entries.values()}:
            singular = next((e['text'] for e in entries.values() if e['source'].lower()==value['pattern'].lower()),value['text'])
            entries[key+'.plural'] = {'source':plural,'text':singular}
# Where the original builder appends another sentence, retain its translated prefix.
for key, value in list(entries.items()):
    if value['source'].startswith('&'):
        clean = value['source'][1:]
        if clean.lower() not in {e['source'].lower() for e in entries.values()}:
            entries[key+'.list_fragment'] = {**value,'source':clean,'text':value['text'].lstrip('&＆')}
    last = re.search(r'\{(\d+)\}$',value['source'])
    if last and value['text'].endswith(last[0]) and len(re.sub(r'\{\d+\}','',value['source']))>=8:
        pattern = value['source'][:last.start()].rstrip()
        if not pattern or pattern.lower() in {e['source'].lower() for e in entries.values()}: continue
        entry = {**value,'source':pattern,'text':value['text'][:-len(last[0])].rstrip()}
        if '_kinds' in entry: entry['_kinds'] = entry['_kinds'][:int(last[1])]
        if '_domains' in entry: entry['_domains'] = entry['_domains'][:int(last[1])]
        entry['arguments'] = entry.get('arguments',[])[:int(last[1])]
        entries[key+'.prefix'] = entry
sources = set()
lines = ["/* Generated by tools/compile-locales.py from locales/ja/*.json. */", "static const LocaleEntry localeEntries[] = {"]
compiled_count = 0
def specificity(item):
    source = item[1]['source']
    placeholders = re.findall(r'\{\d+\}', source)
    return (bool(placeholders), source in ('{0} of {1}','{0} of {1}{2}'), -len(re.sub(r'\{\d+\}', '', source)))

for entry_id, entry in sorted(entries.items(), key=specificity):
    source, translated = entry["source"], entry["text"]
    kinds = entry.get('_kinds', locale_source.argument_kinds(source, list(enumerate(entry.get('arguments', [])))))
    # The renderer removes binary color escapes before matching English text.
    for i,kind in enumerate(kinds):
        if kind == 'e':
            source = source.replace('{'+str(i)+'}','')
            translated = translated.replace('{'+str(i)+'}','')
    source = source.strip()
    if source.lower() in sources: continue
    sources.add(source.lower())
    expected = set(re.findall(r"\{(\d+)\}", source))
    actual = set(re.findall(r"\{(\d+)\}", translated))
    omitted = {str(i) for i in entry.get('omitted_arguments', [])}
    if actual != expected - omitted or any(int(i) >= 16 for i in expected):
        raise SystemExit("Unknown translation argument: " + entry_id)
    if not re.sub(r'\{\d+\}', '', source).strip() and source != '{0} {1}':
        continue  # Assembly formats contain no English phrase of their own.
    for value in (entry_id, source, translated):
        if "\x00" in value:
            raise SystemExit("Embedded null in dictionary")
    if source == '{0} (x{1})': kinds = 'mi'
    if source == '{0} (many)': kinds = 'm'
    if source == '{0} of {1}': kinds = 'kk'
    if source in ('{0} <{1}>','{0}<{1}>'): kinds = 'ki'
    if source == '{0} ({1})': kinds = 'kc'
    if source == '{0} [{1}]<{2}>': kinds = 'kii'
    if source == '{0} {1}': kinds = 'ik'
    if re.fullmatch(r'\{0\} (?:dagger|leather armor|darts?|rations? of food)',source): kinds = 'i'
    if source == 'a {0} dagger <{1}>': kinds = 'ii'
    if source == 'a {0} leather armor [{1}]<{2}>': kinds = 'iii'
    weight = len(re.findall('[A-Za-z]',re.sub(r'\{\d+\}','',source)))
    domains = entry.get('_domains', [])
    domain_array = '{' + ', '.join(json.dumps(d,ensure_ascii=False).replace('\\u001f','\\037') if d else 'NULL' for d in domains) + '}' if domains else '{NULL}'
    lines.append("    {" + ", ".join(json.dumps(value, ensure_ascii=False) for value in (entry_id, source, translated, kinds)) + ', ' + str(weight) + ', ' + domain_array + "},")
    compiled_count += 1
lines += ["};", "static const LocalePhoneme localePhonemes[] = {"]
phonemes = json.loads((ROOT/'locales/ja/content.json').read_text(encoding='utf8'))['entries']
for entry in phonemes.values():
    if any(s['symbol']=='titlePhonemes' for s in entry['sources']):
        lines.append('    {' + json.dumps(entry['pattern'],ensure_ascii=False) + ', ' + json.dumps(entry['text'],ensure_ascii=False) + '},')
lines += ['};','']
destination = ROOT / "src/brogue/LocalizedTextData.h"
serialized = "\n".join(lines)
if options.check:
    if not destination.exists() or destination.read_text(encoding="utf-8") != serialized:
        raise SystemExit("Compiled locale header is stale; run tools/compile-locales.py")
else:
    destination.write_text(serialized, encoding="utf-8", newline="\n")
print("Compiled Japanese display entries:", compiled_count)
report = {'categories':coverage, 'missing':0, 'runtime_patterns':compiled_count}
report_path = ROOT / 'locales/ja/coverage.json'
if not options.check:
    report_path.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
